// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: judge.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelQueuedJudgeTask = `-- name: CancelQueuedJudgeTask :one
UPDATE judge_task
SET status = 7, updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND status = 1
RETURNING id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
`

type CancelQueuedJudgeTaskParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) CancelQueuedJudgeTask(ctx context.Context, arg CancelQueuedJudgeTaskParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, cancelQueuedJudgeTask, arg.TenantID, arg.ID)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JudgerID,
		&i.SourceRef,
		&i.SourceOwnerID,
		&i.SourceCourseID,
		&i.SourceScope,
		&i.SubmitterID,
		&i.ProblemRef,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InputSnapshot,
		&i.SandboxMode,
		&i.TargetSandboxRef,
		&i.Priority,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJudgeTask = `-- name: CompleteJudgeTask :one
UPDATE judge_task
SET status = 3, last_error = NULL, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
`

type CompleteJudgeTaskParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) CompleteJudgeTask(ctx context.Context, arg CompleteJudgeTaskParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, completeJudgeTask, arg.TenantID, arg.ID)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JudgerID,
		&i.SourceRef,
		&i.SourceOwnerID,
		&i.SourceCourseID,
		&i.SourceScope,
		&i.SubmitterID,
		&i.ProblemRef,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InputSnapshot,
		&i.SandboxMode,
		&i.TargetSandboxRef,
		&i.Priority,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countJudgeTasks = `-- name: CountJudgeTasks :one
SELECT COUNT(*)::bigint
FROM judge_task
JOIN judger ON judger.id = judge_task.judger_id
WHERE judge_task.tenant_id = $1
  AND ($2::text = '' OR judge_task.source_ref = $2)
  AND ($3::boolean = false OR (judge_task.status = 2 AND judger.type = 6))
  AND ($4::bigint = 0 OR judge_task.source_owner_id = $4 OR judge_task.submitter_id = $4)
`

type CountJudgeTasksParams struct {
	TenantID int64  `json:"tenant_id"`
	Column2  string `json:"column_2"`
	Column3  bool   `json:"column_3"`
	Column4  int64  `json:"column_4"`
}

func (q *Queries) CountJudgeTasks(ctx context.Context, arg CountJudgeTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJudgeTasks,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createJudgeOutbox = `-- name: CreateJudgeOutbox :one
INSERT INTO judge_event_outbox (id, tenant_id, task_id, subject, payload, status, retry_count, last_error, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 1, 0, NULL, now(), now())
RETURNING id, tenant_id, task_id, subject, payload, status, retry_count, next_attempt_at, last_error, created_at, updated_at
`

type CreateJudgeOutboxParams struct {
	ID       int64  `json:"id"`
	TenantID int64  `json:"tenant_id"`
	TaskID   int64  `json:"task_id"`
	Subject  string `json:"subject"`
	Payload  []byte `json:"payload"`
}

func (q *Queries) CreateJudgeOutbox(ctx context.Context, arg CreateJudgeOutboxParams) (JudgeEventOutbox, error) {
	row := q.db.QueryRow(ctx, createJudgeOutbox,
		arg.ID,
		arg.TenantID,
		arg.TaskID,
		arg.Subject,
		arg.Payload,
	)
	var i JudgeEventOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.Subject,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJudgeTask = `-- name: CreateJudgeTask :one
WITH inserted AS (
    INSERT INTO judge_task (
        id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope,
        submitter_id, problem_ref, code_storage_key, code_hash,
        input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error,
        created_at, updated_at
    )
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, 0, $17, NULL, now(), now())
    ON CONFLICT (tenant_id, source_ref, problem_ref) DO NOTHING
    RETURNING id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
)
SELECT id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
FROM inserted
UNION ALL
SELECT id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
FROM judge_task
WHERE tenant_id = $2 AND source_ref = $4 AND problem_ref = $9 AND NOT EXISTS (SELECT 1 FROM inserted)
LIMIT 1
`

type CreateJudgeTaskParams struct {
	ID               int64       `json:"id"`
	TenantID         int64       `json:"tenant_id"`
	JudgerID         int64       `json:"judger_id"`
	SourceRef        string      `json:"source_ref"`
	SourceOwnerID    int64       `json:"source_owner_id"`
	SourceCourseID   int64       `json:"source_course_id"`
	SourceScope      string      `json:"source_scope"`
	SubmitterID      int64       `json:"submitter_id"`
	ProblemRef       string      `json:"problem_ref"`
	CodeStorageKey   string      `json:"code_storage_key"`
	CodeHash         string      `json:"code_hash"`
	InputSnapshot    []byte      `json:"input_snapshot"`
	SandboxMode      int16       `json:"sandbox_mode"`
	TargetSandboxRef pgtype.Text `json:"target_sandbox_ref"`
	Priority         int16       `json:"priority"`
	Status           int16       `json:"status"`
	MaxRetries       int32       `json:"max_retries"`
}

type CreateJudgeTaskRow struct {
	ID               int64              `json:"id"`
	TenantID         int64              `json:"tenant_id"`
	JudgerID         int64              `json:"judger_id"`
	SourceRef        string             `json:"source_ref"`
	SourceOwnerID    int64              `json:"source_owner_id"`
	SourceCourseID   int64              `json:"source_course_id"`
	SourceScope      string             `json:"source_scope"`
	SubmitterID      int64              `json:"submitter_id"`
	ProblemRef       string             `json:"problem_ref"`
	CodeStorageKey   string             `json:"code_storage_key"`
	CodeHash         string             `json:"code_hash"`
	InputSnapshot    []byte             `json:"input_snapshot"`
	SandboxMode      int16              `json:"sandbox_mode"`
	TargetSandboxRef pgtype.Text        `json:"target_sandbox_ref"`
	Priority         int16              `json:"priority"`
	Status           int16              `json:"status"`
	RetryCount       int32              `json:"retry_count"`
	MaxRetries       int32              `json:"max_retries"`
	LastError        pgtype.Text        `json:"last_error"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateJudgeTask(ctx context.Context, arg CreateJudgeTaskParams) (CreateJudgeTaskRow, error) {
	row := q.db.QueryRow(ctx, createJudgeTask,
		arg.ID,
		arg.TenantID,
		arg.JudgerID,
		arg.SourceRef,
		arg.SourceOwnerID,
		arg.SourceCourseID,
		arg.SourceScope,
		arg.SubmitterID,
		arg.ProblemRef,
		arg.CodeStorageKey,
		arg.CodeHash,
		arg.InputSnapshot,
		arg.SandboxMode,
		arg.TargetSandboxRef,
		arg.Priority,
		arg.Status,
		arg.MaxRetries,
	)
	var i CreateJudgeTaskRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JudgerID,
		&i.SourceRef,
		&i.SourceOwnerID,
		&i.SourceCourseID,
		&i.SourceScope,
		&i.SubmitterID,
		&i.ProblemRef,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InputSnapshot,
		&i.SandboxMode,
		&i.TargetSandboxRef,
		&i.Priority,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubmissionFingerprint = `-- name: CreateSubmissionFingerprint :one
INSERT INTO submission_fingerprint (id, tenant_id, source_ref, problem_ref, submitter_id, code_hash, sim_vector, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
RETURNING id, tenant_id, source_ref, problem_ref, submitter_id, code_hash, sim_vector, created_at
`

type CreateSubmissionFingerprintParams struct {
	ID          int64  `json:"id"`
	TenantID    int64  `json:"tenant_id"`
	SourceRef   string `json:"source_ref"`
	ProblemRef  string `json:"problem_ref"`
	SubmitterID int64  `json:"submitter_id"`
	CodeHash    string `json:"code_hash"`
	SimVector   []byte `json:"sim_vector"`
}

func (q *Queries) CreateSubmissionFingerprint(ctx context.Context, arg CreateSubmissionFingerprintParams) (SubmissionFingerprint, error) {
	row := q.db.QueryRow(ctx, createSubmissionFingerprint,
		arg.ID,
		arg.TenantID,
		arg.SourceRef,
		arg.ProblemRef,
		arg.SubmitterID,
		arg.CodeHash,
		arg.SimVector,
	)
	var i SubmissionFingerprint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceRef,
		&i.ProblemRef,
		&i.SubmitterID,
		&i.CodeHash,
		&i.SimVector,
		&i.CreatedAt,
	)
	return i, err
}

const dequeueJudgeTasks = `-- name: DequeueJudgeTasks :many
UPDATE judge_task t
SET status = 2, updated_at = now()
WHERE t.id IN (
    SELECT id
    FROM judge_task
    WHERE status = 1
    ORDER BY priority DESC, created_at ASC, id ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
`

func (q *Queries) DequeueJudgeTasks(ctx context.Context, limit int32) ([]JudgeTask, error) {
	rows, err := q.db.Query(ctx, dequeueJudgeTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JudgeTask{}
	for rows.Next() {
		var i JudgeTask
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JudgerID,
			&i.SourceRef,
			&i.SourceOwnerID,
			&i.SourceCourseID,
			&i.SourceScope,
			&i.SubmitterID,
			&i.ProblemRef,
			&i.CodeStorageKey,
			&i.CodeHash,
			&i.InputSnapshot,
			&i.SandboxMode,
			&i.TargetSandboxRef,
			&i.Priority,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failJudgeTask = `-- name: FailJudgeTask :one
UPDATE judge_task
SET status = 5, last_error = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
`

type FailJudgeTaskParams struct {
	TenantID  int64       `json:"tenant_id"`
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) FailJudgeTask(ctx context.Context, arg FailJudgeTaskParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, failJudgeTask, arg.TenantID, arg.ID, arg.LastError)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JudgerID,
		&i.SourceRef,
		&i.SourceOwnerID,
		&i.SourceCourseID,
		&i.SourceScope,
		&i.SubmitterID,
		&i.ProblemRef,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InputSnapshot,
		&i.SandboxMode,
		&i.TargetSandboxRef,
		&i.Priority,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findExactFingerprints = `-- name: FindExactFingerprints :many
SELECT id, tenant_id, source_ref, problem_ref, submitter_id, code_hash, sim_vector, created_at
FROM submission_fingerprint
WHERE tenant_id = $1 AND problem_ref = $2 AND code_hash = $3
ORDER BY created_at DESC, id DESC
`

type FindExactFingerprintsParams struct {
	TenantID   int64  `json:"tenant_id"`
	ProblemRef string `json:"problem_ref"`
	CodeHash   string `json:"code_hash"`
}

func (q *Queries) FindExactFingerprints(ctx context.Context, arg FindExactFingerprintsParams) ([]SubmissionFingerprint, error) {
	rows, err := q.db.Query(ctx, findExactFingerprints, arg.TenantID, arg.ProblemRef, arg.CodeHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubmissionFingerprint{}
	for rows.Next() {
		var i SubmissionFingerprint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceRef,
			&i.ProblemRef,
			&i.SubmitterID,
			&i.CodeHash,
			&i.SimVector,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJudgeTask = `-- name: GetJudgeTask :one
SELECT id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
FROM judge_task
WHERE tenant_id = $1 AND id = $2
`

type GetJudgeTaskParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetJudgeTask(ctx context.Context, arg GetJudgeTaskParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, getJudgeTask, arg.TenantID, arg.ID)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JudgerID,
		&i.SourceRef,
		&i.SourceOwnerID,
		&i.SourceCourseID,
		&i.SourceScope,
		&i.SubmitterID,
		&i.ProblemRef,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InputSnapshot,
		&i.SandboxMode,
		&i.TargetSandboxRef,
		&i.Priority,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJudgeTaskBySourceRef = `-- name: GetJudgeTaskBySourceRef :one
SELECT id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
FROM judge_task
WHERE tenant_id = $1 AND source_ref = $2 AND problem_ref = $3
`

type GetJudgeTaskBySourceRefParams struct {
	TenantID   int64  `json:"tenant_id"`
	SourceRef  string `json:"source_ref"`
	ProblemRef string `json:"problem_ref"`
}

func (q *Queries) GetJudgeTaskBySourceRef(ctx context.Context, arg GetJudgeTaskBySourceRefParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, getJudgeTaskBySourceRef, arg.TenantID, arg.SourceRef, arg.ProblemRef)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JudgerID,
		&i.SourceRef,
		&i.SourceOwnerID,
		&i.SourceCourseID,
		&i.SourceScope,
		&i.SubmitterID,
		&i.ProblemRef,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InputSnapshot,
		&i.SandboxMode,
		&i.TargetSandboxRef,
		&i.Priority,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJudgeTaskWithResult = `-- name: GetJudgeTaskWithResult :one
SELECT
    t.id, t.tenant_id, t.judger_id, t.source_ref, t.source_owner_id, t.source_course_id, t.source_scope,
    t.submitter_id, t.problem_ref, t.code_storage_key, t.code_hash,
    t.input_snapshot, t.sandbox_mode, t.target_sandbox_ref, t.priority, t.status, t.retry_count, t.max_retries, t.last_error, t.created_at, t.updated_at,
    COALESCE(r.id, 0)::bigint AS result_id,
    COALESCE(r.version, 0)::int AS result_version,
    COALESCE(r.passed, false)::boolean AS passed,
    COALESCE(r.score, 0)::int AS score,
    COALESCE(r.max_score, 0)::int AS max_score,
    COALESCE(r.details, '[]'::jsonb) AS details,
    COALESCE(r.judge_sandbox_ref, '')::varchar AS judge_sandbox_ref,
    r.judged_at,
    COALESCE(r.is_rejudge, false)::boolean AS is_rejudge
FROM judge_task t
LEFT JOIN LATERAL (
    SELECT id, version, passed, score, max_score, details, judge_sandbox_ref, judged_at, is_rejudge
    FROM judge_result
    WHERE tenant_id = t.tenant_id AND task_id = t.id
    ORDER BY version DESC
    LIMIT 1
) r ON true
WHERE t.tenant_id = $1 AND t.id = $2
`

type GetJudgeTaskWithResultParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

type GetJudgeTaskWithResultRow struct {
	ID               int64              `json:"id"`
	TenantID         int64              `json:"tenant_id"`
	JudgerID         int64              `json:"judger_id"`
	SourceRef        string             `json:"source_ref"`
	SourceOwnerID    int64              `json:"source_owner_id"`
	SourceCourseID   int64              `json:"source_course_id"`
	SourceScope      string             `json:"source_scope"`
	SubmitterID      int64              `json:"submitter_id"`
	ProblemRef       string             `json:"problem_ref"`
	CodeStorageKey   string             `json:"code_storage_key"`
	CodeHash         string             `json:"code_hash"`
	InputSnapshot    []byte             `json:"input_snapshot"`
	SandboxMode      int16              `json:"sandbox_mode"`
	TargetSandboxRef pgtype.Text        `json:"target_sandbox_ref"`
	Priority         int16              `json:"priority"`
	Status           int16              `json:"status"`
	RetryCount       int32              `json:"retry_count"`
	MaxRetries       int32              `json:"max_retries"`
	LastError        pgtype.Text        `json:"last_error"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ResultID         int64              `json:"result_id"`
	ResultVersion    int32              `json:"result_version"`
	Passed           bool               `json:"passed"`
	Score            int32              `json:"score"`
	MaxScore         int32              `json:"max_score"`
	Details          []byte             `json:"details"`
	JudgeSandboxRef  string             `json:"judge_sandbox_ref"`
	JudgedAt         pgtype.Timestamptz `json:"judged_at"`
	IsRejudge        bool               `json:"is_rejudge"`
}

func (q *Queries) GetJudgeTaskWithResult(ctx context.Context, arg GetJudgeTaskWithResultParams) (GetJudgeTaskWithResultRow, error) {
	row := q.db.QueryRow(ctx, getJudgeTaskWithResult, arg.TenantID, arg.ID)
	var i GetJudgeTaskWithResultRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JudgerID,
		&i.SourceRef,
		&i.SourceOwnerID,
		&i.SourceCourseID,
		&i.SourceScope,
		&i.SubmitterID,
		&i.ProblemRef,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InputSnapshot,
		&i.SandboxMode,
		&i.TargetSandboxRef,
		&i.Priority,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResultID,
		&i.ResultVersion,
		&i.Passed,
		&i.Score,
		&i.MaxScore,
		&i.Details,
		&i.JudgeSandboxRef,
		&i.JudgedAt,
		&i.IsRejudge,
	)
	return i, err
}

const getJudgerByCode = `-- name: GetJudgerByCode :one
SELECT id, code, name, type, executor_ref, runtime_required, default_timeout_sec, resource_spec, selftest_status, status, created_at, updated_at
FROM judger
WHERE code = $1
`

func (q *Queries) GetJudgerByCode(ctx context.Context, code string) (Judger, error) {
	row := q.db.QueryRow(ctx, getJudgerByCode, code)
	var i Judger
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.ExecutorRef,
		&i.RuntimeRequired,
		&i.DefaultTimeoutSec,
		&i.ResourceSpec,
		&i.SelftestStatus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJudgerByID = `-- name: GetJudgerByID :one
SELECT id, code, name, type, executor_ref, runtime_required, default_timeout_sec, resource_spec, selftest_status, status, created_at, updated_at
FROM judger
WHERE id = $1
`

func (q *Queries) GetJudgerByID(ctx context.Context, id int64) (Judger, error) {
	row := q.db.QueryRow(ctx, getJudgerByID, id)
	var i Judger
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.ExecutorRef,
		&i.RuntimeRequired,
		&i.DefaultTimeoutSec,
		&i.ResourceSpec,
		&i.SelftestStatus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFingerprintsForProblem = `-- name: ListFingerprintsForProblem :many
SELECT id, tenant_id, source_ref, problem_ref, submitter_id, code_hash, sim_vector, created_at
FROM submission_fingerprint
WHERE tenant_id = $1 AND problem_ref = $2 AND ($3::text = '' OR source_ref <> $3)
ORDER BY created_at DESC, id DESC
`

type ListFingerprintsForProblemParams struct {
	TenantID   int64  `json:"tenant_id"`
	ProblemRef string `json:"problem_ref"`
	Column3    string `json:"column_3"`
}

func (q *Queries) ListFingerprintsForProblem(ctx context.Context, arg ListFingerprintsForProblemParams) ([]SubmissionFingerprint, error) {
	rows, err := q.db.Query(ctx, listFingerprintsForProblem, arg.TenantID, arg.ProblemRef, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubmissionFingerprint{}
	for rows.Next() {
		var i SubmissionFingerprint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceRef,
			&i.ProblemRef,
			&i.SubmitterID,
			&i.CodeHash,
			&i.SimVector,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJudgeTasks = `-- name: ListJudgeTasks :many
SELECT
    t.id, t.tenant_id, t.judger_id, t.source_ref, t.source_owner_id, t.source_course_id, t.source_scope,
    t.submitter_id, t.problem_ref, t.code_storage_key, t.code_hash,
    t.input_snapshot, t.sandbox_mode, t.target_sandbox_ref, t.priority, t.status, t.retry_count, t.max_retries, t.last_error, t.created_at, t.updated_at,
    COALESCE(r.id, 0)::bigint AS result_id,
    COALESCE(r.version, 0)::int AS result_version,
    COALESCE(r.passed, false)::boolean AS passed,
    COALESCE(r.score, 0)::int AS score,
    COALESCE(r.max_score, 0)::int AS max_score,
    COALESCE(r.details, '[]'::jsonb) AS details,
    COALESCE(r.judge_sandbox_ref, '')::varchar AS judge_sandbox_ref,
    r.judged_at,
    COALESCE(r.is_rejudge, false)::boolean AS is_rejudge
FROM judge_task t
LEFT JOIN LATERAL (
    SELECT id, version, passed, score, max_score, details, judge_sandbox_ref, judged_at, is_rejudge
    FROM judge_result
    WHERE tenant_id = t.tenant_id AND task_id = t.id
    ORDER BY version DESC
    LIMIT 1
) r ON true
JOIN judger j ON j.id = t.judger_id
WHERE t.tenant_id = $1
  AND ($2::text = '' OR t.source_ref = $2)
  AND ($3::boolean = false OR (t.status = 2 AND j.type = 6))
  AND ($4::bigint = 0 OR t.source_owner_id = $4 OR t.submitter_id = $4)
ORDER BY t.created_at DESC, t.id DESC
LIMIT $5 OFFSET $6
`

type ListJudgeTasksParams struct {
	TenantID int64  `json:"tenant_id"`
	Column2  string `json:"column_2"`
	Column3  bool   `json:"column_3"`
	Column4  int64  `json:"column_4"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type ListJudgeTasksRow struct {
	ID               int64              `json:"id"`
	TenantID         int64              `json:"tenant_id"`
	JudgerID         int64              `json:"judger_id"`
	SourceRef        string             `json:"source_ref"`
	SourceOwnerID    int64              `json:"source_owner_id"`
	SourceCourseID   int64              `json:"source_course_id"`
	SourceScope      string             `json:"source_scope"`
	SubmitterID      int64              `json:"submitter_id"`
	ProblemRef       string             `json:"problem_ref"`
	CodeStorageKey   string             `json:"code_storage_key"`
	CodeHash         string             `json:"code_hash"`
	InputSnapshot    []byte             `json:"input_snapshot"`
	SandboxMode      int16              `json:"sandbox_mode"`
	TargetSandboxRef pgtype.Text        `json:"target_sandbox_ref"`
	Priority         int16              `json:"priority"`
	Status           int16              `json:"status"`
	RetryCount       int32              `json:"retry_count"`
	MaxRetries       int32              `json:"max_retries"`
	LastError        pgtype.Text        `json:"last_error"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ResultID         int64              `json:"result_id"`
	ResultVersion    int32              `json:"result_version"`
	Passed           bool               `json:"passed"`
	Score            int32              `json:"score"`
	MaxScore         int32              `json:"max_score"`
	Details          []byte             `json:"details"`
	JudgeSandboxRef  string             `json:"judge_sandbox_ref"`
	JudgedAt         pgtype.Timestamptz `json:"judged_at"`
	IsRejudge        bool               `json:"is_rejudge"`
}

func (q *Queries) ListJudgeTasks(ctx context.Context, arg ListJudgeTasksParams) ([]ListJudgeTasksRow, error) {
	rows, err := q.db.Query(ctx, listJudgeTasks,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJudgeTasksRow{}
	for rows.Next() {
		var i ListJudgeTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JudgerID,
			&i.SourceRef,
			&i.SourceOwnerID,
			&i.SourceCourseID,
			&i.SourceScope,
			&i.SubmitterID,
			&i.ProblemRef,
			&i.CodeStorageKey,
			&i.CodeHash,
			&i.InputSnapshot,
			&i.SandboxMode,
			&i.TargetSandboxRef,
			&i.Priority,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResultID,
			&i.ResultVersion,
			&i.Passed,
			&i.Score,
			&i.MaxScore,
			&i.Details,
			&i.JudgeSandboxRef,
			&i.JudgedAt,
			&i.IsRejudge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJudgeTasksBySourceRef = `-- name: ListJudgeTasksBySourceRef :many
SELECT id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
FROM judge_task
WHERE tenant_id = $1 AND source_ref = $2
ORDER BY created_at DESC, id DESC
`

type ListJudgeTasksBySourceRefParams struct {
	TenantID  int64  `json:"tenant_id"`
	SourceRef string `json:"source_ref"`
}

func (q *Queries) ListJudgeTasksBySourceRef(ctx context.Context, arg ListJudgeTasksBySourceRefParams) ([]JudgeTask, error) {
	rows, err := q.db.Query(ctx, listJudgeTasksBySourceRef, arg.TenantID, arg.SourceRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JudgeTask{}
	for rows.Next() {
		var i JudgeTask
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JudgerID,
			&i.SourceRef,
			&i.SourceOwnerID,
			&i.SourceCourseID,
			&i.SourceScope,
			&i.SubmitterID,
			&i.ProblemRef,
			&i.CodeStorageKey,
			&i.CodeHash,
			&i.InputSnapshot,
			&i.SandboxMode,
			&i.TargetSandboxRef,
			&i.Priority,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJudgers = `-- name: ListJudgers :many
SELECT id, code, name, type, executor_ref, runtime_required, default_timeout_sec, resource_spec, selftest_status, status, created_at, updated_at
FROM judger
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListJudgers(ctx context.Context) ([]Judger, error) {
	rows, err := q.db.Query(ctx, listJudgers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Judger{}
	for rows.Next() {
		var i Judger
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.ExecutorRef,
			&i.RuntimeRequired,
			&i.DefaultTimeoutSec,
			&i.ResourceSpec,
			&i.SelftestStatus,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJudgeOutbox = `-- name: ListPendingJudgeOutbox :many
SELECT id, tenant_id, task_id, subject, payload, status, retry_count, next_attempt_at, last_error, created_at, updated_at
FROM judge_event_outbox
WHERE status IN (1, 3) AND next_attempt_at <= now()
ORDER BY next_attempt_at ASC, created_at ASC, id ASC
LIMIT $1
`

func (q *Queries) ListPendingJudgeOutbox(ctx context.Context, limit int32) ([]JudgeEventOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingJudgeOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JudgeEventOutbox{}
	for rows.Next() {
		var i JudgeEventOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TaskID,
			&i.Subject,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentJudgeTasksBySubmitterProblem = `-- name: ListRecentJudgeTasksBySubmitterProblem :many
SELECT id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
FROM judge_task
WHERE tenant_id = $1 AND submitter_id = $2 AND problem_ref = $3 AND created_at >= now() - make_interval(secs => $4::int)
ORDER BY created_at DESC, id DESC
`

type ListRecentJudgeTasksBySubmitterProblemParams struct {
	TenantID    int64  `json:"tenant_id"`
	SubmitterID int64  `json:"submitter_id"`
	ProblemRef  string `json:"problem_ref"`
	Column4     int32  `json:"column_4"`
}

func (q *Queries) ListRecentJudgeTasksBySubmitterProblem(ctx context.Context, arg ListRecentJudgeTasksBySubmitterProblemParams) ([]JudgeTask, error) {
	rows, err := q.db.Query(ctx, listRecentJudgeTasksBySubmitterProblem,
		arg.TenantID,
		arg.SubmitterID,
		arg.ProblemRef,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JudgeTask{}
	for rows.Next() {
		var i JudgeTask
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JudgerID,
			&i.SourceRef,
			&i.SourceOwnerID,
			&i.SourceCourseID,
			&i.SourceScope,
			&i.SubmitterID,
			&i.ProblemRef,
			&i.CodeStorageKey,
			&i.CodeHash,
			&i.InputSnapshot,
			&i.SandboxMode,
			&i.TargetSandboxRef,
			&i.Priority,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJudgeOutboxFailed = `-- name: MarkJudgeOutboxFailed :one
UPDATE judge_event_outbox
SET status = 3,
    retry_count = retry_count + 1,
    next_attempt_at = now() + (LEAST(300, power(2, LEAST(retry_count + 1, 8))::int) || ' seconds')::interval,
    last_error = $3,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, task_id, subject, payload, status, retry_count, next_attempt_at, last_error, created_at, updated_at
`

type MarkJudgeOutboxFailedParams struct {
	TenantID  int64       `json:"tenant_id"`
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkJudgeOutboxFailed(ctx context.Context, arg MarkJudgeOutboxFailedParams) (JudgeEventOutbox, error) {
	row := q.db.QueryRow(ctx, markJudgeOutboxFailed, arg.TenantID, arg.ID, arg.LastError)
	var i JudgeEventOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.Subject,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markJudgeOutboxPublished = `-- name: MarkJudgeOutboxPublished :one
UPDATE judge_event_outbox
SET status = 2, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, task_id, subject, payload, status, retry_count, next_attempt_at, last_error, created_at, updated_at
`

type MarkJudgeOutboxPublishedParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) MarkJudgeOutboxPublished(ctx context.Context, arg MarkJudgeOutboxPublishedParams) (JudgeEventOutbox, error) {
	row := q.db.QueryRow(ctx, markJudgeOutboxPublished, arg.TenantID, arg.ID)
	var i JudgeEventOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.Subject,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markJudgeTaskError = `-- name: MarkJudgeTaskError :one
UPDATE judge_task
SET status = 6, last_error = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
`

type MarkJudgeTaskErrorParams struct {
	TenantID  int64       `json:"tenant_id"`
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkJudgeTaskError(ctx context.Context, arg MarkJudgeTaskErrorParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, markJudgeTaskError, arg.TenantID, arg.ID, arg.LastError)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JudgerID,
		&i.SourceRef,
		&i.SourceOwnerID,
		&i.SourceCourseID,
		&i.SourceScope,
		&i.SubmitterID,
		&i.ProblemRef,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InputSnapshot,
		&i.SandboxMode,
		&i.TargetSandboxRef,
		&i.Priority,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markJudgeTaskTimeout = `-- name: MarkJudgeTaskTimeout :one
UPDATE judge_task
SET status = 4, last_error = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
`

type MarkJudgeTaskTimeoutParams struct {
	TenantID  int64       `json:"tenant_id"`
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkJudgeTaskTimeout(ctx context.Context, arg MarkJudgeTaskTimeoutParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, markJudgeTaskTimeout, arg.TenantID, arg.ID, arg.LastError)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JudgerID,
		&i.SourceRef,
		&i.SourceOwnerID,
		&i.SourceCourseID,
		&i.SourceScope,
		&i.SubmitterID,
		&i.ProblemRef,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InputSnapshot,
		&i.SandboxMode,
		&i.TargetSandboxRef,
		&i.Priority,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetJudgeTaskForRejudge = `-- name: ResetJudgeTaskForRejudge :one
UPDATE judge_task
SET status = 1,
    retry_count = 0,
    input_snapshot = $3,
    last_error = NULL,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND status IN (3, 5)
RETURNING id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
`

type ResetJudgeTaskForRejudgeParams struct {
	TenantID      int64  `json:"tenant_id"`
	ID            int64  `json:"id"`
	InputSnapshot []byte `json:"input_snapshot"`
}

func (q *Queries) ResetJudgeTaskForRejudge(ctx context.Context, arg ResetJudgeTaskForRejudgeParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, resetJudgeTaskForRejudge, arg.TenantID, arg.ID, arg.InputSnapshot)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JudgerID,
		&i.SourceRef,
		&i.SourceOwnerID,
		&i.SourceCourseID,
		&i.SourceScope,
		&i.SubmitterID,
		&i.ProblemRef,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InputSnapshot,
		&i.SandboxMode,
		&i.TargetSandboxRef,
		&i.Priority,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryJudgeTask = `-- name: RetryJudgeTask :one
UPDATE judge_task
SET status = 1, retry_count = retry_count + 1, last_error = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, judger_id, source_ref, source_owner_id, source_course_id, source_scope, submitter_id, problem_ref, code_storage_key, code_hash, input_snapshot, sandbox_mode, target_sandbox_ref, priority, status, retry_count, max_retries, last_error, created_at, updated_at
`

type RetryJudgeTaskParams struct {
	TenantID  int64       `json:"tenant_id"`
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) RetryJudgeTask(ctx context.Context, arg RetryJudgeTaskParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, retryJudgeTask, arg.TenantID, arg.ID, arg.LastError)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JudgerID,
		&i.SourceRef,
		&i.SourceOwnerID,
		&i.SourceCourseID,
		&i.SourceScope,
		&i.SubmitterID,
		&i.ProblemRef,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InputSnapshot,
		&i.SandboxMode,
		&i.TargetSandboxRef,
		&i.Priority,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJudgerSelftest = `-- name: UpdateJudgerSelftest :one
UPDATE judger
SET selftest_status = $2, status = $3, updated_at = now()
WHERE id = $1
RETURNING id, code, name, type, executor_ref, runtime_required, default_timeout_sec, resource_spec, selftest_status, status, created_at, updated_at
`

type UpdateJudgerSelftestParams struct {
	ID             int64 `json:"id"`
	SelftestStatus int16 `json:"selftest_status"`
	Status         int16 `json:"status"`
}

func (q *Queries) UpdateJudgerSelftest(ctx context.Context, arg UpdateJudgerSelftestParams) (Judger, error) {
	row := q.db.QueryRow(ctx, updateJudgerSelftest, arg.ID, arg.SelftestStatus, arg.Status)
	var i Judger
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.ExecutorRef,
		&i.RuntimeRequired,
		&i.DefaultTimeoutSec,
		&i.ResourceSpec,
		&i.SelftestStatus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertJudgeResult = `-- name: UpsertJudgeResult :one
INSERT INTO judge_result (id, task_id, tenant_id, version, passed, score, max_score, details, judge_sandbox_ref, judged_at, is_rejudge)
VALUES (
    $1, $2, $3,
    COALESCE((SELECT max(version) + 1 FROM judge_result WHERE tenant_id = $3 AND task_id = $2), 1),
    $4, $5, $6, $7, $8, now(), $9
)
RETURNING id, task_id, tenant_id, version, passed, score, max_score, details, judge_sandbox_ref, judged_at, is_rejudge
`

type UpsertJudgeResultParams struct {
	ID              int64  `json:"id"`
	TaskID          int64  `json:"task_id"`
	TenantID        int64  `json:"tenant_id"`
	Passed          bool   `json:"passed"`
	Score           int32  `json:"score"`
	MaxScore        int32  `json:"max_score"`
	Details         []byte `json:"details"`
	JudgeSandboxRef string `json:"judge_sandbox_ref"`
	IsRejudge       bool   `json:"is_rejudge"`
}

func (q *Queries) UpsertJudgeResult(ctx context.Context, arg UpsertJudgeResultParams) (JudgeResult, error) {
	row := q.db.QueryRow(ctx, upsertJudgeResult,
		arg.ID,
		arg.TaskID,
		arg.TenantID,
		arg.Passed,
		arg.Score,
		arg.MaxScore,
		arg.Details,
		arg.JudgeSandboxRef,
		arg.IsRejudge,
	)
	var i JudgeResult
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TenantID,
		&i.Version,
		&i.Passed,
		&i.Score,
		&i.MaxScore,
		&i.Details,
		&i.JudgeSandboxRef,
		&i.JudgedAt,
		&i.IsRejudge,
	)
	return i, err
}

const upsertJudger = `-- name: UpsertJudger :one
INSERT INTO judger (id, code, name, type, executor_ref, runtime_required, default_timeout_sec, resource_spec, selftest_status, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now(), now())
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    type = EXCLUDED.type,
    executor_ref = EXCLUDED.executor_ref,
    runtime_required = EXCLUDED.runtime_required,
    default_timeout_sec = EXCLUDED.default_timeout_sec,
    resource_spec = EXCLUDED.resource_spec,
    selftest_status = EXCLUDED.selftest_status,
    status = EXCLUDED.status,
    updated_at = now()
RETURNING id, code, name, type, executor_ref, runtime_required, default_timeout_sec, resource_spec, selftest_status, status, created_at, updated_at
`

type UpsertJudgerParams struct {
	ID                int64  `json:"id"`
	Code              string `json:"code"`
	Name              string `json:"name"`
	Type              int16  `json:"type"`
	ExecutorRef       string `json:"executor_ref"`
	RuntimeRequired   bool   `json:"runtime_required"`
	DefaultTimeoutSec int32  `json:"default_timeout_sec"`
	ResourceSpec      []byte `json:"resource_spec"`
	SelftestStatus    int16  `json:"selftest_status"`
	Status            int16  `json:"status"`
}

func (q *Queries) UpsertJudger(ctx context.Context, arg UpsertJudgerParams) (Judger, error) {
	row := q.db.QueryRow(ctx, upsertJudger,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.ExecutorRef,
		arg.RuntimeRequired,
		arg.DefaultTimeoutSec,
		arg.ResourceSpec,
		arg.SelftestStatus,
		arg.Status,
	)
	var i Judger
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.ExecutorRef,
		&i.RuntimeRequired,
		&i.DefaultTimeoutSec,
		&i.ResourceSpec,
		&i.SelftestStatus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
