// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CancelQueuedJudgeTask(ctx context.Context, id int64) (JudgeTask, error)
	CreateJudgeResult(ctx context.Context, arg CreateJudgeResultParams) (JudgeResult, error)
	CreateJudgeTask(ctx context.Context, arg CreateJudgeTaskParams) (JudgeTask, error)
	// M3 judge sqlc 查询源。
	// 约定:租户表依赖 RLS 透明过滤;平台级 judger 通过 app 事务访问。
	CreateJudger(ctx context.Context, arg CreateJudgerParams) (Judger, error)
	CreateSubmissionFingerprint(ctx context.Context, arg CreateSubmissionFingerprintParams) (SubmissionFingerprint, error)
	FailJudgeTask(ctx context.Context, id int64) (JudgeTask, error)
	GetJudgeTaskByID(ctx context.Context, id int64) (JudgeTask, error)
	GetJudgeTaskBySourceRef(ctx context.Context, arg GetJudgeTaskBySourceRefParams) (JudgeTask, error)
	GetJudgeTaskWithResult(ctx context.Context, id int64) (GetJudgeTaskWithResultRow, error)
	GetJudgerByCode(ctx context.Context, code string) (Judger, error)
	GetJudgerByID(ctx context.Context, id int64) (Judger, error)
	ListExactFingerprints(ctx context.Context, arg ListExactFingerprintsParams) ([]SubmissionFingerprint, error)
	ListFingerprintsByProblem(ctx context.Context, arg ListFingerprintsByProblemParams) ([]SubmissionFingerprint, error)
	ListJudgers(ctx context.Context, arg ListJudgersParams) ([]Judger, error)
	ListManualPendingTasks(ctx context.Context, arg ListManualPendingTasksParams) ([]JudgeTask, error)
	ListTasksBySourceRef(ctx context.Context, arg ListTasksBySourceRefParams) ([]JudgeTask, error)
	MarkJudgeTaskJudging(ctx context.Context, id int64) (JudgeTask, error)
	MarkJudgeTaskRejudge(ctx context.Context, id int64) (JudgeTask, error)
	RetryJudgeTask(ctx context.Context, id int64) (JudgeTask, error)
	UpdateJudgeTaskStatus(ctx context.Context, arg UpdateJudgeTaskStatusParams) (JudgeTask, error)
	UpdateJudger(ctx context.Context, arg UpdateJudgerParams) (Judger, error)
	UpdateJudgerSelftest(ctx context.Context, arg UpdateJudgerSelftestParams) (Judger, error)
}

var _ Querier = (*Queries)(nil)
