// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CancelQueuedJudgeTask(ctx context.Context, arg CancelQueuedJudgeTaskParams) (CancelQueuedJudgeTaskRow, error)
	ClaimPendingJudgeOutbox(ctx context.Context, arg ClaimPendingJudgeOutboxParams) ([]JudgeEventOutbox, error)
	CompleteJudgeTask(ctx context.Context, arg CompleteJudgeTaskParams) (CompleteJudgeTaskRow, error)
	CompleteManualJudgeTask(ctx context.Context, arg CompleteManualJudgeTaskParams) (CompleteManualJudgeTaskRow, error)
	CountJudgeTasks(ctx context.Context, arg CountJudgeTasksParams) (int64, error)
	CreateJudgeOutbox(ctx context.Context, arg CreateJudgeOutboxParams) (JudgeEventOutbox, error)
	CreateJudgeTask(ctx context.Context, arg CreateJudgeTaskParams) (CreateJudgeTaskRow, error)
	CreateSubmissionFingerprint(ctx context.Context, arg CreateSubmissionFingerprintParams) (CreateSubmissionFingerprintRow, error)
	DequeueJudgeTasks(ctx context.Context, arg DequeueJudgeTasksParams) ([]DequeueJudgeTasksRow, error)
	ExhaustExpiredJudgeEventOutbox(ctx context.Context, arg ExhaustExpiredJudgeEventOutboxParams) (int64, error)
	FailExpiredJudgeTasks(ctx context.Context, arg FailExpiredJudgeTasksParams) ([]FailExpiredJudgeTasksRow, error)
	FailJudgeTask(ctx context.Context, arg FailJudgeTaskParams) (FailJudgeTaskRow, error)
	FindExactFingerprints(ctx context.Context, arg FindExactFingerprintsParams) ([]FindExactFingerprintsRow, error)
	GetJudgeTask(ctx context.Context, arg GetJudgeTaskParams) (GetJudgeTaskRow, error)
	GetJudgeTaskBySourceRef(ctx context.Context, arg GetJudgeTaskBySourceRefParams) (GetJudgeTaskBySourceRefRow, error)
	GetJudgeTaskWithResult(ctx context.Context, arg GetJudgeTaskWithResultParams) (GetJudgeTaskWithResultRow, error)
	GetJudgerByCode(ctx context.Context, code string) (Judger, error)
	GetJudgerByID(ctx context.Context, id int64) (Judger, error)
	// 编排目录只取判题方式的 code/name/type,不出 resource_spec 与执行引用;停用项不进可选集。
	ListCatalogJudgers(ctx context.Context) ([]ListCatalogJudgersRow, error)
	ListFingerprintsForProblem(ctx context.Context, arg ListFingerprintsForProblemParams) ([]ListFingerprintsForProblemRow, error)
	ListJudgeTasks(ctx context.Context, arg ListJudgeTasksParams) ([]ListJudgeTasksRow, error)
	ListJudgeTasksBySourceRef(ctx context.Context, arg ListJudgeTasksBySourceRefParams) ([]ListJudgeTasksBySourceRefRow, error)
	ListJudgers(ctx context.Context) ([]Judger, error)
	ListRecentJudgeTasksBySubmitterProblem(ctx context.Context, arg ListRecentJudgeTasksBySubmitterProblemParams) ([]ListRecentJudgeTasksBySubmitterProblemRow, error)
	MarkJudgeOutboxFailed(ctx context.Context, arg MarkJudgeOutboxFailedParams) (JudgeEventOutbox, error)
	MarkJudgeOutboxPublished(ctx context.Context, arg MarkJudgeOutboxPublishedParams) (JudgeEventOutbox, error)
	// 执行期心跳仅允许当前持有者延长未过期租约,避免长时判题被另一 worker 重领。
	RenewJudgeTaskLease(ctx context.Context, arg RenewJudgeTaskLeaseParams) (int64, error)
	ResetJudgeTaskForRejudge(ctx context.Context, arg ResetJudgeTaskForRejudgeParams) (ResetJudgeTaskForRejudgeRow, error)
	RetryJudgeTask(ctx context.Context, arg RetryJudgeTaskParams) (RetryJudgeTaskRow, error)
	UpdateJudgerSelftest(ctx context.Context, arg UpdateJudgerSelftestParams) (Judger, error)
	UpsertJudgeResult(ctx context.Context, arg UpsertJudgeResultParams) (JudgeResult, error)
	UpsertJudger(ctx context.Context, arg UpsertJudgerParams) (Judger, error)
}

var _ Querier = (*Queries)(nil)
