# 数据命名空间密钥同步,与系统命名空间保持同一远端密钥集合。
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chaimir-data-secret
  namespace: chaimir-data
  labels:
    app.kubernetes.io/part-of: chaimir
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: chaimir-external-secret-store
  target:
    name: chaimir-data-secret
    creationPolicy: Owner
  data:
    - secretKey: PG_PRIV_USER
      remoteRef: {key: chaimir, property: PG_PRIV_USER}
    - secretKey: PG_PRIV_PASSWORD
      remoteRef: {key: chaimir, property: PG_PRIV_PASSWORD}
    - secretKey: REDIS_PASSWORD
      remoteRef: {key: chaimir, property: REDIS_PASSWORD}
    - secretKey: MINIO_ACCESS_KEY
      remoteRef: {key: chaimir, property: MINIO_ACCESS_KEY}
    - secretKey: MINIO_SECRET_KEY
      remoteRef: {key: chaimir, property: MINIO_SECRET_KEY}
    - secretKey: NATS_TOKEN
      remoteRef: {key: chaimir, property: NATS_TOKEN}
