// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SimActionLog struct {
	ID        int64              `json:"id"`
	TenantID  int64              `json:"tenant_id"`
	SessionID int64              `json:"session_id"`
	Seq       int32              `json:"seq"`
	AtTick    int32              `json:"at_tick"`
	EventType string             `json:"event_type"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SimCheckpoint struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	SessionID    int64              `json:"session_id"`
	CheckpointID string             `json:"checkpoint_id"`
	Answer       []byte             `json:"answer"`
	Achieved     bool               `json:"achieved"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SimPackage struct {
	ID                int64              `json:"id"`
	Code              string             `json:"code"`
	Version           string             `json:"version"`
	Name              string             `json:"name"`
	Category          string             `json:"category"`
	Compute           int16              `json:"compute"`
	ScaleLimit        []byte             `json:"scale_limit"`
	BundleKey         string             `json:"bundle_key"`
	BundleHash        string             `json:"bundle_hash"`
	BackendAdapter    pgtype.Text        `json:"backend_adapter"`
	BackendConfig     []byte             `json:"backend_config"`
	InteractionSchema []byte             `json:"interaction_schema"`
	CodeTrace         []byte             `json:"code_trace"`
	AuthorType        int16              `json:"author_type"`
	AuthorID          pgtype.Int8        `json:"author_id"`
	Status            int16              `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type SimPackageReview struct {
	ID            int64              `json:"id"`
	PackageID     int64              `json:"package_id"`
	SubmitterID   int64              `json:"submitter_id"`
	PreviewReport []byte             `json:"preview_report"`
	ReviewerID    pgtype.Int8        `json:"reviewer_id"`
	Result        int16              `json:"result"`
	Comment       pgtype.Text        `json:"comment"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SimSession struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	PackageID      int64              `json:"package_id"`
	SourceRef      string             `json:"source_ref"`
	OwnerAccountID int64              `json:"owner_account_id"`
	Seed           int64              `json:"seed"`
	InitParams     []byte             `json:"init_params"`
	Compute        int16              `json:"compute"`
	Status         int16              `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SimShare struct {
	ID        int64              `json:"id"`
	TenantID  int64              `json:"tenant_id"`
	SessionID int64              `json:"session_id"`
	Code      string             `json:"code"`
	CreatedBy int64              `json:"created_by"`
	Status    int16              `json:"status"`
	ExpireAt  pgtype.Timestamptz `json:"expire_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
