// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	ArchiveSimSession(ctx context.Context, arg ArchiveSimSessionParams) (SimSession, error)
	ArchiveSimSessionsBySourceRef(ctx context.Context, arg ArchiveSimSessionsBySourceRefParams) ([]SimSession, error)
	CompleteSimReview(ctx context.Context, arg CompleteSimReviewParams) (SimPackageReview, error)
	CountSimPackages(ctx context.Context, arg CountSimPackagesParams) (int64, error)
	CountSimReviews(ctx context.Context, dollar_1 int16) (int64, error)
	CreateSimAction(ctx context.Context, arg CreateSimActionParams) (SimActionLog, error)
	CreateSimPackage(ctx context.Context, arg CreateSimPackageParams) (SimPackage, error)
	CreateSimPackageReview(ctx context.Context, arg CreateSimPackageReviewParams) (SimPackageReview, error)
	CreateSimSession(ctx context.Context, arg CreateSimSessionParams) (SimSession, error)
	CreateSimShare(ctx context.Context, arg CreateSimShareParams) (SimShare, error)
	GetLastSimAction(ctx context.Context, arg GetLastSimActionParams) (SimActionLog, error)
	GetLatestSimReviewForPackage(ctx context.Context, packageID int64) (SimPackageReview, error)
	GetSimActionBySeq(ctx context.Context, arg GetSimActionBySeqParams) (SimActionLog, error)
	GetSimPackageByCodeVersion(ctx context.Context, arg GetSimPackageByCodeVersionParams) (SimPackage, error)
	GetSimPackageByID(ctx context.Context, id int64) (SimPackage, error)
	GetSimReviewByID(ctx context.Context, id int64) (SimPackageReview, error)
	GetSimSession(ctx context.Context, arg GetSimSessionParams) (SimSession, error)
	GetSimSessionWithPackage(ctx context.Context, arg GetSimSessionWithPackageParams) (GetSimSessionWithPackageRow, error)
	GetSimShareByCode(ctx context.Context, code string) (SimShare, error)
	ListSimActions(ctx context.Context, arg ListSimActionsParams) ([]SimActionLog, error)
	ListSimPackageVersions(ctx context.Context, code string) ([]SimPackage, error)
	ListSimPackages(ctx context.Context, arg ListSimPackagesParams) ([]SimPackage, error)
	ListSimReviews(ctx context.Context, arg ListSimReviewsParams) ([]ListSimReviewsRow, error)
	MergeSimValidationReport(ctx context.Context, arg MergeSimValidationReportParams) (SimPackageReview, error)
	UpdateSimPackageDraft(ctx context.Context, arg UpdateSimPackageDraftParams) (SimPackage, error)
	UpdateSimPackageStatus(ctx context.Context, arg UpdateSimPackageStatusParams) (SimPackage, error)
	UpdateSimSessionStatus(ctx context.Context, arg UpdateSimSessionStatusParams) (SimSession, error)
	UpsertSimCheckpoint(ctx context.Context, arg UpsertSimCheckpointParams) (SimCheckpoint, error)
}

var _ Querier = (*Queries)(nil)
