// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sim.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveSimSessionsBySourceRef = `-- name: ArchiveSimSessionsBySourceRef :many
UPDATE sim_session
SET status = 5, updated_at = now()
WHERE tenant_id = $1 AND source_ref = $2 AND status IN (1, 2, 3, 4)
RETURNING id, tenant_id, package_id, source_ref, owner_account_id, seed, init_params, compute, status, created_at, updated_at
`

type ArchiveSimSessionsBySourceRefParams struct {
	TenantID  int64  `json:"tenant_id"`
	SourceRef string `json:"source_ref"`
}

func (q *Queries) ArchiveSimSessionsBySourceRef(ctx context.Context, arg ArchiveSimSessionsBySourceRefParams) ([]SimSession, error) {
	rows, err := q.db.Query(ctx, archiveSimSessionsBySourceRef, arg.TenantID, arg.SourceRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimSession{}
	for rows.Next() {
		var i SimSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PackageID,
			&i.SourceRef,
			&i.OwnerAccountID,
			&i.Seed,
			&i.InitParams,
			&i.Compute,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeSimReview = `-- name: CompleteSimReview :one
UPDATE sim_package_review
SET result = $2,
    reviewer_id = $3,
    comment = $4,
    updated_at = now()
WHERE id = $1 AND result = 1
RETURNING id, package_id, submitter_id, preview_report, reviewer_id, result, comment, created_at, updated_at
`

type CompleteSimReviewParams struct {
	ID         int64       `json:"id"`
	Result     int16       `json:"result"`
	ReviewerID pgtype.Int8 `json:"reviewer_id"`
	Comment    pgtype.Text `json:"comment"`
}

func (q *Queries) CompleteSimReview(ctx context.Context, arg CompleteSimReviewParams) (SimPackageReview, error) {
	row := q.db.QueryRow(ctx, completeSimReview,
		arg.ID,
		arg.Result,
		arg.ReviewerID,
		arg.Comment,
	)
	var i SimPackageReview
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.SubmitterID,
		&i.PreviewReport,
		&i.ReviewerID,
		&i.Result,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countSimPackages = `-- name: CountSimPackages :one
SELECT COUNT(*)::bigint
FROM sim_package
WHERE ($1::smallint = 0 OR status = $1)
  AND ($2::text = '' OR category = $2)
  AND ($3::text = '' OR code ILIKE '%' || $3 || '%' OR name ILIKE '%' || $3 || '%')
`

type CountSimPackagesParams struct {
	Column1 int16  `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) CountSimPackages(ctx context.Context, arg CountSimPackagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSimPackages, arg.Column1, arg.Column2, arg.Column3)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSimReviews = `-- name: CountSimReviews :one
SELECT COUNT(*)::bigint
FROM sim_package_review
WHERE ($1::smallint = 0 OR result = $1)
`

func (q *Queries) CountSimReviews(ctx context.Context, dollar_1 int16) (int64, error) {
	row := q.db.QueryRow(ctx, countSimReviews, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSimAction = `-- name: CreateSimAction :one
INSERT INTO sim_action_log (id, tenant_id, session_id, seq, at_tick, event_type, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
RETURNING id, tenant_id, session_id, seq, at_tick, event_type, payload, created_at
`

type CreateSimActionParams struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	SessionID int64  `json:"session_id"`
	Seq       int32  `json:"seq"`
	AtTick    int32  `json:"at_tick"`
	EventType string `json:"event_type"`
	Payload   []byte `json:"payload"`
}

func (q *Queries) CreateSimAction(ctx context.Context, arg CreateSimActionParams) (SimActionLog, error) {
	row := q.db.QueryRow(ctx, createSimAction,
		arg.ID,
		arg.TenantID,
		arg.SessionID,
		arg.Seq,
		arg.AtTick,
		arg.EventType,
		arg.Payload,
	)
	var i SimActionLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SessionID,
		&i.Seq,
		&i.AtTick,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createSimPackage = `-- name: CreateSimPackage :one
INSERT INTO sim_package (
    id, code, version, name, category, compute, scale_limit, bundle_key, bundle_hash,
    backend_adapter, backend_config, interaction_schema, code_trace, author_type, author_id, status, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, now(), now())
RETURNING id, code, version, name, category, compute, scale_limit, bundle_key, bundle_hash,
          backend_adapter, backend_config, interaction_schema, code_trace, author_type, author_id, status, created_at, updated_at
`

type CreateSimPackageParams struct {
	ID                int64       `json:"id"`
	Code              string      `json:"code"`
	Version           string      `json:"version"`
	Name              string      `json:"name"`
	Category          string      `json:"category"`
	Compute           int16       `json:"compute"`
	ScaleLimit        []byte      `json:"scale_limit"`
	BundleKey         string      `json:"bundle_key"`
	BundleHash        string      `json:"bundle_hash"`
	BackendAdapter    pgtype.Text `json:"backend_adapter"`
	BackendConfig     []byte      `json:"backend_config"`
	InteractionSchema []byte      `json:"interaction_schema"`
	CodeTrace         []byte      `json:"code_trace"`
	AuthorType        int16       `json:"author_type"`
	AuthorID          pgtype.Int8 `json:"author_id"`
	Status            int16       `json:"status"`
}

func (q *Queries) CreateSimPackage(ctx context.Context, arg CreateSimPackageParams) (SimPackage, error) {
	row := q.db.QueryRow(ctx, createSimPackage,
		arg.ID,
		arg.Code,
		arg.Version,
		arg.Name,
		arg.Category,
		arg.Compute,
		arg.ScaleLimit,
		arg.BundleKey,
		arg.BundleHash,
		arg.BackendAdapter,
		arg.BackendConfig,
		arg.InteractionSchema,
		arg.CodeTrace,
		arg.AuthorType,
		arg.AuthorID,
		arg.Status,
	)
	var i SimPackage
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Version,
		&i.Name,
		&i.Category,
		&i.Compute,
		&i.ScaleLimit,
		&i.BundleKey,
		&i.BundleHash,
		&i.BackendAdapter,
		&i.BackendConfig,
		&i.InteractionSchema,
		&i.CodeTrace,
		&i.AuthorType,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSimPackageReview = `-- name: CreateSimPackageReview :one
INSERT INTO sim_package_review (id, package_id, submitter_id, preview_report, reviewer_id, result, comment, created_at, updated_at)
VALUES ($1, $2, $3, $4, NULL, 1, NULL, now(), now())
RETURNING id, package_id, submitter_id, preview_report, reviewer_id, result, comment, created_at, updated_at
`

type CreateSimPackageReviewParams struct {
	ID            int64  `json:"id"`
	PackageID     int64  `json:"package_id"`
	SubmitterID   int64  `json:"submitter_id"`
	PreviewReport []byte `json:"preview_report"`
}

func (q *Queries) CreateSimPackageReview(ctx context.Context, arg CreateSimPackageReviewParams) (SimPackageReview, error) {
	row := q.db.QueryRow(ctx, createSimPackageReview,
		arg.ID,
		arg.PackageID,
		arg.SubmitterID,
		arg.PreviewReport,
	)
	var i SimPackageReview
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.SubmitterID,
		&i.PreviewReport,
		&i.ReviewerID,
		&i.Result,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSimSession = `-- name: CreateSimSession :one
INSERT INTO sim_session (id, tenant_id, package_id, source_ref, owner_account_id, seed, init_params, compute, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now())
RETURNING id, tenant_id, package_id, source_ref, owner_account_id, seed, init_params, compute, status, created_at, updated_at
`

type CreateSimSessionParams struct {
	ID             int64  `json:"id"`
	TenantID       int64  `json:"tenant_id"`
	PackageID      int64  `json:"package_id"`
	SourceRef      string `json:"source_ref"`
	OwnerAccountID int64  `json:"owner_account_id"`
	Seed           int64  `json:"seed"`
	InitParams     []byte `json:"init_params"`
	Compute        int16  `json:"compute"`
	Status         int16  `json:"status"`
}

func (q *Queries) CreateSimSession(ctx context.Context, arg CreateSimSessionParams) (SimSession, error) {
	row := q.db.QueryRow(ctx, createSimSession,
		arg.ID,
		arg.TenantID,
		arg.PackageID,
		arg.SourceRef,
		arg.OwnerAccountID,
		arg.Seed,
		arg.InitParams,
		arg.Compute,
		arg.Status,
	)
	var i SimSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PackageID,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Seed,
		&i.InitParams,
		&i.Compute,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSimShare = `-- name: CreateSimShare :one
INSERT INTO sim_share (id, tenant_id, session_id, code, created_by, status, expire_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 1, $6, now(), now())
RETURNING id, tenant_id, session_id, code, created_by, status, expire_at, created_at, updated_at
`

type CreateSimShareParams struct {
	ID        int64              `json:"id"`
	TenantID  int64              `json:"tenant_id"`
	SessionID int64              `json:"session_id"`
	Code      string             `json:"code"`
	CreatedBy int64              `json:"created_by"`
	ExpireAt  pgtype.Timestamptz `json:"expire_at"`
}

func (q *Queries) CreateSimShare(ctx context.Context, arg CreateSimShareParams) (SimShare, error) {
	row := q.db.QueryRow(ctx, createSimShare,
		arg.ID,
		arg.TenantID,
		arg.SessionID,
		arg.Code,
		arg.CreatedBy,
		arg.ExpireAt,
	)
	var i SimShare
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SessionID,
		&i.Code,
		&i.CreatedBy,
		&i.Status,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastSimAction = `-- name: GetLastSimAction :one
SELECT id, tenant_id, session_id, seq, at_tick, event_type, payload, created_at
FROM sim_action_log
WHERE tenant_id = $1 AND session_id = $2
ORDER BY seq DESC
LIMIT 1
`

type GetLastSimActionParams struct {
	TenantID  int64 `json:"tenant_id"`
	SessionID int64 `json:"session_id"`
}

func (q *Queries) GetLastSimAction(ctx context.Context, arg GetLastSimActionParams) (SimActionLog, error) {
	row := q.db.QueryRow(ctx, getLastSimAction, arg.TenantID, arg.SessionID)
	var i SimActionLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SessionID,
		&i.Seq,
		&i.AtTick,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSimReviewForPackage = `-- name: GetLatestSimReviewForPackage :one
SELECT id, package_id, submitter_id, preview_report, reviewer_id, result, comment, created_at, updated_at
FROM sim_package_review
WHERE package_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestSimReviewForPackage(ctx context.Context, packageID int64) (SimPackageReview, error) {
	row := q.db.QueryRow(ctx, getLatestSimReviewForPackage, packageID)
	var i SimPackageReview
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.SubmitterID,
		&i.PreviewReport,
		&i.ReviewerID,
		&i.Result,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSimActionBySeq = `-- name: GetSimActionBySeq :one
SELECT id, tenant_id, session_id, seq, at_tick, event_type, payload, created_at
FROM sim_action_log
WHERE tenant_id = $1 AND session_id = $2 AND seq = $3
`

type GetSimActionBySeqParams struct {
	TenantID  int64 `json:"tenant_id"`
	SessionID int64 `json:"session_id"`
	Seq       int32 `json:"seq"`
}

func (q *Queries) GetSimActionBySeq(ctx context.Context, arg GetSimActionBySeqParams) (SimActionLog, error) {
	row := q.db.QueryRow(ctx, getSimActionBySeq, arg.TenantID, arg.SessionID, arg.Seq)
	var i SimActionLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SessionID,
		&i.Seq,
		&i.AtTick,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getSimPackageByCodeVersion = `-- name: GetSimPackageByCodeVersion :one
SELECT id, code, version, name, category, compute, scale_limit, bundle_key, bundle_hash,
       backend_adapter, backend_config, interaction_schema, code_trace, author_type, author_id, status, created_at, updated_at
FROM sim_package
WHERE code = $1 AND version = $2
`

type GetSimPackageByCodeVersionParams struct {
	Code    string `json:"code"`
	Version string `json:"version"`
}

func (q *Queries) GetSimPackageByCodeVersion(ctx context.Context, arg GetSimPackageByCodeVersionParams) (SimPackage, error) {
	row := q.db.QueryRow(ctx, getSimPackageByCodeVersion, arg.Code, arg.Version)
	var i SimPackage
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Version,
		&i.Name,
		&i.Category,
		&i.Compute,
		&i.ScaleLimit,
		&i.BundleKey,
		&i.BundleHash,
		&i.BackendAdapter,
		&i.BackendConfig,
		&i.InteractionSchema,
		&i.CodeTrace,
		&i.AuthorType,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSimPackageByID = `-- name: GetSimPackageByID :one
SELECT id, code, version, name, category, compute, scale_limit, bundle_key, bundle_hash,
       backend_adapter, backend_config, interaction_schema, code_trace, author_type, author_id, status, created_at, updated_at
FROM sim_package
WHERE id = $1
`

func (q *Queries) GetSimPackageByID(ctx context.Context, id int64) (SimPackage, error) {
	row := q.db.QueryRow(ctx, getSimPackageByID, id)
	var i SimPackage
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Version,
		&i.Name,
		&i.Category,
		&i.Compute,
		&i.ScaleLimit,
		&i.BundleKey,
		&i.BundleHash,
		&i.BackendAdapter,
		&i.BackendConfig,
		&i.InteractionSchema,
		&i.CodeTrace,
		&i.AuthorType,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSimReviewByID = `-- name: GetSimReviewByID :one
SELECT id, package_id, submitter_id, preview_report, reviewer_id, result, comment, created_at, updated_at
FROM sim_package_review
WHERE id = $1
`

func (q *Queries) GetSimReviewByID(ctx context.Context, id int64) (SimPackageReview, error) {
	row := q.db.QueryRow(ctx, getSimReviewByID, id)
	var i SimPackageReview
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.SubmitterID,
		&i.PreviewReport,
		&i.ReviewerID,
		&i.Result,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSimSession = `-- name: GetSimSession :one
SELECT id, tenant_id, package_id, source_ref, owner_account_id, seed, init_params, compute, status, created_at, updated_at
FROM sim_session
WHERE tenant_id = $1 AND id = $2
`

type GetSimSessionParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetSimSession(ctx context.Context, arg GetSimSessionParams) (SimSession, error) {
	row := q.db.QueryRow(ctx, getSimSession, arg.TenantID, arg.ID)
	var i SimSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PackageID,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Seed,
		&i.InitParams,
		&i.Compute,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSimSessionWithPackage = `-- name: GetSimSessionWithPackage :one
SELECT s.id, s.tenant_id, s.package_id, s.source_ref, s.owner_account_id, s.seed, s.init_params, s.compute, s.status, s.created_at, s.updated_at,
       p.code, p.version, p.name, p.category, p.scale_limit, p.bundle_key, p.bundle_hash, p.backend_adapter, p.backend_config,
       p.interaction_schema, p.status AS package_status
FROM sim_session s
JOIN sim_package p ON p.id = s.package_id
WHERE s.tenant_id = $1 AND s.id = $2
`

type GetSimSessionWithPackageParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

type GetSimSessionWithPackageRow struct {
	ID                int64              `json:"id"`
	TenantID          int64              `json:"tenant_id"`
	PackageID         int64              `json:"package_id"`
	SourceRef         string             `json:"source_ref"`
	OwnerAccountID    int64              `json:"owner_account_id"`
	Seed              int64              `json:"seed"`
	InitParams        []byte             `json:"init_params"`
	Compute           int16              `json:"compute"`
	Status            int16              `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Code              string             `json:"code"`
	Version           string             `json:"version"`
	Name              string             `json:"name"`
	Category          string             `json:"category"`
	ScaleLimit        []byte             `json:"scale_limit"`
	BundleKey         string             `json:"bundle_key"`
	BundleHash        string             `json:"bundle_hash"`
	BackendAdapter    pgtype.Text        `json:"backend_adapter"`
	BackendConfig     []byte             `json:"backend_config"`
	InteractionSchema []byte             `json:"interaction_schema"`
	PackageStatus     int16              `json:"package_status"`
}

func (q *Queries) GetSimSessionWithPackage(ctx context.Context, arg GetSimSessionWithPackageParams) (GetSimSessionWithPackageRow, error) {
	row := q.db.QueryRow(ctx, getSimSessionWithPackage, arg.TenantID, arg.ID)
	var i GetSimSessionWithPackageRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PackageID,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Seed,
		&i.InitParams,
		&i.Compute,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
		&i.Version,
		&i.Name,
		&i.Category,
		&i.ScaleLimit,
		&i.BundleKey,
		&i.BundleHash,
		&i.BackendAdapter,
		&i.BackendConfig,
		&i.InteractionSchema,
		&i.PackageStatus,
	)
	return i, err
}

const getSimShareByCode = `-- name: GetSimShareByCode :one
SELECT id, tenant_id, session_id, code, created_by, status, expire_at, created_at, updated_at
FROM sim_share
WHERE code = $1
`

func (q *Queries) GetSimShareByCode(ctx context.Context, code string) (SimShare, error) {
	row := q.db.QueryRow(ctx, getSimShareByCode, code)
	var i SimShare
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SessionID,
		&i.Code,
		&i.CreatedBy,
		&i.Status,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSimActions = `-- name: ListSimActions :many
SELECT id, tenant_id, session_id, seq, at_tick, event_type, payload, created_at
FROM sim_action_log
WHERE tenant_id = $1 AND session_id = $2
ORDER BY seq ASC
`

type ListSimActionsParams struct {
	TenantID  int64 `json:"tenant_id"`
	SessionID int64 `json:"session_id"`
}

func (q *Queries) ListSimActions(ctx context.Context, arg ListSimActionsParams) ([]SimActionLog, error) {
	rows, err := q.db.Query(ctx, listSimActions, arg.TenantID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimActionLog{}
	for rows.Next() {
		var i SimActionLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SessionID,
			&i.Seq,
			&i.AtTick,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimPackageVersions = `-- name: ListSimPackageVersions :many
SELECT id, code, version, name, category, compute, scale_limit, bundle_key, bundle_hash,
       backend_adapter, backend_config, interaction_schema, code_trace, author_type, author_id, status, created_at, updated_at
FROM sim_package
WHERE code = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListSimPackageVersions(ctx context.Context, code string) ([]SimPackage, error) {
	rows, err := q.db.Query(ctx, listSimPackageVersions, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimPackage{}
	for rows.Next() {
		var i SimPackage
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Version,
			&i.Name,
			&i.Category,
			&i.Compute,
			&i.ScaleLimit,
			&i.BundleKey,
			&i.BundleHash,
			&i.BackendAdapter,
			&i.BackendConfig,
			&i.InteractionSchema,
			&i.CodeTrace,
			&i.AuthorType,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimPackages = `-- name: ListSimPackages :many
SELECT id, code, version, name, category, compute, scale_limit, bundle_key, bundle_hash,
       backend_adapter, backend_config, interaction_schema, code_trace, author_type, author_id, status, created_at, updated_at
FROM sim_package
WHERE ($1::smallint = 0 OR status = $1)
  AND ($2::text = '' OR category = $2)
  AND ($3::text = '' OR code ILIKE '%' || $3 || '%' OR name ILIKE '%' || $3 || '%')
ORDER BY updated_at DESC, id DESC
LIMIT $4 OFFSET $5
`

type ListSimPackagesParams struct {
	Column1 int16  `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListSimPackages(ctx context.Context, arg ListSimPackagesParams) ([]SimPackage, error) {
	rows, err := q.db.Query(ctx, listSimPackages,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimPackage{}
	for rows.Next() {
		var i SimPackage
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Version,
			&i.Name,
			&i.Category,
			&i.Compute,
			&i.ScaleLimit,
			&i.BundleKey,
			&i.BundleHash,
			&i.BackendAdapter,
			&i.BackendConfig,
			&i.InteractionSchema,
			&i.CodeTrace,
			&i.AuthorType,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimReviews = `-- name: ListSimReviews :many
SELECT r.id, r.package_id, r.submitter_id, r.preview_report, r.reviewer_id, r.result, r.comment, r.created_at, r.updated_at,
       p.code, p.version, p.name, p.category, p.compute, p.status
FROM sim_package_review r
JOIN sim_package p ON p.id = r.package_id
WHERE ($1::smallint = 0 OR r.result = $1)
ORDER BY r.created_at ASC, r.id ASC
LIMIT $2 OFFSET $3
`

type ListSimReviewsParams struct {
	Column1 int16 `json:"column_1"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type ListSimReviewsRow struct {
	ID            int64              `json:"id"`
	PackageID     int64              `json:"package_id"`
	SubmitterID   int64              `json:"submitter_id"`
	PreviewReport []byte             `json:"preview_report"`
	ReviewerID    pgtype.Int8        `json:"reviewer_id"`
	Result        int16              `json:"result"`
	Comment       pgtype.Text        `json:"comment"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Code          string             `json:"code"`
	Version       string             `json:"version"`
	Name          string             `json:"name"`
	Category      string             `json:"category"`
	Compute       int16              `json:"compute"`
	Status        int16              `json:"status"`
}

func (q *Queries) ListSimReviews(ctx context.Context, arg ListSimReviewsParams) ([]ListSimReviewsRow, error) {
	rows, err := q.db.Query(ctx, listSimReviews, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSimReviewsRow{}
	for rows.Next() {
		var i ListSimReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.SubmitterID,
			&i.PreviewReport,
			&i.ReviewerID,
			&i.Result,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Code,
			&i.Version,
			&i.Name,
			&i.Category,
			&i.Compute,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeSimValidationReport = `-- name: MergeSimValidationReport :one
UPDATE sim_package_review
SET preview_report = preview_report || $2,
    updated_at = now()
WHERE package_id = $1 AND result = 1
RETURNING id, package_id, submitter_id, preview_report, reviewer_id, result, comment, created_at, updated_at
`

type MergeSimValidationReportParams struct {
	PackageID     int64  `json:"package_id"`
	PreviewReport []byte `json:"preview_report"`
}

func (q *Queries) MergeSimValidationReport(ctx context.Context, arg MergeSimValidationReportParams) (SimPackageReview, error) {
	row := q.db.QueryRow(ctx, mergeSimValidationReport, arg.PackageID, arg.PreviewReport)
	var i SimPackageReview
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.SubmitterID,
		&i.PreviewReport,
		&i.ReviewerID,
		&i.Result,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSimPackageDraft = `-- name: UpdateSimPackageDraft :one
UPDATE sim_package
SET name = $2,
    category = $3,
    compute = $4,
    scale_limit = $5,
    bundle_key = $6,
    bundle_hash = $7,
    backend_adapter = $8,
    backend_config = $9,
    interaction_schema = $10,
    code_trace = $11,
    status = $12,
    updated_at = now()
WHERE id = $1 AND status IN (1, 5)
RETURNING id, code, version, name, category, compute, scale_limit, bundle_key, bundle_hash,
          backend_adapter, backend_config, interaction_schema, code_trace, author_type, author_id, status, created_at, updated_at
`

type UpdateSimPackageDraftParams struct {
	ID                int64       `json:"id"`
	Name              string      `json:"name"`
	Category          string      `json:"category"`
	Compute           int16       `json:"compute"`
	ScaleLimit        []byte      `json:"scale_limit"`
	BundleKey         string      `json:"bundle_key"`
	BundleHash        string      `json:"bundle_hash"`
	BackendAdapter    pgtype.Text `json:"backend_adapter"`
	BackendConfig     []byte      `json:"backend_config"`
	InteractionSchema []byte      `json:"interaction_schema"`
	CodeTrace         []byte      `json:"code_trace"`
	Status            int16       `json:"status"`
}

func (q *Queries) UpdateSimPackageDraft(ctx context.Context, arg UpdateSimPackageDraftParams) (SimPackage, error) {
	row := q.db.QueryRow(ctx, updateSimPackageDraft,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Compute,
		arg.ScaleLimit,
		arg.BundleKey,
		arg.BundleHash,
		arg.BackendAdapter,
		arg.BackendConfig,
		arg.InteractionSchema,
		arg.CodeTrace,
		arg.Status,
	)
	var i SimPackage
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Version,
		&i.Name,
		&i.Category,
		&i.Compute,
		&i.ScaleLimit,
		&i.BundleKey,
		&i.BundleHash,
		&i.BackendAdapter,
		&i.BackendConfig,
		&i.InteractionSchema,
		&i.CodeTrace,
		&i.AuthorType,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSimPackageStatus = `-- name: UpdateSimPackageStatus :one
UPDATE sim_package
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, code, version, name, category, compute, scale_limit, bundle_key, bundle_hash,
          backend_adapter, backend_config, interaction_schema, code_trace, author_type, author_id, status, created_at, updated_at
`

type UpdateSimPackageStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) UpdateSimPackageStatus(ctx context.Context, arg UpdateSimPackageStatusParams) (SimPackage, error) {
	row := q.db.QueryRow(ctx, updateSimPackageStatus, arg.ID, arg.Status)
	var i SimPackage
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Version,
		&i.Name,
		&i.Category,
		&i.Compute,
		&i.ScaleLimit,
		&i.BundleKey,
		&i.BundleHash,
		&i.BackendAdapter,
		&i.BackendConfig,
		&i.InteractionSchema,
		&i.CodeTrace,
		&i.AuthorType,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSimSessionStatus = `-- name: UpdateSimSessionStatus :one
UPDATE sim_session
SET status = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
  AND status IN (1, 2, 3, 4)
  AND $3 IN (2, 3, 4, 5, 6)
RETURNING id, tenant_id, package_id, source_ref, owner_account_id, seed, init_params, compute, status, created_at, updated_at
`

type UpdateSimSessionStatusParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
	Status   int16 `json:"status"`
}

func (q *Queries) UpdateSimSessionStatus(ctx context.Context, arg UpdateSimSessionStatusParams) (SimSession, error) {
	row := q.db.QueryRow(ctx, updateSimSessionStatus, arg.TenantID, arg.ID, arg.Status)
	var i SimSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PackageID,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Seed,
		&i.InitParams,
		&i.Compute,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSimCheckpoint = `-- name: UpsertSimCheckpoint :one
INSERT INTO sim_checkpoint (id, tenant_id, session_id, checkpoint_id, answer, achieved, created_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (tenant_id, session_id, checkpoint_id) DO UPDATE
SET answer = EXCLUDED.answer,
    achieved = EXCLUDED.achieved,
    created_at = now()
RETURNING id, tenant_id, session_id, checkpoint_id, answer, achieved, created_at
`

type UpsertSimCheckpointParams struct {
	ID           int64  `json:"id"`
	TenantID     int64  `json:"tenant_id"`
	SessionID    int64  `json:"session_id"`
	CheckpointID string `json:"checkpoint_id"`
	Answer       []byte `json:"answer"`
	Achieved     bool   `json:"achieved"`
}

func (q *Queries) UpsertSimCheckpoint(ctx context.Context, arg UpsertSimCheckpointParams) (SimCheckpoint, error) {
	row := q.db.QueryRow(ctx, upsertSimCheckpoint,
		arg.ID,
		arg.TenantID,
		arg.SessionID,
		arg.CheckpointID,
		arg.Answer,
		arg.Achieved,
	)
	var i SimCheckpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SessionID,
		&i.CheckpointID,
		&i.Answer,
		&i.Achieved,
		&i.CreatedAt,
	)
	return i, err
}
