// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contest.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_member (id, tenant_id, team_id, account_id, member_tenant_id, is_leader)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, team_id, account_id) DO UPDATE SET is_leader = EXCLUDED.is_leader
RETURNING id, tenant_id, team_id, account_id, member_tenant_id, is_leader
`

type AddTeamMemberParams struct {
	ID             int64 `json:"id"`
	TenantID       int64 `json:"tenant_id"`
	TeamID         int64 `json:"team_id"`
	AccountID      int64 `json:"account_id"`
	MemberTenantID int64 `json:"member_tenant_id"`
	IsLeader       bool  `json:"is_leader"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember,
		arg.ID,
		arg.TenantID,
		arg.TeamID,
		arg.AccountID,
		arg.MemberTenantID,
		arg.IsLeader,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.AccountID,
		&i.MemberTenantID,
		&i.IsLeader,
	)
	return i, err
}

const countActiveContests = `-- name: CountActiveContests :one
SELECT count(*)::bigint FROM contest WHERE deleted_at IS NULL AND status IN (2, 3, 4)
`

func (q *Queries) CountActiveContests(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveContests)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countContestTeams = `-- name: CountContestTeams :one
SELECT count(*)::bigint FROM team
`

func (q *Queries) CountContestTeams(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countContestTeams)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countContests = `-- name: CountContests :one
SELECT count(*)::bigint FROM contest WHERE deleted_at IS NULL AND ($1::smallint IS NULL OR status = $1)
`

func (q *Queries) CountContests(ctx context.Context, status pgtype.Int2) (int64, error) {
	row := q.db.QueryRow(ctx, countContests, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createBattleEntry = `-- name: CreateBattleEntry :one
WITH disabled AS (
  UPDATE battle_entry SET is_active = false WHERE contest_id = $3 AND team_id = $4 AND role = $5
)
INSERT INTO battle_entry (id, tenant_id, contest_id, team_id, role, artifact_ref, version_no, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, true)
RETURNING id, tenant_id, contest_id, team_id, role, artifact_ref, version_no, is_active, submitted_at
`

type CreateBattleEntryParams struct {
	ID          int64  `json:"id"`
	TenantID    int64  `json:"tenant_id"`
	ContestID   int64  `json:"contest_id"`
	TeamID      int64  `json:"team_id"`
	Role        int16  `json:"role"`
	ArtifactRef string `json:"artifact_ref"`
	VersionNo   int32  `json:"version_no"`
}

func (q *Queries) CreateBattleEntry(ctx context.Context, arg CreateBattleEntryParams) (BattleEntry, error) {
	row := q.db.QueryRow(ctx, createBattleEntry,
		arg.ID,
		arg.TenantID,
		arg.ContestID,
		arg.TeamID,
		arg.Role,
		arg.ArtifactRef,
		arg.VersionNo,
	)
	var i BattleEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.TeamID,
		&i.Role,
		&i.ArtifactRef,
		&i.VersionNo,
		&i.IsActive,
		&i.SubmittedAt,
	)
	return i, err
}

const createBattleMatch = `-- name: CreateBattleMatch :one
INSERT INTO battle_match (id, tenant_id, contest_id, entry_a_id, entry_b_id, sandbox_ref, result, score_delta, replay_ref, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
RETURNING id, tenant_id, contest_id, entry_a_id, entry_b_id, sandbox_ref, result, score_delta, replay_ref, matched_at, finished_at
`

type CreateBattleMatchParams struct {
	ID         int64  `json:"id"`
	TenantID   int64  `json:"tenant_id"`
	ContestID  int64  `json:"contest_id"`
	EntryAID   int64  `json:"entry_a_id"`
	EntryBID   int64  `json:"entry_b_id"`
	SandboxRef string `json:"sandbox_ref"`
	Result     int16  `json:"result"`
	ScoreDelta []byte `json:"score_delta"`
	ReplayRef  string `json:"replay_ref"`
}

func (q *Queries) CreateBattleMatch(ctx context.Context, arg CreateBattleMatchParams) (BattleMatch, error) {
	row := q.db.QueryRow(ctx, createBattleMatch,
		arg.ID,
		arg.TenantID,
		arg.ContestID,
		arg.EntryAID,
		arg.EntryBID,
		arg.SandboxRef,
		arg.Result,
		arg.ScoreDelta,
		arg.ReplayRef,
	)
	var i BattleMatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.EntryAID,
		&i.EntryBID,
		&i.SandboxRef,
		&i.Result,
		&i.ScoreDelta,
		&i.ReplayRef,
		&i.MatchedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createCheatRecord = `-- name: CreateCheatRecord :one
INSERT INTO cheat_record (id, tenant_id, contest_id, team_id, type, evidence, action, operator_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, contest_id, team_id, type, evidence, action, operator_id, created_at
`

type CreateCheatRecordParams struct {
	ID         int64       `json:"id"`
	TenantID   int64       `json:"tenant_id"`
	ContestID  int64       `json:"contest_id"`
	TeamID     int64       `json:"team_id"`
	Type       int16       `json:"type"`
	Evidence   []byte      `json:"evidence"`
	Action     int16       `json:"action"`
	OperatorID pgtype.Int8 `json:"operator_id"`
}

func (q *Queries) CreateCheatRecord(ctx context.Context, arg CreateCheatRecordParams) (CheatRecord, error) {
	row := q.db.QueryRow(ctx, createCheatRecord,
		arg.ID,
		arg.TenantID,
		arg.ContestID,
		arg.TeamID,
		arg.Type,
		arg.Evidence,
		arg.Action,
		arg.OperatorID,
	)
	var i CheatRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.TeamID,
		&i.Type,
		&i.Evidence,
		&i.Action,
		&i.OperatorID,
		&i.CreatedAt,
	)
	return i, err
}

const createContest = `-- name: CreateContest :one

INSERT INTO contest (id, tenant_id, organizer_id, name, mode, match_mode, team_mode, signup_start, signup_end, start_at, end_at, freeze_minutes, rules, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, tenant_id, organizer_id, name, mode, match_mode, team_mode, signup_start, signup_end, start_at, end_at, freeze_minutes, rules, status, deleted_at, created_at, updated_at
`

type CreateContestParams struct {
	ID            int64              `json:"id"`
	TenantID      int64              `json:"tenant_id"`
	OrganizerID   int64              `json:"organizer_id"`
	Name          string             `json:"name"`
	Mode          int16              `json:"mode"`
	MatchMode     pgtype.Int2        `json:"match_mode"`
	TeamMode      int16              `json:"team_mode"`
	SignupStart   pgtype.Timestamptz `json:"signup_start"`
	SignupEnd     pgtype.Timestamptz `json:"signup_end"`
	StartAt       pgtype.Timestamptz `json:"start_at"`
	EndAt         pgtype.Timestamptz `json:"end_at"`
	FreezeMinutes int32              `json:"freeze_minutes"`
	Rules         []byte             `json:"rules"`
	Status        int16              `json:"status"`
}

// M8 contest sqlc 查询:仅访问 contest 模块自有租户表。
func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, createContest,
		arg.ID,
		arg.TenantID,
		arg.OrganizerID,
		arg.Name,
		arg.Mode,
		arg.MatchMode,
		arg.TeamMode,
		arg.SignupStart,
		arg.SignupEnd,
		arg.StartAt,
		arg.EndAt,
		arg.FreezeMinutes,
		arg.Rules,
		arg.Status,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrganizerID,
		&i.Name,
		&i.Mode,
		&i.MatchMode,
		&i.TeamMode,
		&i.SignupStart,
		&i.SignupEnd,
		&i.StartAt,
		&i.EndAt,
		&i.FreezeMinutes,
		&i.Rules,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContestProblem = `-- name: CreateContestProblem :one
INSERT INTO contest_problem (id, tenant_id, contest_id, item_code, item_version, score, dynamic_score, battle_rule, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, contest_id, item_code, item_version, score, dynamic_score, battle_rule, seq
`

type CreateContestProblemParams struct {
	ID           int64       `json:"id"`
	TenantID     int64       `json:"tenant_id"`
	ContestID    int64       `json:"contest_id"`
	ItemCode     string      `json:"item_code"`
	ItemVersion  string      `json:"item_version"`
	Score        int32       `json:"score"`
	DynamicScore []byte      `json:"dynamic_score"`
	BattleRule   pgtype.Int2 `json:"battle_rule"`
	Seq          int32       `json:"seq"`
}

func (q *Queries) CreateContestProblem(ctx context.Context, arg CreateContestProblemParams) (ContestProblem, error) {
	row := q.db.QueryRow(ctx, createContestProblem,
		arg.ID,
		arg.TenantID,
		arg.ContestID,
		arg.ItemCode,
		arg.ItemVersion,
		arg.Score,
		arg.DynamicScore,
		arg.BattleRule,
		arg.Seq,
	)
	var i ContestProblem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.ItemCode,
		&i.ItemVersion,
		&i.Score,
		&i.DynamicScore,
		&i.BattleRule,
		&i.Seq,
	)
	return i, err
}

const createResultSnapshot = `-- name: CreateResultSnapshot :one
INSERT INTO contest_result_snapshot (id, tenant_id, contest_id, final_ranking)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, contest_id) DO UPDATE SET final_ranking = EXCLUDED.final_ranking, generated_at = now()
RETURNING id, tenant_id, contest_id, final_ranking, generated_at
`

type CreateResultSnapshotParams struct {
	ID           int64  `json:"id"`
	TenantID     int64  `json:"tenant_id"`
	ContestID    int64  `json:"contest_id"`
	FinalRanking []byte `json:"final_ranking"`
}

func (q *Queries) CreateResultSnapshot(ctx context.Context, arg CreateResultSnapshotParams) (ContestResultSnapshot, error) {
	row := q.db.QueryRow(ctx, createResultSnapshot,
		arg.ID,
		arg.TenantID,
		arg.ContestID,
		arg.FinalRanking,
	)
	var i ContestResultSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.FinalRanking,
		&i.GeneratedAt,
	)
	return i, err
}

const createSolveSubmission = `-- name: CreateSolveSubmission :one
INSERT INTO solve_submission (id, tenant_id, contest_id, problem_id, team_id, submitter_id, content_ref, source_ref, judge_task_ref, sandbox_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, contest_id, problem_id, team_id, submitter_id, content_ref, source_ref, judge_task_ref, passed, score, sandbox_ref, submitted_at
`

type CreateSolveSubmissionParams struct {
	ID           int64       `json:"id"`
	TenantID     int64       `json:"tenant_id"`
	ContestID    int64       `json:"contest_id"`
	ProblemID    int64       `json:"problem_id"`
	TeamID       int64       `json:"team_id"`
	SubmitterID  int64       `json:"submitter_id"`
	ContentRef   []byte      `json:"content_ref"`
	SourceRef    string      `json:"source_ref"`
	JudgeTaskRef pgtype.Text `json:"judge_task_ref"`
	SandboxRef   pgtype.Text `json:"sandbox_ref"`
}

func (q *Queries) CreateSolveSubmission(ctx context.Context, arg CreateSolveSubmissionParams) (SolveSubmission, error) {
	row := q.db.QueryRow(ctx, createSolveSubmission,
		arg.ID,
		arg.TenantID,
		arg.ContestID,
		arg.ProblemID,
		arg.TeamID,
		arg.SubmitterID,
		arg.ContentRef,
		arg.SourceRef,
		arg.JudgeTaskRef,
		arg.SandboxRef,
	)
	var i SolveSubmission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.ProblemID,
		&i.TeamID,
		&i.SubmitterID,
		&i.ContentRef,
		&i.SourceRef,
		&i.JudgeTaskRef,
		&i.Passed,
		&i.Score,
		&i.SandboxRef,
		&i.SubmittedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO team (id, tenant_id, contest_id, name, invite_code, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, contest_id, name, invite_code, status, created_at
`

type CreateTeamParams struct {
	ID         int64       `json:"id"`
	TenantID   int64       `json:"tenant_id"`
	ContestID  int64       `json:"contest_id"`
	Name       string      `json:"name"`
	InviteCode pgtype.Text `json:"invite_code"`
	Status     int16       `json:"status"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.ID,
		arg.TenantID,
		arg.ContestID,
		arg.Name,
		arg.InviteCode,
		arg.Status,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.Name,
		&i.InviteCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createVulnProblem = `-- name: CreateVulnProblem :one
INSERT INTO vuln_problem (id, tenant_id, source_id, external_ref, title, level, runtime_mode, draft_body, prevalidate_status, prevalidate_detail, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, source_id, external_ref, title, level, runtime_mode, draft_body, prevalidate_status, prevalidate_detail, content_item_code, content_item_version, status, created_at, updated_at
`

type CreateVulnProblemParams struct {
	ID                int64       `json:"id"`
	TenantID          int64       `json:"tenant_id"`
	SourceID          pgtype.Int8 `json:"source_id"`
	ExternalRef       pgtype.Text `json:"external_ref"`
	Title             string      `json:"title"`
	Level             int16       `json:"level"`
	RuntimeMode       int16       `json:"runtime_mode"`
	DraftBody         []byte      `json:"draft_body"`
	PrevalidateStatus int16       `json:"prevalidate_status"`
	PrevalidateDetail []byte      `json:"prevalidate_detail"`
	Status            int16       `json:"status"`
}

func (q *Queries) CreateVulnProblem(ctx context.Context, arg CreateVulnProblemParams) (VulnProblem, error) {
	row := q.db.QueryRow(ctx, createVulnProblem,
		arg.ID,
		arg.TenantID,
		arg.SourceID,
		arg.ExternalRef,
		arg.Title,
		arg.Level,
		arg.RuntimeMode,
		arg.DraftBody,
		arg.PrevalidateStatus,
		arg.PrevalidateDetail,
		arg.Status,
	)
	var i VulnProblem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.ExternalRef,
		&i.Title,
		&i.Level,
		&i.RuntimeMode,
		&i.DraftBody,
		&i.PrevalidateStatus,
		&i.PrevalidateDetail,
		&i.ContentItemCode,
		&i.ContentItemVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVulnSource = `-- name: CreateVulnSource :one
INSERT INTO vuln_source (id, tenant_id, type, name, config, default_level, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, type, name, config, default_level, enabled, last_sync_at, created_at, updated_at
`

type CreateVulnSourceParams struct {
	ID           int64       `json:"id"`
	TenantID     pgtype.Int8 `json:"tenant_id"`
	Type         int16       `json:"type"`
	Name         string      `json:"name"`
	Config       []byte      `json:"config"`
	DefaultLevel int16       `json:"default_level"`
	Enabled      bool        `json:"enabled"`
}

func (q *Queries) CreateVulnSource(ctx context.Context, arg CreateVulnSourceParams) (VulnSource, error) {
	row := q.db.QueryRow(ctx, createVulnSource,
		arg.ID,
		arg.TenantID,
		arg.Type,
		arg.Name,
		arg.Config,
		arg.DefaultLevel,
		arg.Enabled,
	)
	var i VulnSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.DefaultLevel,
		&i.Enabled,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeVulnProblem = `-- name: FinalizeVulnProblem :one
UPDATE vuln_problem SET status = $1, content_item_code = $2, content_item_version = $3
WHERE id = $4
RETURNING id, tenant_id, source_id, external_ref, title, level, runtime_mode, draft_body, prevalidate_status, prevalidate_detail, content_item_code, content_item_version, status, created_at, updated_at
`

type FinalizeVulnProblemParams struct {
	Status             int16       `json:"status"`
	ContentItemCode    pgtype.Text `json:"content_item_code"`
	ContentItemVersion pgtype.Text `json:"content_item_version"`
	ID                 int64       `json:"id"`
}

func (q *Queries) FinalizeVulnProblem(ctx context.Context, arg FinalizeVulnProblemParams) (VulnProblem, error) {
	row := q.db.QueryRow(ctx, finalizeVulnProblem,
		arg.Status,
		arg.ContentItemCode,
		arg.ContentItemVersion,
		arg.ID,
	)
	var i VulnProblem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.ExternalRef,
		&i.Title,
		&i.Level,
		&i.RuntimeMode,
		&i.DraftBody,
		&i.PrevalidateStatus,
		&i.PrevalidateDetail,
		&i.ContentItemCode,
		&i.ContentItemVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBattleEntryByID = `-- name: GetBattleEntryByID :one
SELECT id, tenant_id, contest_id, team_id, role, artifact_ref, version_no, is_active, submitted_at FROM battle_entry WHERE id = $1
`

func (q *Queries) GetBattleEntryByID(ctx context.Context, id int64) (BattleEntry, error) {
	row := q.db.QueryRow(ctx, getBattleEntryByID, id)
	var i BattleEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.TeamID,
		&i.Role,
		&i.ArtifactRef,
		&i.VersionNo,
		&i.IsActive,
		&i.SubmittedAt,
	)
	return i, err
}

const getBattleMatchByID = `-- name: GetBattleMatchByID :one
SELECT id, tenant_id, contest_id, entry_a_id, entry_b_id, sandbox_ref, result, score_delta, replay_ref, matched_at, finished_at FROM battle_match WHERE id = $1
`

func (q *Queries) GetBattleMatchByID(ctx context.Context, id int64) (BattleMatch, error) {
	row := q.db.QueryRow(ctx, getBattleMatchByID, id)
	var i BattleMatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.EntryAID,
		&i.EntryBID,
		&i.SandboxRef,
		&i.Result,
		&i.ScoreDelta,
		&i.ReplayRef,
		&i.MatchedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getContestByID = `-- name: GetContestByID :one
SELECT id, tenant_id, organizer_id, name, mode, match_mode, team_mode, signup_start, signup_end, start_at, end_at, freeze_minutes, rules, status, deleted_at, created_at, updated_at FROM contest WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetContestByID(ctx context.Context, id int64) (Contest, error) {
	row := q.db.QueryRow(ctx, getContestByID, id)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrganizerID,
		&i.Name,
		&i.Mode,
		&i.MatchMode,
		&i.TeamMode,
		&i.SignupStart,
		&i.SignupEnd,
		&i.StartAt,
		&i.EndAt,
		&i.FreezeMinutes,
		&i.Rules,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContestProblemByID = `-- name: GetContestProblemByID :one
SELECT id, tenant_id, contest_id, item_code, item_version, score, dynamic_score, battle_rule, seq FROM contest_problem WHERE id = $1
`

func (q *Queries) GetContestProblemByID(ctx context.Context, id int64) (ContestProblem, error) {
	row := q.db.QueryRow(ctx, getContestProblemByID, id)
	var i ContestProblem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.ItemCode,
		&i.ItemVersion,
		&i.Score,
		&i.DynamicScore,
		&i.BattleRule,
		&i.Seq,
	)
	return i, err
}

const getLadderRank = `-- name: GetLadderRank :one
SELECT id, tenant_id, contest_id, team_id, score, solved_count, last_solve_at, rank, updated_at FROM ladder_rank WHERE contest_id = $1 AND team_id = $2
`

type GetLadderRankParams struct {
	ContestID int64 `json:"contest_id"`
	TeamID    int64 `json:"team_id"`
}

func (q *Queries) GetLadderRank(ctx context.Context, arg GetLadderRankParams) (LadderRank, error) {
	row := q.db.QueryRow(ctx, getLadderRank, arg.ContestID, arg.TeamID)
	var i LadderRank
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.TeamID,
		&i.Score,
		&i.SolvedCount,
		&i.LastSolveAt,
		&i.Rank,
		&i.UpdatedAt,
	)
	return i, err
}

const getResultSnapshot = `-- name: GetResultSnapshot :one
SELECT id, tenant_id, contest_id, final_ranking, generated_at FROM contest_result_snapshot WHERE contest_id = $1
`

func (q *Queries) GetResultSnapshot(ctx context.Context, contestID int64) (ContestResultSnapshot, error) {
	row := q.db.QueryRow(ctx, getResultSnapshot, contestID)
	var i ContestResultSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.FinalRanking,
		&i.GeneratedAt,
	)
	return i, err
}

const getSolveSubmissionByID = `-- name: GetSolveSubmissionByID :one
SELECT id, tenant_id, contest_id, problem_id, team_id, submitter_id, content_ref, source_ref, judge_task_ref, passed, score, sandbox_ref, submitted_at FROM solve_submission WHERE id = $1
`

func (q *Queries) GetSolveSubmissionByID(ctx context.Context, id int64) (SolveSubmission, error) {
	row := q.db.QueryRow(ctx, getSolveSubmissionByID, id)
	var i SolveSubmission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.ProblemID,
		&i.TeamID,
		&i.SubmitterID,
		&i.ContentRef,
		&i.SourceRef,
		&i.JudgeTaskRef,
		&i.Passed,
		&i.Score,
		&i.SandboxRef,
		&i.SubmittedAt,
	)
	return i, err
}

const getSolveSubmissionByJudgeTask = `-- name: GetSolveSubmissionByJudgeTask :one
SELECT s.id, s.tenant_id, s.contest_id, s.problem_id, s.team_id, s.submitter_id, s.content_ref, s.source_ref, s.judge_task_ref, s.passed, s.score, s.sandbox_ref, s.submitted_at, p.score AS max_score FROM solve_submission s
JOIN contest_problem p ON p.id = s.problem_id
WHERE s.judge_task_ref = $1
`

type GetSolveSubmissionByJudgeTaskRow struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	ContestID    int64              `json:"contest_id"`
	ProblemID    int64              `json:"problem_id"`
	TeamID       int64              `json:"team_id"`
	SubmitterID  int64              `json:"submitter_id"`
	ContentRef   []byte             `json:"content_ref"`
	SourceRef    string             `json:"source_ref"`
	JudgeTaskRef pgtype.Text        `json:"judge_task_ref"`
	Passed       bool               `json:"passed"`
	Score        int32              `json:"score"`
	SandboxRef   pgtype.Text        `json:"sandbox_ref"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
	MaxScore     int32              `json:"max_score"`
}

func (q *Queries) GetSolveSubmissionByJudgeTask(ctx context.Context, judgeTaskRef pgtype.Text) (GetSolveSubmissionByJudgeTaskRow, error) {
	row := q.db.QueryRow(ctx, getSolveSubmissionByJudgeTask, judgeTaskRef)
	var i GetSolveSubmissionByJudgeTaskRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.ProblemID,
		&i.TeamID,
		&i.SubmitterID,
		&i.ContentRef,
		&i.SourceRef,
		&i.JudgeTaskRef,
		&i.Passed,
		&i.Score,
		&i.SandboxRef,
		&i.SubmittedAt,
		&i.MaxScore,
	)
	return i, err
}

const getTeamByContestAndAccount = `-- name: GetTeamByContestAndAccount :one
SELECT t.id, t.tenant_id, t.contest_id, t.name, t.invite_code, t.status, t.created_at FROM team t
JOIN team_member tm ON tm.team_id = t.id
WHERE t.contest_id = $1 AND tm.account_id = $2
`

type GetTeamByContestAndAccountParams struct {
	ContestID int64 `json:"contest_id"`
	AccountID int64 `json:"account_id"`
}

func (q *Queries) GetTeamByContestAndAccount(ctx context.Context, arg GetTeamByContestAndAccountParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByContestAndAccount, arg.ContestID, arg.AccountID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.Name,
		&i.InviteCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, tenant_id, contest_id, name, invite_code, status, created_at FROM team WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.Name,
		&i.InviteCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT id, tenant_id, team_id, account_id, member_tenant_id, is_leader FROM team_member WHERE team_id = $1 AND account_id = $2
`

type GetTeamMemberParams struct {
	TeamID    int64 `json:"team_id"`
	AccountID int64 `json:"account_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TeamID, arg.AccountID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.AccountID,
		&i.MemberTenantID,
		&i.IsLeader,
	)
	return i, err
}

const getVulnProblemByID = `-- name: GetVulnProblemByID :one
SELECT id, tenant_id, source_id, external_ref, title, level, runtime_mode, draft_body, prevalidate_status, prevalidate_detail, content_item_code, content_item_version, status, created_at, updated_at FROM vuln_problem WHERE id = $1
`

func (q *Queries) GetVulnProblemByID(ctx context.Context, id int64) (VulnProblem, error) {
	row := q.db.QueryRow(ctx, getVulnProblemByID, id)
	var i VulnProblem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.ExternalRef,
		&i.Title,
		&i.Level,
		&i.RuntimeMode,
		&i.DraftBody,
		&i.PrevalidateStatus,
		&i.PrevalidateDetail,
		&i.ContentItemCode,
		&i.ContentItemVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVulnSourceByID = `-- name: GetVulnSourceByID :one
SELECT id, tenant_id, type, name, config, default_level, enabled, last_sync_at, created_at, updated_at FROM vuln_source WHERE id = $1
`

func (q *Queries) GetVulnSourceByID(ctx context.Context, id int64) (VulnSource, error) {
	row := q.db.QueryRow(ctx, getVulnSourceByID, id)
	var i VulnSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.DefaultLevel,
		&i.Enabled,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBattleEntries = `-- name: ListBattleEntries :many
SELECT id, tenant_id, contest_id, team_id, role, artifact_ref, version_no, is_active, submitted_at FROM battle_entry WHERE contest_id = $1 AND team_id = $2 ORDER BY version_no DESC
`

type ListBattleEntriesParams struct {
	ContestID int64 `json:"contest_id"`
	TeamID    int64 `json:"team_id"`
}

func (q *Queries) ListBattleEntries(ctx context.Context, arg ListBattleEntriesParams) ([]BattleEntry, error) {
	rows, err := q.db.Query(ctx, listBattleEntries, arg.ContestID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BattleEntry{}
	for rows.Next() {
		var i BattleEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContestID,
			&i.TeamID,
			&i.Role,
			&i.ArtifactRef,
			&i.VersionNo,
			&i.IsActive,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBattleMatches = `-- name: ListBattleMatches :many
SELECT id, tenant_id, contest_id, entry_a_id, entry_b_id, sandbox_ref, result, score_delta, replay_ref, matched_at, finished_at FROM battle_match
WHERE contest_id = $1 AND ($2::bigint IS NULL OR entry_a_id = $2 OR entry_b_id = $2)
ORDER BY matched_at DESC
LIMIT $4 OFFSET $3
`

type ListBattleMatchesParams struct {
	ContestID   int64       `json:"contest_id"`
	EntryID     pgtype.Int8 `json:"entry_id"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListBattleMatches(ctx context.Context, arg ListBattleMatchesParams) ([]BattleMatch, error) {
	rows, err := q.db.Query(ctx, listBattleMatches,
		arg.ContestID,
		arg.EntryID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BattleMatch{}
	for rows.Next() {
		var i BattleMatch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContestID,
			&i.EntryAID,
			&i.EntryBID,
			&i.SandboxRef,
			&i.Result,
			&i.ScoreDelta,
			&i.ReplayRef,
			&i.MatchedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBattleMatchesByTeam = `-- name: ListBattleMatchesByTeam :many
SELECT m.id, m.tenant_id, m.contest_id, m.entry_a_id, m.entry_b_id, m.sandbox_ref, m.result, m.score_delta, m.replay_ref, m.matched_at, m.finished_at FROM battle_match m
JOIN battle_entry ea ON ea.id = m.entry_a_id
JOIN battle_entry eb ON eb.id = m.entry_b_id
WHERE m.contest_id = $1 AND (ea.team_id = $2 OR eb.team_id = $2)
ORDER BY m.matched_at DESC
LIMIT $4 OFFSET $3
`

type ListBattleMatchesByTeamParams struct {
	ContestID   int64 `json:"contest_id"`
	TeamID      int64 `json:"team_id"`
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListBattleMatchesByTeam(ctx context.Context, arg ListBattleMatchesByTeamParams) ([]BattleMatch, error) {
	rows, err := q.db.Query(ctx, listBattleMatchesByTeam,
		arg.ContestID,
		arg.TeamID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BattleMatch{}
	for rows.Next() {
		var i BattleMatch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContestID,
			&i.EntryAID,
			&i.EntryBID,
			&i.SandboxRef,
			&i.Result,
			&i.ScoreDelta,
			&i.ReplayRef,
			&i.MatchedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheatRecordsByContest = `-- name: ListCheatRecordsByContest :many
SELECT id, tenant_id, contest_id, team_id, type, evidence, action, operator_id, created_at FROM cheat_record WHERE contest_id = $1 ORDER BY created_at DESC LIMIT $3 OFFSET $2
`

type ListCheatRecordsByContestParams struct {
	ContestID   int64 `json:"contest_id"`
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListCheatRecordsByContest(ctx context.Context, arg ListCheatRecordsByContestParams) ([]CheatRecord, error) {
	rows, err := q.db.Query(ctx, listCheatRecordsByContest, arg.ContestID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheatRecord{}
	for rows.Next() {
		var i CheatRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContestID,
			&i.TeamID,
			&i.Type,
			&i.Evidence,
			&i.Action,
			&i.OperatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestProblems = `-- name: ListContestProblems :many
SELECT id, tenant_id, contest_id, item_code, item_version, score, dynamic_score, battle_rule, seq FROM contest_problem WHERE contest_id = $1 ORDER BY seq ASC
`

func (q *Queries) ListContestProblems(ctx context.Context, contestID int64) ([]ContestProblem, error) {
	rows, err := q.db.Query(ctx, listContestProblems, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContestProblem{}
	for rows.Next() {
		var i ContestProblem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContestID,
			&i.ItemCode,
			&i.ItemVersion,
			&i.Score,
			&i.DynamicScore,
			&i.BattleRule,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContests = `-- name: ListContests :many
SELECT id, tenant_id, organizer_id, name, mode, match_mode, team_mode, signup_start, signup_end, start_at, end_at, freeze_minutes, rules, status, deleted_at, created_at, updated_at FROM contest
WHERE deleted_at IS NULL
  AND ($1::smallint IS NULL OR status = $1)
ORDER BY start_at DESC
LIMIT $3 OFFSET $2
`

type ListContestsParams struct {
	Status      pgtype.Int2 `json:"status"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListContests(ctx context.Context, arg ListContestsParams) ([]Contest, error) {
	rows, err := q.db.Query(ctx, listContests, arg.Status, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contest{}
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrganizerID,
			&i.Name,
			&i.Mode,
			&i.MatchMode,
			&i.TeamMode,
			&i.SignupStart,
			&i.SignupEnd,
			&i.StartAt,
			&i.EndAt,
			&i.FreezeMinutes,
			&i.Rules,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLadderRanks = `-- name: ListLadderRanks :many
SELECT id, tenant_id, contest_id, team_id, score, solved_count, last_solve_at, rank, updated_at FROM ladder_rank WHERE contest_id = $1 ORDER BY rank ASC, score DESC LIMIT $3 OFFSET $2
`

type ListLadderRanksParams struct {
	ContestID   int64 `json:"contest_id"`
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListLadderRanks(ctx context.Context, arg ListLadderRanksParams) ([]LadderRank, error) {
	rows, err := q.db.Query(ctx, listLadderRanks, arg.ContestID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LadderRank{}
	for rows.Next() {
		var i LadderRank
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContestID,
			&i.TeamID,
			&i.Score,
			&i.SolvedCount,
			&i.LastSolveAt,
			&i.Rank,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentAchievements = `-- name: ListStudentAchievements :many
SELECT lr.id, lr.tenant_id, lr.contest_id, lr.team_id, lr.score, lr.solved_count, lr.last_solve_at, lr.rank, lr.updated_at FROM ladder_rank lr
JOIN team_member tm ON tm.team_id = lr.team_id
WHERE tm.account_id = $1
ORDER BY lr.rank ASC, lr.score DESC
LIMIT $3 OFFSET $2
`

type ListStudentAchievementsParams struct {
	StudentID   int64 `json:"student_id"`
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListStudentAchievements(ctx context.Context, arg ListStudentAchievementsParams) ([]LadderRank, error) {
	rows, err := q.db.Query(ctx, listStudentAchievements, arg.StudentID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LadderRank{}
	for rows.Next() {
		var i LadderRank
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContestID,
			&i.TeamID,
			&i.Score,
			&i.SolvedCount,
			&i.LastSolveAt,
			&i.Rank,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT id, tenant_id, team_id, account_id, member_tenant_id, is_leader FROM team_member WHERE team_id = $1 ORDER BY is_leader DESC, id ASC
`

func (q *Queries) ListTeamMembers(ctx context.Context, teamID int64) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamMember{}
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TeamID,
			&i.AccountID,
			&i.MemberTenantID,
			&i.IsLeader,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVulnSources = `-- name: ListVulnSources :many
SELECT id, tenant_id, type, name, config, default_level, enabled, last_sync_at, created_at, updated_at FROM vuln_source ORDER BY id DESC LIMIT $2 OFFSET $1
`

type ListVulnSourcesParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListVulnSources(ctx context.Context, arg ListVulnSourcesParams) ([]VulnSource, error) {
	rows, err := q.db.Query(ctx, listVulnSources, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VulnSource{}
	for rows.Next() {
		var i VulnSource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.DefaultLevel,
			&i.Enabled,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTeam = `-- name: LockTeam :one
UPDATE team SET status = $1 WHERE id = $2 RETURNING id, tenant_id, contest_id, name, invite_code, status, created_at
`

type LockTeamParams struct {
	Status int16 `json:"status"`
	ID     int64 `json:"id"`
}

func (q *Queries) LockTeam(ctx context.Context, arg LockTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, lockTeam, arg.Status, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.Name,
		&i.InviteCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const markVulnSourceSynced = `-- name: MarkVulnSourceSynced :one
UPDATE vuln_source SET last_sync_at = now() WHERE id = $1 RETURNING id, tenant_id, type, name, config, default_level, enabled, last_sync_at, created_at, updated_at
`

func (q *Queries) MarkVulnSourceSynced(ctx context.Context, id int64) (VulnSource, error) {
	row := q.db.QueryRow(ctx, markVulnSourceSynced, id)
	var i VulnSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.DefaultLevel,
		&i.Enabled,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContest = `-- name: UpdateContest :one
UPDATE contest SET name = $1, mode = $2, match_mode = $3, team_mode = $4,
  signup_start = $5, signup_end = $6, start_at = $7, end_at = $8,
  freeze_minutes = $9, rules = $10
WHERE id = $11 AND deleted_at IS NULL
RETURNING id, tenant_id, organizer_id, name, mode, match_mode, team_mode, signup_start, signup_end, start_at, end_at, freeze_minutes, rules, status, deleted_at, created_at, updated_at
`

type UpdateContestParams struct {
	Name          string             `json:"name"`
	Mode          int16              `json:"mode"`
	MatchMode     pgtype.Int2        `json:"match_mode"`
	TeamMode      int16              `json:"team_mode"`
	SignupStart   pgtype.Timestamptz `json:"signup_start"`
	SignupEnd     pgtype.Timestamptz `json:"signup_end"`
	StartAt       pgtype.Timestamptz `json:"start_at"`
	EndAt         pgtype.Timestamptz `json:"end_at"`
	FreezeMinutes int32              `json:"freeze_minutes"`
	Rules         []byte             `json:"rules"`
	ID            int64              `json:"id"`
}

func (q *Queries) UpdateContest(ctx context.Context, arg UpdateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, updateContest,
		arg.Name,
		arg.Mode,
		arg.MatchMode,
		arg.TeamMode,
		arg.SignupStart,
		arg.SignupEnd,
		arg.StartAt,
		arg.EndAt,
		arg.FreezeMinutes,
		arg.Rules,
		arg.ID,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrganizerID,
		&i.Name,
		&i.Mode,
		&i.MatchMode,
		&i.TeamMode,
		&i.SignupStart,
		&i.SignupEnd,
		&i.StartAt,
		&i.EndAt,
		&i.FreezeMinutes,
		&i.Rules,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContestStatus = `-- name: UpdateContestStatus :one
UPDATE contest SET status = $1 WHERE id = $2 AND deleted_at IS NULL RETURNING id, tenant_id, organizer_id, name, mode, match_mode, team_mode, signup_start, signup_end, start_at, end_at, freeze_minutes, rules, status, deleted_at, created_at, updated_at
`

type UpdateContestStatusParams struct {
	Status int16 `json:"status"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateContestStatus(ctx context.Context, arg UpdateContestStatusParams) (Contest, error) {
	row := q.db.QueryRow(ctx, updateContestStatus, arg.Status, arg.ID)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrganizerID,
		&i.Name,
		&i.Mode,
		&i.MatchMode,
		&i.TeamMode,
		&i.SignupStart,
		&i.SignupEnd,
		&i.StartAt,
		&i.EndAt,
		&i.FreezeMinutes,
		&i.Rules,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSolveSubmissionResult = `-- name: UpdateSolveSubmissionResult :one
UPDATE solve_submission SET passed = $1, score = $2 WHERE id = $3 RETURNING id, tenant_id, contest_id, problem_id, team_id, submitter_id, content_ref, source_ref, judge_task_ref, passed, score, sandbox_ref, submitted_at
`

type UpdateSolveSubmissionResultParams struct {
	Passed bool  `json:"passed"`
	Score  int32 `json:"score"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateSolveSubmissionResult(ctx context.Context, arg UpdateSolveSubmissionResultParams) (SolveSubmission, error) {
	row := q.db.QueryRow(ctx, updateSolveSubmissionResult, arg.Passed, arg.Score, arg.ID)
	var i SolveSubmission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.ProblemID,
		&i.TeamID,
		&i.SubmitterID,
		&i.ContentRef,
		&i.SourceRef,
		&i.JudgeTaskRef,
		&i.Passed,
		&i.Score,
		&i.SandboxRef,
		&i.SubmittedAt,
	)
	return i, err
}

const updateVulnProblemPrevalidate = `-- name: UpdateVulnProblemPrevalidate :one
UPDATE vuln_problem SET prevalidate_status = $1, prevalidate_detail = $2
WHERE id = $3
RETURNING id, tenant_id, source_id, external_ref, title, level, runtime_mode, draft_body, prevalidate_status, prevalidate_detail, content_item_code, content_item_version, status, created_at, updated_at
`

type UpdateVulnProblemPrevalidateParams struct {
	PrevalidateStatus int16  `json:"prevalidate_status"`
	PrevalidateDetail []byte `json:"prevalidate_detail"`
	ID                int64  `json:"id"`
}

func (q *Queries) UpdateVulnProblemPrevalidate(ctx context.Context, arg UpdateVulnProblemPrevalidateParams) (VulnProblem, error) {
	row := q.db.QueryRow(ctx, updateVulnProblemPrevalidate, arg.PrevalidateStatus, arg.PrevalidateDetail, arg.ID)
	var i VulnProblem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.ExternalRef,
		&i.Title,
		&i.Level,
		&i.RuntimeMode,
		&i.DraftBody,
		&i.PrevalidateStatus,
		&i.PrevalidateDetail,
		&i.ContentItemCode,
		&i.ContentItemVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLadderRank = `-- name: UpsertLadderRank :one
INSERT INTO ladder_rank (id, tenant_id, contest_id, team_id, score, solved_count, last_solve_at, rank)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (tenant_id, contest_id, team_id) DO UPDATE SET
  score = EXCLUDED.score,
  solved_count = EXCLUDED.solved_count,
  last_solve_at = COALESCE(EXCLUDED.last_solve_at, ladder_rank.last_solve_at),
  rank = EXCLUDED.rank,
  updated_at = now()
RETURNING id, tenant_id, contest_id, team_id, score, solved_count, last_solve_at, rank, updated_at
`

type UpsertLadderRankParams struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	ContestID   int64              `json:"contest_id"`
	TeamID      int64              `json:"team_id"`
	Score       pgtype.Numeric     `json:"score"`
	SolvedCount int32              `json:"solved_count"`
	LastSolveAt pgtype.Timestamptz `json:"last_solve_at"`
	Rank        int32              `json:"rank"`
}

func (q *Queries) UpsertLadderRank(ctx context.Context, arg UpsertLadderRankParams) (LadderRank, error) {
	row := q.db.QueryRow(ctx, upsertLadderRank,
		arg.ID,
		arg.TenantID,
		arg.ContestID,
		arg.TeamID,
		arg.Score,
		arg.SolvedCount,
		arg.LastSolveAt,
		arg.Rank,
	)
	var i LadderRank
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContestID,
		&i.TeamID,
		&i.Score,
		&i.SolvedCount,
		&i.LastSolveAt,
		&i.Rank,
		&i.UpdatedAt,
	)
	return i, err
}
