// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BattleEntry struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	ContestID    int64              `json:"contest_id"`
	ProblemID    int64              `json:"problem_id"`
	TeamID       int64              `json:"team_id"`
	Role         int16              `json:"role"`
	ArtifactRef  string             `json:"artifact_ref"`
	ArtifactHash string             `json:"artifact_hash"`
	VersionNo    int32              `json:"version_no"`
	IsActive     bool               `json:"is_active"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
}

type BattleMatch struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	ContestID    int64              `json:"contest_id"`
	ProblemID    int64              `json:"problem_id"`
	EntryAID     int64              `json:"entry_a_id"`
	EntryBID     int64              `json:"entry_b_id"`
	SourceRef    string             `json:"source_ref"`
	SandboxRef   pgtype.Text        `json:"sandbox_ref"`
	JudgeTaskRef pgtype.Text        `json:"judge_task_ref"`
	Result       pgtype.Int2        `json:"result"`
	ScoreDelta   []byte             `json:"score_delta"`
	ReplayRef    pgtype.Text        `json:"replay_ref"`
	Status       int16              `json:"status"`
	MatchedAt    pgtype.Timestamptz `json:"matched_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
}

type CheatRecord struct {
	ID         int64              `json:"id"`
	TenantID   int64              `json:"tenant_id"`
	ContestID  int64              `json:"contest_id"`
	TeamID     int64              `json:"team_id"`
	Type       int16              `json:"type"`
	Evidence   []byte             `json:"evidence"`
	Action     int16              `json:"action"`
	OperatorID pgtype.Int8        `json:"operator_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Contest struct {
	ID            int64              `json:"id"`
	TenantID      int64              `json:"tenant_id"`
	OrganizerID   int64              `json:"organizer_id"`
	Name          string             `json:"name"`
	Mode          int16              `json:"mode"`
	MatchMode     pgtype.Int2        `json:"match_mode"`
	TeamMode      int16              `json:"team_mode"`
	SignupStart   pgtype.Timestamptz `json:"signup_start"`
	SignupEnd     pgtype.Timestamptz `json:"signup_end"`
	StartAt       pgtype.Timestamptz `json:"start_at"`
	EndAt         pgtype.Timestamptz `json:"end_at"`
	FreezeMinutes int32              `json:"freeze_minutes"`
	Rules         []byte             `json:"rules"`
	Status        int16              `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type ContestProblem struct {
	ID           int64       `json:"id"`
	TenantID     int64       `json:"tenant_id"`
	ContestID    int64       `json:"contest_id"`
	ItemCode     string      `json:"item_code"`
	ItemVersion  string      `json:"item_version"`
	Score        int32       `json:"score"`
	DynamicScore []byte      `json:"dynamic_score"`
	BattleRule   pgtype.Int2 `json:"battle_rule"`
	Seq          int32       `json:"seq"`
}

type ContestResultSnapshot struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	ContestID    int64              `json:"contest_id"`
	FinalRanking []byte             `json:"final_ranking"`
	GeneratedAt  pgtype.Timestamptz `json:"generated_at"`
}

type SolveSubmission struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	ContestID    int64              `json:"contest_id"`
	ProblemID    int64              `json:"problem_id"`
	TeamID       int64              `json:"team_id"`
	SubmitterID  int64              `json:"submitter_id"`
	ContentRef   []byte             `json:"content_ref"`
	SourceRef    string             `json:"source_ref"`
	JudgeTaskRef pgtype.Text        `json:"judge_task_ref"`
	Passed       bool               `json:"passed"`
	Score        int32              `json:"score"`
	SandboxRef   pgtype.Text        `json:"sandbox_ref"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
}

type Team struct {
	ID         int64              `json:"id"`
	TenantID   int64              `json:"tenant_id"`
	ContestID  int64              `json:"contest_id"`
	Name       string             `json:"name"`
	InviteCode pgtype.Text        `json:"invite_code"`
	Status     int16              `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type TeamMember struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	TeamID         int64              `json:"team_id"`
	AccountID      int64              `json:"account_id"`
	MemberTenantID int64              `json:"member_tenant_id"`
	IsLeader       bool               `json:"is_leader"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
}

type VulnProblem struct {
	ID                 int64              `json:"id"`
	TenantID           int64              `json:"tenant_id"`
	SourceID           pgtype.Int8        `json:"source_id"`
	ExternalRef        pgtype.Text        `json:"external_ref"`
	Title              string             `json:"title"`
	Level              int16              `json:"level"`
	RuntimeMode        int16              `json:"runtime_mode"`
	DraftBody          []byte             `json:"draft_body"`
	PrevalidateStatus  int16              `json:"prevalidate_status"`
	PrevalidateDetail  []byte             `json:"prevalidate_detail"`
	ContentItemCode    pgtype.Text        `json:"content_item_code"`
	ContentItemVersion pgtype.Text        `json:"content_item_version"`
	Status             int16              `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type VulnSource struct {
	ID           int64              `json:"id"`
	TenantID     pgtype.Int8        `json:"tenant_id"`
	Type         int16              `json:"type"`
	Name         string             `json:"name"`
	Config       []byte             `json:"config"`
	DefaultLevel int16              `json:"default_level"`
	Enabled      bool               `json:"enabled"`
	LastSyncAt   pgtype.Timestamptz `json:"last_sync_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
