// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnnouncementRead struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	AnnouncementID int64              `json:"announcement_id"`
	AccountID      int64              `json:"account_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
}

type Notification struct {
	ID         int64              `json:"id"`
	TenantID   int64              `json:"tenant_id"`
	ReceiverID int64              `json:"receiver_id"`
	Type       string             `json:"type"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Link       pgtype.Text        `json:"link"`
	IsRead     bool               `json:"is_read"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type NotificationPreference struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	AccountID int64  `json:"account_id"`
	Type      string `json:"type"`
	Enabled   bool   `json:"enabled"`
}

type NotificationTemplate struct {
	ID         int64              `json:"id"`
	Type       string             `json:"type"`
	TitleTpl   string             `json:"title_tpl"`
	ContentTpl string             `json:"content_tpl"`
	Channels   []string           `json:"channels"`
	Force      bool               `json:"force"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SystemAnnouncement struct {
	ID          int64              `json:"id"`
	TenantID    pgtype.Int8        `json:"tenant_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Scope       int16              `json:"scope"`
	TargetRoles []int16            `json:"target_roles"`
	PublisherID int64              `json:"publisher_id"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ExpireAt    pgtype.Timestamptz `json:"expire_at"`
}
