// labels 文件是 apps/web 业务文案的唯一公共出口，实现按后端模块拆分在 labels 目录。

export * from './labels/admin'
export * from './labels/content'
export * from './labels/contest'
export * from './labels/experiment'
export * from './labels/grade'
export * from './labels/identity'
export * from './labels/judge'
export * from './labels/notify'
export * from './labels/reference'
export * from './labels/sandbox'
export * from './labels/sim'
export * from './labels/teaching'
export * from './labels/transfer'
