"""校验 images 层全量镜像目录、manifest 安全字段和禁用实现口径。"""

from __future__ import annotations

import ast
import re
import unittest
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parents[2]
IMAGES_ROOT = REPO_ROOT / "images"
DEPLOY_ENV_FILE = REPO_ROOT / "deploy" / "config" / "chaimir.env"
SECRET_ENV_EXAMPLE_FILE = REPO_ROOT / "deploy" / "config" / "secret.env.example"

REQUIRED_IMAGES = {
    "service": ["backend", "frontend", "migrate"],
    "runtime": [
        "evm-hardhat",
        "evm-foundry",
        "evm-geth",
        "evm-besu",
        "evm-ganache",
        "fabric",
        "fisco-bcos",
        "chainmaker",
        "solana",
        "move-aptos",
        "move-sui",
        "cosmos",
        "substrate",
        "near",
        "bitcoin",
        "edu-chain",
    ],
    "infra": [
        "chainlink-node",
        "ipfs",
        "ipfs-cluster",
        "thegraph-node",
        "postgres-graph",
        "bridge-relayer",
        "op-stack",
        "zk-prover",
        "aa-bundler",
        "paymaster",
        "wallet-backend",
        "rpc-gateway",
        "event-listener",
    ],
    "tool": [
        "code-server",
        "remix",
        "jupyter",
        "theia",
        "blockscout",
        "fabric-explorer",
        "wallet-sim",
        "contract-ui",
        "slither",
        "gas-profiler",
        "mythril",
        "novnc-desktop",
        "db-viewer",
    ],
    "judger": [
        "testcase-evm",
        "testcase-fabric",
        "testcase-fisco",
        "testcase-chainmaker",
        "static-scan",
    ],
    "sim": ["graph-layout"],
    "sidecar": ["collector", "log-shipper"],
    "init": ["sandbox-seed"],
    "base": ["go-builder", "node-builder", "runtime-min", "judge-min", "chain-tools"],
    "middleware": ["postgres", "redis", "minio", "nats", "couchdb", "harbor"],
    "observability": ["prometheus", "grafana"],
    "ingress": ["ingress-nginx"],
}

VALID_SOURCE_TYPES = {"platform-built", "thin-wrapper", "build-base", "upstream-pinned"}
DOCKERFILE_SOURCE_TYPES = {"platform-built", "thin-wrapper", "build-base"}

FORBIDDEN_PATTERNS = [
    re.compile(pattern, re.IGNORECASE)
    for pattern in (
        r"sleep\s+infinity",
        r"\bTODO\b",
        r"\bTBD\b",
        r"占位",
        r"假实现",
        r"Generated by",
        r"sync_catalog",
        r"imagectl",
        r"catalog\.yaml",
        r"FROM\s+\S+:latest\b",
        r"image:\s+\S+:latest\b",
        r"ARG\s+\S+=latest\b",
        r"FROM\s+\S+:(stable|next|edge|main|master)\b",
        r"image:\s+\S+:(stable|next|edge|main|master)\b",
        r"ARG\s+\S+=(stable|next|edge|main|master)\b",
        r"hostNetwork:\s*true",
        r"privileged:\s*true",
        r"automount_service_account_token:\s*true",
    )
]

DISALLOWED_COMPOSITION_KEYS = {
    "same_pod_bundles",
    "fixed_bundles",
    "compatible_images",
    "incompatible_images",
    "allowed_images",
    "required_images",
    "only_with",
}

ALLOWED_SELF_DEVELOPED_HTTP_IMAGES = {
    ("runtime", "edu-chain"),
    ("tool", "wallet-sim"),
    ("tool", "contract-ui"),
}


class ImageContractsTest(unittest.TestCase):
    """覆盖镜像层发布前必须满足的结构、安全和范围规则。"""

    def required_image_dirs(self) -> list[tuple[str, str, Path]]:
        """返回文档规定的全部镜像目录。"""
        return [
            (category, name, IMAGES_ROOT / category / name)
            for category, names in REQUIRED_IMAGES.items()
            for name in names
        ]

    def load_manifest(self, manifest_path: Path) -> dict[str, object]:
        """读取并返回 manifest,同时确保 YAML 结构是对象。"""
        self.assertTrue(manifest_path.is_file(), f"{manifest_path} 必须存在")
        with manifest_path.open("r", encoding="utf-8") as handle:
            loaded = yaml.safe_load(handle)
        self.assertIsInstance(loaded, dict, f"{manifest_path} 必须是 YAML 对象")
        return loaded

    def dockerfile_lines(self, image_dir: Path) -> list[str]:
        """读取 Dockerfile 的非空行。"""
        return [
            line.strip()
            for line in (image_dir / "Dockerfile").read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]

    def deploy_env_keys(self) -> set[str]:
        """读取 deploy/config/chaimir.env 中声明的普通配置键和密钥变量键。"""
        keys: set[str] = set()
        for line in DEPLOY_ENV_FILE.read_text(encoding="utf-8-sig").splitlines():
            stripped = line.strip()
            if stripped.startswith("# secret-env:"):
                keys.add(stripped.split(":", 1)[1].strip())
                continue
            if not line or line.lstrip().startswith("#") or "=" not in line:
                continue
            keys.add(line.split("=", 1)[0].strip())
        return keys

    def deploy_configmap_env_keys(self) -> set[str]:
        """读取 deploy/config/chaimir.env 中会进入 ConfigMap 的普通配置键。"""
        keys: set[str] = set()
        for line in DEPLOY_ENV_FILE.read_text(encoding="utf-8-sig").splitlines():
            if not line or line.lstrip().startswith("#") or "=" not in line:
                continue
            keys.add(line.split("=", 1)[0].strip())
        return keys

    def deploy_secret_env_keys(self) -> set[str]:
        """读取 deploy/config/chaimir.env 中登记的密钥变量键。"""
        keys: set[str] = set()
        for line in DEPLOY_ENV_FILE.read_text(encoding="utf-8-sig").splitlines():
            stripped = line.strip()
            if stripped.startswith("# secret-env:"):
                keys.add(stripped.split(":", 1)[1].strip())
        return keys

    def secret_example_keys(self) -> set[str]:
        """读取 deploy/config/secret.env.example 中可生成 Secret 的变量键。"""
        keys: set[str] = set()
        for line in SECRET_ENV_EXAMPLE_FILE.read_text(encoding="utf-8-sig").splitlines():
            if not line or line.lstrip().startswith("#") or "=" not in line:
                continue
            keys.add(line.split("=", 1)[0].strip())
        return keys

    def test_all_documented_images_have_handwritten_directories(self) -> None:
        """文档列出的全部镜像都必须有目录和生产清单,Dockerfile 由来源类型决定。"""
        missing: list[str] = []
        for category, name, image_dir in self.required_image_dirs():
            for filename in ("manifest.yaml", "README.md"):
                if not (image_dir / filename).is_file():
                    missing.append(f"{category}/{name}/{filename}")
            if not (image_dir / "manifest.yaml").is_file():
                continue
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            source_type = manifest.get("source", {}).get("type")
            if source_type in DOCKERFILE_SOURCE_TYPES and not (image_dir / "Dockerfile").is_file():
                missing.append(f"{category}/{name}/Dockerfile")
            if source_type == "upstream-pinned" and (image_dir / "Dockerfile").exists():
                missing.append(f"{category}/{name}/Dockerfile 不应存在,纯上游固定镜像只登记不重打包")
        self.assertEqual([], missing)

    def test_manifest_category_name_and_image_prefix_are_unified(self) -> None:
        """manifest 分类、镜像名前缀和本地目录必须完全一致。"""
        errors: list[str] = []
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            if manifest.get("category") != category:
                errors.append(f"{category}/{name}: category={manifest.get('category')!r}")
            if manifest.get("name") != name:
                errors.append(f"{category}/{name}: name={manifest.get('name')!r}")
            if manifest.get("image") != f"{category}/{name}":
                errors.append(f"{category}/{name}: image={manifest.get('image')!r}")
        self.assertEqual([], errors)

    def test_manifest_declares_production_security_contract(self) -> None:
        """每个镜像必须声明生产安全、资源、自检和供应链门禁。"""
        errors: list[str] = []
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            security = manifest.get("security", {})
            resources = manifest.get("resources", {})
            selftest = manifest.get("selftest", {})
            supply_chain = manifest.get("supply_chain", {})

            upstream_pinned = manifest.get("source", {}).get("type") == "upstream-pinned"
            expected_security = {
                "run_as_non_root": True,
                "allow_privilege_escalation": False,
                "privileged": False,
                "host_network": False,
                "automount_service_account_token": False,
            }
            for key, expected in expected_security.items():
                if security.get(key) != expected:
                    errors.append(f"{category}/{name}: security.{key}={security.get(key)!r}")
            if security.get("read_only_root_filesystem") is False:
                exceptions = manifest.get("security_exceptions", [])
                if not exceptions:
                    errors.append(f"{category}/{name}: 只读根文件系统例外缺少 security_exceptions")
            elif security.get("read_only_root_filesystem") is not True:
                errors.append(f"{category}/{name}: security.read_only_root_filesystem={security.get('read_only_root_filesystem')!r}")
            if "ALL" not in security.get("drop_capabilities", []):
                errors.append(f"{category}/{name}: security.drop_capabilities 缺少 ALL")
            for key in ("cpu_request", "cpu_limit", "memory_request", "memory_limit", "ephemeral_storage_limit"):
                if not resources.get(key):
                    errors.append(f"{category}/{name}: resources.{key} 缺失")
            if not selftest.get("commands") and not (category == "base" and selftest.get("note")) and not upstream_pinned:
                errors.append(f"{category}/{name}: selftest.commands 缺失")
            for key in ("sbom", "trivy_required", "cosign_required", "pull_by_digest_in_production"):
                if supply_chain.get(key) is not True:
                    errors.append(f"{category}/{name}: supply_chain.{key} 不是 true")
        self.assertEqual([], errors)

    def test_manifest_declares_image_source_contract(self) -> None:
        """每个镜像必须声明来源类型,Dockerfile 与上游锁定契约由来源类型决定。"""
        errors: list[str] = []
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            source = manifest.get("source", {})
            source_type = source.get("type")
            if source_type not in VALID_SOURCE_TYPES:
                errors.append(f"{category}/{name}: source.type 非法或缺失")
                continue
            if source_type == "upstream-pinned":
                if (image_dir / "Dockerfile").exists():
                    errors.append(f"{category}/{name}: upstream-pinned 不得维护 Dockerfile")
                upstream = manifest.get("upstream", {})
                for key in ("image", "version", "registry", "license"):
                    if not upstream.get(key):
                        errors.append(f"{category}/{name}: upstream.{key} 缺失")
                if upstream.get("digest_required") is not True:
                    errors.append(f"{category}/{name}: upstream.digest_required 必须为 true")
                digest = upstream.get("digest")
                lock_ref = upstream.get("digest_lock_ref")
                components = upstream.get("components", [])
                has_locked_component = any(component.get("digest") for component in components if isinstance(component, dict))
                if not digest and not lock_ref and not has_locked_component:
                    errors.append(f"{category}/{name}: upstream 必须以内联 digest、digest_lock_ref 或组件 digest 锁定")
                if digest and not re.fullmatch(r"sha256:[0-9a-f]{64}", str(digest)):
                    errors.append(f"{category}/{name}: upstream.digest 格式非法")
                delivery = manifest.get("private_delivery", {})
                if delivery.get("offline_bundle") is not True:
                    errors.append(f"{category}/{name}: private_delivery.offline_bundle 必须为 true")
                if not delivery.get("import_project"):
                    errors.append(f"{category}/{name}: private_delivery.import_project 缺失")
                if manifest.get("student_access", {}).get("enabled") is not False:
                    errors.append(f"{category}/{name}: 上游中间件/入口/观测镜像不得声明学生入口")
                for key in ("secrets_required", "data_volumes", "backup", "network"):
                    if key not in manifest:
                        errors.append(f"{category}/{name}: {key} 缺失")
            if source_type in DOCKERFILE_SOURCE_TYPES and not (image_dir / "Dockerfile").is_file():
                errors.append(f"{category}/{name}: {source_type} 必须维护 Dockerfile")
            if source_type == "thin-wrapper":
                upstream = manifest.get("upstream", {})
                if not upstream.get("image"):
                    errors.append(f"{category}/{name}: thin-wrapper 必须声明 upstream.image")
        self.assertEqual([], errors)

    def test_manifest_declares_standard_operational_labels(self) -> None:
        """每个镜像必须声明统一运维标签,供 seed、准入、审计和成本归属使用。"""
        errors: list[str] = []
        sensitivity_by_category = {
            "service": "control-plane",
            "runtime": "student-runtime",
            "infra": "sandbox-infra",
            "tool": "student-tool",
            "judger": "judge-private",
            "sim": "backend-compute",
            "sidecar": "control-sidecar",
            "init": "init-private",
            "base": "build-base",
            "middleware": "stateful-middleware",
            "observability": "observability",
            "ingress": "edge-gateway",
        }
        scope_by_category = {
            "service": "platform",
            "runtime": "sandbox",
            "infra": "sandbox",
            "tool": "sandbox",
            "judger": "judge",
            "sim": "sim",
            "sidecar": "sandbox",
            "init": "sandbox",
            "base": "build",
            "middleware": "middleware",
            "observability": "observability",
            "ingress": "ingress",
        }
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            labels = manifest.get("labels", {})
            if not isinstance(labels, dict):
                errors.append(f"{category}/{name}: labels 必须是对象")
                continue
            expected = {
                "app.kubernetes.io/name": name,
                "app.kubernetes.io/component": category,
                "app.kubernetes.io/part-of": "chaimir",
                "chaimir.io/category": category,
                "chaimir.io/image": f"{category}/{name}",
                "chaimir.io/data-driven": str(manifest.get("data_driven") is True).lower(),
                "chaimir.io/student-access": str(manifest.get("student_access", {}).get("enabled") is True).lower(),
                "chaimir.io/sensitivity": sensitivity_by_category[category],
                "chaimir.io/scope": scope_by_category[category],
                "chaimir.io/source": str(manifest.get("source", {}).get("type", "")),
            }
            for key, expected_value in expected.items():
                if labels.get(key) != expected_value:
                    errors.append(f"{category}/{name}: labels.{key}={labels.get(key)!r}, want {expected_value!r}")
        self.assertEqual([], errors)

    def test_manifest_env_keys_are_declared_in_deploy_env_source(self) -> None:
        """镜像需要的配置和密钥变量名必须统一来自 deploy/config/chaimir.env。"""
        errors: list[str] = []
        deploy_keys = self.deploy_env_keys()
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            env_keys = manifest.get("env_keys", {})
            if env_keys:
                if not isinstance(env_keys, dict):
                    errors.append(f"{category}/{name}: env_keys 必须是对象")
                for group in ("config", "secret"):
                    for key in env_keys.get(group, []):
                        if key not in deploy_keys:
                            errors.append(f"{category}/{name}: env_keys.{group} {key} 未在 deploy/config/chaimir.env 声明")
            for secret in manifest.get("secrets_required", []):
                env = secret.get("env")
                if not env:
                    errors.append(f"{category}/{name}: secrets_required 缺少 env")
                    continue
                if env not in deploy_keys:
                    errors.append(f"{category}/{name}: secrets_required {env} 未在 deploy/config/chaimir.env 声明")
                if secret.get("source") != "deploy/config/chaimir.env":
                    errors.append(f"{category}/{name}: secrets_required {env} source 必须为 deploy/config/chaimir.env")
                if secret.get("runtime_value") != "secret-or-kms":
                    errors.append(f"{category}/{name}: secrets_required {env} runtime_value 必须为 secret-or-kms")
        self.assertEqual([], errors)

    def test_sensitive_node_infra_services_are_self_authenticated_and_manifest_declared(self) -> None:
        """持有私钥或内部链访问配置的 Node infra 服务必须自身鉴权且声明全部运行期变量。"""
        errors: list[str] = []
        sensitive_files = [
            IMAGES_ROOT / "infra" / "wallet-backend" / "wallet-backend.mjs",
            IMAGES_ROOT / "infra" / "paymaster" / "paymaster-service.mjs",
            IMAGES_ROOT / "infra" / "event-listener" / "event-listener.mjs",
        ]
        for path in sensitive_files:
            category, name = path.relative_to(IMAGES_ROOT).parts[:2]
            source = path.read_text(encoding="utf-8")
            if "verifyServiceSignature" not in source:
                errors.append(f"{category}/{name}: 服务入口缺少自身 HMAC 鉴权")
        self.assertEqual([], errors)

    def test_source_environment_variables_are_manifest_declared(self) -> None:
        """源码读取的 CHAIMIR_* 环境变量必须在镜像 manifest 和 deploy/config/chaimir.env 中声明。"""
        errors: list[str] = []
        deploy_keys = self.deploy_env_keys()
        patterns = [
            re.compile(r"process\.env\.([A-Z0-9_]+)"),
            re.compile(r"os\.environ\.get\([\"']([A-Z0-9_]+)[\"']"),
            re.compile(r"os\.environ\[[\"']([A-Z0-9_]+)[\"']\]"),
            re.compile(r"getenv\([\"']([A-Z0-9_]+)[\"']"),
        ]
        for path in IMAGES_ROOT.rglob("*"):
            if path.suffix not in {".py", ".mjs", ".js"} or "tests" in path.parts:
                continue
            relative = path.relative_to(IMAGES_ROOT)
            category, name = relative.parts[:2]
            manifest_path = IMAGES_ROOT / category / name / "manifest.yaml"
            if not manifest_path.is_file():
                continue
            manifest = self.load_manifest(manifest_path)
            manifest_envs = set(manifest.get("env_keys", {}).get("config", []))
            manifest_envs.update(manifest.get("env_keys", {}).get("secret", []))
            manifest_envs.update(secret.get("env") for secret in manifest.get("secrets_required", []) if secret.get("env"))
            source = path.read_text(encoding="utf-8")
            envs = {match.group(1) for pattern in patterns for match in pattern.finditer(source)}
            for env in sorted(env for env in envs if env.startswith("CHAIMIR_")):
                if env not in manifest_envs:
                    errors.append(f"{category}/{name}: {relative} 读取 {env} 但 manifest 未声明")
                if env not in deploy_keys:
                    errors.append(f"{category}/{name}: {relative} 读取 {env} 但 deploy/config/chaimir.env 未声明")
        self.assertEqual([], errors)

    def test_secret_env_keys_do_not_enter_configmap_env_file(self) -> None:
        """密钥变量名可以登记在 chaimir.env,但不得以 KEY= 形式进入 ConfigMap。"""
        secret_keys: set[str] = set()
        for _, _, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            env_keys = manifest.get("env_keys", {})
            secret_keys.update(env_keys.get("secret", []))
            secret_keys.update(secret.get("env") for secret in manifest.get("secrets_required", []) if secret.get("env"))
        configmap_keys = self.deploy_configmap_env_keys()
        leaked = sorted(secret_keys & configmap_keys)
        self.assertEqual([], leaked)

    def test_secret_env_keys_have_secret_template_entries(self) -> None:
        """chaimir.env 登记的密钥键必须在 secret.env.example 中有同名模板。"""
        registered = self.deploy_secret_env_keys()
        templated = self.secret_example_keys()
        missing = sorted(registered - templated)
        self.assertEqual([], missing)

    def test_dockerfiles_end_with_required_runtime_user(self) -> None:
        """沙箱消费镜像必须固定 1000:1000,其他构建镜像至少显式非 root。"""
        errors: list[str] = []
        sandbox_consumed_categories = {"runtime", "tool", "judger", "infra"}
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            if manifest.get("source", {}).get("type") == "upstream-pinned":
                continue
            user_lines = [line for line in self.dockerfile_lines(image_dir) if line.upper().startswith("USER ")]
            if not user_lines:
                errors.append(f"{category}/{name}: Dockerfile 缺少 USER")
                continue
            last_user = user_lines[-1].split(None, 1)[1]
            if category in sandbox_consumed_categories and last_user != "1000:1000":
                errors.append(f"{category}/{name}: Dockerfile 最终 USER={last_user!r}, 必须为 1000:1000")
            if last_user in {"root", "0", "0:0"}:
                errors.append(f"{category}/{name}: Dockerfile 最终 USER 是 root")
        self.assertEqual([], errors)

    def test_web_tools_delegate_auth_to_platform_when_internal_auth_is_disabled(self) -> None:
        """关闭内置认证的 Web 工具必须显式声明由平台代理鉴权。"""
        errors: list[str] = []
        auth_disabled_patterns = ("--auth\", \"none", "token=", "password=", "--ServerApp.allow_origin=*")
        for category, name, image_dir in self.required_image_dirs():
            if category != "tool":
                continue
            dockerfile = (image_dir / "Dockerfile").read_text(encoding="utf-8")
            if any(pattern in dockerfile for pattern in auth_disabled_patterns):
                manifest = self.load_manifest(image_dir / "manifest.yaml")
                if manifest.get("auth", {}).get("delegated_to_platform") is not True:
                    errors.append(f"{category}/{name}: 关闭内置认证但未声明 auth.delegated_to_platform")
        self.assertEqual([], errors)

    def test_shell_entrypoints_fail_fast(self) -> None:
        """所有 shell 入口脚本必须显式启用失败即退出。"""
        errors: list[str] = []
        for path in IMAGES_ROOT.rglob("*.sh"):
            if "__pycache__" in path.parts:
                continue
            content = path.read_text(encoding="utf-8")
            if "set -eu" not in content and "set -euo pipefail" not in content:
                errors.append(str(path.relative_to(IMAGES_ROOT)))
        self.assertEqual([], errors)

    def test_config_driven_infra_images_do_not_default_to_help_or_ready_placeholders(self) -> None:
        """配置驱动的真实 infra 镜像不得用 help/ready 作为默认运行实现。"""
        errors: list[str] = []
        checked = [
            IMAGES_ROOT / "infra" / "aa-bundler" / "Dockerfile",
            IMAGES_ROOT / "infra" / "op-stack" / "Dockerfile",
            IMAGES_ROOT / "infra" / "bridge-relayer" / "Dockerfile",
            IMAGES_ROOT / "infra" / "zk-prover" / "Dockerfile",
        ]
        for path in checked:
            content = path.read_text(encoding="utf-8")
            if re.search(r'CMD\s+\[.*--help|console\.log\(["\'].*ready', content, re.IGNORECASE):
                errors.append(f"{path.relative_to(IMAGES_ROOT)}: 默认入口仍是 help/ready 占位")
            if "ENTRYPOINT" not in content:
                errors.append(f"{path.relative_to(IMAGES_ROOT)}: 缺少显式 ENTRYPOINT")
        self.assertEqual([], errors)

    def test_python_sources_follow_image_runtime_contract(self) -> None:
        """Python 镜像入口必须有职责注释、显式错误处理,且 HTTP 端口来自环境变量。"""
        errors: list[str] = []
        for path in IMAGES_ROOT.rglob("*.py"):
            if "__pycache__" in path.parts:
                continue
            relative = path.relative_to(IMAGES_ROOT)
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(relative))
            if not ast.get_docstring(tree):
                errors.append(f"{relative}: 缺少文件头职责 docstring")
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                    if not ast.get_docstring(node):
                        errors.append(f"{relative}: {node.name} 缺少职责 docstring")
                if isinstance(node, ast.ExceptHandler) and node.type is None:
                    errors.append(f"{relative}: 存在裸 except")
                if isinstance(node, ast.Pass):
                    errors.append(f"{relative}: 存在 pass 空实现")
                if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
                    if node.func.id != "ThreadingHTTPServer" or not node.args:
                        continue
                    address = node.args[0]
                    if isinstance(address, ast.Tuple) and len(address.elts) == 2:
                        port = address.elts[1]
                        if isinstance(port, ast.Constant) and isinstance(port.value, int):
                            errors.append(f"{relative}: HTTP 服务端口必须来自环境变量")
                if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
                    if node.func.attr != "read":
                        continue
                    if isinstance(node.func.value, ast.Attribute) and node.func.value.attr == "rfile":
                        parent_function = self.enclosing_function_name(tree, node)
                        if parent_function == "do_POST" and not self.function_references_name(tree, node, "MAX_BODY_BYTES"):
                            errors.append(f"{relative}: POST 请求体读取必须先检查 MAX_BODY_BYTES")
        self.assertEqual([], errors)

    def enclosing_function_name(self, tree: ast.AST, target: ast.AST) -> str | None:
        """返回目标节点所在的最近函数名。"""
        result: str | None = None
        for node in ast.walk(tree):
            if not isinstance(node, ast.FunctionDef):
                continue
            for child in ast.walk(node):
                if child is target:
                    result = node.name
                    break
        return result

    def function_references_name(self, tree: ast.AST, target: ast.AST, name: str) -> bool:
        """检查目标节点所在函数是否引用指定名称。"""
        for node in ast.walk(tree):
            if not isinstance(node, ast.FunctionDef):
                continue
            if not any(child is target for child in ast.walk(node)):
                continue
            return any(isinstance(child, ast.Name) and child.id == name for child in ast.walk(node))
        return False

    def test_dockerfiles_do_not_embed_sensitive_runtime_values(self) -> None:
        """Dockerfile 不得通过 ENV/ARG/COPY 写入运行期敏感材料。"""
        errors: list[str] = []
        sensitive_patterns = [
            re.compile(pattern, re.IGNORECASE)
            for pattern in (
                r"^(ENV|ARG)\s+\S*(SECRET|PASSWORD|TOKEN|PRIVATE_KEY|ANSWER)\S*=",
                r"^COPY\s+.*(secret|password|token|private[_-]?key|answer)",
            )
        ]
        for path in IMAGES_ROOT.rglob("Dockerfile"):
            for line in path.read_text(encoding="utf-8").splitlines():
                stripped = line.strip()
                if any(pattern.search(stripped) for pattern in sensitive_patterns):
                    errors.append(f"{path.relative_to(IMAGES_ROOT)}: {stripped}")
        self.assertEqual([], errors)

    def test_node_dependencies_are_lockfile_driven(self) -> None:
        """Node 依赖必须通过 package-lock.json 与 npm ci 安装,禁止构建时无锁解析。"""
        errors: list[str] = []
        for path in IMAGES_ROOT.rglob("Dockerfile"):
            content = path.read_text(encoding="utf-8")
            if re.search(r"\bnpm\s+install\b", content):
                errors.append(f"{path.relative_to(IMAGES_ROOT)}: 禁止 npm install,必须使用 npm ci + package-lock.json")
            if "npm ci" in content:
                image_dir = path.parent
                if not (image_dir / "package.json").is_file() or not (image_dir / "package-lock.json").is_file():
                    errors.append(f"{path.relative_to(IMAGES_ROOT)}: npm ci 缺少 package.json 或 package-lock.json")
        self.assertEqual([], errors)

    def test_every_manifest_has_health_or_command_selftest(self) -> None:
        """每个非 distroless 基座镜像都必须有可执行自检命令。"""
        errors: list[str] = []
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            selftest = manifest.get("selftest", {})
            commands = selftest.get("commands", [])
            if category == "base" and selftest.get("note"):
                continue
            for command in commands:
                if not command.get("name") or not command.get("command"):
                    errors.append(f"{category}/{name}: selftest command 缺少 name 或 command")
        self.assertEqual([], errors)

    def test_images_layer_does_not_define_fixed_composition_matrix(self) -> None:
        """镜像层不得定义固定组合矩阵,具体容器组必须由 runtime manifest 与 M2 编排。"""
        errors: list[str] = []
        if (IMAGES_ROOT / "composition.yaml").exists():
            errors.append("images/composition.yaml 不应存在,组合由 runtime.adapter_spec 或实验模板声明")
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            forbidden = sorted(DISALLOWED_COMPOSITION_KEYS & set(manifest))
            if forbidden:
                errors.append(f"{category}/{name}: manifest 包含固定组合字段 {forbidden}")
        self.assertEqual([], errors)

    def test_data_driven_manifests_declare_capabilities_not_pairings(self) -> None:
        """manifest 只能声明本镜像能力和约束,不得把能力表达成镜像到镜像的固定绑定。"""
        errors: list[str] = []
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            capabilities = manifest.get("capabilities", [])
            if not isinstance(capabilities, list) or not capabilities:
                errors.append(f"{category}/{name}: capabilities 缺失")

            if category in {"runtime", "infra", "tool", "judger", "sim"} and manifest.get("data_driven") is not True:
                errors.append(f"{category}/{name}: 数据驱动镜像 data_driven 必须为 true")
            if category == "runtime":
                runtime = manifest.get("runtime", {})
                if not runtime.get("eco"):
                    errors.append(f"{category}/{name}: runtime.eco 缺失")
                if runtime.get("adapter_level") not in {1, 2, 3}:
                    errors.append(f"{category}/{name}: runtime.adapter_level 非法")
                default_tools = runtime.get("default_tool_codes", [])
                if default_tools and not isinstance(default_tools, list):
                    errors.append(f"{category}/{name}: runtime.default_tool_codes 必须是建议列表")
            if category == "tool":
                tool = manifest.get("tool", {})
                if tool.get("kind") not in {"web-embed", "cli"}:
                    errors.append(f"{category}/{name}: tool.kind 非法")
                if not tool.get("eco_tags"):
                    errors.append(f"{category}/{name}: tool.eco_tags 缺失")
                if not isinstance(tool.get("mount_workspace"), bool):
                    errors.append(f"{category}/{name}: tool.mount_workspace 必须是布尔值")
            if category == "infra":
                infra = manifest.get("infra", {})
                if not infra.get("eco_tags"):
                    errors.append(f"{category}/{name}: infra.eco_tags 缺失")
                if not infra.get("roles"):
                    errors.append(f"{category}/{name}: infra.roles 缺失")
            if category == "sidecar" and not manifest.get("sidecar", {}).get("purpose"):
                errors.append(f"{category}/{name}: sidecar.purpose 缺失")
            if category == "sim":
                sim = manifest.get("sim", {})
                if sim.get("compute") != "backend":
                    errors.append(f"{category}/{name}: sim.compute 必须为 backend")
                if not sim.get("backend_adapter"):
                    errors.append(f"{category}/{name}: sim.backend_adapter 缺失")
                if sim.get("protocol") != "stdio-json":
                    errors.append(f"{category}/{name}: sim.protocol 必须为 stdio-json")
                determinism = sim.get("determinism", {})
                if determinism.get("required") is not True:
                    errors.append(f"{category}/{name}: sim.determinism.required 必须为 true")
                if not manifest.get("resources", {}).get("timeout_seconds"):
                    errors.append(f"{category}/{name}: resources.timeout_seconds 缺失")
                if not manifest.get("resources", {}).get("max_input_bytes"):
                    errors.append(f"{category}/{name}: resources.max_input_bytes 缺失")
            if category == "judger":
                judger = manifest.get("judger", {})
                if judger.get("type") not in {"testcase", "static-scan"}:
                    errors.append(f"{category}/{name}: judger.type 非法或缺失")
                output = judger.get("output_contract", {})
                for key in ("passed", "score", "max_score", "details"):
                    if key not in output.get("required_fields", []):
                        errors.append(f"{category}/{name}: output_contract 缺少 {key}")
                if judger.get("leaks_expected_values") is not False:
                    errors.append(f"{category}/{name}: judger.leaks_expected_values 必须为 false")
                if not manifest.get("resources", {}).get("timeout_seconds"):
                    errors.append(f"{category}/{name}: resources.timeout_seconds 缺失")
        self.assertEqual([], errors)

    def test_backend_native_judgers_are_not_duplicated_as_required_images(self) -> None:
        """J2/J3/J5 由 M3 后端策略承接时,镜像层不得再保留重复执行器。"""
        forbidden_dirs = [
            IMAGES_ROOT / "judger" / "onchain-assert",
            IMAGES_ROOT / "judger" / "flag",
            IMAGES_ROOT / "judger" / "sim-checkpoint",
        ]
        existing = [str(path.relative_to(IMAGES_ROOT)) for path in forbidden_dirs if path.exists()]
        self.assertEqual([], existing)

    def test_infra_mock_services_are_not_required_platform_images(self) -> None:
        """教师脚本和题目固化资产可表达的 mock 能力,不得成为平台必需服务镜像。"""
        forbidden_dirs = sorted(
            str(path.relative_to(IMAGES_ROOT))
            for path in (IMAGES_ROOT / "infra").glob("*-mock")
            if path.is_dir()
        )
        self.assertEqual([], forbidden_dirs)

    def test_non_mock_infra_images_do_not_replace_real_components_with_python_http_services(self) -> None:
        """非 mock 的真实生态组件不得用自研 Python HTTP 教学服务替代。"""
        errors: list[str] = []
        for category, name, image_dir in self.required_image_dirs():
            if category not in {"infra", "tool", "runtime"}:
                continue
            if not (image_dir / "Dockerfile").exists():
                continue
            dockerfile = (image_dir / "Dockerfile").read_text(encoding="utf-8")
            if "FROM python:" not in dockerfile:
                continue
            if "ThreadingHTTPServer" not in "\n".join(
                path.read_text(encoding="utf-8") for path in image_dir.glob("*.py")
            ):
                continue
            if (category, name) not in ALLOWED_SELF_DEVELOPED_HTTP_IMAGES:
                errors.append(f"{category}/{name}: 真实组件不得用 Python HTTP 教学服务替代")
        self.assertEqual([], errors)

    def test_ports_and_student_access_do_not_bypass_control_plane(self) -> None:
        """端口和学生访问权限不得绕过 M2 控制面与安全域约束。"""
        errors: list[str] = []
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            for mapping in manifest.get("local_dev", {}).get("host_mappings", []):
                if mapping.get("host") != "127.0.0.1":
                    errors.append(f"{category}/{name}: 本地映射未绑定 127.0.0.1")
                if not mapping.get("env"):
                    errors.append(f"{category}/{name}: 本地映射缺少环境变量名")
            student_access = manifest.get("student_access", {})
            if student_access.get("enabled") is True:
                allowed = set(student_access.get("allowed_mounts", []))
                forbidden_mounts = {"judge-private", "secret", "kubeconfig", "host", "teacher-answer"}
                if allowed & forbidden_mounts:
                    errors.append(f"{category}/{name}: 学生挂载域包含敏感域 {sorted(allowed & forbidden_mounts)}")
                for exception in manifest.get("security_exceptions", []):
                    writable = set(exception.get("writable_mounts", []))
                    if writable & forbidden_mounts:
                        errors.append(
                            f"{category}/{name}: 学生容器只读例外包含敏感写入域 {sorted(writable & forbidden_mounts)}"
                        )
                if category in {"service", "judger", "init", "sidecar"}:
                    errors.append(f"{category}/{name}: 敏感分类不允许学生入口")
        self.assertEqual([], errors)

    def test_runtime_images_with_wide_rpc_flags_declare_m2_controls(self) -> None:
        """运行时若开放宽 RPC 监听或危险 RPC 标志,manifest 必须声明 M2 强制控制项。"""
        errors: list[str] = []
        required_controls = {
            "network_policy_deny_all",
            "platform_authenticated_proxy",
            "no_direct_student_shell_to_rpc_admin",
            "m2_port_allowlist",
        }
        for name in ("evm-geth", "evm-besu", "substrate", "bitcoin"):
            manifest = self.load_manifest(IMAGES_ROOT / "runtime" / name / "manifest.yaml")
            exposure = manifest.get("rpc_exposure", {})
            controls = set(exposure.get("required_controls", []))
            if exposure.get("bind_all_interfaces") is not True:
                errors.append(f"runtime/{name}: rpc_exposure.bind_all_interfaces 必须为 true")
            if not exposure.get("reason"):
                errors.append(f"runtime/{name}: rpc_exposure.reason 缺失")
            missing = sorted(required_controls - controls)
            if missing:
                errors.append(f"runtime/{name}: rpc_exposure.required_controls 缺少 {missing}")
        self.assertEqual([], errors)

    def test_ports_are_unique_and_local_defaults_do_not_collide(self) -> None:
        """同一镜像容器端口不得重复,本地默认映射端口也不得冲突。"""
        errors: list[str] = []
        local_defaults: dict[int, str] = {}
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            seen_ports: set[tuple[int, str]] = set()
            for port in manifest.get("ports", []):
                key = (int(port.get("container_port", 0)), str(port.get("protocol", "TCP")))
                if key in seen_ports:
                    errors.append(f"{category}/{name}: 容器端口重复 {key[0]}/{key[1]}")
                seen_ports.add(key)
                if port.get("expose") not in {"internal", "proxy", "gateway", "none"}:
                    errors.append(f"{category}/{name}: ports.expose={port.get('expose')!r} 非法")
            for mapping in manifest.get("local_dev", {}).get("host_mappings", []):
                default = int(mapping.get("default", 0))
                owner = f"{category}/{name}"
                if default in local_defaults:
                    errors.append(f"{owner}: 本地默认端口 {default} 与 {local_defaults[default]} 冲突")
                local_defaults[default] = owner
        self.assertEqual([], errors)

    def test_read_only_root_exceptions_are_scoped(self) -> None:
        """只读根文件系统例外必须写清原因和允许写入的受控卷域。"""
        errors: list[str] = []
        allowed_domains = {"workspace", "runtime-state", "tool-cache", "secret"}
        for category, name, image_dir in self.required_image_dirs():
            manifest = self.load_manifest(image_dir / "manifest.yaml")
            security = manifest.get("security", {})
            exceptions = manifest.get("security_exceptions", [])
            if security.get("read_only_root_filesystem") is False:
                if not exceptions:
                    errors.append(f"{category}/{name}: 只读根文件系统例外缺失")
                for exception in exceptions:
                    if exception.get("field") != "read_only_root_filesystem":
                        errors.append(f"{category}/{name}: security_exceptions.field 非法")
                    if not exception.get("reason"):
                        errors.append(f"{category}/{name}: security_exceptions.reason 缺失")
                    writable = set(exception.get("writable_mounts", []))
                    if not writable:
                        errors.append(f"{category}/{name}: security_exceptions.writable_mounts 缺失")
                    if writable - allowed_domains:
                        errors.append(f"{category}/{name}: 未知写入域 {sorted(writable - allowed_domains)}")
        self.assertEqual([], errors)

    def test_images_layer_has_no_forbidden_release_gate_terms(self) -> None:
        """镜像层不得残留临时实现、批量生成路线或宿主机网络绕过字样。"""
        hits: list[str] = []
        for path in IMAGES_ROOT.rglob("*"):
            if (
                path.is_dir()
                or "__pycache__" in path.parts
                or "tests" in path.parts
                or path.suffix == ".pyc"
            ):
                continue
            content = path.read_text(encoding="utf-8")
            for pattern in FORBIDDEN_PATTERNS:
                if pattern.search(content):
                    hits.append(f"{path.relative_to(IMAGES_ROOT)}: {pattern.pattern}")
        self.assertEqual([], hits)


if __name__ == "__main__":
    unittest.main()
