// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAccountRole = `-- name: AddAccountRole :exec

INSERT INTO account_role (id, tenant_id, account_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, account_id, role) DO NOTHING
`

type AddAccountRoleParams struct {
	ID        int64 `json:"id"`
	TenantID  int64 `json:"tenant_id"`
	AccountID int64 `json:"account_id"`
	Role      int16 `json:"role"`
}

// ============================================================
// account_role
// ============================================================
func (q *Queries) AddAccountRole(ctx context.Context, arg AddAccountRoleParams) error {
	_, err := q.db.Exec(ctx, addAccountRole,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.Role,
	)
	return err
}

const approveTenantApplication = `-- name: ApproveTenantApplication :one
UPDATE tenant_application SET status = 2, reviewed_by = $2, tenant_id = $3
WHERE id = $1 AND status = 1
RETURNING id, school_name, school_type, contact_name, contact_phone, contact_email, status, reject_reason, reviewed_by, tenant_id, created_at, updated_at
`

type ApproveTenantApplicationParams struct {
	ID         int64       `json:"id"`
	ReviewedBy pgtype.Int8 `json:"reviewed_by"`
	TenantID   pgtype.Int8 `json:"tenant_id"`
}

func (q *Queries) ApproveTenantApplication(ctx context.Context, arg ApproveTenantApplicationParams) (TenantApplication, error) {
	row := q.db.QueryRow(ctx, approveTenantApplication, arg.ID, arg.ReviewedBy, arg.TenantID)
	var i TenantApplication
	err := row.Scan(
		&i.ID,
		&i.SchoolName,
		&i.SchoolType,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Status,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveAccountsByClass = `-- name: ArchiveAccountsByClass :exec
UPDATE account SET status = 4
WHERE base_identity = 1 AND status = 2
  AND id IN (SELECT account_id FROM account_profile WHERE org_id = $1)
`

// 班级归档级联:该班级在读学生账号一并归档(status 2正常 → 4归档)。
func (q *Queries) ArchiveAccountsByClass(ctx context.Context, orgID int64) error {
	_, err := q.db.Exec(ctx, archiveAccountsByClass, orgID)
	return err
}

const archiveClass = `-- name: ArchiveClass :exec
UPDATE class SET status = 2 WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ArchiveClass(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, archiveClass, id)
	return err
}

const archiveStudentAccountsByEnrollmentYear = `-- name: ArchiveStudentAccountsByEnrollmentYear :many
UPDATE account a SET status = 4
FROM account_profile p
WHERE p.account_id = a.id
  AND a.base_identity = 1
  AND a.status = 2
  AND p.enrollment_year = $1
RETURNING a.id
`

// 学年归档:仅归档当前租户内正常状态学生账号,避免教师或停用/注销账号被误改。
func (q *Queries) ArchiveStudentAccountsByEnrollmentYear(ctx context.Context, enrollmentYear pgtype.Int2) ([]int64, error) {
	rows, err := q.db.Query(ctx, archiveStudentAccountsByEnrollmentYear, enrollmentYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM account a
LEFT JOIN account_profile p ON p.account_id = a.id
WHERE ($1::SMALLINT IS NULL OR a.status = $1)
  AND ($2::SMALLINT IS NULL OR a.base_identity = $2)
  AND ($3::SMALLINT IS NULL OR EXISTS (
    SELECT 1 FROM account_role ar WHERE ar.account_id = a.id AND ar.role = $3
  ))
  AND ($4::BIGINT IS NULL OR (
    a.base_identity = 1 AND p.org_id = $4
  ))
  AND ($5::TEXT IS NULL OR a.name ILIKE '%' || $5 || '%')
`

type CountAccountsParams struct {
	Status       pgtype.Int2 `json:"status"`
	BaseIdentity pgtype.Int2 `json:"base_identity"`
	Role         pgtype.Int2 `json:"role"`
	ClassID      pgtype.Int8 `json:"class_id"`
	Keyword      pgtype.Text `json:"keyword"`
}

func (q *Queries) CountAccounts(ctx context.Context, arg CountAccountsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts,
		arg.Status,
		arg.BaseIdentity,
		arg.Role,
		arg.ClassID,
		arg.Keyword,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllAccounts = `-- name: CountAllAccounts :one
SELECT count(*)::bigint FROM account
WHERE status <> 5
  AND ($1::SMALLINT IS NULL OR base_identity = $1)
`

func (q *Queries) CountAllAccounts(ctx context.Context, baseIdentity pgtype.Int2) (int64, error) {
	row := q.db.QueryRow(ctx, countAllAccounts, baseIdentity)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*)::bigint FROM audit_log
WHERE ($1::BIGINT IS NULL OR actor_id = $1)
  AND ($2::TEXT IS NULL OR action = $2)
  AND ($3::TEXT IS NULL OR target_type = $3)
  AND ($4::TIMESTAMPTZ IS NULL OR created_at >= $4)
  AND ($5::TIMESTAMPTZ IS NULL OR created_at <= $5)
`

type CountAuditLogsParams struct {
	ActorID    pgtype.Int8        `json:"actor_id"`
	Action     pgtype.Text        `json:"action"`
	TargetType pgtype.Text        `json:"target_type"`
	FromTime   pgtype.Timestamptz `json:"from_time"`
	ToTime     pgtype.Timestamptz `json:"to_time"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.FromTime,
		arg.ToTime,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countImportBatches = `-- name: CountImportBatches :one
SELECT count(*)::bigint FROM import_batch
`

func (q *Queries) CountImportBatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countImportBatches)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPlatformAuditLogs = `-- name: CountPlatformAuditLogs :one
SELECT count(*)::bigint FROM audit_log
WHERE ($1::BIGINT IS NULL OR actor_id = $1)
  AND ($2::TEXT IS NULL OR action = $2)
  AND ($3::TEXT IS NULL OR target_type = $3)
  AND ($4::TIMESTAMPTZ IS NULL OR created_at >= $4)
  AND ($5::TIMESTAMPTZ IS NULL OR created_at <= $5)
`

type CountPlatformAuditLogsParams struct {
	ActorID    pgtype.Int8        `json:"actor_id"`
	Action     pgtype.Text        `json:"action"`
	TargetType pgtype.Text        `json:"target_type"`
	FromTime   pgtype.Timestamptz `json:"from_time"`
	ToTime     pgtype.Timestamptz `json:"to_time"`
}

func (q *Queries) CountPlatformAuditLogs(ctx context.Context, arg CountPlatformAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatformAuditLogs,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.FromTime,
		arg.ToTime,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTenantApplications = `-- name: CountTenantApplications :one
SELECT count(*)::bigint FROM tenant_application
WHERE ($1::SMALLINT IS NULL OR status = $1)
`

func (q *Queries) CountTenantApplications(ctx context.Context, status pgtype.Int2) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantApplications, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTenants = `-- name: CountTenants :one
SELECT count(*) FROM tenant
WHERE ($1::SMALLINT IS NULL OR status = $1)
`

func (q *Queries) CountTenants(ctx context.Context, status pgtype.Int2) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one

INSERT INTO account (id, tenant_id, phone_enc, phone_hash, password_hash, name, base_identity, status, must_change_pwd)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, phone_enc, phone_hash, password_hash, name, base_identity, status, must_change_pwd, pwd_failed_count, locked_until, activated_at, created_at, updated_at
`

type CreateAccountParams struct {
	ID            int64       `json:"id"`
	TenantID      int64       `json:"tenant_id"`
	PhoneEnc      []byte      `json:"phone_enc"`
	PhoneHash     string      `json:"phone_hash"`
	PasswordHash  pgtype.Text `json:"password_hash"`
	Name          string      `json:"name"`
	BaseIdentity  int16       `json:"base_identity"`
	Status        int16       `json:"status"`
	MustChangePwd bool        `json:"must_change_pwd"`
}

// ============================================================
// account
// ============================================================
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.TenantID,
		arg.PhoneEnc,
		arg.PhoneHash,
		arg.PasswordHash,
		arg.Name,
		arg.BaseIdentity,
		arg.Status,
		arg.MustChangePwd,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneEnc,
		&i.PhoneHash,
		&i.PasswordHash,
		&i.Name,
		&i.BaseIdentity,
		&i.Status,
		&i.MustChangePwd,
		&i.PwdFailedCount,
		&i.LockedUntil,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAccountProfile = `-- name: CreateAccountProfile :one

INSERT INTO account_profile (account_id, tenant_id, no, org_id, enrollment_year, title)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING account_id, tenant_id, no, org_id, enrollment_year, title
`

type CreateAccountProfileParams struct {
	AccountID      int64       `json:"account_id"`
	TenantID       int64       `json:"tenant_id"`
	No             string      `json:"no"`
	OrgID          int64       `json:"org_id"`
	EnrollmentYear pgtype.Int2 `json:"enrollment_year"`
	Title          pgtype.Text `json:"title"`
}

// ============================================================
// account_profile
// ============================================================
func (q *Queries) CreateAccountProfile(ctx context.Context, arg CreateAccountProfileParams) (AccountProfile, error) {
	row := q.db.QueryRow(ctx, createAccountProfile,
		arg.AccountID,
		arg.TenantID,
		arg.No,
		arg.OrgID,
		arg.EnrollmentYear,
		arg.Title,
	)
	var i AccountProfile
	err := row.Scan(
		&i.AccountID,
		&i.TenantID,
		&i.No,
		&i.OrgID,
		&i.EnrollmentYear,
		&i.Title,
	)
	return i, err
}

const createActivationCode = `-- name: CreateActivationCode :one

INSERT INTO activation_code (id, tenant_id, account_id, code_hash, status, expire_at, created_by)
VALUES ($1, $2, $3, $4, 1, $5, $6)
RETURNING id, tenant_id, account_id, code_hash, status, expire_at, used_at, created_by, created_at
`

type CreateActivationCodeParams struct {
	ID        int64              `json:"id"`
	TenantID  int64              `json:"tenant_id"`
	AccountID int64              `json:"account_id"`
	CodeHash  string             `json:"code_hash"`
	ExpireAt  pgtype.Timestamptz `json:"expire_at"`
	CreatedBy pgtype.Int8        `json:"created_by"`
}

// ============================================================
// activation_code
// ============================================================
func (q *Queries) CreateActivationCode(ctx context.Context, arg CreateActivationCodeParams) (ActivationCode, error) {
	row := q.db.QueryRow(ctx, createActivationCode,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.CodeHash,
		arg.ExpireAt,
		arg.CreatedBy,
	)
	var i ActivationCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.CodeHash,
		&i.Status,
		&i.ExpireAt,
		&i.UsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :exec

INSERT INTO audit_log (id, tenant_id, actor_id, actor_role, action, target_type, target_id, detail, ip, trace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateAuditLogParams struct {
	ID         int64       `json:"id"`
	TenantID   pgtype.Int8 `json:"tenant_id"`
	ActorID    int64       `json:"actor_id"`
	ActorRole  int16       `json:"actor_role"`
	Action     string      `json:"action"`
	TargetType string      `json:"target_type"`
	TargetID   pgtype.Int8 `json:"target_id"`
	Detail     []byte      `json:"detail"`
	Ip         pgtype.Text `json:"ip"`
	TraceID    pgtype.Text `json:"trace_id"`
}

// ============================================================
// audit_log(全平台唯一审计表)
// ============================================================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.ActorRole,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Detail,
		arg.Ip,
		arg.TraceID,
	)
	return err
}

const createAuthSession = `-- name: CreateAuthSession :one

INSERT INTO auth_session (id, tenant_id, account_id, refresh_token_hash, device_info, ip, status, expire_at)
VALUES ($1, $2, $3, $4, $5, $6, 1, $7)
RETURNING id, tenant_id, account_id, refresh_token_hash, device_info, ip, status, expire_at, created_at
`

type CreateAuthSessionParams struct {
	ID               int64              `json:"id"`
	TenantID         int64              `json:"tenant_id"`
	AccountID        int64              `json:"account_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceInfo       pgtype.Text        `json:"device_info"`
	Ip               pgtype.Text        `json:"ip"`
	ExpireAt         pgtype.Timestamptz `json:"expire_at"`
}

// ============================================================
// auth_session
// ============================================================
func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.RefreshTokenHash,
		arg.DeviceInfo,
		arg.Ip,
		arg.ExpireAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.RefreshTokenHash,
		&i.DeviceInfo,
		&i.Ip,
		&i.Status,
		&i.ExpireAt,
		&i.CreatedAt,
	)
	return i, err
}

const createClass = `-- name: CreateClass :one
INSERT INTO class (id, tenant_id, major_id, name, enrollment_year, status)
VALUES ($1, $2, $3, $4, $5, 1) RETURNING id, tenant_id, major_id, name, enrollment_year, status, created_at, updated_at, deleted_at
`

type CreateClassParams struct {
	ID             int64  `json:"id"`
	TenantID       int64  `json:"tenant_id"`
	MajorID        int64  `json:"major_id"`
	Name           string `json:"name"`
	EnrollmentYear int16  `json:"enrollment_year"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass,
		arg.ID,
		arg.TenantID,
		arg.MajorID,
		arg.Name,
		arg.EnrollmentYear,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MajorID,
		&i.Name,
		&i.EnrollmentYear,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDepartment = `-- name: CreateDepartment :one

INSERT INTO department (id, tenant_id, name, code) VALUES ($1, $2, $3, $4) RETURNING id, tenant_id, name, code, created_at, updated_at, deleted_at
`

type CreateDepartmentParams struct {
	ID       int64       `json:"id"`
	TenantID int64       `json:"tenant_id"`
	Name     string      `json:"name"`
	Code     pgtype.Text `json:"code"`
}

// ============================================================
// department / major / class(租户表,RLS 透明)
// ============================================================
func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Code,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batch (id, tenant_id, operator_id, target_type, file_name, total, success, failed, error_detail, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, operator_id, target_type, file_name, total, success, failed, error_detail, status, created_at
`

type CreateImportBatchParams struct {
	ID          int64  `json:"id"`
	TenantID    int64  `json:"tenant_id"`
	OperatorID  int64  `json:"operator_id"`
	TargetType  int16  `json:"target_type"`
	FileName    string `json:"file_name"`
	Total       int32  `json:"total"`
	Success     int32  `json:"success"`
	Failed      int32  `json:"failed"`
	ErrorDetail []byte `json:"error_detail"`
	Status      int16  `json:"status"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.ID,
		arg.TenantID,
		arg.OperatorID,
		arg.TargetType,
		arg.FileName,
		arg.Total,
		arg.Success,
		arg.Failed,
		arg.ErrorDetail,
		arg.Status,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OperatorID,
		&i.TargetType,
		&i.FileName,
		&i.Total,
		&i.Success,
		&i.Failed,
		&i.ErrorDetail,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createImportPreview = `-- name: CreateImportPreview :one

INSERT INTO import_preview (id, tenant_id, operator_id, target_type, file_name, rows, preview_result, status, expire_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1, $8)
RETURNING id, tenant_id, operator_id, target_type, file_name, rows, preview_result, status, expire_at, created_at, submitted_at
`

type CreateImportPreviewParams struct {
	ID            int64              `json:"id"`
	TenantID      int64              `json:"tenant_id"`
	OperatorID    int64              `json:"operator_id"`
	TargetType    int16              `json:"target_type"`
	FileName      string             `json:"file_name"`
	Rows          []byte             `json:"rows"`
	PreviewResult []byte             `json:"preview_result"`
	ExpireAt      pgtype.Timestamptz `json:"expire_at"`
}

// ============================================================
// import_batch
// ============================================================
func (q *Queries) CreateImportPreview(ctx context.Context, arg CreateImportPreviewParams) (ImportPreview, error) {
	row := q.db.QueryRow(ctx, createImportPreview,
		arg.ID,
		arg.TenantID,
		arg.OperatorID,
		arg.TargetType,
		arg.FileName,
		arg.Rows,
		arg.PreviewResult,
		arg.ExpireAt,
	)
	var i ImportPreview
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OperatorID,
		&i.TargetType,
		&i.FileName,
		&i.Rows,
		&i.PreviewResult,
		&i.Status,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const createMajor = `-- name: CreateMajor :one
INSERT INTO major (id, tenant_id, department_id, name) VALUES ($1, $2, $3, $4) RETURNING id, tenant_id, department_id, name, created_at, updated_at, deleted_at
`

type CreateMajorParams struct {
	ID           int64  `json:"id"`
	TenantID     int64  `json:"tenant_id"`
	DepartmentID int64  `json:"department_id"`
	Name         string `json:"name"`
}

func (q *Queries) CreateMajor(ctx context.Context, arg CreateMajorParams) (Major, error) {
	row := q.db.QueryRow(ctx, createMajor,
		arg.ID,
		arg.TenantID,
		arg.DepartmentID,
		arg.Name,
	)
	var i Major
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DepartmentID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPlatformAdmin = `-- name: CreatePlatformAdmin :one
INSERT INTO platform_admin (id, username, password_hash, name, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password_hash, name, status, created_at, updated_at
`

type CreatePlatformAdminParams struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
	Status       int16  `json:"status"`
}

func (q *Queries) CreatePlatformAdmin(ctx context.Context, arg CreatePlatformAdminParams) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, createPlatformAdmin,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Name,
		arg.Status,
	)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlatformAuthSession = `-- name: CreatePlatformAuthSession :one
INSERT INTO platform_auth_session (id, platform_admin_id, refresh_token_hash, device_info, ip, status, expire_at)
VALUES ($1, $2, $3, $4, $5, 1, $6)
RETURNING id, platform_admin_id, refresh_token_hash, device_info, ip, status, expire_at, created_at
`

type CreatePlatformAuthSessionParams struct {
	ID               int64              `json:"id"`
	PlatformAdminID  int64              `json:"platform_admin_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceInfo       pgtype.Text        `json:"device_info"`
	Ip               pgtype.Text        `json:"ip"`
	ExpireAt         pgtype.Timestamptz `json:"expire_at"`
}

func (q *Queries) CreatePlatformAuthSession(ctx context.Context, arg CreatePlatformAuthSessionParams) (PlatformAuthSession, error) {
	row := q.db.QueryRow(ctx, createPlatformAuthSession,
		arg.ID,
		arg.PlatformAdminID,
		arg.RefreshTokenHash,
		arg.DeviceInfo,
		arg.Ip,
		arg.ExpireAt,
	)
	var i PlatformAuthSession
	err := row.Scan(
		&i.ID,
		&i.PlatformAdminID,
		&i.RefreshTokenHash,
		&i.DeviceInfo,
		&i.Ip,
		&i.Status,
		&i.ExpireAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSmsCode = `-- name: CreateSmsCode :one

INSERT INTO sms_code (id, tenant_id, phone_hash, code_hash, scene, expire_at, used)
VALUES ($1, $2, $3, $4, $5, $6, false)
RETURNING id, tenant_id, phone_hash, code_hash, scene, expire_at, used, created_at
`

type CreateSmsCodeParams struct {
	ID        int64              `json:"id"`
	TenantID  pgtype.Int8        `json:"tenant_id"`
	PhoneHash string             `json:"phone_hash"`
	CodeHash  string             `json:"code_hash"`
	Scene     int16              `json:"scene"`
	ExpireAt  pgtype.Timestamptz `json:"expire_at"`
}

// ============================================================
// sms_code
// ============================================================
func (q *Queries) CreateSmsCode(ctx context.Context, arg CreateSmsCodeParams) (SmsCode, error) {
	row := q.db.QueryRow(ctx, createSmsCode,
		arg.ID,
		arg.TenantID,
		arg.PhoneHash,
		arg.CodeHash,
		arg.Scene,
		arg.ExpireAt,
	)
	var i SmsCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneHash,
		&i.CodeHash,
		&i.Scene,
		&i.ExpireAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenant (id, code, name, type, status, deploy_mode, expire_at, auth_mode, enable_activation_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, name, type, status, deploy_mode, expire_at, logo_url, display_name, feature_flags, auth_mode, enable_activation_code, created_at, updated_at
`

type CreateTenantParams struct {
	ID                   int64              `json:"id"`
	Code                 string             `json:"code"`
	Name                 string             `json:"name"`
	Type                 int16              `json:"type"`
	Status               int16              `json:"status"`
	DeployMode           int16              `json:"deploy_mode"`
	ExpireAt             pgtype.Timestamptz `json:"expire_at"`
	AuthMode             int16              `json:"auth_mode"`
	EnableActivationCode bool               `json:"enable_activation_code"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.DeployMode,
		arg.ExpireAt,
		arg.AuthMode,
		arg.EnableActivationCode,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.DeployMode,
		&i.ExpireAt,
		&i.LogoUrl,
		&i.DisplayName,
		&i.FeatureFlags,
		&i.AuthMode,
		&i.EnableActivationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenantApplication = `-- name: CreateTenantApplication :one

INSERT INTO tenant_application (id, school_name, school_type, contact_name, contact_phone, contact_email, status)
VALUES ($1, $2, $3, $4, $5, $6, 1)
RETURNING id, school_name, school_type, contact_name, contact_phone, contact_email, status, reject_reason, reviewed_by, tenant_id, created_at, updated_at
`

type CreateTenantApplicationParams struct {
	ID           int64  `json:"id"`
	SchoolName   string `json:"school_name"`
	SchoolType   int16  `json:"school_type"`
	ContactName  string `json:"contact_name"`
	ContactPhone string `json:"contact_phone"`
	ContactEmail string `json:"contact_email"`
}

// ============================================================
// tenant_application
// ============================================================
func (q *Queries) CreateTenantApplication(ctx context.Context, arg CreateTenantApplicationParams) (TenantApplication, error) {
	row := q.db.QueryRow(ctx, createTenantApplication,
		arg.ID,
		arg.SchoolName,
		arg.SchoolType,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactEmail,
	)
	var i TenantApplication
	err := row.Scan(
		&i.ID,
		&i.SchoolName,
		&i.SchoolType,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Status,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAccountsByPhoneAllTenants = `-- name: FindAccountsByPhoneAllTenants :many
SELECT a.id AS account_id, a.tenant_id, a.name, t.code AS tenant_code, t.name AS tenant_name, t.status AS tenant_status
FROM account a
JOIN tenant t ON t.id = a.tenant_id
WHERE a.phone_hash = $1 AND a.status <> 5
`

type FindAccountsByPhoneAllTenantsRow struct {
	AccountID    int64  `json:"account_id"`
	TenantID     int64  `json:"tenant_id"`
	Name         string `json:"name"`
	TenantCode   string `json:"tenant_code"`
	TenantName   string `json:"tenant_name"`
	TenantStatus int16  `json:"tenant_status"`
}

// 一号多校登录定位:跨租户按 phone_hash 查账号。
// ★ 必须在特权连接(属主,绕 RLS)上执行;返回登录定位最小字段(不含手机号/密码)。
func (q *Queries) FindAccountsByPhoneAllTenants(ctx context.Context, phoneHash string) ([]FindAccountsByPhoneAllTenantsRow, error) {
	rows, err := q.db.Query(ctx, findAccountsByPhoneAllTenants, phoneHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAccountsByPhoneAllTenantsRow{}
	for rows.Next() {
		var i FindAccountsByPhoneAllTenantsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.TenantID,
			&i.Name,
			&i.TenantCode,
			&i.TenantName,
			&i.TenantStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlatformSessionByTokenHash = `-- name: FindPlatformSessionByTokenHash :one
SELECT id, platform_admin_id, status, expire_at FROM platform_auth_session WHERE refresh_token_hash = $1
`

type FindPlatformSessionByTokenHashRow struct {
	ID              int64              `json:"id"`
	PlatformAdminID int64              `json:"platform_admin_id"`
	Status          int16              `json:"status"`
	ExpireAt        pgtype.Timestamptz `json:"expire_at"`
}

func (q *Queries) FindPlatformSessionByTokenHash(ctx context.Context, refreshTokenHash string) (FindPlatformSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findPlatformSessionByTokenHash, refreshTokenHash)
	var i FindPlatformSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.PlatformAdminID,
		&i.Status,
		&i.ExpireAt,
	)
	return i, err
}

const findSessionByTokenHash = `-- name: FindSessionByTokenHash :one
SELECT id, tenant_id, account_id, status, expire_at FROM auth_session WHERE refresh_token_hash = $1
`

type FindSessionByTokenHashRow struct {
	ID        int64              `json:"id"`
	TenantID  int64              `json:"tenant_id"`
	AccountID int64              `json:"account_id"`
	Status    int16              `json:"status"`
	ExpireAt  pgtype.Timestamptz `json:"expire_at"`
}

// Refresh 轮转/重放检测:跨租户按 refresh_token_hash 定位会话。
// ★ 必须在特权连接(属主,绕 RLS)上执行(Refresh Token 不含租户信息)。
func (q *Queries) FindSessionByTokenHash(ctx context.Context, refreshTokenHash string) (FindSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findSessionByTokenHash, refreshTokenHash)
	var i FindSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Status,
		&i.ExpireAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, tenant_id, phone_enc, phone_hash, password_hash, name, base_identity, status, must_change_pwd, pwd_failed_count, locked_until, activated_at, created_at, updated_at FROM account WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneEnc,
		&i.PhoneHash,
		&i.PasswordHash,
		&i.Name,
		&i.BaseIdentity,
		&i.Status,
		&i.MustChangePwd,
		&i.PwdFailedCount,
		&i.LockedUntil,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByPhoneHash = `-- name: GetAccountByPhoneHash :one
SELECT id, tenant_id, phone_enc, phone_hash, password_hash, name, base_identity, status, must_change_pwd, pwd_failed_count, locked_until, activated_at, created_at, updated_at FROM account WHERE phone_hash = $1
`

func (q *Queries) GetAccountByPhoneHash(ctx context.Context, phoneHash string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPhoneHash, phoneHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneEnc,
		&i.PhoneHash,
		&i.PasswordHash,
		&i.Name,
		&i.BaseIdentity,
		&i.Status,
		&i.MustChangePwd,
		&i.PwdFailedCount,
		&i.LockedUntil,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountProfile = `-- name: GetAccountProfile :one
SELECT account_id, tenant_id, no, org_id, enrollment_year, title FROM account_profile WHERE account_id = $1
`

func (q *Queries) GetAccountProfile(ctx context.Context, accountID int64) (AccountProfile, error) {
	row := q.db.QueryRow(ctx, getAccountProfile, accountID)
	var i AccountProfile
	err := row.Scan(
		&i.AccountID,
		&i.TenantID,
		&i.No,
		&i.OrgID,
		&i.EnrollmentYear,
		&i.Title,
	)
	return i, err
}

const getAccountProfileByNo = `-- name: GetAccountProfileByNo :one
SELECT account_id, tenant_id, no, org_id, enrollment_year, title FROM account_profile WHERE no = $1
`

func (q *Queries) GetAccountProfileByNo(ctx context.Context, no string) (AccountProfile, error) {
	row := q.db.QueryRow(ctx, getAccountProfileByNo, no)
	var i AccountProfile
	err := row.Scan(
		&i.AccountID,
		&i.TenantID,
		&i.No,
		&i.OrgID,
		&i.EnrollmentYear,
		&i.Title,
	)
	return i, err
}

const getActivationCodeByHash = `-- name: GetActivationCodeByHash :one
SELECT id, tenant_id, account_id, code_hash, status, expire_at, used_at, created_by, created_at FROM activation_code WHERE code_hash = $1
`

// 登录前激活码定位:必须在特权连接上执行,仅返回激活码最小字段用于定位租户与账号。
func (q *Queries) GetActivationCodeByHash(ctx context.Context, codeHash string) (ActivationCode, error) {
	row := q.db.QueryRow(ctx, getActivationCodeByHash, codeHash)
	var i ActivationCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.CodeHash,
		&i.Status,
		&i.ExpireAt,
		&i.UsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getClassByID = `-- name: GetClassByID :one
SELECT id, tenant_id, major_id, name, enrollment_year, status, created_at, updated_at, deleted_at FROM class WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetClassByID(ctx context.Context, id int64) (Class, error) {
	row := q.db.QueryRow(ctx, getClassByID, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MajorID,
		&i.Name,
		&i.EnrollmentYear,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, tenant_id, name, code, created_at, updated_at, deleted_at FROM department WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id int64) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestSmsCode = `-- name: GetLatestSmsCode :one
SELECT id, tenant_id, phone_hash, code_hash, scene, expire_at, used, created_at FROM sms_code
WHERE phone_hash = $1 AND scene = $2 AND used = false AND expire_at > now()
ORDER BY created_at DESC LIMIT 1
`

type GetLatestSmsCodeParams struct {
	PhoneHash string `json:"phone_hash"`
	Scene     int16  `json:"scene"`
}

func (q *Queries) GetLatestSmsCode(ctx context.Context, arg GetLatestSmsCodeParams) (SmsCode, error) {
	row := q.db.QueryRow(ctx, getLatestSmsCode, arg.PhoneHash, arg.Scene)
	var i SmsCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneHash,
		&i.CodeHash,
		&i.Scene,
		&i.ExpireAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getMajorByID = `-- name: GetMajorByID :one
SELECT id, tenant_id, department_id, name, created_at, updated_at, deleted_at FROM major WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMajorByID(ctx context.Context, id int64) (Major, error) {
	row := q.db.QueryRow(ctx, getMajorByID, id)
	var i Major
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DepartmentID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPendingImportPreview = `-- name: GetPendingImportPreview :one
SELECT id, tenant_id, operator_id, target_type, file_name, rows, preview_result, status, expire_at, created_at, submitted_at FROM import_preview
WHERE id = $1 AND operator_id = $2 AND status = 1 AND expire_at > now()
FOR UPDATE
`

type GetPendingImportPreviewParams struct {
	ID         int64 `json:"id"`
	OperatorID int64 `json:"operator_id"`
}

func (q *Queries) GetPendingImportPreview(ctx context.Context, arg GetPendingImportPreviewParams) (ImportPreview, error) {
	row := q.db.QueryRow(ctx, getPendingImportPreview, arg.ID, arg.OperatorID)
	var i ImportPreview
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OperatorID,
		&i.TargetType,
		&i.FileName,
		&i.Rows,
		&i.PreviewResult,
		&i.Status,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const getPlatformAdminByID = `-- name: GetPlatformAdminByID :one
SELECT id, username, password_hash, name, status, created_at, updated_at FROM platform_admin WHERE id = $1
`

func (q *Queries) GetPlatformAdminByID(ctx context.Context, id int64) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByID, id)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformAdminByUsername = `-- name: GetPlatformAdminByUsername :one


SELECT id, username, password_hash, name, status, created_at, updated_at FROM platform_admin WHERE username = $1
`

// M1 identity sqlc 查询源。
// 约定:租户表查询不显式写 tenant_id 条件(RLS 透明过滤),仅写业务条件;插入带 tenant_id(WITH CHECK)。
// 雪花 ID 由应用传入。全局表(platform_admin/tenant/tenant_application)无 RLS。
// 受控特权路径(预认证定位、平台级 tenant_id=NULL 审计/验证码):由 service 在【特权连接】上执行
//
//	(属主绕 RLS,见 docs/01 §8);sqlc 正常类型化,无手写 SQL。
//
// ============================================================
// platform_admin
// ============================================================
func (q *Queries) GetPlatformAdminByUsername(ctx context.Context, username string) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByUsername, username)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSsoConfig = `-- name: GetSsoConfig :one

SELECT id, tenant_id, type, config, match_field, enabled, created_at, updated_at FROM sso_config WHERE tenant_id = $1 AND enabled = true LIMIT 1
`

// ============================================================
// sso_config
// ============================================================
func (q *Queries) GetSsoConfig(ctx context.Context, tenantID int64) (SsoConfig, error) {
	row := q.db.QueryRow(ctx, getSsoConfig, tenantID)
	var i SsoConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Config,
		&i.MatchField,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantApplicationByID = `-- name: GetTenantApplicationByID :one
SELECT id, school_name, school_type, contact_name, contact_phone, contact_email, status, reject_reason, reviewed_by, tenant_id, created_at, updated_at FROM tenant_application WHERE id = $1
`

func (q *Queries) GetTenantApplicationByID(ctx context.Context, id int64) (TenantApplication, error) {
	row := q.db.QueryRow(ctx, getTenantApplicationByID, id)
	var i TenantApplication
	err := row.Scan(
		&i.ID,
		&i.SchoolName,
		&i.SchoolType,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Status,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByCode = `-- name: GetTenantByCode :one
SELECT id, code, name, type, status, deploy_mode, expire_at, logo_url, display_name, feature_flags, auth_mode, enable_activation_code, created_at, updated_at FROM tenant WHERE code = $1
`

func (q *Queries) GetTenantByCode(ctx context.Context, code string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByCode, code)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.DeployMode,
		&i.ExpireAt,
		&i.LogoUrl,
		&i.DisplayName,
		&i.FeatureFlags,
		&i.AuthMode,
		&i.EnableActivationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one

SELECT id, code, name, type, status, deploy_mode, expire_at, logo_url, display_name, feature_flags, auth_mode, enable_activation_code, created_at, updated_at FROM tenant WHERE id = $1
`

// ============================================================
// tenant
// ============================================================
func (q *Queries) GetTenantByID(ctx context.Context, id int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.DeployMode,
		&i.ExpireAt,
		&i.LogoUrl,
		&i.DisplayName,
		&i.FeatureFlags,
		&i.AuthMode,
		&i.EnableActivationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasAccountRole = `-- name: HasAccountRole :one
SELECT EXISTS(SELECT 1 FROM account_role WHERE account_id = $1 AND role = $2)
`

type HasAccountRoleParams struct {
	AccountID int64 `json:"account_id"`
	Role      int16 `json:"role"`
}

func (q *Queries) HasAccountRole(ctx context.Context, arg HasAccountRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAccountRole, arg.AccountID, arg.Role)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrAccountPwdFailed = `-- name: IncrAccountPwdFailed :one
UPDATE account
SET pwd_failed_count = pwd_failed_count + 1,
    locked_until = CASE WHEN pwd_failed_count + 1 >= $2
                        THEN now() + ($3 || ' minutes')::interval
                        ELSE locked_until END
WHERE id = $1
RETURNING id, tenant_id, phone_enc, phone_hash, password_hash, name, base_identity, status, must_change_pwd, pwd_failed_count, locked_until, activated_at, created_at, updated_at
`

type IncrAccountPwdFailedParams struct {
	ID             int64       `json:"id"`
	PwdFailedCount int16       `json:"pwd_failed_count"`
	Column3        pgtype.Text `json:"column_3"`
}

// 密码失败计数 +1,达阈值($2)则锁定 $3 分钟;返回更新后账号。
func (q *Queries) IncrAccountPwdFailed(ctx context.Context, arg IncrAccountPwdFailedParams) (Account, error) {
	row := q.db.QueryRow(ctx, incrAccountPwdFailed, arg.ID, arg.PwdFailedCount, arg.Column3)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneEnc,
		&i.PhoneHash,
		&i.PasswordHash,
		&i.Name,
		&i.BaseIdentity,
		&i.Status,
		&i.MustChangePwd,
		&i.PwdFailedCount,
		&i.LockedUntil,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountRoles = `-- name: ListAccountRoles :many
SELECT role FROM account_role WHERE account_id = $1 ORDER BY role
`

func (q *Queries) ListAccountRoles(ctx context.Context, accountID int64) ([]int16, error) {
	rows, err := q.db.Query(ctx, listAccountRoles, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int16{}
	for rows.Next() {
		var role int16
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.tenant_id, a.phone_enc, a.phone_hash, a.password_hash, a.name, a.base_identity, a.status, a.must_change_pwd, a.pwd_failed_count, a.locked_until, a.activated_at, a.created_at, a.updated_at FROM account a
LEFT JOIN account_profile p ON p.account_id = a.id
WHERE ($3::SMALLINT IS NULL OR a.status = $3)
  AND ($4::SMALLINT IS NULL OR EXISTS (
    SELECT 1 FROM account_role ar WHERE ar.account_id = a.id AND ar.role = $4
  ))
  AND ($5::BIGINT IS NULL OR (
    a.base_identity = 1 AND p.org_id = $5
  ))
  AND ($6::TEXT IS NULL OR a.name ILIKE '%' || $6 || '%')
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAccountsParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Status  pgtype.Int2 `json:"status"`
	Role    pgtype.Int2 `json:"role"`
	ClassID pgtype.Int8 `json:"class_id"`
	Keyword pgtype.Text `json:"keyword"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Role,
		arg.ClassID,
		arg.Keyword,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PhoneEnc,
			&i.PhoneHash,
			&i.PasswordHash,
			&i.Name,
			&i.BaseIdentity,
			&i.Status,
			&i.MustChangePwd,
			&i.PwdFailedCount,
			&i.LockedUntil,
			&i.ActivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, tenant_id, account_id, refresh_token_hash, device_info, ip, status, expire_at, created_at FROM auth_session WHERE account_id = $1 AND status = 1 ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessions(ctx context.Context, accountID int64) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.RefreshTokenHash,
			&i.DeviceInfo,
			&i.Ip,
			&i.Status,
			&i.ExpireAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, tenant_id, actor_id, actor_role, action, target_type, target_id, detail, ip, trace_id, created_at FROM audit_log
WHERE ($3::BIGINT IS NULL OR actor_id = $3)
  AND ($4::TEXT IS NULL OR action = $4)
  AND ($5::TEXT IS NULL OR target_type = $5)
  AND ($6::TIMESTAMPTZ IS NULL OR created_at >= $6)
  AND ($7::TIMESTAMPTZ IS NULL OR created_at <= $7)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
	ActorID    pgtype.Int8        `json:"actor_id"`
	Action     pgtype.Text        `json:"action"`
	TargetType pgtype.Text        `json:"target_type"`
	FromTime   pgtype.Timestamptz `json:"from_time"`
	ToTime     pgtype.Timestamptz `json:"to_time"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.Ip,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesByMajor = `-- name: ListClassesByMajor :many
SELECT id, tenant_id, major_id, name, enrollment_year, status, created_at, updated_at, deleted_at FROM class WHERE major_id = $1 AND deleted_at IS NULL ORDER BY enrollment_year DESC, name
`

func (q *Queries) ListClassesByMajor(ctx context.Context, majorID int64) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClassesByMajor, majorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MajorID,
			&i.Name,
			&i.EnrollmentYear,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, tenant_id, name, code, created_at, updated_at, deleted_at FROM department WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportBatches = `-- name: ListImportBatches :many
SELECT id, tenant_id, operator_id, target_type, file_name, total, success, failed, error_detail, status, created_at FROM import_batch ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListImportBatchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListImportBatches(ctx context.Context, arg ListImportBatchesParams) ([]ImportBatch, error) {
	rows, err := q.db.Query(ctx, listImportBatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportBatch{}
	for rows.Next() {
		var i ImportBatch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OperatorID,
			&i.TargetType,
			&i.FileName,
			&i.Total,
			&i.Success,
			&i.Failed,
			&i.ErrorDetail,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMajorsByDepartment = `-- name: ListMajorsByDepartment :many
SELECT id, tenant_id, department_id, name, created_at, updated_at, deleted_at FROM major WHERE department_id = $1 AND deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListMajorsByDepartment(ctx context.Context, departmentID int64) ([]Major, error) {
	rows, err := q.db.Query(ctx, listMajorsByDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Major{}
	for rows.Next() {
		var i Major
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DepartmentID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformAuditLogs = `-- name: ListPlatformAuditLogs :many
SELECT id, tenant_id, actor_id, actor_role, action, target_type, target_id, detail, ip, trace_id, created_at FROM audit_log
WHERE ($3::BIGINT IS NULL OR actor_id = $3)
  AND ($4::TEXT IS NULL OR action = $4)
  AND ($5::TEXT IS NULL OR target_type = $5)
  AND ($6::TIMESTAMPTZ IS NULL OR created_at >= $6)
  AND ($7::TIMESTAMPTZ IS NULL OR created_at <= $7)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPlatformAuditLogsParams struct {
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
	ActorID    pgtype.Int8        `json:"actor_id"`
	Action     pgtype.Text        `json:"action"`
	TargetType pgtype.Text        `json:"target_type"`
	FromTime   pgtype.Timestamptz `json:"from_time"`
	ToTime     pgtype.Timestamptz `json:"to_time"`
}

// 平台管理员查平台级与全校审计;必须走特权连接,由 M1 contract 收敛权限入口。
func (q *Queries) ListPlatformAuditLogs(ctx context.Context, arg ListPlatformAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listPlatformAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.Ip,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantApplications = `-- name: ListTenantApplications :many
SELECT id, school_name, school_type, contact_name, contact_phone, contact_email, status, reject_reason, reviewed_by, tenant_id, created_at, updated_at FROM tenant_application
WHERE ($3::SMALLINT IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantApplicationsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Int2 `json:"status"`
}

func (q *Queries) ListTenantApplications(ctx context.Context, arg ListTenantApplicationsParams) ([]TenantApplication, error) {
	rows, err := q.db.Query(ctx, listTenantApplications, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantApplication{}
	for rows.Next() {
		var i TenantApplication
		if err := rows.Scan(
			&i.ID,
			&i.SchoolName,
			&i.SchoolType,
			&i.ContactName,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.Status,
			&i.RejectReason,
			&i.ReviewedBy,
			&i.TenantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, code, name, type, status, deploy_mode, expire_at, logo_url, display_name, feature_flags, auth_mode, enable_activation_code, created_at, updated_at FROM tenant
WHERE ($3::SMALLINT IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Int2 `json:"status"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.DeployMode,
			&i.ExpireAt,
			&i.LogoUrl,
			&i.DisplayName,
			&i.FeatureFlags,
			&i.AuthMode,
			&i.EnableActivationCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActivationCodeUsed = `-- name: MarkActivationCodeUsed :exec
UPDATE activation_code SET status = 2, used_at = now() WHERE id = $1 AND status = 1
`

func (q *Queries) MarkActivationCodeUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markActivationCodeUsed, id)
	return err
}

const markImportPreviewSubmitted = `-- name: MarkImportPreviewSubmitted :exec
UPDATE import_preview SET status = 2, submitted_at = now()
WHERE id = $1 AND operator_id = $2 AND status = 1
`

type MarkImportPreviewSubmittedParams struct {
	ID         int64 `json:"id"`
	OperatorID int64 `json:"operator_id"`
}

func (q *Queries) MarkImportPreviewSubmitted(ctx context.Context, arg MarkImportPreviewSubmittedParams) error {
	_, err := q.db.Exec(ctx, markImportPreviewSubmitted, arg.ID, arg.OperatorID)
	return err
}

const markSmsCodeUsed = `-- name: MarkSmsCodeUsed :exec
UPDATE sms_code SET used = true WHERE id = $1
`

func (q *Queries) MarkSmsCodeUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSmsCodeUsed, id)
	return err
}

const rejectTenantApplication = `-- name: RejectTenantApplication :one
UPDATE tenant_application SET status = 3, reviewed_by = $2, reject_reason = $3
WHERE id = $1 AND status = 1
RETURNING id, school_name, school_type, contact_name, contact_phone, contact_email, status, reject_reason, reviewed_by, tenant_id, created_at, updated_at
`

type RejectTenantApplicationParams struct {
	ID           int64       `json:"id"`
	ReviewedBy   pgtype.Int8 `json:"reviewed_by"`
	RejectReason pgtype.Text `json:"reject_reason"`
}

func (q *Queries) RejectTenantApplication(ctx context.Context, arg RejectTenantApplicationParams) (TenantApplication, error) {
	row := q.db.QueryRow(ctx, rejectTenantApplication, arg.ID, arg.ReviewedBy, arg.RejectReason)
	var i TenantApplication
	err := row.Scan(
		&i.ID,
		&i.SchoolName,
		&i.SchoolType,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Status,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeAccountRole = `-- name: RemoveAccountRole :exec
DELETE FROM account_role WHERE account_id = $1 AND role = $2
`

type RemoveAccountRoleParams struct {
	AccountID int64 `json:"account_id"`
	Role      int16 `json:"role"`
}

func (q *Queries) RemoveAccountRole(ctx context.Context, arg RemoveAccountRoleParams) error {
	_, err := q.db.Exec(ctx, removeAccountRole, arg.AccountID, arg.Role)
	return err
}

const resetAccountPwdFailed = `-- name: ResetAccountPwdFailed :exec
UPDATE account SET pwd_failed_count = 0, locked_until = NULL WHERE id = $1
`

func (q *Queries) ResetAccountPwdFailed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetAccountPwdFailed, id)
	return err
}

const revokeAllAccountSessions = `-- name: RevokeAllAccountSessions :exec
UPDATE auth_session SET status = 2 WHERE account_id = $1 AND status = 1
`

// 单端登录踢人 / Refresh 重放检测:吊销该账号全部有效会话。
func (q *Queries) RevokeAllAccountSessions(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, revokeAllAccountSessions, accountID)
	return err
}

const revokeAllPlatformAdminSessions = `-- name: RevokeAllPlatformAdminSessions :exec
UPDATE platform_auth_session SET status = 2 WHERE platform_admin_id = $1 AND status = 1
`

func (q *Queries) RevokeAllPlatformAdminSessions(ctx context.Context, platformAdminID int64) error {
	_, err := q.db.Exec(ctx, revokeAllPlatformAdminSessions, platformAdminID)
	return err
}

const revokeAuthSession = `-- name: RevokeAuthSession :exec
UPDATE auth_session SET status = 2 WHERE id = $1
`

func (q *Queries) RevokeAuthSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeAuthSession, id)
	return err
}

const revokePlatformAuthSession = `-- name: RevokePlatformAuthSession :exec
UPDATE platform_auth_session SET status = 2 WHERE id = $1
`

func (q *Queries) RevokePlatformAuthSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokePlatformAuthSession, id)
	return err
}

const setAccountActivated = `-- name: SetAccountActivated :exec
UPDATE account SET status = 2, must_change_pwd = false, activated_at = now() WHERE id = $1
`

func (q *Queries) SetAccountActivated(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setAccountActivated, id)
	return err
}

const softDeleteClass = `-- name: SoftDeleteClass :exec
UPDATE class SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteClass(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteClass, id)
	return err
}

const softDeleteDepartment = `-- name: SoftDeleteDepartment :exec
UPDATE department SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDepartment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteDepartment, id)
	return err
}

const softDeleteMajor = `-- name: SoftDeleteMajor :exec
UPDATE major SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMajor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteMajor, id)
	return err
}

const updateAccountName = `-- name: UpdateAccountName :one
UPDATE account SET name = $2 WHERE id = $1 RETURNING id, tenant_id, phone_enc, phone_hash, password_hash, name, base_identity, status, must_change_pwd, pwd_failed_count, locked_until, activated_at, created_at, updated_at
`

type UpdateAccountNameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateAccountName(ctx context.Context, arg UpdateAccountNameParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountName, arg.ID, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneEnc,
		&i.PhoneHash,
		&i.PasswordHash,
		&i.Name,
		&i.BaseIdentity,
		&i.Status,
		&i.MustChangePwd,
		&i.PwdFailedCount,
		&i.LockedUntil,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :exec
UPDATE account SET password_hash = $2, must_change_pwd = $3 WHERE id = $1
`

type UpdateAccountPasswordParams struct {
	ID            int64       `json:"id"`
	PasswordHash  pgtype.Text `json:"password_hash"`
	MustChangePwd bool        `json:"must_change_pwd"`
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAccountPassword, arg.ID, arg.PasswordHash, arg.MustChangePwd)
	return err
}

const updateAccountPhone = `-- name: UpdateAccountPhone :exec
UPDATE account SET phone_enc = $2, phone_hash = $3 WHERE id = $1
`

type UpdateAccountPhoneParams struct {
	ID        int64  `json:"id"`
	PhoneEnc  []byte `json:"phone_enc"`
	PhoneHash string `json:"phone_hash"`
}

func (q *Queries) UpdateAccountPhone(ctx context.Context, arg UpdateAccountPhoneParams) error {
	_, err := q.db.Exec(ctx, updateAccountPhone, arg.ID, arg.PhoneEnc, arg.PhoneHash)
	return err
}

const updateAccountProfileOrg = `-- name: UpdateAccountProfileOrg :exec
UPDATE account_profile SET org_id = $2, title = $3 WHERE account_id = $1
`

type UpdateAccountProfileOrgParams struct {
	AccountID int64       `json:"account_id"`
	OrgID     int64       `json:"org_id"`
	Title     pgtype.Text `json:"title"`
}

func (q *Queries) UpdateAccountProfileOrg(ctx context.Context, arg UpdateAccountProfileOrgParams) error {
	_, err := q.db.Exec(ctx, updateAccountProfileOrg, arg.AccountID, arg.OrgID, arg.Title)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE account SET status = $2 WHERE id = $1 RETURNING id, tenant_id, phone_enc, phone_hash, password_hash, name, base_identity, status, must_change_pwd, pwd_failed_count, locked_until, activated_at, created_at, updated_at
`

type UpdateAccountStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneEnc,
		&i.PhoneHash,
		&i.PasswordHash,
		&i.Name,
		&i.BaseIdentity,
		&i.Status,
		&i.MustChangePwd,
		&i.PwdFailedCount,
		&i.LockedUntil,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClass = `-- name: UpdateClass :one
UPDATE class SET name = $2, enrollment_year = $3 WHERE id = $1 AND deleted_at IS NULL RETURNING id, tenant_id, major_id, name, enrollment_year, status, created_at, updated_at, deleted_at
`

type UpdateClassParams struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	EnrollmentYear int16  `json:"enrollment_year"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, updateClass, arg.ID, arg.Name, arg.EnrollmentYear)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MajorID,
		&i.Name,
		&i.EnrollmentYear,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE department SET name = $2, code = $3 WHERE id = $1 AND deleted_at IS NULL RETURNING id, tenant_id, name, code, created_at, updated_at, deleted_at
`

type UpdateDepartmentParams struct {
	ID   int64       `json:"id"`
	Name string      `json:"name"`
	Code pgtype.Text `json:"code"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment, arg.ID, arg.Name, arg.Code)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMajor = `-- name: UpdateMajor :one
UPDATE major SET name = $2 WHERE id = $1 AND deleted_at IS NULL RETURNING id, tenant_id, department_id, name, created_at, updated_at, deleted_at
`

type UpdateMajorParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateMajor(ctx context.Context, arg UpdateMajorParams) (Major, error) {
	row := q.db.QueryRow(ctx, updateMajor, arg.ID, arg.Name)
	var i Major
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DepartmentID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTenantConfig = `-- name: UpdateTenantConfig :one
UPDATE tenant
SET logo_url = $2, display_name = $3, feature_flags = $4, auth_mode = $5, enable_activation_code = $6
WHERE id = $1
RETURNING id, code, name, type, status, deploy_mode, expire_at, logo_url, display_name, feature_flags, auth_mode, enable_activation_code, created_at, updated_at
`

type UpdateTenantConfigParams struct {
	ID                   int64       `json:"id"`
	LogoUrl              pgtype.Text `json:"logo_url"`
	DisplayName          pgtype.Text `json:"display_name"`
	FeatureFlags         []byte      `json:"feature_flags"`
	AuthMode             int16       `json:"auth_mode"`
	EnableActivationCode bool        `json:"enable_activation_code"`
}

func (q *Queries) UpdateTenantConfig(ctx context.Context, arg UpdateTenantConfigParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantConfig,
		arg.ID,
		arg.LogoUrl,
		arg.DisplayName,
		arg.FeatureFlags,
		arg.AuthMode,
		arg.EnableActivationCode,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.DeployMode,
		&i.ExpireAt,
		&i.LogoUrl,
		&i.DisplayName,
		&i.FeatureFlags,
		&i.AuthMode,
		&i.EnableActivationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :one
UPDATE tenant SET status = $2, expire_at = $3 WHERE id = $1
RETURNING id, code, name, type, status, deploy_mode, expire_at, logo_url, display_name, feature_flags, auth_mode, enable_activation_code, created_at, updated_at
`

type UpdateTenantStatusParams struct {
	ID       int64              `json:"id"`
	Status   int16              `json:"status"`
	ExpireAt pgtype.Timestamptz `json:"expire_at"`
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantStatus, arg.ID, arg.Status, arg.ExpireAt)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.DeployMode,
		&i.ExpireAt,
		&i.LogoUrl,
		&i.DisplayName,
		&i.FeatureFlags,
		&i.AuthMode,
		&i.EnableActivationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSsoConfig = `-- name: UpsertSsoConfig :one
INSERT INTO sso_config (id, tenant_id, type, config, match_field, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id) DO UPDATE
SET type = EXCLUDED.type,
    config = EXCLUDED.config,
    match_field = EXCLUDED.match_field,
    enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING id, tenant_id, type, config, match_field, enabled, created_at, updated_at
`

type UpsertSsoConfigParams struct {
	ID         int64  `json:"id"`
	TenantID   int64  `json:"tenant_id"`
	Type       int16  `json:"type"`
	Config     []byte `json:"config"`
	MatchField int16  `json:"match_field"`
	Enabled    bool   `json:"enabled"`
}

func (q *Queries) UpsertSsoConfig(ctx context.Context, arg UpsertSsoConfigParams) (SsoConfig, error) {
	row := q.db.QueryRow(ctx, upsertSsoConfig,
		arg.ID,
		arg.TenantID,
		arg.Type,
		arg.Config,
		arg.MatchField,
		arg.Enabled,
	)
	var i SsoConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Config,
		&i.MatchField,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
