// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	PhoneEnc       []byte             `json:"phone_enc"`
	PhoneHash      string             `json:"phone_hash"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	Name           string             `json:"name"`
	BaseIdentity   int16              `json:"base_identity"`
	Status         int16              `json:"status"`
	MustChangePwd  bool               `json:"must_change_pwd"`
	PwdFailedCount int16              `json:"pwd_failed_count"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	ActivatedAt    pgtype.Timestamptz `json:"activated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ActivationCode struct {
	ID        int64              `json:"id"`
	TenantID  int64              `json:"tenant_id"`
	AccountID int64              `json:"account_id"`
	CodeHash  string             `json:"code_hash"`
	Status    int16              `json:"status"`
	ExpireAt  pgtype.Timestamptz `json:"expire_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedBy pgtype.Int8        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID         int64              `json:"id"`
	TenantID   pgtype.Int8        `json:"tenant_id"`
	ActorID    int64              `json:"actor_id"`
	ActorRole  int16              `json:"actor_role"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   pgtype.Int8        `json:"target_id"`
	Detail     []byte             `json:"detail"`
	Ip         pgtype.Text        `json:"ip"`
	TraceID    pgtype.Text        `json:"trace_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthSession struct {
	ID               int64              `json:"id"`
	TenantID         int64              `json:"tenant_id"`
	AccountID        int64              `json:"account_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceInfo       pgtype.Text        `json:"device_info"`
	Ip               pgtype.Text        `json:"ip"`
	Status           int16              `json:"status"`
	ExpireAt         pgtype.Timestamptz `json:"expire_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Class struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	MajorID        int64              `json:"major_id"`
	Name           string             `json:"name"`
	EnrollmentYear int16              `json:"enrollment_year"`
	Status         int16              `json:"status"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Department struct {
	ID        int64              `json:"id"`
	TenantID  int64              `json:"tenant_id"`
	Name      string             `json:"name"`
	Code      pgtype.Text        `json:"code"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ImportBatch struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	OperatorID  int64              `json:"operator_id"`
	TargetType  int16              `json:"target_type"`
	FileName    string             `json:"file_name"`
	Total       int32              `json:"total"`
	Success     int32              `json:"success"`
	Failed      int32              `json:"failed"`
	ErrorDetail []byte             `json:"error_detail"`
	Status      int16              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ImportPreview struct {
	ID            int64              `json:"id"`
	TenantID      int64              `json:"tenant_id"`
	OperatorID    int64              `json:"operator_id"`
	TargetType    int16              `json:"target_type"`
	FileName      string             `json:"file_name"`
	Rows          []byte             `json:"rows"`
	PreviewResult []byte             `json:"preview_result"`
	Status        int16              `json:"status"`
	ExpireAt      pgtype.Timestamptz `json:"expire_at"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Major struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	DepartmentID int64              `json:"department_id"`
	Name         string             `json:"name"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type PlatformAdmin struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Status       int16              `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PlatformAuthSession struct {
	ID               int64              `json:"id"`
	PlatformAdminID  int64              `json:"platform_admin_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceInfo       pgtype.Text        `json:"device_info"`
	Ip               pgtype.Text        `json:"ip"`
	Status           int16              `json:"status"`
	ExpireAt         pgtype.Timestamptz `json:"expire_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type SmsCode struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	PhoneHash      string             `json:"phone_hash"`
	CodeHash       string             `json:"code_hash"`
	Scene          int16              `json:"scene"`
	ExpireAt       pgtype.Timestamptz `json:"expire_at"`
	VerifyAttempts int16              `json:"verify_attempts"`
	Used           bool               `json:"used"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SsoConfig struct {
	ID         int64              `json:"id"`
	TenantID   int64              `json:"tenant_id"`
	Type       int16              `json:"type"`
	Config     []byte             `json:"config"`
	MatchField int16              `json:"match_field"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID                   int64              `json:"id"`
	Code                 string             `json:"code"`
	Name                 string             `json:"name"`
	Type                 int16              `json:"type"`
	Status               int16              `json:"status"`
	DeployMode           int16              `json:"deploy_mode"`
	ExpireAt             pgtype.Timestamptz `json:"expire_at"`
	LogoUrl              pgtype.Text        `json:"logo_url"`
	DisplayName          pgtype.Text        `json:"display_name"`
	FeatureFlags         []byte             `json:"feature_flags"`
	AuthMode             int16              `json:"auth_mode"`
	EnableActivationCode bool               `json:"enable_activation_code"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type TenantApplication struct {
	ID           int64              `json:"id"`
	SchoolName   string             `json:"school_name"`
	SchoolType   int16              `json:"school_type"`
	ContactName  string             `json:"contact_name"`
	ContactPhone string             `json:"contact_phone"`
	ContactEmail string             `json:"contact_email"`
	Status       int16              `json:"status"`
	RejectReason pgtype.Text        `json:"reject_reason"`
	ReviewedBy   pgtype.Int8        `json:"reviewed_by"`
	TenantID     pgtype.Int8        `json:"tenant_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
