-- 回滚迁移 0002:删除 M1 全部表(级联清理 RLS 策略/索引/触发器)。
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS import_batch CASCADE;
DROP TABLE IF EXISTS import_preview CASCADE;
DROP TABLE IF EXISTS sso_config CASCADE;
DROP TABLE IF EXISTS activation_code CASCADE;
DROP TABLE IF EXISTS sms_code CASCADE;
DROP TABLE IF EXISTS auth_session CASCADE;
DROP TABLE IF EXISTS account_profile CASCADE;
DROP TABLE IF EXISTS account_role CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS class CASCADE;
DROP TABLE IF EXISTS major CASCADE;
DROP TABLE IF EXISTS department CASCADE;
DROP TABLE IF EXISTS tenant_application CASCADE;
DROP TABLE IF EXISTS tenant CASCADE;
DROP TABLE IF EXISTS platform_auth_session CASCADE;
DROP TABLE IF EXISTS platform_admin CASCADE;
