DROP POLICY IF EXISTS teaching_grade_event_outbox_tenant_rls ON teaching_grade_event_outbox;
DROP POLICY IF EXISTS course_grade_tenant_rls ON course_grade;
DROP POLICY IF EXISTS grade_weight_tenant_rls ON grade_weight;
DROP POLICY IF EXISTS course_review_tenant_rls ON course_review;
DROP POLICY IF EXISTS announcement_tenant_rls ON announcement;
DROP POLICY IF EXISTS discussion_post_tenant_rls ON discussion_post;
DROP POLICY IF EXISTS lesson_progress_tenant_rls ON lesson_progress;
DROP POLICY IF EXISTS submission_draft_tenant_rls ON submission_draft;
DROP POLICY IF EXISTS submission_judge_outbox_tenant_rls ON submission_judge_outbox;
DROP POLICY IF EXISTS submission_tenant_rls ON submission;
DROP POLICY IF EXISTS assignment_item_tenant_rls ON assignment_item;
DROP POLICY IF EXISTS assignment_tenant_rls ON assignment;
DROP POLICY IF EXISTS course_member_tenant_rls ON course_member;
DROP POLICY IF EXISTS lesson_tenant_rls ON lesson;
DROP POLICY IF EXISTS chapter_tenant_rls ON chapter;
DROP POLICY IF EXISTS course_delete_tenant_rls ON course;
DROP POLICY IF EXISTS course_update_tenant_rls ON course;
DROP POLICY IF EXISTS course_insert_tenant_rls ON course;
DROP POLICY IF EXISTS course_select_tenant_or_shared_rls ON course;

DROP TABLE IF EXISTS teaching_grade_event_outbox;
DROP TABLE IF EXISTS course_grade;
DROP TABLE IF EXISTS grade_weight;
DROP TABLE IF EXISTS course_review;
DROP TABLE IF EXISTS announcement;
DROP TABLE IF EXISTS discussion_post;
DROP TABLE IF EXISTS lesson_progress;
DROP TABLE IF EXISTS submission_draft;
DROP TABLE IF EXISTS submission_judge_outbox;
DROP TABLE IF EXISTS submission;
DROP TABLE IF EXISTS assignment_item;
DROP TABLE IF EXISTS assignment;
DROP TABLE IF EXISTS course_member;
DROP TABLE IF EXISTS lesson;
DROP TABLE IF EXISTS chapter;
DROP TABLE IF EXISTS course;
