// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateAlertEvent(ctx context.Context, arg CreateAlertEventParams) (AlertEvent, error)
	CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error)
	CreateBackupRecord(ctx context.Context, arg CreateBackupRecordParams) (BackupRecord, error)
	CreateConfigChangeLog(ctx context.Context, arg CreateConfigChangeLogParams) (ConfigChangeLog, error)
	CreateSystemConfig(ctx context.Context, arg CreateSystemConfigParams) (SystemConfig, error)
	GetAlertRule(ctx context.Context, id int64) (AlertRule, error)
	GetConfigChangeLog(ctx context.Context, arg GetConfigChangeLogParams) (ConfigChangeLog, error)
	GetSystemConfig(ctx context.Context, arg GetSystemConfigParams) (SystemConfig, error)
	HandleAlertEvent(ctx context.Context, arg HandleAlertEventParams) (AlertEvent, error)
	ListAlertEvents(ctx context.Context, arg ListAlertEventsParams) ([]AlertEvent, error)
	ListAlertRules(ctx context.Context, arg ListAlertRulesParams) ([]AlertRule, error)
	ListBackupRecords(ctx context.Context, arg ListBackupRecordsParams) ([]BackupRecord, error)
	ListConfigChangeLogs(ctx context.Context, arg ListConfigChangeLogsParams) ([]ConfigChangeLog, error)
	ListPlatformStatistics(ctx context.Context, arg ListPlatformStatisticsParams) ([]PlatformStatistic, error)
	ListSystemConfigs(ctx context.Context, arg ListSystemConfigsParams) ([]SystemConfig, error)
	UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error)
	UpdateSystemConfig(ctx context.Context, arg UpdateSystemConfigParams) (SystemConfig, error)
	UpsertGlobalPlatformStatistics(ctx context.Context, arg UpsertGlobalPlatformStatisticsParams) (PlatformStatistic, error)
	UpsertTenantPlatformStatistics(ctx context.Context, arg UpsertTenantPlatformStatisticsParams) (PlatformStatistic, error)
}

var _ Querier = (*Queries)(nil)
