// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teaching.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCourseMember = `-- name: AddCourseMember :one
INSERT INTO course_member (id, tenant_id, course_id, student_id, join_mode)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, course_id, student_id) DO UPDATE SET join_mode = EXCLUDED.join_mode
RETURNING id, tenant_id, course_id, student_id, joined_at, join_mode
`

type AddCourseMemberParams struct {
	ID        int64 `json:"id"`
	TenantID  int64 `json:"tenant_id"`
	CourseID  int64 `json:"course_id"`
	StudentID int64 `json:"student_id"`
	JoinMode  int16 `json:"join_mode"`
}

func (q *Queries) AddCourseMember(ctx context.Context, arg AddCourseMemberParams) (CourseMember, error) {
	row := q.db.QueryRow(ctx, addCourseMember,
		arg.ID,
		arg.TenantID,
		arg.CourseID,
		arg.StudentID,
		arg.JoinMode,
	)
	var i CourseMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.StudentID,
		&i.JoinedAt,
		&i.JoinMode,
	)
	return i, err
}

const completeSubmissionJudgeOutbox = `-- name: CompleteSubmissionJudgeOutbox :one
UPDATE submission_judge_outbox
SET status = $1, last_error = NULL
WHERE id = $2
RETURNING id, tenant_id, submission_id, assignment_id, student_id, item_code, item_version, judger_code, code_storage_key, code_hash, extra_input, source_ref, status, retry_count, last_error, created_at, updated_at
`

type CompleteSubmissionJudgeOutboxParams struct {
	DoneStatus int16 `json:"done_status"`
	ID         int64 `json:"id"`
}

func (q *Queries) CompleteSubmissionJudgeOutbox(ctx context.Context, arg CompleteSubmissionJudgeOutboxParams) (SubmissionJudgeOutbox, error) {
	row := q.db.QueryRow(ctx, completeSubmissionJudgeOutbox, arg.DoneStatus, arg.ID)
	var i SubmissionJudgeOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubmissionID,
		&i.AssignmentID,
		&i.StudentID,
		&i.ItemCode,
		&i.ItemVersion,
		&i.JudgerCode,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.ExtraInput,
		&i.SourceRef,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveCourses = `-- name: CountActiveCourses :one
SELECT count(*)::bigint FROM course WHERE deleted_at IS NULL AND status IN (2, 3)
`

func (q *Queries) CountActiveCourses(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCourses)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countCourses = `-- name: CountCourses :one
SELECT count(*)::bigint FROM course WHERE deleted_at IS NULL
`

func (q *Queries) CountCourses(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSubmissionsByStudent = `-- name: CountSubmissionsByStudent :one
SELECT count(*)::bigint FROM submission WHERE assignment_id = $1 AND student_id = $2
`

type CountSubmissionsByStudentParams struct {
	AssignmentID int64 `json:"assignment_id"`
	StudentID    int64 `json:"student_id"`
}

func (q *Queries) CountSubmissionsByStudent(ctx context.Context, arg CountSubmissionsByStudentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissionsByStudent, arg.AssignmentID, arg.StudentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcement (id, tenant_id, course_id, title, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, course_id, title, content, is_pinned, deleted_at, created_at, updated_at
`

type CreateAnnouncementParams struct {
	ID       int64  `json:"id"`
	TenantID int64  `json:"tenant_id"`
	CourseID int64  `json:"course_id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.ID,
		arg.TenantID,
		arg.CourseID,
		arg.Title,
		arg.Content,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignment (id, tenant_id, course_id, title, chapter_id, due_at, max_attempts, late_policy, late_penalty, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, course_id, title, chapter_id, due_at, max_attempts, late_policy, late_penalty, status, deleted_at, created_at, updated_at
`

type CreateAssignmentParams struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	CourseID    int64              `json:"course_id"`
	Title       string             `json:"title"`
	ChapterID   pgtype.Int8        `json:"chapter_id"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
	MaxAttempts int32              `json:"max_attempts"`
	LatePolicy  int16              `json:"late_policy"`
	LatePenalty []byte             `json:"late_penalty"`
	Status      int16              `json:"status"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.ID,
		arg.TenantID,
		arg.CourseID,
		arg.Title,
		arg.ChapterID,
		arg.DueAt,
		arg.MaxAttempts,
		arg.LatePolicy,
		arg.LatePenalty,
		arg.Status,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.ChapterID,
		&i.DueAt,
		&i.MaxAttempts,
		&i.LatePolicy,
		&i.LatePenalty,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssignmentItem = `-- name: CreateAssignmentItem :one
INSERT INTO assignment_item (id, tenant_id, assignment_id, item_code, item_version, score, seq, grading_mode, judger_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, assignment_id, item_code, item_version, score, seq, grading_mode, judger_code, created_at
`

type CreateAssignmentItemParams struct {
	ID           int64       `json:"id"`
	TenantID     int64       `json:"tenant_id"`
	AssignmentID int64       `json:"assignment_id"`
	ItemCode     string      `json:"item_code"`
	ItemVersion  string      `json:"item_version"`
	Score        int32       `json:"score"`
	Seq          int32       `json:"seq"`
	GradingMode  int16       `json:"grading_mode"`
	JudgerCode   pgtype.Text `json:"judger_code"`
}

func (q *Queries) CreateAssignmentItem(ctx context.Context, arg CreateAssignmentItemParams) (AssignmentItem, error) {
	row := q.db.QueryRow(ctx, createAssignmentItem,
		arg.ID,
		arg.TenantID,
		arg.AssignmentID,
		arg.ItemCode,
		arg.ItemVersion,
		arg.Score,
		arg.Seq,
		arg.GradingMode,
		arg.JudgerCode,
	)
	var i AssignmentItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.ItemCode,
		&i.ItemVersion,
		&i.Score,
		&i.Seq,
		&i.GradingMode,
		&i.JudgerCode,
		&i.CreatedAt,
	)
	return i, err
}

const createChapter = `-- name: CreateChapter :one
INSERT INTO chapter (id, tenant_id, course_id, title, sort)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, course_id, title, sort, deleted_at, created_at, updated_at
`

type CreateChapterParams struct {
	ID       int64  `json:"id"`
	TenantID int64  `json:"tenant_id"`
	CourseID int64  `json:"course_id"`
	Title    string `json:"title"`
	Sort     int32  `json:"sort"`
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, createChapter,
		arg.ID,
		arg.TenantID,
		arg.CourseID,
		arg.Title,
		arg.Sort,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Sort,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one

INSERT INTO course (id, tenant_id, teacher_id, name, description, type, difficulty, cover_url, semester, credits, schedule, invite_code, status, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, tenant_id, teacher_id, name, description, type, difficulty, cover_url, semester, credits, schedule, invite_code, status, visibility, deleted_at, created_at, updated_at
`

type CreateCourseParams struct {
	ID          int64          `json:"id"`
	TenantID    int64          `json:"tenant_id"`
	TeacherID   int64          `json:"teacher_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Type        int16          `json:"type"`
	Difficulty  int16          `json:"difficulty"`
	CoverUrl    pgtype.Text    `json:"cover_url"`
	Semester    string         `json:"semester"`
	Credits     pgtype.Numeric `json:"credits"`
	Schedule    []byte         `json:"schedule"`
	InviteCode  string         `json:"invite_code"`
	Status      int16          `json:"status"`
	Visibility  int16          `json:"visibility"`
}

// M6 teaching sqlc 查询:仅访问 teaching 模块自有租户表。
func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.ID,
		arg.TenantID,
		arg.TeacherID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Difficulty,
		arg.CoverUrl,
		arg.Semester,
		arg.Credits,
		arg.Schedule,
		arg.InviteCode,
		arg.Status,
		arg.Visibility,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.CoverUrl,
		&i.Semester,
		&i.Credits,
		&i.Schedule,
		&i.InviteCode,
		&i.Status,
		&i.Visibility,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDiscussionPost = `-- name: CreateDiscussionPost :one
INSERT INTO discussion_post (id, tenant_id, course_id, parent_id, author_id, content)
SELECT $1, $2, $3, $4, $5, $6
WHERE $4::bigint IS NULL
   OR EXISTS (
     SELECT 1 FROM discussion_post parent
     WHERE parent.id = $4::bigint
       AND parent.course_id = $3
       AND parent.deleted_at IS NULL
   )
RETURNING id, tenant_id, course_id, parent_id, author_id, content, is_pinned, like_count, deleted_at, created_at, updated_at
`

type CreateDiscussionPostParams struct {
	ID       int64       `json:"id"`
	TenantID int64       `json:"tenant_id"`
	CourseID int64       `json:"course_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
	AuthorID int64       `json:"author_id"`
	Content  string      `json:"content"`
}

func (q *Queries) CreateDiscussionPost(ctx context.Context, arg CreateDiscussionPostParams) (DiscussionPost, error) {
	row := q.db.QueryRow(ctx, createDiscussionPost,
		arg.ID,
		arg.TenantID,
		arg.CourseID,
		arg.ParentID,
		arg.AuthorID,
		arg.Content,
	)
	var i DiscussionPost
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.ParentID,
		&i.AuthorID,
		&i.Content,
		&i.IsPinned,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGradeWeight = `-- name: CreateGradeWeight :one
INSERT INTO grade_weight (id, tenant_id, course_id, source_type, source_ref, weight)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, course_id, source_type, source_ref, weight
`

type CreateGradeWeightParams struct {
	ID         int64          `json:"id"`
	TenantID   int64          `json:"tenant_id"`
	CourseID   int64          `json:"course_id"`
	SourceType int16          `json:"source_type"`
	SourceRef  string         `json:"source_ref"`
	Weight     pgtype.Numeric `json:"weight"`
}

func (q *Queries) CreateGradeWeight(ctx context.Context, arg CreateGradeWeightParams) (GradeWeight, error) {
	row := q.db.QueryRow(ctx, createGradeWeight,
		arg.ID,
		arg.TenantID,
		arg.CourseID,
		arg.SourceType,
		arg.SourceRef,
		arg.Weight,
	)
	var i GradeWeight
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.SourceType,
		&i.SourceRef,
		&i.Weight,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lesson (id, tenant_id, chapter_id, title, content_type, content_ref, sort)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, chapter_id, title, content_type, content_ref, sort, deleted_at, created_at, updated_at
`

type CreateLessonParams struct {
	ID          int64  `json:"id"`
	TenantID    int64  `json:"tenant_id"`
	ChapterID   int64  `json:"chapter_id"`
	Title       string `json:"title"`
	ContentType int16  `json:"content_type"`
	ContentRef  []byte `json:"content_ref"`
	Sort        int32  `json:"sort"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.ID,
		arg.TenantID,
		arg.ChapterID,
		arg.Title,
		arg.ContentType,
		arg.ContentRef,
		arg.Sort,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChapterID,
		&i.Title,
		&i.ContentType,
		&i.ContentRef,
		&i.Sort,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submission (id, tenant_id, assignment_id, student_id, attempt_no, content_ref, judge_task_ref, auto_score, manual_score, final_score, comment, is_late, status)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
WHERE EXISTS (
  SELECT 1 FROM assignment a
  JOIN course c ON c.id = a.course_id AND c.tenant_id = a.tenant_id
  JOIN course_member m ON m.tenant_id = c.tenant_id AND m.course_id = c.id
  WHERE a.id = $3
    AND a.deleted_at IS NULL
    AND c.deleted_at IS NULL
    AND m.student_id = $4
)
RETURNING id, tenant_id, assignment_id, student_id, attempt_no, content_ref, judge_task_ref, auto_score, manual_score, final_score, comment, is_late, status, submitted_at
`

type CreateSubmissionParams struct {
	ID           int64       `json:"id"`
	TenantID     int64       `json:"tenant_id"`
	AssignmentID int64       `json:"assignment_id"`
	StudentID    int64       `json:"student_id"`
	AttemptNo    int32       `json:"attempt_no"`
	ContentRef   []byte      `json:"content_ref"`
	JudgeTaskRef pgtype.Text `json:"judge_task_ref"`
	AutoScore    pgtype.Int4 `json:"auto_score"`
	ManualScore  pgtype.Int4 `json:"manual_score"`
	FinalScore   pgtype.Int4 `json:"final_score"`
	Comment      pgtype.Text `json:"comment"`
	IsLate       bool        `json:"is_late"`
	Status       int16       `json:"status"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ID,
		arg.TenantID,
		arg.AssignmentID,
		arg.StudentID,
		arg.AttemptNo,
		arg.ContentRef,
		arg.JudgeTaskRef,
		arg.AutoScore,
		arg.ManualScore,
		arg.FinalScore,
		arg.Comment,
		arg.IsLate,
		arg.Status,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.StudentID,
		&i.AttemptNo,
		&i.ContentRef,
		&i.JudgeTaskRef,
		&i.AutoScore,
		&i.ManualScore,
		&i.FinalScore,
		&i.Comment,
		&i.IsLate,
		&i.Status,
		&i.SubmittedAt,
	)
	return i, err
}

const createSubmissionJudgeOutbox = `-- name: CreateSubmissionJudgeOutbox :one
INSERT INTO submission_judge_outbox (
  id, tenant_id, submission_id, assignment_id, student_id, item_code, item_version,
  judger_code, code_storage_key, code_hash, extra_input, source_ref, status
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13
)
RETURNING id, tenant_id, submission_id, assignment_id, student_id, item_code, item_version, judger_code, code_storage_key, code_hash, extra_input, source_ref, status, retry_count, last_error, created_at, updated_at
`

type CreateSubmissionJudgeOutboxParams struct {
	ID             int64  `json:"id"`
	TenantID       int64  `json:"tenant_id"`
	SubmissionID   int64  `json:"submission_id"`
	AssignmentID   int64  `json:"assignment_id"`
	StudentID      int64  `json:"student_id"`
	ItemCode       string `json:"item_code"`
	ItemVersion    string `json:"item_version"`
	JudgerCode     string `json:"judger_code"`
	CodeStorageKey string `json:"code_storage_key"`
	CodeHash       string `json:"code_hash"`
	ExtraInput     []byte `json:"extra_input"`
	SourceRef      string `json:"source_ref"`
	Status         int16  `json:"status"`
}

func (q *Queries) CreateSubmissionJudgeOutbox(ctx context.Context, arg CreateSubmissionJudgeOutboxParams) (SubmissionJudgeOutbox, error) {
	row := q.db.QueryRow(ctx, createSubmissionJudgeOutbox,
		arg.ID,
		arg.TenantID,
		arg.SubmissionID,
		arg.AssignmentID,
		arg.StudentID,
		arg.ItemCode,
		arg.ItemVersion,
		arg.JudgerCode,
		arg.CodeStorageKey,
		arg.CodeHash,
		arg.ExtraInput,
		arg.SourceRef,
		arg.Status,
	)
	var i SubmissionJudgeOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubmissionID,
		&i.AssignmentID,
		&i.StudentID,
		&i.ItemCode,
		&i.ItemVersion,
		&i.JudgerCode,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.ExtraInput,
		&i.SourceRef,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssignmentItems = `-- name: DeleteAssignmentItems :exec
DELETE FROM assignment_item WHERE assignment_id = $1
`

func (q *Queries) DeleteAssignmentItems(ctx context.Context, assignmentID int64) error {
	_, err := q.db.Exec(ctx, deleteAssignmentItems, assignmentID)
	return err
}

const deleteGradeWeightsByCourse = `-- name: DeleteGradeWeightsByCourse :exec
DELETE FROM grade_weight WHERE course_id = $1
`

func (q *Queries) DeleteGradeWeightsByCourse(ctx context.Context, courseID int64) error {
	_, err := q.db.Exec(ctx, deleteGradeWeightsByCourse, courseID)
	return err
}

const deleteSubmissionDraft = `-- name: DeleteSubmissionDraft :exec
DELETE FROM submission_draft
WHERE assignment_id = $1
  AND student_id = $2
`

type DeleteSubmissionDraftParams struct {
	AssignmentID int64 `json:"assignment_id"`
	StudentID    int64 `json:"student_id"`
}

func (q *Queries) DeleteSubmissionDraft(ctx context.Context, arg DeleteSubmissionDraftParams) error {
	_, err := q.db.Exec(ctx, deleteSubmissionDraft, arg.AssignmentID, arg.StudentID)
	return err
}

const ensureCoursePublishable = `-- name: EnsureCoursePublishable :one
SELECT (
  EXISTS (
    SELECT 1 FROM chapter ch
    WHERE ch.course_id = $1
      AND ch.deleted_at IS NULL
  )
  AND NOT EXISTS (
    SELECT 1 FROM chapter ch
    WHERE ch.course_id = $1
      AND ch.deleted_at IS NULL
      AND NOT EXISTS (
        SELECT 1 FROM lesson l
        WHERE l.chapter_id = ch.id
          AND l.deleted_at IS NULL
      )
  )
)::boolean AS publishable
`

func (q *Queries) EnsureCoursePublishable(ctx context.Context, courseID int64) (bool, error) {
	row := q.db.QueryRow(ctx, ensureCoursePublishable, courseID)
	var publishable bool
	err := row.Scan(&publishable)
	return publishable, err
}

const failSubmissionJudgeOutbox = `-- name: FailSubmissionJudgeOutbox :one
UPDATE submission_judge_outbox
SET status = $1, last_error = $2
WHERE id = $3
RETURNING id, tenant_id, submission_id, assignment_id, student_id, item_code, item_version, judger_code, code_storage_key, code_hash, extra_input, source_ref, status, retry_count, last_error, created_at, updated_at
`

type FailSubmissionJudgeOutboxParams struct {
	PendingStatus int16       `json:"pending_status"`
	LastError     pgtype.Text `json:"last_error"`
	ID            int64       `json:"id"`
}

func (q *Queries) FailSubmissionJudgeOutbox(ctx context.Context, arg FailSubmissionJudgeOutboxParams) (SubmissionJudgeOutbox, error) {
	row := q.db.QueryRow(ctx, failSubmissionJudgeOutbox, arg.PendingStatus, arg.LastError, arg.ID)
	var i SubmissionJudgeOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubmissionID,
		&i.AssignmentID,
		&i.StudentID,
		&i.ItemCode,
		&i.ItemVersion,
		&i.JudgerCode,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.ExtraInput,
		&i.SourceRef,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, tenant_id, course_id, title, chapter_id, due_at, max_attempts, late_policy, late_penalty, status, deleted_at, created_at, updated_at FROM assignment WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAssignmentByID(ctx context.Context, id int64) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentByID, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.ChapterID,
		&i.DueAt,
		&i.MaxAttempts,
		&i.LatePolicy,
		&i.LatePenalty,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChapterByID = `-- name: GetChapterByID :one
SELECT id, tenant_id, course_id, title, sort, deleted_at, created_at, updated_at FROM chapter WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetChapterByID(ctx context.Context, id int64) (Chapter, error) {
	row := q.db.QueryRow(ctx, getChapterByID, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Sort,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, tenant_id, teacher_id, name, description, type, difficulty, cover_url, semester, credits, schedule, invite_code, status, visibility, deleted_at, created_at, updated_at FROM course WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCourseByID(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.CoverUrl,
		&i.Semester,
		&i.Credits,
		&i.Schedule,
		&i.InviteCode,
		&i.Status,
		&i.Visibility,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseByInviteCode = `-- name: GetCourseByInviteCode :one
SELECT id, tenant_id, teacher_id, name, description, type, difficulty, cover_url, semester, credits, schedule, invite_code, status, visibility, deleted_at, created_at, updated_at FROM course WHERE invite_code = $1 AND status IN (2, 3) AND deleted_at IS NULL
`

func (q *Queries) GetCourseByInviteCode(ctx context.Context, inviteCode string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByInviteCode, inviteCode)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.CoverUrl,
		&i.Semester,
		&i.Credits,
		&i.Schedule,
		&i.InviteCode,
		&i.Status,
		&i.Visibility,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseGrade = `-- name: GetCourseGrade :one
SELECT id, tenant_id, course_id, student_id, auto_total, override_total, is_overridden, updated_at FROM course_grade WHERE course_id = $1 AND student_id = $2
`

type GetCourseGradeParams struct {
	CourseID  int64 `json:"course_id"`
	StudentID int64 `json:"student_id"`
}

func (q *Queries) GetCourseGrade(ctx context.Context, arg GetCourseGradeParams) (CourseGrade, error) {
	row := q.db.QueryRow(ctx, getCourseGrade, arg.CourseID, arg.StudentID)
	var i CourseGrade
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.StudentID,
		&i.AutoTotal,
		&i.OverrideTotal,
		&i.IsOverridden,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseMember = `-- name: GetCourseMember :one
SELECT id, tenant_id, course_id, student_id, joined_at, join_mode FROM course_member WHERE course_id = $1 AND student_id = $2
`

type GetCourseMemberParams struct {
	CourseID  int64 `json:"course_id"`
	StudentID int64 `json:"student_id"`
}

func (q *Queries) GetCourseMember(ctx context.Context, arg GetCourseMemberParams) (CourseMember, error) {
	row := q.db.QueryRow(ctx, getCourseMember, arg.CourseID, arg.StudentID)
	var i CourseMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.StudentID,
		&i.JoinedAt,
		&i.JoinMode,
	)
	return i, err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, tenant_id, chapter_id, title, content_type, content_ref, sort, deleted_at, created_at, updated_at FROM lesson WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLessonByID(ctx context.Context, id int64) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLessonByID, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChapterID,
		&i.Title,
		&i.ContentType,
		&i.ContentRef,
		&i.Sort,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLessonProgress = `-- name: GetLessonProgress :one
SELECT id, tenant_id, lesson_id, student_id, status, video_pos, duration_sec, updated_at FROM lesson_progress WHERE lesson_id = $1 AND student_id = $2
`

type GetLessonProgressParams struct {
	LessonID  int64 `json:"lesson_id"`
	StudentID int64 `json:"student_id"`
}

func (q *Queries) GetLessonProgress(ctx context.Context, arg GetLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRow(ctx, getLessonProgress, arg.LessonID, arg.StudentID)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.StudentID,
		&i.Status,
		&i.VideoPos,
		&i.DurationSec,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, tenant_id, assignment_id, student_id, attempt_no, content_ref, judge_task_ref, auto_score, manual_score, final_score, comment, is_late, status, submitted_at FROM submission WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.StudentID,
		&i.AttemptNo,
		&i.ContentRef,
		&i.JudgeTaskRef,
		&i.AutoScore,
		&i.ManualScore,
		&i.FinalScore,
		&i.Comment,
		&i.IsLate,
		&i.Status,
		&i.SubmittedAt,
	)
	return i, err
}

const getSubmissionByJudgeTaskRef = `-- name: GetSubmissionByJudgeTaskRef :one
SELECT id, tenant_id, assignment_id, student_id, attempt_no, content_ref, judge_task_ref, auto_score, manual_score, final_score, comment, is_late, status, submitted_at FROM submission WHERE judge_task_ref = $1
`

func (q *Queries) GetSubmissionByJudgeTaskRef(ctx context.Context, judgeTaskRef pgtype.Text) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByJudgeTaskRef, judgeTaskRef)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.StudentID,
		&i.AttemptNo,
		&i.ContentRef,
		&i.JudgeTaskRef,
		&i.AutoScore,
		&i.ManualScore,
		&i.FinalScore,
		&i.Comment,
		&i.IsLate,
		&i.Status,
		&i.SubmittedAt,
	)
	return i, err
}

const getSubmissionDraft = `-- name: GetSubmissionDraft :one
SELECT id, tenant_id, assignment_id, student_id, content, updated_at FROM submission_draft
WHERE assignment_id = $1
  AND student_id = $2
`

type GetSubmissionDraftParams struct {
	AssignmentID int64 `json:"assignment_id"`
	StudentID    int64 `json:"student_id"`
}

func (q *Queries) GetSubmissionDraft(ctx context.Context, arg GetSubmissionDraftParams) (SubmissionDraft, error) {
	row := q.db.QueryRow(ctx, getSubmissionDraft, arg.AssignmentID, arg.StudentID)
	var i SubmissionDraft
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementPostLike = `-- name: IncrementPostLike :one
UPDATE discussion_post p
SET like_count = p.like_count + 1
FROM course c
WHERE p.id = $1
  AND p.deleted_at IS NULL
  AND c.id = p.course_id
  AND c.deleted_at IS NULL
  AND (
    $2::boolean
    OR c.teacher_id = $3
    OR EXISTS (
      SELECT 1 FROM course_member m
      WHERE m.tenant_id = p.tenant_id
        AND m.course_id = p.course_id
        AND m.student_id = $3
    )
  )
RETURNING p.id, p.tenant_id, p.course_id, p.parent_id, p.author_id, p.content, p.is_pinned, p.like_count, p.deleted_at, p.created_at, p.updated_at
`

type IncrementPostLikeParams struct {
	ID         int64 `json:"id"`
	IsPlatform bool  `json:"is_platform"`
	ActorID    int64 `json:"actor_id"`
}

func (q *Queries) IncrementPostLike(ctx context.Context, arg IncrementPostLikeParams) (DiscussionPost, error) {
	row := q.db.QueryRow(ctx, incrementPostLike, arg.ID, arg.IsPlatform, arg.ActorID)
	var i DiscussionPost
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.ParentID,
		&i.AuthorID,
		&i.Content,
		&i.IsPinned,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, tenant_id, course_id, title, content, is_pinned, deleted_at, created_at, updated_at FROM announcement
WHERE course_id = $1 AND deleted_at IS NULL
ORDER BY is_pinned DESC, created_at DESC
LIMIT $3 OFFSET $2
`

type ListAnnouncementsParams struct {
	CourseID    int64 `json:"course_id"`
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements, arg.CourseID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentItems = `-- name: ListAssignmentItems :many
SELECT id, tenant_id, assignment_id, item_code, item_version, score, seq, grading_mode, judger_code, created_at FROM assignment_item WHERE assignment_id = $1 ORDER BY seq ASC, id ASC
`

func (q *Queries) ListAssignmentItems(ctx context.Context, assignmentID int64) ([]AssignmentItem, error) {
	rows, err := q.db.Query(ctx, listAssignmentItems, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignmentItem{}
	for rows.Next() {
		var i AssignmentItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssignmentID,
			&i.ItemCode,
			&i.ItemVersion,
			&i.Score,
			&i.Seq,
			&i.GradingMode,
			&i.JudgerCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsByCourse = `-- name: ListAssignmentsByCourse :many
SELECT id, tenant_id, course_id, title, chapter_id, due_at, max_attempts, late_policy, late_penalty, status, deleted_at, created_at, updated_at FROM assignment WHERE course_id = $1 AND deleted_at IS NULL ORDER BY due_at ASC, id ASC
`

func (q *Queries) ListAssignmentsByCourse(ctx context.Context, courseID int64) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.Title,
			&i.ChapterID,
			&i.DueAt,
			&i.MaxAttempts,
			&i.LatePolicy,
			&i.LatePenalty,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersByCourse = `-- name: ListChaptersByCourse :many
SELECT id, tenant_id, course_id, title, sort, deleted_at, created_at, updated_at FROM chapter WHERE course_id = $1 AND deleted_at IS NULL ORDER BY sort ASC, id ASC
`

func (q *Queries) ListChaptersByCourse(ctx context.Context, courseID int64) ([]Chapter, error) {
	rows, err := q.db.Query(ctx, listChaptersByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.Title,
			&i.Sort,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseGrades = `-- name: ListCourseGrades :many
SELECT id, tenant_id, course_id, student_id, auto_total, override_total, is_overridden, updated_at FROM course_grade WHERE course_id = $1 ORDER BY student_id ASC LIMIT $3 OFFSET $2
`

type ListCourseGradesParams struct {
	CourseID    int64 `json:"course_id"`
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListCourseGrades(ctx context.Context, arg ListCourseGradesParams) ([]CourseGrade, error) {
	rows, err := q.db.Query(ctx, listCourseGrades, arg.CourseID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseGrade{}
	for rows.Next() {
		var i CourseGrade
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.StudentID,
			&i.AutoTotal,
			&i.OverrideTotal,
			&i.IsOverridden,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseMembers = `-- name: ListCourseMembers :many
SELECT id, tenant_id, course_id, student_id, joined_at, join_mode FROM course_member WHERE course_id = $1 ORDER BY joined_at DESC LIMIT $3 OFFSET $2
`

type ListCourseMembersParams struct {
	CourseID    int64 `json:"course_id"`
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListCourseMembers(ctx context.Context, arg ListCourseMembersParams) ([]CourseMember, error) {
	rows, err := q.db.Query(ctx, listCourseMembers, arg.CourseID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseMember{}
	for rows.Next() {
		var i CourseMember
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.StudentID,
			&i.JoinedAt,
			&i.JoinMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscussionPosts = `-- name: ListDiscussionPosts :many
SELECT id, tenant_id, course_id, parent_id, author_id, content, is_pinned, like_count, deleted_at, created_at, updated_at FROM discussion_post
WHERE course_id = $1 AND deleted_at IS NULL
ORDER BY is_pinned DESC, created_at DESC
LIMIT $3 OFFSET $2
`

type ListDiscussionPostsParams struct {
	CourseID    int64 `json:"course_id"`
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListDiscussionPosts(ctx context.Context, arg ListDiscussionPostsParams) ([]DiscussionPost, error) {
	rows, err := q.db.Query(ctx, listDiscussionPosts, arg.CourseID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscussionPost{}
	for rows.Next() {
		var i DiscussionPost
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.ParentID,
			&i.AuthorID,
			&i.Content,
			&i.IsPinned,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGradeWeightsByCourse = `-- name: ListGradeWeightsByCourse :many
SELECT id, tenant_id, course_id, source_type, source_ref, weight FROM grade_weight WHERE course_id = $1 ORDER BY source_type ASC, source_ref ASC
`

func (q *Queries) ListGradeWeightsByCourse(ctx context.Context, courseID int64) ([]GradeWeight, error) {
	rows, err := q.db.Query(ctx, listGradeWeightsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GradeWeight{}
	for rows.Next() {
		var i GradeWeight
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.SourceType,
			&i.SourceRef,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestAssignmentScoresForCourse = `-- name: ListLatestAssignmentScoresForCourse :many
SELECT DISTINCT ON (s.assignment_id, s.student_id)
  s.assignment_id, s.student_id, s.final_score
FROM submission s
JOIN assignment a ON a.id = s.assignment_id
WHERE a.course_id = $1 AND s.final_score IS NOT NULL
ORDER BY s.assignment_id, s.student_id, s.attempt_no DESC, s.submitted_at DESC
`

type ListLatestAssignmentScoresForCourseRow struct {
	AssignmentID int64       `json:"assignment_id"`
	StudentID    int64       `json:"student_id"`
	FinalScore   pgtype.Int4 `json:"final_score"`
}

func (q *Queries) ListLatestAssignmentScoresForCourse(ctx context.Context, courseID int64) ([]ListLatestAssignmentScoresForCourseRow, error) {
	rows, err := q.db.Query(ctx, listLatestAssignmentScoresForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestAssignmentScoresForCourseRow{}
	for rows.Next() {
		var i ListLatestAssignmentScoresForCourseRow
		if err := rows.Scan(&i.AssignmentID, &i.StudentID, &i.FinalScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonProgressByCourse = `-- name: ListLessonProgressByCourse :many
SELECT p.id, p.tenant_id, p.lesson_id, p.student_id, p.status, p.video_pos, p.duration_sec, p.updated_at FROM lesson_progress p
JOIN lesson l ON l.id = p.lesson_id
JOIN chapter c ON c.id = l.chapter_id
WHERE c.course_id = $1
ORDER BY p.updated_at DESC
`

func (q *Queries) ListLessonProgressByCourse(ctx context.Context, courseID int64) ([]LessonProgress, error) {
	rows, err := q.db.Query(ctx, listLessonProgressByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonProgress{}
	for rows.Next() {
		var i LessonProgress
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LessonID,
			&i.StudentID,
			&i.Status,
			&i.VideoPos,
			&i.DurationSec,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonProgressByCourseAndStudent = `-- name: ListLessonProgressByCourseAndStudent :many
SELECT p.id, p.tenant_id, p.lesson_id, p.student_id, p.status, p.video_pos, p.duration_sec, p.updated_at FROM lesson_progress p
JOIN lesson l ON l.id = p.lesson_id
JOIN chapter c ON c.id = l.chapter_id
WHERE c.course_id = $1
  AND p.student_id = $2
ORDER BY p.updated_at DESC
`

type ListLessonProgressByCourseAndStudentParams struct {
	CourseID  int64 `json:"course_id"`
	StudentID int64 `json:"student_id"`
}

func (q *Queries) ListLessonProgressByCourseAndStudent(ctx context.Context, arg ListLessonProgressByCourseAndStudentParams) ([]LessonProgress, error) {
	rows, err := q.db.Query(ctx, listLessonProgressByCourseAndStudent, arg.CourseID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonProgress{}
	for rows.Next() {
		var i LessonProgress
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LessonID,
			&i.StudentID,
			&i.Status,
			&i.VideoPos,
			&i.DurationSec,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsByChapter = `-- name: ListLessonsByChapter :many
SELECT id, tenant_id, chapter_id, title, content_type, content_ref, sort, deleted_at, created_at, updated_at FROM lesson WHERE chapter_id = $1 AND deleted_at IS NULL ORDER BY sort ASC, id ASC
`

func (q *Queries) ListLessonsByChapter(ctx context.Context, chapterID int64) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsByChapter, chapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChapterID,
			&i.Title,
			&i.ContentType,
			&i.ContentRef,
			&i.Sort,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSubmissionJudgeOutbox = `-- name: ListPendingSubmissionJudgeOutbox :many
SELECT id, tenant_id, submission_id, assignment_id, student_id, item_code, item_version, judger_code, code_storage_key, code_hash, extra_input, source_ref, status, retry_count, last_error, created_at, updated_at FROM submission_judge_outbox
WHERE status = $1
ORDER BY created_at ASC
LIMIT $2
`

type ListPendingSubmissionJudgeOutboxParams struct {
	Status     int16 `json:"status"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListPendingSubmissionJudgeOutbox(ctx context.Context, arg ListPendingSubmissionJudgeOutboxParams) ([]SubmissionJudgeOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingSubmissionJudgeOutbox, arg.Status, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubmissionJudgeOutbox{}
	for rows.Next() {
		var i SubmissionJudgeOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubmissionID,
			&i.AssignmentID,
			&i.StudentID,
			&i.ItemCode,
			&i.ItemVersion,
			&i.JudgerCode,
			&i.CodeStorageKey,
			&i.CodeHash,
			&i.ExtraInput,
			&i.SourceRef,
			&i.Status,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSubmissionJudgeOutboxTenants = `-- name: ListPendingSubmissionJudgeOutboxTenants :many
SELECT DISTINCT tenant_id FROM submission_judge_outbox
WHERE status = $1
ORDER BY tenant_id ASC
LIMIT $2
`

type ListPendingSubmissionJudgeOutboxTenantsParams struct {
	Status     int16 `json:"status"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListPendingSubmissionJudgeOutboxTenants(ctx context.Context, arg ListPendingSubmissionJudgeOutboxTenantsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listPendingSubmissionJudgeOutboxTenants, arg.Status, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var tenant_id int64
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentCourseGrades = `-- name: ListStudentCourseGrades :many
SELECT
    cg.id,
    cg.tenant_id,
    cg.course_id,
    cg.student_id,
    cg.auto_total,
    cg.override_total,
    cg.is_overridden,
    cg.updated_at,
    c.credits
FROM course_grade cg
JOIN course c ON c.id = cg.course_id
WHERE cg.student_id = $1
ORDER BY c.semester ASC, cg.course_id ASC
`

type ListStudentCourseGradesRow struct {
	ID            int64              `json:"id"`
	TenantID      int64              `json:"tenant_id"`
	CourseID      int64              `json:"course_id"`
	StudentID     int64              `json:"student_id"`
	AutoTotal     pgtype.Numeric     `json:"auto_total"`
	OverrideTotal pgtype.Numeric     `json:"override_total"`
	IsOverridden  bool               `json:"is_overridden"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Credits       pgtype.Numeric     `json:"credits"`
}

func (q *Queries) ListStudentCourseGrades(ctx context.Context, studentID int64) ([]ListStudentCourseGradesRow, error) {
	rows, err := q.db.Query(ctx, listStudentCourseGrades, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentCourseGradesRow{}
	for rows.Next() {
		var i ListStudentCourseGradesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.StudentID,
			&i.AutoTotal,
			&i.OverrideTotal,
			&i.IsOverridden,
			&i.UpdatedAt,
			&i.Credits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentCourses = `-- name: ListStudentCourses :many
SELECT c.id, c.tenant_id, c.teacher_id, c.name, c.description, c.type, c.difficulty, c.cover_url, c.semester, c.credits, c.schedule, c.invite_code, c.status, c.visibility, c.deleted_at, c.created_at, c.updated_at FROM course c
JOIN course_member m ON m.course_id = c.id AND m.tenant_id = c.tenant_id
WHERE c.deleted_at IS NULL
  AND m.student_id = $1
  AND ($2::smallint IS NULL OR c.status = $2)
ORDER BY c.created_at DESC
LIMIT $4 OFFSET $3
`

type ListStudentCoursesParams struct {
	StudentID   int64       `json:"student_id"`
	Status      pgtype.Int2 `json:"status"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListStudentCourses(ctx context.Context, arg ListStudentCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listStudentCourses,
		arg.StudentID,
		arg.Status,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TeacherID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Difficulty,
			&i.CoverUrl,
			&i.Semester,
			&i.Credits,
			&i.Schedule,
			&i.InviteCode,
			&i.Status,
			&i.Visibility,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByAssignment = `-- name: ListSubmissionsByAssignment :many
SELECT id, tenant_id, assignment_id, student_id, attempt_no, content_ref, judge_task_ref, auto_score, manual_score, final_score, comment, is_late, status, submitted_at FROM submission WHERE assignment_id = $1 ORDER BY submitted_at DESC LIMIT $3 OFFSET $2
`

type ListSubmissionsByAssignmentParams struct {
	AssignmentID int64 `json:"assignment_id"`
	OffsetCount  int32 `json:"offset_count"`
	LimitCount   int32 `json:"limit_count"`
}

func (q *Queries) ListSubmissionsByAssignment(ctx context.Context, arg ListSubmissionsByAssignmentParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByAssignment, arg.AssignmentID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssignmentID,
			&i.StudentID,
			&i.AttemptNo,
			&i.ContentRef,
			&i.JudgeTaskRef,
			&i.AutoScore,
			&i.ManualScore,
			&i.FinalScore,
			&i.Comment,
			&i.IsLate,
			&i.Status,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherCourses = `-- name: ListTeacherCourses :many
SELECT id, tenant_id, teacher_id, name, description, type, difficulty, cover_url, semester, credits, schedule, invite_code, status, visibility, deleted_at, created_at, updated_at FROM course
WHERE deleted_at IS NULL
  AND teacher_id = $1
  AND ($2::smallint IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListTeacherCoursesParams struct {
	TeacherID   int64       `json:"teacher_id"`
	Status      pgtype.Int2 `json:"status"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListTeacherCourses(ctx context.Context, arg ListTeacherCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listTeacherCourses,
		arg.TeacherID,
		arg.Status,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TeacherID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Difficulty,
			&i.CoverUrl,
			&i.Semester,
			&i.Credits,
			&i.Schedule,
			&i.InviteCode,
			&i.Status,
			&i.Visibility,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubmissionJudgeOutboxRunning = `-- name: MarkSubmissionJudgeOutboxRunning :one
UPDATE submission_judge_outbox
SET status = $1, retry_count = retry_count + 1, last_error = NULL
WHERE id = $2
  AND status = $3
RETURNING id, tenant_id, submission_id, assignment_id, student_id, item_code, item_version, judger_code, code_storage_key, code_hash, extra_input, source_ref, status, retry_count, last_error, created_at, updated_at
`

type MarkSubmissionJudgeOutboxRunningParams struct {
	RunningStatus int16 `json:"running_status"`
	ID            int64 `json:"id"`
	PendingStatus int16 `json:"pending_status"`
}

func (q *Queries) MarkSubmissionJudgeOutboxRunning(ctx context.Context, arg MarkSubmissionJudgeOutboxRunningParams) (SubmissionJudgeOutbox, error) {
	row := q.db.QueryRow(ctx, markSubmissionJudgeOutboxRunning, arg.RunningStatus, arg.ID, arg.PendingStatus)
	var i SubmissionJudgeOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubmissionID,
		&i.AssignmentID,
		&i.StudentID,
		&i.ItemCode,
		&i.ItemVersion,
		&i.JudgerCode,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.ExtraInput,
		&i.SourceRef,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeCourseMember = `-- name: RemoveCourseMember :exec
DELETE FROM course_member WHERE course_id = $1 AND student_id = $2
`

type RemoveCourseMemberParams struct {
	CourseID  int64 `json:"course_id"`
	StudentID int64 `json:"student_id"`
}

func (q *Queries) RemoveCourseMember(ctx context.Context, arg RemoveCourseMemberParams) error {
	_, err := q.db.Exec(ctx, removeCourseMember, arg.CourseID, arg.StudentID)
	return err
}

const softDeleteChapter = `-- name: SoftDeleteChapter :one
UPDATE chapter SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, course_id, title, sort, deleted_at, created_at, updated_at
`

func (q *Queries) SoftDeleteChapter(ctx context.Context, id int64) (Chapter, error) {
	row := q.db.QueryRow(ctx, softDeleteChapter, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Sort,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteCourse = `-- name: SoftDeleteCourse :one
UPDATE course SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, teacher_id, name, description, type, difficulty, cover_url, semester, credits, schedule, invite_code, status, visibility, deleted_at, created_at, updated_at
`

func (q *Queries) SoftDeleteCourse(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, softDeleteCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.CoverUrl,
		&i.Semester,
		&i.Credits,
		&i.Schedule,
		&i.InviteCode,
		&i.Status,
		&i.Visibility,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteLesson = `-- name: SoftDeleteLesson :one
UPDATE lesson SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, chapter_id, title, content_type, content_ref, sort, deleted_at, created_at, updated_at
`

func (q *Queries) SoftDeleteLesson(ctx context.Context, id int64) (Lesson, error) {
	row := q.db.QueryRow(ctx, softDeleteLesson, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChapterID,
		&i.Title,
		&i.ContentType,
		&i.ContentRef,
		&i.Sort,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeletePost = `-- name: SoftDeletePost :one
UPDATE discussion_post p
SET deleted_at = now()
FROM course c
WHERE p.id = $1
  AND p.deleted_at IS NULL
  AND c.id = p.course_id
  AND c.deleted_at IS NULL
  AND ($2::boolean OR c.teacher_id = $3)
RETURNING p.id, p.tenant_id, p.course_id, p.parent_id, p.author_id, p.content, p.is_pinned, p.like_count, p.deleted_at, p.created_at, p.updated_at
`

type SoftDeletePostParams struct {
	ID         int64 `json:"id"`
	IsPlatform bool  `json:"is_platform"`
	ActorID    int64 `json:"actor_id"`
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) (DiscussionPost, error) {
	row := q.db.QueryRow(ctx, softDeletePost, arg.ID, arg.IsPlatform, arg.ActorID)
	var i DiscussionPost
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.ParentID,
		&i.AuthorID,
		&i.Content,
		&i.IsPinned,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumLearningDuration = `-- name: SumLearningDuration :one
SELECT coalesce(sum(duration_sec), 0)::bigint FROM lesson_progress
`

func (q *Queries) SumLearningDuration(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumLearningDuration)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const toggleAnnouncementPin = `-- name: ToggleAnnouncementPin :one
UPDATE announcement a
SET is_pinned = NOT a.is_pinned
FROM course c
WHERE a.id = $1
  AND a.deleted_at IS NULL
  AND c.id = a.course_id
  AND c.deleted_at IS NULL
  AND ($2::boolean OR c.teacher_id = $3)
RETURNING a.id, a.tenant_id, a.course_id, a.title, a.content, a.is_pinned, a.deleted_at, a.created_at, a.updated_at
`

type ToggleAnnouncementPinParams struct {
	ID         int64 `json:"id"`
	IsPlatform bool  `json:"is_platform"`
	ActorID    int64 `json:"actor_id"`
}

func (q *Queries) ToggleAnnouncementPin(ctx context.Context, arg ToggleAnnouncementPinParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, toggleAnnouncementPin, arg.ID, arg.IsPlatform, arg.ActorID)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const togglePostPin = `-- name: TogglePostPin :one
UPDATE discussion_post p
SET is_pinned = NOT p.is_pinned
FROM course c
WHERE p.id = $1
  AND p.deleted_at IS NULL
  AND c.id = p.course_id
  AND c.deleted_at IS NULL
  AND ($2::boolean OR c.teacher_id = $3)
RETURNING p.id, p.tenant_id, p.course_id, p.parent_id, p.author_id, p.content, p.is_pinned, p.like_count, p.deleted_at, p.created_at, p.updated_at
`

type TogglePostPinParams struct {
	ID         int64 `json:"id"`
	IsPlatform bool  `json:"is_platform"`
	ActorID    int64 `json:"actor_id"`
}

func (q *Queries) TogglePostPin(ctx context.Context, arg TogglePostPinParams) (DiscussionPost, error) {
	row := q.db.QueryRow(ctx, togglePostPin, arg.ID, arg.IsPlatform, arg.ActorID)
	var i DiscussionPost
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.ParentID,
		&i.AuthorID,
		&i.Content,
		&i.IsPinned,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE assignment SET
  title = $1,
  chapter_id = $2,
  due_at = $3,
  max_attempts = $4,
  late_policy = $5,
  late_penalty = $6
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, tenant_id, course_id, title, chapter_id, due_at, max_attempts, late_policy, late_penalty, status, deleted_at, created_at, updated_at
`

type UpdateAssignmentParams struct {
	Title       string             `json:"title"`
	ChapterID   pgtype.Int8        `json:"chapter_id"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
	MaxAttempts int32              `json:"max_attempts"`
	LatePolicy  int16              `json:"late_policy"`
	LatePenalty []byte             `json:"late_penalty"`
	ID          int64              `json:"id"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, updateAssignment,
		arg.Title,
		arg.ChapterID,
		arg.DueAt,
		arg.MaxAttempts,
		arg.LatePolicy,
		arg.LatePenalty,
		arg.ID,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.ChapterID,
		&i.DueAt,
		&i.MaxAttempts,
		&i.LatePolicy,
		&i.LatePenalty,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssignmentStatus = `-- name: UpdateAssignmentStatus :one
UPDATE assignment SET status = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, course_id, title, chapter_id, due_at, max_attempts, late_policy, late_penalty, status, deleted_at, created_at, updated_at
`

type UpdateAssignmentStatusParams struct {
	Status int16 `json:"status"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateAssignmentStatus(ctx context.Context, arg UpdateAssignmentStatusParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, updateAssignmentStatus, arg.Status, arg.ID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.ChapterID,
		&i.DueAt,
		&i.MaxAttempts,
		&i.LatePolicy,
		&i.LatePenalty,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChapter = `-- name: UpdateChapter :one
UPDATE chapter SET title = $1, sort = $2
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, tenant_id, course_id, title, sort, deleted_at, created_at, updated_at
`

type UpdateChapterParams struct {
	Title string `json:"title"`
	Sort  int32  `json:"sort"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateChapter(ctx context.Context, arg UpdateChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, updateChapter, arg.Title, arg.Sort, arg.ID)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Sort,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE course SET
  name = $1,
  description = $2,
  type = $3,
  difficulty = $4,
  cover_url = $5,
  semester = $6,
  credits = $7,
  schedule = $8
WHERE id = $9 AND deleted_at IS NULL
RETURNING id, tenant_id, teacher_id, name, description, type, difficulty, cover_url, semester, credits, schedule, invite_code, status, visibility, deleted_at, created_at, updated_at
`

type UpdateCourseParams struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Type        int16          `json:"type"`
	Difficulty  int16          `json:"difficulty"`
	CoverUrl    pgtype.Text    `json:"cover_url"`
	Semester    string         `json:"semester"`
	Credits     pgtype.Numeric `json:"credits"`
	Schedule    []byte         `json:"schedule"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Difficulty,
		arg.CoverUrl,
		arg.Semester,
		arg.Credits,
		arg.Schedule,
		arg.ID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.CoverUrl,
		&i.Semester,
		&i.Credits,
		&i.Schedule,
		&i.InviteCode,
		&i.Status,
		&i.Visibility,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourseInviteCode = `-- name: UpdateCourseInviteCode :one
UPDATE course SET invite_code = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, teacher_id, name, description, type, difficulty, cover_url, semester, credits, schedule, invite_code, status, visibility, deleted_at, created_at, updated_at
`

type UpdateCourseInviteCodeParams struct {
	InviteCode string `json:"invite_code"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateCourseInviteCode(ctx context.Context, arg UpdateCourseInviteCodeParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourseInviteCode, arg.InviteCode, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.CoverUrl,
		&i.Semester,
		&i.Credits,
		&i.Schedule,
		&i.InviteCode,
		&i.Status,
		&i.Visibility,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourseStatus = `-- name: UpdateCourseStatus :one
UPDATE course SET status = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, teacher_id, name, description, type, difficulty, cover_url, semester, credits, schedule, invite_code, status, visibility, deleted_at, created_at, updated_at
`

type UpdateCourseStatusParams struct {
	Status int16 `json:"status"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateCourseStatus(ctx context.Context, arg UpdateCourseStatusParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourseStatus, arg.Status, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.CoverUrl,
		&i.Semester,
		&i.Credits,
		&i.Schedule,
		&i.InviteCode,
		&i.Status,
		&i.Visibility,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourseVisibility = `-- name: UpdateCourseVisibility :one
UPDATE course SET visibility = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, teacher_id, name, description, type, difficulty, cover_url, semester, credits, schedule, invite_code, status, visibility, deleted_at, created_at, updated_at
`

type UpdateCourseVisibilityParams struct {
	Visibility int16 `json:"visibility"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateCourseVisibility(ctx context.Context, arg UpdateCourseVisibilityParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourseVisibility, arg.Visibility, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.CoverUrl,
		&i.Semester,
		&i.Credits,
		&i.Schedule,
		&i.InviteCode,
		&i.Status,
		&i.Visibility,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLesson = `-- name: UpdateLesson :one
UPDATE lesson SET title = $1, content_type = $2, content_ref = $3, sort = $4
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, tenant_id, chapter_id, title, content_type, content_ref, sort, deleted_at, created_at, updated_at
`

type UpdateLessonParams struct {
	Title       string `json:"title"`
	ContentType int16  `json:"content_type"`
	ContentRef  []byte `json:"content_ref"`
	Sort        int32  `json:"sort"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, updateLesson,
		arg.Title,
		arg.ContentType,
		arg.ContentRef,
		arg.Sort,
		arg.ID,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChapterID,
		&i.Title,
		&i.ContentType,
		&i.ContentRef,
		&i.Sort,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLessonContent = `-- name: UpdateLessonContent :one
UPDATE lesson SET content_type = $1, content_ref = $2
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, tenant_id, chapter_id, title, content_type, content_ref, sort, deleted_at, created_at, updated_at
`

type UpdateLessonContentParams struct {
	ContentType int16  `json:"content_type"`
	ContentRef  []byte `json:"content_ref"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateLessonContent(ctx context.Context, arg UpdateLessonContentParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, updateLessonContent, arg.ContentType, arg.ContentRef, arg.ID)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChapterID,
		&i.Title,
		&i.ContentType,
		&i.ContentRef,
		&i.Sort,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubmissionAutoScore = `-- name: UpdateSubmissionAutoScore :one
UPDATE submission SET auto_score = $1, final_score = $2, status = $3
WHERE id = $4
RETURNING id, tenant_id, assignment_id, student_id, attempt_no, content_ref, judge_task_ref, auto_score, manual_score, final_score, comment, is_late, status, submitted_at
`

type UpdateSubmissionAutoScoreParams struct {
	AutoScore  pgtype.Int4 `json:"auto_score"`
	FinalScore pgtype.Int4 `json:"final_score"`
	Status     int16       `json:"status"`
	ID         int64       `json:"id"`
}

func (q *Queries) UpdateSubmissionAutoScore(ctx context.Context, arg UpdateSubmissionAutoScoreParams) (Submission, error) {
	row := q.db.QueryRow(ctx, updateSubmissionAutoScore,
		arg.AutoScore,
		arg.FinalScore,
		arg.Status,
		arg.ID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.StudentID,
		&i.AttemptNo,
		&i.ContentRef,
		&i.JudgeTaskRef,
		&i.AutoScore,
		&i.ManualScore,
		&i.FinalScore,
		&i.Comment,
		&i.IsLate,
		&i.Status,
		&i.SubmittedAt,
	)
	return i, err
}

const updateSubmissionJudgeTaskRef = `-- name: UpdateSubmissionJudgeTaskRef :one
UPDATE submission SET judge_task_ref = $1
WHERE id = $2
RETURNING id, tenant_id, assignment_id, student_id, attempt_no, content_ref, judge_task_ref, auto_score, manual_score, final_score, comment, is_late, status, submitted_at
`

type UpdateSubmissionJudgeTaskRefParams struct {
	JudgeTaskRef pgtype.Text `json:"judge_task_ref"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateSubmissionJudgeTaskRef(ctx context.Context, arg UpdateSubmissionJudgeTaskRefParams) (Submission, error) {
	row := q.db.QueryRow(ctx, updateSubmissionJudgeTaskRef, arg.JudgeTaskRef, arg.ID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.StudentID,
		&i.AttemptNo,
		&i.ContentRef,
		&i.JudgeTaskRef,
		&i.AutoScore,
		&i.ManualScore,
		&i.FinalScore,
		&i.Comment,
		&i.IsLate,
		&i.Status,
		&i.SubmittedAt,
	)
	return i, err
}

const updateSubmissionManualScore = `-- name: UpdateSubmissionManualScore :one
UPDATE submission SET manual_score = $1, final_score = $2, comment = $3, status = $4
WHERE id = $5
RETURNING id, tenant_id, assignment_id, student_id, attempt_no, content_ref, judge_task_ref, auto_score, manual_score, final_score, comment, is_late, status, submitted_at
`

type UpdateSubmissionManualScoreParams struct {
	ManualScore pgtype.Int4 `json:"manual_score"`
	FinalScore  pgtype.Int4 `json:"final_score"`
	Comment     pgtype.Text `json:"comment"`
	Status      int16       `json:"status"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateSubmissionManualScore(ctx context.Context, arg UpdateSubmissionManualScoreParams) (Submission, error) {
	row := q.db.QueryRow(ctx, updateSubmissionManualScore,
		arg.ManualScore,
		arg.FinalScore,
		arg.Comment,
		arg.Status,
		arg.ID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.StudentID,
		&i.AttemptNo,
		&i.ContentRef,
		&i.JudgeTaskRef,
		&i.AutoScore,
		&i.ManualScore,
		&i.FinalScore,
		&i.Comment,
		&i.IsLate,
		&i.Status,
		&i.SubmittedAt,
	)
	return i, err
}

const upsertCourseGrade = `-- name: UpsertCourseGrade :one
INSERT INTO course_grade (id, tenant_id, course_id, student_id, auto_total, override_total, is_overridden)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, course_id, student_id) DO UPDATE SET
  auto_total = EXCLUDED.auto_total,
  override_total = EXCLUDED.override_total,
  is_overridden = EXCLUDED.is_overridden,
  updated_at = now()
RETURNING id, tenant_id, course_id, student_id, auto_total, override_total, is_overridden, updated_at
`

type UpsertCourseGradeParams struct {
	ID            int64          `json:"id"`
	TenantID      int64          `json:"tenant_id"`
	CourseID      int64          `json:"course_id"`
	StudentID     int64          `json:"student_id"`
	AutoTotal     pgtype.Numeric `json:"auto_total"`
	OverrideTotal pgtype.Numeric `json:"override_total"`
	IsOverridden  bool           `json:"is_overridden"`
}

func (q *Queries) UpsertCourseGrade(ctx context.Context, arg UpsertCourseGradeParams) (CourseGrade, error) {
	row := q.db.QueryRow(ctx, upsertCourseGrade,
		arg.ID,
		arg.TenantID,
		arg.CourseID,
		arg.StudentID,
		arg.AutoTotal,
		arg.OverrideTotal,
		arg.IsOverridden,
	)
	var i CourseGrade
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.StudentID,
		&i.AutoTotal,
		&i.OverrideTotal,
		&i.IsOverridden,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCourseReview = `-- name: UpsertCourseReview :one
INSERT INTO course_review (id, tenant_id, course_id, student_id, rating, comment)
SELECT $1, $2, $3, $4, $5, $6
WHERE EXISTS (
  SELECT 1 FROM course c
  JOIN course_member m ON m.tenant_id = c.tenant_id AND m.course_id = c.id
  WHERE c.id = $3
    AND c.deleted_at IS NULL
    AND m.student_id = $4
)
ON CONFLICT (tenant_id, course_id, student_id) DO UPDATE SET rating = EXCLUDED.rating, comment = EXCLUDED.comment
RETURNING id, tenant_id, course_id, student_id, rating, comment, created_at
`

type UpsertCourseReviewParams struct {
	ID        int64       `json:"id"`
	TenantID  int64       `json:"tenant_id"`
	CourseID  int64       `json:"course_id"`
	StudentID int64       `json:"student_id"`
	Rating    int16       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
}

func (q *Queries) UpsertCourseReview(ctx context.Context, arg UpsertCourseReviewParams) (CourseReview, error) {
	row := q.db.QueryRow(ctx, upsertCourseReview,
		arg.ID,
		arg.TenantID,
		arg.CourseID,
		arg.StudentID,
		arg.Rating,
		arg.Comment,
	)
	var i CourseReview
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.StudentID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const upsertLessonProgress = `-- name: UpsertLessonProgress :one
INSERT INTO lesson_progress (id, tenant_id, lesson_id, student_id, status, video_pos, duration_sec)
SELECT $1, $2, $3, $4, $5, $6, $7
WHERE EXISTS (
  SELECT 1 FROM lesson l
  JOIN chapter ch ON ch.id = l.chapter_id AND ch.tenant_id = l.tenant_id
  JOIN course c ON c.id = ch.course_id AND c.tenant_id = ch.tenant_id
  JOIN course_member m ON m.tenant_id = c.tenant_id AND m.course_id = c.id
  WHERE l.id = $3
    AND l.deleted_at IS NULL
    AND ch.deleted_at IS NULL
    AND c.deleted_at IS NULL
    AND m.student_id = $4
)
ON CONFLICT (tenant_id, lesson_id, student_id) DO UPDATE SET status = EXCLUDED.status, video_pos = EXCLUDED.video_pos, duration_sec = lesson_progress.duration_sec + EXCLUDED.duration_sec, updated_at = now()
RETURNING id, tenant_id, lesson_id, student_id, status, video_pos, duration_sec, updated_at
`

type UpsertLessonProgressParams struct {
	ID          int64       `json:"id"`
	TenantID    int64       `json:"tenant_id"`
	LessonID    int64       `json:"lesson_id"`
	StudentID   int64       `json:"student_id"`
	Status      int16       `json:"status"`
	VideoPos    pgtype.Int4 `json:"video_pos"`
	DurationSec int32       `json:"duration_sec"`
}

func (q *Queries) UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRow(ctx, upsertLessonProgress,
		arg.ID,
		arg.TenantID,
		arg.LessonID,
		arg.StudentID,
		arg.Status,
		arg.VideoPos,
		arg.DurationSec,
	)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.StudentID,
		&i.Status,
		&i.VideoPos,
		&i.DurationSec,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubmissionDraft = `-- name: UpsertSubmissionDraft :one
INSERT INTO submission_draft (id, tenant_id, assignment_id, student_id, content)
SELECT $1, $2, $3, $4, $5
WHERE EXISTS (
  SELECT 1 FROM assignment a
  JOIN course c ON c.id = a.course_id AND c.tenant_id = a.tenant_id
  JOIN course_member m ON m.tenant_id = c.tenant_id AND m.course_id = c.id
  WHERE a.id = $3
    AND a.deleted_at IS NULL
    AND c.deleted_at IS NULL
    AND m.student_id = $4
)
ON CONFLICT (tenant_id, assignment_id, student_id) DO UPDATE SET content = EXCLUDED.content, updated_at = now()
RETURNING id, tenant_id, assignment_id, student_id, content, updated_at
`

type UpsertSubmissionDraftParams struct {
	ID           int64  `json:"id"`
	TenantID     int64  `json:"tenant_id"`
	AssignmentID int64  `json:"assignment_id"`
	StudentID    int64  `json:"student_id"`
	Content      []byte `json:"content"`
}

func (q *Queries) UpsertSubmissionDraft(ctx context.Context, arg UpsertSubmissionDraftParams) (SubmissionDraft, error) {
	row := q.db.QueryRow(ctx, upsertSubmissionDraft,
		arg.ID,
		arg.TenantID,
		arg.AssignmentID,
		arg.StudentID,
		arg.Content,
	)
	var i SubmissionDraft
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}
