// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CountActiveSandboxes(ctx context.Context) (int64, error)
	// M2 sandbox sqlc 查询源。
	// 约定:租户表查询依赖 RLS 透明过滤;插入显式带 tenant_id(WITH CHECK)。
	// ============================================================
	// runtime / runtime_image / tool(全局配置)
	// ============================================================
	CreateRuntime(ctx context.Context, arg CreateRuntimeParams) (Runtime, error)
	CreateRuntimeImage(ctx context.Context, arg CreateRuntimeImageParams) (RuntimeImage, error)
	// ============================================================
	// sandbox / sandbox_tool / sandbox_event
	// ============================================================
	CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error)
	CreateSandboxEvent(ctx context.Context, arg CreateSandboxEventParams) error
	CreateSandboxTool(ctx context.Context, arg CreateSandboxToolParams) (SandboxTool, error)
	CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error)
	DestroySandbox(ctx context.Context, id int64) (Sandbox, error)
	GetDefaultRuntimeImage(ctx context.Context, runtimeID int64) (RuntimeImage, error)
	GetRuntimeByCode(ctx context.Context, code string) (Runtime, error)
	GetRuntimeByID(ctx context.Context, id int64) (Runtime, error)
	GetRuntimeImage(ctx context.Context, arg GetRuntimeImageParams) (RuntimeImage, error)
	GetRuntimeImageByVersion(ctx context.Context, arg GetRuntimeImageByVersionParams) (RuntimeImage, error)
	GetSandboxByID(ctx context.Context, id int64) (Sandbox, error)
	GetSandboxToolForProxy(ctx context.Context, arg GetSandboxToolForProxyParams) (GetSandboxToolForProxyRow, error)
	GetTenantQuota(ctx context.Context, tenantID int64) (TenantQuotum, error)
	GetToolByCode(ctx context.Context, code string) (Tool, error)
	ListActiveSandboxResourceSpecs(ctx context.Context) ([]ListActiveSandboxResourceSpecsRow, error)
	ListDueSandboxRecycles(ctx context.Context, arg ListDueSandboxRecyclesParams) ([]Sandbox, error)
	ListExpiredSandboxSnapshots(ctx context.Context, limit int32) ([]Sandbox, error)
	ListRuntimes(ctx context.Context, arg ListRuntimesParams) ([]Runtime, error)
	ListSandboxEvents(ctx context.Context, arg ListSandboxEventsParams) ([]SandboxEvent, error)
	ListSandboxTools(ctx context.Context, sandboxID int64) ([]ListSandboxToolsRow, error)
	ListSandboxesBySourceRef(ctx context.Context, sourceRef string) ([]Sandbox, error)
	ListTools(ctx context.Context, arg ListToolsParams) ([]Tool, error)
	MarkSandboxActive(ctx context.Context, id int64) error
	RecycleSandbox(ctx context.Context, id int64) (Sandbox, error)
	UpdateRuntime(ctx context.Context, arg UpdateRuntimeParams) (Runtime, error)
	UpdateRuntimeImagePrepull(ctx context.Context, arg UpdateRuntimeImagePrepullParams) (RuntimeImage, error)
	UpdateRuntimeSelftest(ctx context.Context, arg UpdateRuntimeSelftestParams) (Runtime, error)
	UpdateSandboxCodeHash(ctx context.Context, arg UpdateSandboxCodeHashParams) (Sandbox, error)
	UpdateSandboxPhaseStatus(ctx context.Context, arg UpdateSandboxPhaseStatusParams) (Sandbox, error)
	UpdateSandboxSnapshot(ctx context.Context, arg UpdateSandboxSnapshotParams) (Sandbox, error)
	// ============================================================
	// tenant_quota
	// ============================================================
	UpsertTenantQuota(ctx context.Context, arg UpsertTenantQuotaParams) (TenantQuotum, error)
}

var _ Querier = (*Queries)(nil)
