// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	ClaimPendingSandboxRecycleOutbox(ctx context.Context, arg ClaimPendingSandboxRecycleOutboxParams) ([]SandboxRecycleOutbox, error)
	CountActiveSandboxes(ctx context.Context, tenantID int64) (int64, error)
	CreateRuntimeImage(ctx context.Context, arg CreateRuntimeImageParams) (RuntimeImage, error)
	CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error)
	CreateSandboxEvent(ctx context.Context, arg CreateSandboxEventParams) (SandboxEvent, error)
	CreateSandboxRecycleOutbox(ctx context.Context, arg CreateSandboxRecycleOutboxParams) (SandboxRecycleOutbox, error)
	CreateSandboxTool(ctx context.Context, arg CreateSandboxToolParams) (SandboxTool, error)
	DisableRuntimeImage(ctx context.Context, arg DisableRuntimeImageParams) (RuntimeImage, error)
	GetDefaultRuntimeImage(ctx context.Context, runtimeID int64) (RuntimeImage, error)
	GetRuntimeByCode(ctx context.Context, code string) (Runtime, error)
	GetRuntimeByID(ctx context.Context, id int64) (Runtime, error)
	GetRuntimeImageByID(ctx context.Context, arg GetRuntimeImageByIDParams) (RuntimeImage, error)
	GetRuntimeImageByVersion(ctx context.Context, arg GetRuntimeImageByVersionParams) (RuntimeImage, error)
	GetSandbox(ctx context.Context, arg GetSandboxParams) (Sandbox, error)
	GetTenantQuota(ctx context.Context, tenantID int64) (TenantQuotum, error)
	GetToolByCode(ctx context.Context, code string) (Tool, error)
	ListRecycleCandidates(ctx context.Context, arg ListRecycleCandidatesParams) ([]Sandbox, error)
	ListRuntimeImages(ctx context.Context, runtimeID int64) ([]RuntimeImage, error)
	ListRuntimes(ctx context.Context) ([]Runtime, error)
	ListSandboxTools(ctx context.Context, arg ListSandboxToolsParams) ([]ListSandboxToolsRow, error)
	ListSandboxesBySourceRef(ctx context.Context, arg ListSandboxesBySourceRefParams) ([]Sandbox, error)
	ListSnapshotCleanupCandidates(ctx context.Context, limit int32) ([]Sandbox, error)
	ListTools(ctx context.Context) ([]Tool, error)
	MarkOtherRuntimeImagesNotDefault(ctx context.Context, arg MarkOtherRuntimeImagesNotDefaultParams) error
	MarkSandboxActive(ctx context.Context, arg MarkSandboxActiveParams) (Sandbox, error)
	MarkSandboxRecycleOutboxFailed(ctx context.Context, arg MarkSandboxRecycleOutboxFailedParams) (SandboxRecycleOutbox, error)
	MarkSandboxRecycleOutboxPublished(ctx context.Context, arg MarkSandboxRecycleOutboxPublishedParams) (SandboxRecycleOutbox, error)
	StatsByTenant(ctx context.Context, tenantID int64) (StatsByTenantRow, error)
	UpdateRuntimeImagePrepull(ctx context.Context, arg UpdateRuntimeImagePrepullParams) (RuntimeImage, error)
	UpdateRuntimeSelftest(ctx context.Context, arg UpdateRuntimeSelftestParams) (Runtime, error)
	UpdateSandboxCode(ctx context.Context, arg UpdateSandboxCodeParams) (Sandbox, error)
	UpdateSandboxPhaseStatus(ctx context.Context, arg UpdateSandboxPhaseStatusParams) (Sandbox, error)
	UpdateSandboxSnapshot(ctx context.Context, arg UpdateSandboxSnapshotParams) (Sandbox, error)
	UpdateSandboxToolStatus(ctx context.Context, arg UpdateSandboxToolStatusParams) (SandboxTool, error)
	UpsertRuntime(ctx context.Context, arg UpsertRuntimeParams) (Runtime, error)
	UpsertTenantQuota(ctx context.Context, arg UpsertTenantQuotaParams) (TenantQuotum, error)
	UpsertTool(ctx context.Context, arg UpsertToolParams) (Tool, error)
}

var _ Querier = (*Queries)(nil)
