// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sandbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSandboxes = `-- name: CountActiveSandboxes :one
SELECT count(*) FROM sandbox WHERE status IN (1,2,3,4)
`

func (q *Queries) CountActiveSandboxes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSandboxes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRuntime = `-- name: CreateRuntime :one


INSERT INTO runtime (id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at
`

type CreateRuntimeParams struct {
	ID             int64       `json:"id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	Eco            string      `json:"eco"`
	AdapterLevel   int16       `json:"adapter_level"`
	AdapterSpec    []byte      `json:"adapter_spec"`
	CapabilityImpl pgtype.Text `json:"capability_impl"`
	PluginRef      pgtype.Text `json:"plugin_ref"`
	SelftestStatus int16       `json:"selftest_status"`
	SelftestDetail []byte      `json:"selftest_detail"`
	Status         int16       `json:"status"`
}

// M2 sandbox sqlc 查询源。
// 约定:租户表查询依赖 RLS 透明过滤;插入显式带 tenant_id(WITH CHECK)。
// ============================================================
// runtime / runtime_image / tool(全局配置)
// ============================================================
func (q *Queries) CreateRuntime(ctx context.Context, arg CreateRuntimeParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, createRuntime,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Eco,
		arg.AdapterLevel,
		arg.AdapterSpec,
		arg.CapabilityImpl,
		arg.PluginRef,
		arg.SelftestStatus,
		arg.SelftestDetail,
		arg.Status,
	)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Eco,
		&i.AdapterLevel,
		&i.AdapterSpec,
		&i.CapabilityImpl,
		&i.PluginRef,
		&i.SelftestStatus,
		&i.SelftestDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRuntimeImage = `-- name: CreateRuntimeImage :one
INSERT INTO runtime_image (id, runtime_id, image_url, version, prepulled, prepull_status, prepull_detail, genesis_baked, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, runtime_id, image_url, version, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at
`

type CreateRuntimeImageParams struct {
	ID            int64  `json:"id"`
	RuntimeID     int64  `json:"runtime_id"`
	ImageUrl      string `json:"image_url"`
	Version       string `json:"version"`
	Prepulled     bool   `json:"prepulled"`
	PrepullStatus int16  `json:"prepull_status"`
	PrepullDetail []byte `json:"prepull_detail"`
	GenesisBaked  bool   `json:"genesis_baked"`
	IsDefault     bool   `json:"is_default"`
}

func (q *Queries) CreateRuntimeImage(ctx context.Context, arg CreateRuntimeImageParams) (RuntimeImage, error) {
	row := q.db.QueryRow(ctx, createRuntimeImage,
		arg.ID,
		arg.RuntimeID,
		arg.ImageUrl,
		arg.Version,
		arg.Prepulled,
		arg.PrepullStatus,
		arg.PrepullDetail,
		arg.GenesisBaked,
		arg.IsDefault,
	)
	var i RuntimeImage
	err := row.Scan(
		&i.ID,
		&i.RuntimeID,
		&i.ImageUrl,
		&i.Version,
		&i.Prepulled,
		&i.PrepullStatus,
		&i.PrepullDetail,
		&i.PrepulledAt,
		&i.GenesisBaked,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createSandbox = `-- name: CreateSandbox :one

INSERT INTO sandbox (
    id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id,
    phase, status, keep_alive, snapshot_enabled, code_storage_key, init_script_ref,
    keep_alive_until, snapshot_expire_at, last_active_at, expire_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, now(), $16)
RETURNING id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_script_ref, snapshot_ref, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
`

type CreateSandboxParams struct {
	ID               int64              `json:"id"`
	TenantID         int64              `json:"tenant_id"`
	RuntimeID        int64              `json:"runtime_id"`
	ImageID          int64              `json:"image_id"`
	Namespace        string             `json:"namespace"`
	SourceRef        string             `json:"source_ref"`
	OwnerAccountID   int64              `json:"owner_account_id"`
	Phase            int16              `json:"phase"`
	Status           int16              `json:"status"`
	KeepAlive        bool               `json:"keep_alive"`
	SnapshotEnabled  bool               `json:"snapshot_enabled"`
	CodeStorageKey   string             `json:"code_storage_key"`
	InitScriptRef    pgtype.Text        `json:"init_script_ref"`
	KeepAliveUntil   pgtype.Timestamptz `json:"keep_alive_until"`
	SnapshotExpireAt pgtype.Timestamptz `json:"snapshot_expire_at"`
	ExpireAt         pgtype.Timestamptz `json:"expire_at"`
}

// ============================================================
// sandbox / sandbox_tool / sandbox_event
// ============================================================
func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, createSandbox,
		arg.ID,
		arg.TenantID,
		arg.RuntimeID,
		arg.ImageID,
		arg.Namespace,
		arg.SourceRef,
		arg.OwnerAccountID,
		arg.Phase,
		arg.Status,
		arg.KeepAlive,
		arg.SnapshotEnabled,
		arg.CodeStorageKey,
		arg.InitScriptRef,
		arg.KeepAliveUntil,
		arg.SnapshotExpireAt,
		arg.ExpireAt,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSandboxEvent = `-- name: CreateSandboxEvent :exec
INSERT INTO sandbox_event (id, tenant_id, sandbox_id, event_type, detail)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSandboxEventParams struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	SandboxID int64  `json:"sandbox_id"`
	EventType string `json:"event_type"`
	Detail    []byte `json:"detail"`
}

func (q *Queries) CreateSandboxEvent(ctx context.Context, arg CreateSandboxEventParams) error {
	_, err := q.db.Exec(ctx, createSandboxEvent,
		arg.ID,
		arg.TenantID,
		arg.SandboxID,
		arg.EventType,
		arg.Detail,
	)
	return err
}

const createSandboxTool = `-- name: CreateSandboxTool :one
INSERT INTO sandbox_tool (id, tenant_id, sandbox_id, tool_id, access_endpoint, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, sandbox_id, tool_id, access_endpoint, status
`

type CreateSandboxToolParams struct {
	ID             int64  `json:"id"`
	TenantID       int64  `json:"tenant_id"`
	SandboxID      int64  `json:"sandbox_id"`
	ToolID         int64  `json:"tool_id"`
	AccessEndpoint string `json:"access_endpoint"`
	Status         int16  `json:"status"`
}

func (q *Queries) CreateSandboxTool(ctx context.Context, arg CreateSandboxToolParams) (SandboxTool, error) {
	row := q.db.QueryRow(ctx, createSandboxTool,
		arg.ID,
		arg.TenantID,
		arg.SandboxID,
		arg.ToolID,
		arg.AccessEndpoint,
		arg.Status,
	)
	var i SandboxTool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SandboxID,
		&i.ToolID,
		&i.AccessEndpoint,
		&i.Status,
	)
	return i, err
}

const createTool = `-- name: CreateTool :one
INSERT INTO tool (id, code, name, kind, image_url, port, eco_tags, resource_spec, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, name, kind, image_url, port, eco_tags, resource_spec, status, created_at, updated_at
`

type CreateToolParams struct {
	ID           int64       `json:"id"`
	Code         string      `json:"code"`
	Name         string      `json:"name"`
	Kind         int16       `json:"kind"`
	ImageUrl     pgtype.Text `json:"image_url"`
	Port         pgtype.Int4 `json:"port"`
	EcoTags      string      `json:"eco_tags"`
	ResourceSpec []byte      `json:"resource_spec"`
	Status       int16       `json:"status"`
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, createTool,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Kind,
		arg.ImageUrl,
		arg.Port,
		arg.EcoTags,
		arg.ResourceSpec,
		arg.Status,
	)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.ImageUrl,
		&i.Port,
		&i.EcoTags,
		&i.ResourceSpec,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const destroySandbox = `-- name: DestroySandbox :one
UPDATE sandbox SET status = 6 WHERE id = $1 AND status = 5
RETURNING id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_script_ref, snapshot_ref, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
`

func (q *Queries) DestroySandbox(ctx context.Context, id int64) (Sandbox, error) {
	row := q.db.QueryRow(ctx, destroySandbox, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultRuntimeImage = `-- name: GetDefaultRuntimeImage :one
SELECT id, runtime_id, image_url, version, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at FROM runtime_image WHERE runtime_id = $1 AND is_default = true
`

func (q *Queries) GetDefaultRuntimeImage(ctx context.Context, runtimeID int64) (RuntimeImage, error) {
	row := q.db.QueryRow(ctx, getDefaultRuntimeImage, runtimeID)
	var i RuntimeImage
	err := row.Scan(
		&i.ID,
		&i.RuntimeID,
		&i.ImageUrl,
		&i.Version,
		&i.Prepulled,
		&i.PrepullStatus,
		&i.PrepullDetail,
		&i.PrepulledAt,
		&i.GenesisBaked,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getRuntimeByCode = `-- name: GetRuntimeByCode :one
SELECT id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at FROM runtime WHERE code = $1
`

func (q *Queries) GetRuntimeByCode(ctx context.Context, code string) (Runtime, error) {
	row := q.db.QueryRow(ctx, getRuntimeByCode, code)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Eco,
		&i.AdapterLevel,
		&i.AdapterSpec,
		&i.CapabilityImpl,
		&i.PluginRef,
		&i.SelftestStatus,
		&i.SelftestDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeByID = `-- name: GetRuntimeByID :one
SELECT id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at FROM runtime WHERE id = $1
`

func (q *Queries) GetRuntimeByID(ctx context.Context, id int64) (Runtime, error) {
	row := q.db.QueryRow(ctx, getRuntimeByID, id)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Eco,
		&i.AdapterLevel,
		&i.AdapterSpec,
		&i.CapabilityImpl,
		&i.PluginRef,
		&i.SelftestStatus,
		&i.SelftestDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeImage = `-- name: GetRuntimeImage :one
SELECT id, runtime_id, image_url, version, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at FROM runtime_image WHERE id = $1 AND runtime_id = $2
`

type GetRuntimeImageParams struct {
	ID        int64 `json:"id"`
	RuntimeID int64 `json:"runtime_id"`
}

func (q *Queries) GetRuntimeImage(ctx context.Context, arg GetRuntimeImageParams) (RuntimeImage, error) {
	row := q.db.QueryRow(ctx, getRuntimeImage, arg.ID, arg.RuntimeID)
	var i RuntimeImage
	err := row.Scan(
		&i.ID,
		&i.RuntimeID,
		&i.ImageUrl,
		&i.Version,
		&i.Prepulled,
		&i.PrepullStatus,
		&i.PrepullDetail,
		&i.PrepulledAt,
		&i.GenesisBaked,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getRuntimeImageByVersion = `-- name: GetRuntimeImageByVersion :one
SELECT id, runtime_id, image_url, version, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at FROM runtime_image WHERE runtime_id = $1 AND version = $2
`

type GetRuntimeImageByVersionParams struct {
	RuntimeID int64  `json:"runtime_id"`
	Version   string `json:"version"`
}

func (q *Queries) GetRuntimeImageByVersion(ctx context.Context, arg GetRuntimeImageByVersionParams) (RuntimeImage, error) {
	row := q.db.QueryRow(ctx, getRuntimeImageByVersion, arg.RuntimeID, arg.Version)
	var i RuntimeImage
	err := row.Scan(
		&i.ID,
		&i.RuntimeID,
		&i.ImageUrl,
		&i.Version,
		&i.Prepulled,
		&i.PrepullStatus,
		&i.PrepullDetail,
		&i.PrepulledAt,
		&i.GenesisBaked,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getSandboxByID = `-- name: GetSandboxByID :one
SELECT id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_script_ref, snapshot_ref, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at FROM sandbox WHERE id = $1
`

func (q *Queries) GetSandboxByID(ctx context.Context, id int64) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxByID, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSandboxToolForProxy = `-- name: GetSandboxToolForProxy :one
SELECT st.id, st.tenant_id, st.sandbox_id, st.tool_id, st.access_endpoint, st.status, t.code AS tool_code, t.name AS tool_name, t.kind AS tool_kind
FROM sandbox_tool st
JOIN tool t ON t.id = st.tool_id
WHERE st.sandbox_id = $1 AND t.code = $2 AND st.status = 1 AND t.status = 1
`

type GetSandboxToolForProxyParams struct {
	SandboxID int64  `json:"sandbox_id"`
	Code      string `json:"code"`
}

type GetSandboxToolForProxyRow struct {
	ID             int64  `json:"id"`
	TenantID       int64  `json:"tenant_id"`
	SandboxID      int64  `json:"sandbox_id"`
	ToolID         int64  `json:"tool_id"`
	AccessEndpoint string `json:"access_endpoint"`
	Status         int16  `json:"status"`
	ToolCode       string `json:"tool_code"`
	ToolName       string `json:"tool_name"`
	ToolKind       int16  `json:"tool_kind"`
}

func (q *Queries) GetSandboxToolForProxy(ctx context.Context, arg GetSandboxToolForProxyParams) (GetSandboxToolForProxyRow, error) {
	row := q.db.QueryRow(ctx, getSandboxToolForProxy, arg.SandboxID, arg.Code)
	var i GetSandboxToolForProxyRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SandboxID,
		&i.ToolID,
		&i.AccessEndpoint,
		&i.Status,
		&i.ToolCode,
		&i.ToolName,
		&i.ToolKind,
	)
	return i, err
}

const getTenantQuota = `-- name: GetTenantQuota :one
SELECT tenant_id, max_concurrent_sandbox, max_cpu, max_memory_mb, idle_timeout_min, max_lifetime_min, max_keepalive_min, max_snapshot_retention_min, updated_at FROM tenant_quota WHERE tenant_id = $1
`

func (q *Queries) GetTenantQuota(ctx context.Context, tenantID int64) (TenantQuotum, error) {
	row := q.db.QueryRow(ctx, getTenantQuota, tenantID)
	var i TenantQuotum
	err := row.Scan(
		&i.TenantID,
		&i.MaxConcurrentSandbox,
		&i.MaxCpu,
		&i.MaxMemoryMb,
		&i.IdleTimeoutMin,
		&i.MaxLifetimeMin,
		&i.MaxKeepaliveMin,
		&i.MaxSnapshotRetentionMin,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolByCode = `-- name: GetToolByCode :one
SELECT id, code, name, kind, image_url, port, eco_tags, resource_spec, status, created_at, updated_at FROM tool WHERE code = $1 AND status = 1
`

func (q *Queries) GetToolByCode(ctx context.Context, code string) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolByCode, code)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.ImageUrl,
		&i.Port,
		&i.EcoTags,
		&i.ResourceSpec,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSandboxResourceSpecs = `-- name: ListActiveSandboxResourceSpecs :many
SELECT
    s.id AS sandbox_id,
    r.adapter_spec AS runtime_adapter_spec,
    t.id AS tool_id,
    t.code AS tool_code,
    t.name AS tool_name,
    t.kind AS tool_kind,
    t.image_url AS tool_image_url,
    t.port AS tool_port,
    t.eco_tags AS tool_eco_tags,
    t.resource_spec AS tool_resource_spec
FROM sandbox s
JOIN runtime r ON r.id = s.runtime_id
LEFT JOIN sandbox_tool st ON st.sandbox_id = s.id
LEFT JOIN tool t ON t.id = st.tool_id
WHERE s.status IN (1,2,3,4)
ORDER BY s.id
`

type ListActiveSandboxResourceSpecsRow struct {
	SandboxID          int64       `json:"sandbox_id"`
	RuntimeAdapterSpec []byte      `json:"runtime_adapter_spec"`
	ToolID             pgtype.Int8 `json:"tool_id"`
	ToolCode           pgtype.Text `json:"tool_code"`
	ToolName           pgtype.Text `json:"tool_name"`
	ToolKind           pgtype.Int2 `json:"tool_kind"`
	ToolImageUrl       pgtype.Text `json:"tool_image_url"`
	ToolPort           pgtype.Int4 `json:"tool_port"`
	ToolEcoTags        pgtype.Text `json:"tool_eco_tags"`
	ToolResourceSpec   []byte      `json:"tool_resource_spec"`
}

func (q *Queries) ListActiveSandboxResourceSpecs(ctx context.Context) ([]ListActiveSandboxResourceSpecsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSandboxResourceSpecs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSandboxResourceSpecsRow{}
	for rows.Next() {
		var i ListActiveSandboxResourceSpecsRow
		if err := rows.Scan(
			&i.SandboxID,
			&i.RuntimeAdapterSpec,
			&i.ToolID,
			&i.ToolCode,
			&i.ToolName,
			&i.ToolKind,
			&i.ToolImageUrl,
			&i.ToolPort,
			&i.ToolEcoTags,
			&i.ToolResourceSpec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimes = `-- name: ListRuntimes :many
SELECT id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at FROM runtime
WHERE ($3::SMALLINT IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRuntimesParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Int2 `json:"status"`
}

func (q *Queries) ListRuntimes(ctx context.Context, arg ListRuntimesParams) ([]Runtime, error) {
	rows, err := q.db.Query(ctx, listRuntimes, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Runtime{}
	for rows.Next() {
		var i Runtime
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Eco,
			&i.AdapterLevel,
			&i.AdapterSpec,
			&i.CapabilityImpl,
			&i.PluginRef,
			&i.SelftestStatus,
			&i.SelftestDetail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxEvents = `-- name: ListSandboxEvents :many
SELECT id, tenant_id, sandbox_id, event_type, detail, created_at FROM sandbox_event WHERE sandbox_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListSandboxEventsParams struct {
	SandboxID int64 `json:"sandbox_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListSandboxEvents(ctx context.Context, arg ListSandboxEventsParams) ([]SandboxEvent, error) {
	rows, err := q.db.Query(ctx, listSandboxEvents, arg.SandboxID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SandboxEvent{}
	for rows.Next() {
		var i SandboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SandboxID,
			&i.EventType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxTools = `-- name: ListSandboxTools :many
SELECT st.id, st.tenant_id, st.sandbox_id, st.tool_id, st.access_endpoint, st.status, t.code AS tool_code, t.name AS tool_name, t.kind AS tool_kind
FROM sandbox_tool st
JOIN tool t ON t.id = st.tool_id
WHERE st.sandbox_id = $1
ORDER BY t.code
`

type ListSandboxToolsRow struct {
	ID             int64  `json:"id"`
	TenantID       int64  `json:"tenant_id"`
	SandboxID      int64  `json:"sandbox_id"`
	ToolID         int64  `json:"tool_id"`
	AccessEndpoint string `json:"access_endpoint"`
	Status         int16  `json:"status"`
	ToolCode       string `json:"tool_code"`
	ToolName       string `json:"tool_name"`
	ToolKind       int16  `json:"tool_kind"`
}

func (q *Queries) ListSandboxTools(ctx context.Context, sandboxID int64) ([]ListSandboxToolsRow, error) {
	rows, err := q.db.Query(ctx, listSandboxTools, sandboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSandboxToolsRow{}
	for rows.Next() {
		var i ListSandboxToolsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SandboxID,
			&i.ToolID,
			&i.AccessEndpoint,
			&i.Status,
			&i.ToolCode,
			&i.ToolName,
			&i.ToolKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesBySourceRef = `-- name: ListSandboxesBySourceRef :many
SELECT id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_script_ref, snapshot_ref, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at FROM sandbox WHERE source_ref = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesBySourceRef(ctx context.Context, sourceRef string) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesBySourceRef, sourceRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuntimeID,
			&i.ImageID,
			&i.Namespace,
			&i.SourceRef,
			&i.OwnerAccountID,
			&i.Phase,
			&i.Status,
			&i.KeepAlive,
			&i.SnapshotEnabled,
			&i.CodeStorageKey,
			&i.CodeHash,
			&i.InitScriptRef,
			&i.SnapshotRef,
			&i.SnapshotCreatedAt,
			&i.SnapshotExpireAt,
			&i.KeepAliveUntil,
			&i.LastActiveAt,
			&i.ExpireAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTools = `-- name: ListTools :many
SELECT id, code, name, kind, image_url, port, eco_tags, resource_spec, status, created_at, updated_at FROM tool
WHERE ($3::SMALLINT IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListToolsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Int2 `json:"status"`
}

func (q *Queries) ListTools(ctx context.Context, arg ListToolsParams) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listTools, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tool{}
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.ImageUrl,
			&i.Port,
			&i.EcoTags,
			&i.ResourceSpec,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSandboxActive = `-- name: MarkSandboxActive :exec
UPDATE sandbox SET status = 3, last_active_at = now() WHERE id = $1 AND status IN (2,3,4)
`

func (q *Queries) MarkSandboxActive(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSandboxActive, id)
	return err
}

const recycleSandbox = `-- name: RecycleSandbox :one
UPDATE sandbox SET status = 5 WHERE id = $1 AND status NOT IN (5,6)
RETURNING id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_script_ref, snapshot_ref, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
`

func (q *Queries) RecycleSandbox(ctx context.Context, id int64) (Sandbox, error) {
	row := q.db.QueryRow(ctx, recycleSandbox, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRuntime = `-- name: UpdateRuntime :one
UPDATE runtime
SET name = $2, eco = $3, adapter_level = $4, adapter_spec = $5,
    capability_impl = $6, plugin_ref = $7, status = $8
WHERE id = $1
RETURNING id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at
`

type UpdateRuntimeParams struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	Eco            string      `json:"eco"`
	AdapterLevel   int16       `json:"adapter_level"`
	AdapterSpec    []byte      `json:"adapter_spec"`
	CapabilityImpl pgtype.Text `json:"capability_impl"`
	PluginRef      pgtype.Text `json:"plugin_ref"`
	Status         int16       `json:"status"`
}

func (q *Queries) UpdateRuntime(ctx context.Context, arg UpdateRuntimeParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, updateRuntime,
		arg.ID,
		arg.Name,
		arg.Eco,
		arg.AdapterLevel,
		arg.AdapterSpec,
		arg.CapabilityImpl,
		arg.PluginRef,
		arg.Status,
	)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Eco,
		&i.AdapterLevel,
		&i.AdapterSpec,
		&i.CapabilityImpl,
		&i.PluginRef,
		&i.SelftestStatus,
		&i.SelftestDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRuntimeImagePrepull = `-- name: UpdateRuntimeImagePrepull :one
UPDATE runtime_image
SET prepulled = $3,
    prepull_status = $4,
    prepull_detail = $5,
    prepulled_at = $6
WHERE id = $1 AND runtime_id = $2
RETURNING id, runtime_id, image_url, version, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at
`

type UpdateRuntimeImagePrepullParams struct {
	ID            int64              `json:"id"`
	RuntimeID     int64              `json:"runtime_id"`
	Prepulled     bool               `json:"prepulled"`
	PrepullStatus int16              `json:"prepull_status"`
	PrepullDetail []byte             `json:"prepull_detail"`
	PrepulledAt   pgtype.Timestamptz `json:"prepulled_at"`
}

func (q *Queries) UpdateRuntimeImagePrepull(ctx context.Context, arg UpdateRuntimeImagePrepullParams) (RuntimeImage, error) {
	row := q.db.QueryRow(ctx, updateRuntimeImagePrepull,
		arg.ID,
		arg.RuntimeID,
		arg.Prepulled,
		arg.PrepullStatus,
		arg.PrepullDetail,
		arg.PrepulledAt,
	)
	var i RuntimeImage
	err := row.Scan(
		&i.ID,
		&i.RuntimeID,
		&i.ImageUrl,
		&i.Version,
		&i.Prepulled,
		&i.PrepullStatus,
		&i.PrepullDetail,
		&i.PrepulledAt,
		&i.GenesisBaked,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updateRuntimeSelftest = `-- name: UpdateRuntimeSelftest :one
UPDATE runtime SET selftest_status = $2, selftest_detail = $3, status = $4
WHERE id = $1
RETURNING id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at
`

type UpdateRuntimeSelftestParams struct {
	ID             int64  `json:"id"`
	SelftestStatus int16  `json:"selftest_status"`
	SelftestDetail []byte `json:"selftest_detail"`
	Status         int16  `json:"status"`
}

func (q *Queries) UpdateRuntimeSelftest(ctx context.Context, arg UpdateRuntimeSelftestParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, updateRuntimeSelftest,
		arg.ID,
		arg.SelftestStatus,
		arg.SelftestDetail,
		arg.Status,
	)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Eco,
		&i.AdapterLevel,
		&i.AdapterSpec,
		&i.CapabilityImpl,
		&i.PluginRef,
		&i.SelftestStatus,
		&i.SelftestDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSandboxCodeHash = `-- name: UpdateSandboxCodeHash :one
UPDATE sandbox SET code_hash = $2 WHERE id = $1 RETURNING id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_script_ref, snapshot_ref, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
`

type UpdateSandboxCodeHashParams struct {
	ID       int64       `json:"id"`
	CodeHash pgtype.Text `json:"code_hash"`
}

func (q *Queries) UpdateSandboxCodeHash(ctx context.Context, arg UpdateSandboxCodeHashParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, updateSandboxCodeHash, arg.ID, arg.CodeHash)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSandboxPhaseStatus = `-- name: UpdateSandboxPhaseStatus :one
UPDATE sandbox SET phase = $2, status = $3 WHERE id = $1 RETURNING id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_script_ref, snapshot_ref, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
`

type UpdateSandboxPhaseStatusParams struct {
	ID     int64 `json:"id"`
	Phase  int16 `json:"phase"`
	Status int16 `json:"status"`
}

func (q *Queries) UpdateSandboxPhaseStatus(ctx context.Context, arg UpdateSandboxPhaseStatusParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, updateSandboxPhaseStatus, arg.ID, arg.Phase, arg.Status)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSandboxSnapshot = `-- name: UpdateSandboxSnapshot :one
UPDATE sandbox
SET snapshot_ref = $2,
    snapshot_created_at = $3,
    snapshot_expire_at = $4
WHERE id = $1
RETURNING id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_script_ref, snapshot_ref, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
`

type UpdateSandboxSnapshotParams struct {
	ID                int64              `json:"id"`
	SnapshotRef       pgtype.Text        `json:"snapshot_ref"`
	SnapshotCreatedAt pgtype.Timestamptz `json:"snapshot_created_at"`
	SnapshotExpireAt  pgtype.Timestamptz `json:"snapshot_expire_at"`
}

func (q *Queries) UpdateSandboxSnapshot(ctx context.Context, arg UpdateSandboxSnapshotParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, updateSandboxSnapshot,
		arg.ID,
		arg.SnapshotRef,
		arg.SnapshotCreatedAt,
		arg.SnapshotExpireAt,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantQuota = `-- name: UpsertTenantQuota :one

INSERT INTO tenant_quota (tenant_id, max_concurrent_sandbox, max_cpu, max_memory_mb, idle_timeout_min, max_lifetime_min, max_keepalive_min, max_snapshot_retention_min)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (tenant_id) DO UPDATE
SET max_concurrent_sandbox = EXCLUDED.max_concurrent_sandbox,
    max_cpu = EXCLUDED.max_cpu,
    max_memory_mb = EXCLUDED.max_memory_mb,
    idle_timeout_min = EXCLUDED.idle_timeout_min,
    max_lifetime_min = EXCLUDED.max_lifetime_min,
    max_keepalive_min = EXCLUDED.max_keepalive_min,
    max_snapshot_retention_min = EXCLUDED.max_snapshot_retention_min,
    updated_at = now()
RETURNING tenant_id, max_concurrent_sandbox, max_cpu, max_memory_mb, idle_timeout_min, max_lifetime_min, max_keepalive_min, max_snapshot_retention_min, updated_at
`

type UpsertTenantQuotaParams struct {
	TenantID                int64 `json:"tenant_id"`
	MaxConcurrentSandbox    int32 `json:"max_concurrent_sandbox"`
	MaxCpu                  int32 `json:"max_cpu"`
	MaxMemoryMb             int32 `json:"max_memory_mb"`
	IdleTimeoutMin          int32 `json:"idle_timeout_min"`
	MaxLifetimeMin          int32 `json:"max_lifetime_min"`
	MaxKeepaliveMin         int32 `json:"max_keepalive_min"`
	MaxSnapshotRetentionMin int32 `json:"max_snapshot_retention_min"`
}

// ============================================================
// tenant_quota
// ============================================================
func (q *Queries) UpsertTenantQuota(ctx context.Context, arg UpsertTenantQuotaParams) (TenantQuotum, error) {
	row := q.db.QueryRow(ctx, upsertTenantQuota,
		arg.TenantID,
		arg.MaxConcurrentSandbox,
		arg.MaxCpu,
		arg.MaxMemoryMb,
		arg.IdleTimeoutMin,
		arg.MaxLifetimeMin,
		arg.MaxKeepaliveMin,
		arg.MaxSnapshotRetentionMin,
	)
	var i TenantQuotum
	err := row.Scan(
		&i.TenantID,
		&i.MaxConcurrentSandbox,
		&i.MaxCpu,
		&i.MaxMemoryMb,
		&i.IdleTimeoutMin,
		&i.MaxLifetimeMin,
		&i.MaxKeepaliveMin,
		&i.MaxSnapshotRetentionMin,
		&i.UpdatedAt,
	)
	return i, err
}
