// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sandbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingSandboxRecycleOutbox = `-- name: ClaimPendingSandboxRecycleOutbox :many
UPDATE sandbox_recycle_outbox
SET status = 2, retry_count = retry_count + 1, updated_at = now()
WHERE id IN (
    SELECT id
    FROM sandbox_recycle_outbox
    WHERE status IN (1, 4) OR (status = 2 AND updated_at <= $1::timestamptz)
    ORDER BY created_at ASC, id ASC
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, tenant_id, sandbox_id, source_ref, owner_account_id, reason, trace_id, recycled_at, status, retry_count, last_error, created_at, updated_at
`

type ClaimPendingSandboxRecycleOutboxParams struct {
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
	PageLimit   int32              `json:"page_limit"`
}

func (q *Queries) ClaimPendingSandboxRecycleOutbox(ctx context.Context, arg ClaimPendingSandboxRecycleOutboxParams) ([]SandboxRecycleOutbox, error) {
	rows, err := q.db.Query(ctx, claimPendingSandboxRecycleOutbox, arg.StaleBefore, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SandboxRecycleOutbox{}
	for rows.Next() {
		var i SandboxRecycleOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SandboxID,
			&i.SourceRef,
			&i.OwnerAccountID,
			&i.Reason,
			&i.TraceID,
			&i.RecycledAt,
			&i.Status,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveSandboxes = `-- name: CountActiveSandboxes :one
SELECT COUNT(*)::bigint
FROM sandbox
WHERE tenant_id = $1 AND status IN (1, 2, 3, 4, 7, 8)
`

func (q *Queries) CountActiveSandboxes(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSandboxes, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createRuntimeImage = `-- name: CreateRuntimeImage :one
INSERT INTO runtime_image (id, runtime_id, image_url, version, status, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at)
VALUES ($1, $2, $3, $4, 1, false, 1, '{}'::jsonb, NULL, $5, $6, now())
RETURNING id, runtime_id, image_url, version, status, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at
`

type CreateRuntimeImageParams struct {
	ID           int64  `json:"id"`
	RuntimeID    int64  `json:"runtime_id"`
	ImageUrl     string `json:"image_url"`
	Version      string `json:"version"`
	GenesisBaked bool   `json:"genesis_baked"`
	IsDefault    bool   `json:"is_default"`
}

func (q *Queries) CreateRuntimeImage(ctx context.Context, arg CreateRuntimeImageParams) (RuntimeImage, error) {
	row := q.db.QueryRow(ctx, createRuntimeImage,
		arg.ID,
		arg.RuntimeID,
		arg.ImageUrl,
		arg.Version,
		arg.GenesisBaked,
		arg.IsDefault,
	)
	var i RuntimeImage
	err := row.Scan(
		&i.ID,
		&i.RuntimeID,
		&i.ImageUrl,
		&i.Version,
		&i.Status,
		&i.Prepulled,
		&i.PrepullStatus,
		&i.PrepullDetail,
		&i.PrepulledAt,
		&i.GenesisBaked,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createSandbox = `-- name: CreateSandbox :one
INSERT INTO sandbox (
    id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status,
    keep_alive, snapshot_enabled, code_storage_key, code_hash, init_code_ref, init_script_ref, snapshot_ref, snapshot_domains,
    snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, now(), $21, now(), now()
)
RETURNING id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_code_ref, init_script_ref, snapshot_ref, snapshot_domains, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
`

type CreateSandboxParams struct {
	ID                int64              `json:"id"`
	TenantID          int64              `json:"tenant_id"`
	RuntimeID         int64              `json:"runtime_id"`
	ImageID           int64              `json:"image_id"`
	Namespace         string             `json:"namespace"`
	SourceRef         string             `json:"source_ref"`
	OwnerAccountID    int64              `json:"owner_account_id"`
	Phase             int16              `json:"phase"`
	Status            int16              `json:"status"`
	KeepAlive         bool               `json:"keep_alive"`
	SnapshotEnabled   bool               `json:"snapshot_enabled"`
	CodeStorageKey    string             `json:"code_storage_key"`
	CodeHash          pgtype.Text        `json:"code_hash"`
	InitCodeRef       pgtype.Text        `json:"init_code_ref"`
	InitScriptRef     pgtype.Text        `json:"init_script_ref"`
	SnapshotRef       pgtype.Text        `json:"snapshot_ref"`
	SnapshotDomains   []byte             `json:"snapshot_domains"`
	SnapshotCreatedAt pgtype.Timestamptz `json:"snapshot_created_at"`
	SnapshotExpireAt  pgtype.Timestamptz `json:"snapshot_expire_at"`
	KeepAliveUntil    pgtype.Timestamptz `json:"keep_alive_until"`
	ExpireAt          pgtype.Timestamptz `json:"expire_at"`
}

func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, createSandbox,
		arg.ID,
		arg.TenantID,
		arg.RuntimeID,
		arg.ImageID,
		arg.Namespace,
		arg.SourceRef,
		arg.OwnerAccountID,
		arg.Phase,
		arg.Status,
		arg.KeepAlive,
		arg.SnapshotEnabled,
		arg.CodeStorageKey,
		arg.CodeHash,
		arg.InitCodeRef,
		arg.InitScriptRef,
		arg.SnapshotRef,
		arg.SnapshotDomains,
		arg.SnapshotCreatedAt,
		arg.SnapshotExpireAt,
		arg.KeepAliveUntil,
		arg.ExpireAt,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitCodeRef,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotDomains,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSandboxEvent = `-- name: CreateSandboxEvent :one
INSERT INTO sandbox_event (id, tenant_id, sandbox_id, event_type, detail, created_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, tenant_id, sandbox_id, event_type, detail, created_at
`

type CreateSandboxEventParams struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	SandboxID int64  `json:"sandbox_id"`
	EventType string `json:"event_type"`
	Detail    []byte `json:"detail"`
}

func (q *Queries) CreateSandboxEvent(ctx context.Context, arg CreateSandboxEventParams) (SandboxEvent, error) {
	row := q.db.QueryRow(ctx, createSandboxEvent,
		arg.ID,
		arg.TenantID,
		arg.SandboxID,
		arg.EventType,
		arg.Detail,
	)
	var i SandboxEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SandboxID,
		&i.EventType,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const createSandboxRecycleOutbox = `-- name: CreateSandboxRecycleOutbox :one
INSERT INTO sandbox_recycle_outbox (id, tenant_id, sandbox_id, source_ref, owner_account_id, reason, trace_id, recycled_at, status, retry_count, last_error, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 1, 0, NULL, now(), now())
RETURNING id, tenant_id, sandbox_id, source_ref, owner_account_id, reason, trace_id, recycled_at, status, retry_count, last_error, created_at, updated_at
`

type CreateSandboxRecycleOutboxParams struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	SandboxID      int64              `json:"sandbox_id"`
	SourceRef      string             `json:"source_ref"`
	OwnerAccountID int64              `json:"owner_account_id"`
	Reason         string             `json:"reason"`
	TraceID        string             `json:"trace_id"`
	RecycledAt     pgtype.Timestamptz `json:"recycled_at"`
}

func (q *Queries) CreateSandboxRecycleOutbox(ctx context.Context, arg CreateSandboxRecycleOutboxParams) (SandboxRecycleOutbox, error) {
	row := q.db.QueryRow(ctx, createSandboxRecycleOutbox,
		arg.ID,
		arg.TenantID,
		arg.SandboxID,
		arg.SourceRef,
		arg.OwnerAccountID,
		arg.Reason,
		arg.TraceID,
		arg.RecycledAt,
	)
	var i SandboxRecycleOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SandboxID,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Reason,
		&i.TraceID,
		&i.RecycledAt,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSandboxTool = `-- name: CreateSandboxTool :one
INSERT INTO sandbox_tool (id, tenant_id, sandbox_id, tool_id, access_endpoint, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, sandbox_id, tool_id, access_endpoint, status
`

type CreateSandboxToolParams struct {
	ID             int64  `json:"id"`
	TenantID       int64  `json:"tenant_id"`
	SandboxID      int64  `json:"sandbox_id"`
	ToolID         int64  `json:"tool_id"`
	AccessEndpoint string `json:"access_endpoint"`
	Status         int16  `json:"status"`
}

func (q *Queries) CreateSandboxTool(ctx context.Context, arg CreateSandboxToolParams) (SandboxTool, error) {
	row := q.db.QueryRow(ctx, createSandboxTool,
		arg.ID,
		arg.TenantID,
		arg.SandboxID,
		arg.ToolID,
		arg.AccessEndpoint,
		arg.Status,
	)
	var i SandboxTool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SandboxID,
		&i.ToolID,
		&i.AccessEndpoint,
		&i.Status,
	)
	return i, err
}

const disableRuntimeImage = `-- name: DisableRuntimeImage :one
UPDATE runtime_image
SET status = 2,
    prepulled = false,
    prepull_status = 1,
    prepull_detail = $3,
    prepulled_at = NULL,
    is_default = false
WHERE id = $1 AND runtime_id = $2
RETURNING id, runtime_id, image_url, version, status, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at
`

type DisableRuntimeImageParams struct {
	ID            int64  `json:"id"`
	RuntimeID     int64  `json:"runtime_id"`
	PrepullDetail []byte `json:"prepull_detail"`
}

func (q *Queries) DisableRuntimeImage(ctx context.Context, arg DisableRuntimeImageParams) (RuntimeImage, error) {
	row := q.db.QueryRow(ctx, disableRuntimeImage, arg.ID, arg.RuntimeID, arg.PrepullDetail)
	var i RuntimeImage
	err := row.Scan(
		&i.ID,
		&i.RuntimeID,
		&i.ImageUrl,
		&i.Version,
		&i.Status,
		&i.Prepulled,
		&i.PrepullStatus,
		&i.PrepullDetail,
		&i.PrepulledAt,
		&i.GenesisBaked,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultRuntimeImage = `-- name: GetDefaultRuntimeImage :one
SELECT id, runtime_id, image_url, version, status, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at
FROM runtime_image
WHERE runtime_id = $1 AND is_default = true AND status = 1
`

func (q *Queries) GetDefaultRuntimeImage(ctx context.Context, runtimeID int64) (RuntimeImage, error) {
	row := q.db.QueryRow(ctx, getDefaultRuntimeImage, runtimeID)
	var i RuntimeImage
	err := row.Scan(
		&i.ID,
		&i.RuntimeID,
		&i.ImageUrl,
		&i.Version,
		&i.Status,
		&i.Prepulled,
		&i.PrepullStatus,
		&i.PrepullDetail,
		&i.PrepulledAt,
		&i.GenesisBaked,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getRuntimeByCode = `-- name: GetRuntimeByCode :one
SELECT id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at
FROM runtime
WHERE code = $1
`

func (q *Queries) GetRuntimeByCode(ctx context.Context, code string) (Runtime, error) {
	row := q.db.QueryRow(ctx, getRuntimeByCode, code)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Eco,
		&i.AdapterLevel,
		&i.AdapterSpec,
		&i.CapabilityImpl,
		&i.PluginRef,
		&i.SelftestStatus,
		&i.SelftestDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeByID = `-- name: GetRuntimeByID :one
SELECT id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at
FROM runtime
WHERE id = $1
`

func (q *Queries) GetRuntimeByID(ctx context.Context, id int64) (Runtime, error) {
	row := q.db.QueryRow(ctx, getRuntimeByID, id)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Eco,
		&i.AdapterLevel,
		&i.AdapterSpec,
		&i.CapabilityImpl,
		&i.PluginRef,
		&i.SelftestStatus,
		&i.SelftestDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeImageByID = `-- name: GetRuntimeImageByID :one
SELECT id, runtime_id, image_url, version, status, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at
FROM runtime_image
WHERE id = $1 AND runtime_id = $2
`

type GetRuntimeImageByIDParams struct {
	ID        int64 `json:"id"`
	RuntimeID int64 `json:"runtime_id"`
}

func (q *Queries) GetRuntimeImageByID(ctx context.Context, arg GetRuntimeImageByIDParams) (RuntimeImage, error) {
	row := q.db.QueryRow(ctx, getRuntimeImageByID, arg.ID, arg.RuntimeID)
	var i RuntimeImage
	err := row.Scan(
		&i.ID,
		&i.RuntimeID,
		&i.ImageUrl,
		&i.Version,
		&i.Status,
		&i.Prepulled,
		&i.PrepullStatus,
		&i.PrepullDetail,
		&i.PrepulledAt,
		&i.GenesisBaked,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getRuntimeImageByVersion = `-- name: GetRuntimeImageByVersion :one
SELECT id, runtime_id, image_url, version, status, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at
FROM runtime_image
WHERE runtime_id = $1 AND version = $2 AND status = 1
`

type GetRuntimeImageByVersionParams struct {
	RuntimeID int64  `json:"runtime_id"`
	Version   string `json:"version"`
}

func (q *Queries) GetRuntimeImageByVersion(ctx context.Context, arg GetRuntimeImageByVersionParams) (RuntimeImage, error) {
	row := q.db.QueryRow(ctx, getRuntimeImageByVersion, arg.RuntimeID, arg.Version)
	var i RuntimeImage
	err := row.Scan(
		&i.ID,
		&i.RuntimeID,
		&i.ImageUrl,
		&i.Version,
		&i.Status,
		&i.Prepulled,
		&i.PrepullStatus,
		&i.PrepullDetail,
		&i.PrepulledAt,
		&i.GenesisBaked,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getSandbox = `-- name: GetSandbox :one
SELECT id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_code_ref, init_script_ref, snapshot_ref, snapshot_domains, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
FROM sandbox
WHERE tenant_id = $1 AND id = $2
`

type GetSandboxParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetSandbox(ctx context.Context, arg GetSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandbox, arg.TenantID, arg.ID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitCodeRef,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotDomains,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantQuota = `-- name: GetTenantQuota :one
SELECT tenant_id, max_concurrent_sandbox, max_cpu, max_memory_mb, idle_timeout_min, max_lifetime_min, max_keepalive_min, max_snapshot_retention_min, updated_at
FROM tenant_quota
WHERE tenant_id = $1
`

func (q *Queries) GetTenantQuota(ctx context.Context, tenantID int64) (TenantQuotum, error) {
	row := q.db.QueryRow(ctx, getTenantQuota, tenantID)
	var i TenantQuotum
	err := row.Scan(
		&i.TenantID,
		&i.MaxConcurrentSandbox,
		&i.MaxCpu,
		&i.MaxMemoryMb,
		&i.IdleTimeoutMin,
		&i.MaxLifetimeMin,
		&i.MaxKeepaliveMin,
		&i.MaxSnapshotRetentionMin,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantQuotaForUpdate = `-- name: GetTenantQuotaForUpdate :one
SELECT tenant_id, max_concurrent_sandbox, max_cpu, max_memory_mb, idle_timeout_min, max_lifetime_min, max_keepalive_min, max_snapshot_retention_min, updated_at
FROM tenant_quota
WHERE tenant_id = $1
FOR UPDATE
`

func (q *Queries) GetTenantQuotaForUpdate(ctx context.Context, tenantID int64) (TenantQuotum, error) {
	row := q.db.QueryRow(ctx, getTenantQuotaForUpdate, tenantID)
	var i TenantQuotum
	err := row.Scan(
		&i.TenantID,
		&i.MaxConcurrentSandbox,
		&i.MaxCpu,
		&i.MaxMemoryMb,
		&i.IdleTimeoutMin,
		&i.MaxLifetimeMin,
		&i.MaxKeepaliveMin,
		&i.MaxSnapshotRetentionMin,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolByCode = `-- name: GetToolByCode :one
SELECT id, code, name, kind, eco_tags, resource_spec, status, created_at, updated_at
FROM tool
WHERE code = $1
`

func (q *Queries) GetToolByCode(ctx context.Context, code string) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolByCode, code)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.EcoTags,
		&i.ResourceSpec,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecycleCandidates = `-- name: ListRecycleCandidates :many
SELECT s.id, s.tenant_id, s.runtime_id, s.image_id, s.namespace, s.source_ref, s.owner_account_id, s.phase, s.status, s.keep_alive, s.snapshot_enabled, s.code_storage_key, s.code_hash, s.init_code_ref, s.init_script_ref, s.snapshot_ref, s.snapshot_domains, s.snapshot_created_at, s.snapshot_expire_at, s.keep_alive_until, s.last_active_at, s.expire_at, s.created_at, s.updated_at
FROM sandbox s
JOIN tenant_quota tq ON tq.tenant_id = s.tenant_id
WHERE s.status IN (4, 6)
   OR (s.status = 1 AND s.last_active_at <= $1)
   OR (s.status = 7 AND s.last_active_at <= $1)
   OR (s.status = 8 AND s.keep_alive = false AND s.last_active_at <= now() - make_interval(mins => tq.idle_timeout_min))
   OR (s.status IN (1, 2, 3, 7, 8) AND s.expire_at <= now())
   OR (s.status IN (1, 2, 3, 7, 8) AND s.keep_alive_until IS NOT NULL AND s.keep_alive_until <= now())
ORDER BY s.updated_at ASC, s.id ASC
LIMIT $2
`

type ListRecycleCandidatesParams struct {
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) ListRecycleCandidates(ctx context.Context, arg ListRecycleCandidatesParams) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listRecycleCandidates, arg.LastActiveAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuntimeID,
			&i.ImageID,
			&i.Namespace,
			&i.SourceRef,
			&i.OwnerAccountID,
			&i.Phase,
			&i.Status,
			&i.KeepAlive,
			&i.SnapshotEnabled,
			&i.CodeStorageKey,
			&i.CodeHash,
			&i.InitCodeRef,
			&i.InitScriptRef,
			&i.SnapshotRef,
			&i.SnapshotDomains,
			&i.SnapshotCreatedAt,
			&i.SnapshotExpireAt,
			&i.KeepAliveUntil,
			&i.LastActiveAt,
			&i.ExpireAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeImages = `-- name: ListRuntimeImages :many
SELECT id, runtime_id, image_url, version, status, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at
FROM runtime_image
WHERE runtime_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListRuntimeImages(ctx context.Context, runtimeID int64) ([]RuntimeImage, error) {
	rows, err := q.db.Query(ctx, listRuntimeImages, runtimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeImage{}
	for rows.Next() {
		var i RuntimeImage
		if err := rows.Scan(
			&i.ID,
			&i.RuntimeID,
			&i.ImageUrl,
			&i.Version,
			&i.Status,
			&i.Prepulled,
			&i.PrepullStatus,
			&i.PrepullDetail,
			&i.PrepulledAt,
			&i.GenesisBaked,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimes = `-- name: ListRuntimes :many
SELECT id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at
FROM runtime
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListRuntimes(ctx context.Context) ([]Runtime, error) {
	rows, err := q.db.Query(ctx, listRuntimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Runtime{}
	for rows.Next() {
		var i Runtime
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Eco,
			&i.AdapterLevel,
			&i.AdapterSpec,
			&i.CapabilityImpl,
			&i.PluginRef,
			&i.SelftestStatus,
			&i.SelftestDetail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxTools = `-- name: ListSandboxTools :many
SELECT st.id, st.tenant_id, st.sandbox_id, st.tool_id, st.access_endpoint, st.status,
       t.code, t.kind, t.resource_spec
FROM sandbox_tool st
JOIN tool t ON t.id = st.tool_id
WHERE st.tenant_id = $1 AND st.sandbox_id = $2
ORDER BY st.id
`

type ListSandboxToolsParams struct {
	TenantID  int64 `json:"tenant_id"`
	SandboxID int64 `json:"sandbox_id"`
}

type ListSandboxToolsRow struct {
	ID             int64  `json:"id"`
	TenantID       int64  `json:"tenant_id"`
	SandboxID      int64  `json:"sandbox_id"`
	ToolID         int64  `json:"tool_id"`
	AccessEndpoint string `json:"access_endpoint"`
	Status         int16  `json:"status"`
	Code           string `json:"code"`
	Kind           int16  `json:"kind"`
	ResourceSpec   []byte `json:"resource_spec"`
}

func (q *Queries) ListSandboxTools(ctx context.Context, arg ListSandboxToolsParams) ([]ListSandboxToolsRow, error) {
	rows, err := q.db.Query(ctx, listSandboxTools, arg.TenantID, arg.SandboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSandboxToolsRow{}
	for rows.Next() {
		var i ListSandboxToolsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SandboxID,
			&i.ToolID,
			&i.AccessEndpoint,
			&i.Status,
			&i.Code,
			&i.Kind,
			&i.ResourceSpec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesBySourceRef = `-- name: ListSandboxesBySourceRef :many
SELECT id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_code_ref, init_script_ref, snapshot_ref, snapshot_domains, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
FROM sandbox
WHERE tenant_id = $1 AND source_ref = $2 AND status <> 5
ORDER BY created_at DESC, id DESC
`

type ListSandboxesBySourceRefParams struct {
	TenantID  int64  `json:"tenant_id"`
	SourceRef string `json:"source_ref"`
}

func (q *Queries) ListSandboxesBySourceRef(ctx context.Context, arg ListSandboxesBySourceRefParams) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesBySourceRef, arg.TenantID, arg.SourceRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuntimeID,
			&i.ImageID,
			&i.Namespace,
			&i.SourceRef,
			&i.OwnerAccountID,
			&i.Phase,
			&i.Status,
			&i.KeepAlive,
			&i.SnapshotEnabled,
			&i.CodeStorageKey,
			&i.CodeHash,
			&i.InitCodeRef,
			&i.InitScriptRef,
			&i.SnapshotRef,
			&i.SnapshotDomains,
			&i.SnapshotCreatedAt,
			&i.SnapshotExpireAt,
			&i.KeepAliveUntil,
			&i.LastActiveAt,
			&i.ExpireAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotCleanupCandidates = `-- name: ListSnapshotCleanupCandidates :many
SELECT id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_code_ref, init_script_ref, snapshot_ref, snapshot_domains, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
FROM sandbox
WHERE status = 5 AND snapshot_expire_at IS NOT NULL AND snapshot_expire_at <= now()
ORDER BY snapshot_expire_at ASC, id ASC
LIMIT $1
`

func (q *Queries) ListSnapshotCleanupCandidates(ctx context.Context, limit int32) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSnapshotCleanupCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuntimeID,
			&i.ImageID,
			&i.Namespace,
			&i.SourceRef,
			&i.OwnerAccountID,
			&i.Phase,
			&i.Status,
			&i.KeepAlive,
			&i.SnapshotEnabled,
			&i.CodeStorageKey,
			&i.CodeHash,
			&i.InitCodeRef,
			&i.InitScriptRef,
			&i.SnapshotRef,
			&i.SnapshotDomains,
			&i.SnapshotCreatedAt,
			&i.SnapshotExpireAt,
			&i.KeepAliveUntil,
			&i.LastActiveAt,
			&i.ExpireAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTools = `-- name: ListTools :many
SELECT id, code, name, kind, eco_tags, resource_spec, status, created_at, updated_at
FROM tool
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tool{}
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.EcoTags,
			&i.ResourceSpec,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIdleSandboxes = `-- name: MarkIdleSandboxes :many
UPDATE sandbox s
SET status = 8, updated_at = now()
FROM tenant_quota tq
WHERE tq.tenant_id = s.tenant_id
  AND s.status = 2
  AND s.keep_alive = false
  AND s.last_active_at <= now() - make_interval(mins => tq.idle_timeout_min)
RETURNING s.id, s.tenant_id, s.runtime_id, s.image_id, s.namespace, s.source_ref, s.owner_account_id, s.phase, s.status, s.keep_alive, s.snapshot_enabled, s.code_storage_key, s.code_hash, s.init_code_ref, s.init_script_ref, s.snapshot_ref, s.snapshot_domains, s.snapshot_created_at, s.snapshot_expire_at, s.keep_alive_until, s.last_active_at, s.expire_at, s.created_at, s.updated_at
`

func (q *Queries) MarkIdleSandboxes(ctx context.Context) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, markIdleSandboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuntimeID,
			&i.ImageID,
			&i.Namespace,
			&i.SourceRef,
			&i.OwnerAccountID,
			&i.Phase,
			&i.Status,
			&i.KeepAlive,
			&i.SnapshotEnabled,
			&i.CodeStorageKey,
			&i.CodeHash,
			&i.InitCodeRef,
			&i.InitScriptRef,
			&i.SnapshotRef,
			&i.SnapshotDomains,
			&i.SnapshotCreatedAt,
			&i.SnapshotExpireAt,
			&i.KeepAliveUntil,
			&i.LastActiveAt,
			&i.ExpireAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOtherRuntimeImagesNotDefault = `-- name: MarkOtherRuntimeImagesNotDefault :exec
UPDATE runtime_image
SET is_default = false
WHERE runtime_id = $1 AND id <> $2
`

type MarkOtherRuntimeImagesNotDefaultParams struct {
	RuntimeID int64 `json:"runtime_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) MarkOtherRuntimeImagesNotDefault(ctx context.Context, arg MarkOtherRuntimeImagesNotDefaultParams) error {
	_, err := q.db.Exec(ctx, markOtherRuntimeImagesNotDefault, arg.RuntimeID, arg.ID)
	return err
}

const markSandboxActive = `-- name: MarkSandboxActive :one
UPDATE sandbox
SET last_active_at = now(),
    status = CASE WHEN status IN (7, 8) THEN 2 ELSE status END,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
  AND status IN (2, 7, 8)
RETURNING id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_code_ref, init_script_ref, snapshot_ref, snapshot_domains, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
`

type MarkSandboxActiveParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) MarkSandboxActive(ctx context.Context, arg MarkSandboxActiveParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, markSandboxActive, arg.TenantID, arg.ID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitCodeRef,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotDomains,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSandboxRecycleOutboxFailed = `-- name: MarkSandboxRecycleOutboxFailed :one
UPDATE sandbox_recycle_outbox
SET status = 4, last_error = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, sandbox_id, source_ref, owner_account_id, reason, trace_id, recycled_at, status, retry_count, last_error, created_at, updated_at
`

type MarkSandboxRecycleOutboxFailedParams struct {
	TenantID  int64       `json:"tenant_id"`
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkSandboxRecycleOutboxFailed(ctx context.Context, arg MarkSandboxRecycleOutboxFailedParams) (SandboxRecycleOutbox, error) {
	row := q.db.QueryRow(ctx, markSandboxRecycleOutboxFailed, arg.TenantID, arg.ID, arg.LastError)
	var i SandboxRecycleOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SandboxID,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Reason,
		&i.TraceID,
		&i.RecycledAt,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSandboxRecycleOutboxPublished = `-- name: MarkSandboxRecycleOutboxPublished :one
UPDATE sandbox_recycle_outbox
SET status = 3, last_error = NULL, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, sandbox_id, source_ref, owner_account_id, reason, trace_id, recycled_at, status, retry_count, last_error, created_at, updated_at
`

type MarkSandboxRecycleOutboxPublishedParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) MarkSandboxRecycleOutboxPublished(ctx context.Context, arg MarkSandboxRecycleOutboxPublishedParams) (SandboxRecycleOutbox, error) {
	row := q.db.QueryRow(ctx, markSandboxRecycleOutboxPublished, arg.TenantID, arg.ID)
	var i SandboxRecycleOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SandboxID,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Reason,
		&i.TraceID,
		&i.RecycledAt,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const statsByTenant = `-- name: StatsByTenant :one
SELECT
  COUNT(*) FILTER (WHERE s.status IN (1, 2, 3, 4, 7, 8))::bigint AS active_sandbox_count,
  tq.max_concurrent_sandbox,
  tq.max_cpu,
  tq.max_memory_mb,
  tq.idle_timeout_min,
  tq.max_lifetime_min,
  tq.max_keepalive_min,
  tq.max_snapshot_retention_min
FROM tenant_quota tq
LEFT JOIN sandbox s ON s.tenant_id = tq.tenant_id
WHERE tq.tenant_id = $1
GROUP BY tq.max_concurrent_sandbox, tq.max_cpu, tq.max_memory_mb, tq.idle_timeout_min, tq.max_lifetime_min, tq.max_keepalive_min, tq.max_snapshot_retention_min
`

type StatsByTenantRow struct {
	ActiveSandboxCount      int64 `json:"active_sandbox_count"`
	MaxConcurrentSandbox    int32 `json:"max_concurrent_sandbox"`
	MaxCpu                  int32 `json:"max_cpu"`
	MaxMemoryMb             int32 `json:"max_memory_mb"`
	IdleTimeoutMin          int32 `json:"idle_timeout_min"`
	MaxLifetimeMin          int32 `json:"max_lifetime_min"`
	MaxKeepaliveMin         int32 `json:"max_keepalive_min"`
	MaxSnapshotRetentionMin int32 `json:"max_snapshot_retention_min"`
}

func (q *Queries) StatsByTenant(ctx context.Context, tenantID int64) (StatsByTenantRow, error) {
	row := q.db.QueryRow(ctx, statsByTenant, tenantID)
	var i StatsByTenantRow
	err := row.Scan(
		&i.ActiveSandboxCount,
		&i.MaxConcurrentSandbox,
		&i.MaxCpu,
		&i.MaxMemoryMb,
		&i.IdleTimeoutMin,
		&i.MaxLifetimeMin,
		&i.MaxKeepaliveMin,
		&i.MaxSnapshotRetentionMin,
	)
	return i, err
}

const updateRuntimeImagePrepull = `-- name: UpdateRuntimeImagePrepull :one
UPDATE runtime_image
SET prepulled = $3, prepull_status = $4, prepull_detail = $5, prepulled_at = $6
WHERE id = $1 AND runtime_id = $2 AND status = 1
RETURNING id, runtime_id, image_url, version, status, prepulled, prepull_status, prepull_detail, prepulled_at, genesis_baked, is_default, created_at
`

type UpdateRuntimeImagePrepullParams struct {
	ID            int64              `json:"id"`
	RuntimeID     int64              `json:"runtime_id"`
	Prepulled     bool               `json:"prepulled"`
	PrepullStatus int16              `json:"prepull_status"`
	PrepullDetail []byte             `json:"prepull_detail"`
	PrepulledAt   pgtype.Timestamptz `json:"prepulled_at"`
}

func (q *Queries) UpdateRuntimeImagePrepull(ctx context.Context, arg UpdateRuntimeImagePrepullParams) (RuntimeImage, error) {
	row := q.db.QueryRow(ctx, updateRuntimeImagePrepull,
		arg.ID,
		arg.RuntimeID,
		arg.Prepulled,
		arg.PrepullStatus,
		arg.PrepullDetail,
		arg.PrepulledAt,
	)
	var i RuntimeImage
	err := row.Scan(
		&i.ID,
		&i.RuntimeID,
		&i.ImageUrl,
		&i.Version,
		&i.Status,
		&i.Prepulled,
		&i.PrepullStatus,
		&i.PrepullDetail,
		&i.PrepulledAt,
		&i.GenesisBaked,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updateRuntimeSelftest = `-- name: UpdateRuntimeSelftest :one
UPDATE runtime
SET selftest_status = $2, selftest_detail = $3, status = $4, updated_at = now()
WHERE id = $1
RETURNING id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at
`

type UpdateRuntimeSelftestParams struct {
	ID             int64  `json:"id"`
	SelftestStatus int16  `json:"selftest_status"`
	SelftestDetail []byte `json:"selftest_detail"`
	Status         int16  `json:"status"`
}

func (q *Queries) UpdateRuntimeSelftest(ctx context.Context, arg UpdateRuntimeSelftestParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, updateRuntimeSelftest,
		arg.ID,
		arg.SelftestStatus,
		arg.SelftestDetail,
		arg.Status,
	)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Eco,
		&i.AdapterLevel,
		&i.AdapterSpec,
		&i.CapabilityImpl,
		&i.PluginRef,
		&i.SelftestStatus,
		&i.SelftestDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSandboxCode = `-- name: UpdateSandboxCode :one
UPDATE sandbox
SET code_storage_key = $3, code_hash = $4, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_code_ref, init_script_ref, snapshot_ref, snapshot_domains, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
`

type UpdateSandboxCodeParams struct {
	TenantID       int64       `json:"tenant_id"`
	ID             int64       `json:"id"`
	CodeStorageKey string      `json:"code_storage_key"`
	CodeHash       pgtype.Text `json:"code_hash"`
}

func (q *Queries) UpdateSandboxCode(ctx context.Context, arg UpdateSandboxCodeParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, updateSandboxCode,
		arg.TenantID,
		arg.ID,
		arg.CodeStorageKey,
		arg.CodeHash,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitCodeRef,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotDomains,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSandboxPhaseStatus = `-- name: UpdateSandboxPhaseStatus :one
UPDATE sandbox
SET phase = $3, status = $4, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_code_ref, init_script_ref, snapshot_ref, snapshot_domains, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
`

type UpdateSandboxPhaseStatusParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
	Phase    int16 `json:"phase"`
	Status   int16 `json:"status"`
}

func (q *Queries) UpdateSandboxPhaseStatus(ctx context.Context, arg UpdateSandboxPhaseStatusParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, updateSandboxPhaseStatus,
		arg.TenantID,
		arg.ID,
		arg.Phase,
		arg.Status,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitCodeRef,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotDomains,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSandboxSnapshot = `-- name: UpdateSandboxSnapshot :one
UPDATE sandbox
SET snapshot_ref = $3, snapshot_domains = $4, snapshot_created_at = $5, snapshot_expire_at = $6, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, runtime_id, image_id, namespace, source_ref, owner_account_id, phase, status, keep_alive, snapshot_enabled, code_storage_key, code_hash, init_code_ref, init_script_ref, snapshot_ref, snapshot_domains, snapshot_created_at, snapshot_expire_at, keep_alive_until, last_active_at, expire_at, created_at, updated_at
`

type UpdateSandboxSnapshotParams struct {
	TenantID          int64              `json:"tenant_id"`
	ID                int64              `json:"id"`
	SnapshotRef       pgtype.Text        `json:"snapshot_ref"`
	SnapshotDomains   []byte             `json:"snapshot_domains"`
	SnapshotCreatedAt pgtype.Timestamptz `json:"snapshot_created_at"`
	SnapshotExpireAt  pgtype.Timestamptz `json:"snapshot_expire_at"`
}

func (q *Queries) UpdateSandboxSnapshot(ctx context.Context, arg UpdateSandboxSnapshotParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, updateSandboxSnapshot,
		arg.TenantID,
		arg.ID,
		arg.SnapshotRef,
		arg.SnapshotDomains,
		arg.SnapshotCreatedAt,
		arg.SnapshotExpireAt,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeID,
		&i.ImageID,
		&i.Namespace,
		&i.SourceRef,
		&i.OwnerAccountID,
		&i.Phase,
		&i.Status,
		&i.KeepAlive,
		&i.SnapshotEnabled,
		&i.CodeStorageKey,
		&i.CodeHash,
		&i.InitCodeRef,
		&i.InitScriptRef,
		&i.SnapshotRef,
		&i.SnapshotDomains,
		&i.SnapshotCreatedAt,
		&i.SnapshotExpireAt,
		&i.KeepAliveUntil,
		&i.LastActiveAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSandboxToolStatus = `-- name: UpdateSandboxToolStatus :one
UPDATE sandbox_tool
SET status = $4, access_endpoint = $5
WHERE tenant_id = $1 AND sandbox_id = $2 AND tool_id = $3
RETURNING id, tenant_id, sandbox_id, tool_id, access_endpoint, status
`

type UpdateSandboxToolStatusParams struct {
	TenantID       int64  `json:"tenant_id"`
	SandboxID      int64  `json:"sandbox_id"`
	ToolID         int64  `json:"tool_id"`
	Status         int16  `json:"status"`
	AccessEndpoint string `json:"access_endpoint"`
}

func (q *Queries) UpdateSandboxToolStatus(ctx context.Context, arg UpdateSandboxToolStatusParams) (SandboxTool, error) {
	row := q.db.QueryRow(ctx, updateSandboxToolStatus,
		arg.TenantID,
		arg.SandboxID,
		arg.ToolID,
		arg.Status,
		arg.AccessEndpoint,
	)
	var i SandboxTool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SandboxID,
		&i.ToolID,
		&i.AccessEndpoint,
		&i.Status,
	)
	return i, err
}

const upsertRuntime = `-- name: UpsertRuntime :one
INSERT INTO runtime (id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now(), now())
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    eco = EXCLUDED.eco,
    adapter_level = EXCLUDED.adapter_level,
    adapter_spec = EXCLUDED.adapter_spec,
    capability_impl = EXCLUDED.capability_impl,
    plugin_ref = EXCLUDED.plugin_ref,
    selftest_status = EXCLUDED.selftest_status,
    selftest_detail = EXCLUDED.selftest_detail,
    status = EXCLUDED.status,
    updated_at = now()
RETURNING id, code, name, eco, adapter_level, adapter_spec, capability_impl, plugin_ref, selftest_status, selftest_detail, status, created_at, updated_at
`

type UpsertRuntimeParams struct {
	ID             int64       `json:"id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	Eco            string      `json:"eco"`
	AdapterLevel   int16       `json:"adapter_level"`
	AdapterSpec    []byte      `json:"adapter_spec"`
	CapabilityImpl pgtype.Text `json:"capability_impl"`
	PluginRef      pgtype.Text `json:"plugin_ref"`
	SelftestStatus int16       `json:"selftest_status"`
	SelftestDetail []byte      `json:"selftest_detail"`
	Status         int16       `json:"status"`
}

func (q *Queries) UpsertRuntime(ctx context.Context, arg UpsertRuntimeParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, upsertRuntime,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Eco,
		arg.AdapterLevel,
		arg.AdapterSpec,
		arg.CapabilityImpl,
		arg.PluginRef,
		arg.SelftestStatus,
		arg.SelftestDetail,
		arg.Status,
	)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Eco,
		&i.AdapterLevel,
		&i.AdapterSpec,
		&i.CapabilityImpl,
		&i.PluginRef,
		&i.SelftestStatus,
		&i.SelftestDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantQuota = `-- name: UpsertTenantQuota :one
INSERT INTO tenant_quota (tenant_id, max_concurrent_sandbox, max_cpu, max_memory_mb, idle_timeout_min, max_lifetime_min, max_keepalive_min, max_snapshot_retention_min, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (tenant_id) DO UPDATE
SET max_concurrent_sandbox = EXCLUDED.max_concurrent_sandbox,
    max_cpu = EXCLUDED.max_cpu,
    max_memory_mb = EXCLUDED.max_memory_mb,
    idle_timeout_min = EXCLUDED.idle_timeout_min,
    max_lifetime_min = EXCLUDED.max_lifetime_min,
    max_keepalive_min = EXCLUDED.max_keepalive_min,
    max_snapshot_retention_min = EXCLUDED.max_snapshot_retention_min,
    updated_at = now()
RETURNING tenant_id, max_concurrent_sandbox, max_cpu, max_memory_mb, idle_timeout_min, max_lifetime_min, max_keepalive_min, max_snapshot_retention_min, updated_at
`

type UpsertTenantQuotaParams struct {
	TenantID                int64 `json:"tenant_id"`
	MaxConcurrentSandbox    int32 `json:"max_concurrent_sandbox"`
	MaxCpu                  int32 `json:"max_cpu"`
	MaxMemoryMb             int32 `json:"max_memory_mb"`
	IdleTimeoutMin          int32 `json:"idle_timeout_min"`
	MaxLifetimeMin          int32 `json:"max_lifetime_min"`
	MaxKeepaliveMin         int32 `json:"max_keepalive_min"`
	MaxSnapshotRetentionMin int32 `json:"max_snapshot_retention_min"`
}

func (q *Queries) UpsertTenantQuota(ctx context.Context, arg UpsertTenantQuotaParams) (TenantQuotum, error) {
	row := q.db.QueryRow(ctx, upsertTenantQuota,
		arg.TenantID,
		arg.MaxConcurrentSandbox,
		arg.MaxCpu,
		arg.MaxMemoryMb,
		arg.IdleTimeoutMin,
		arg.MaxLifetimeMin,
		arg.MaxKeepaliveMin,
		arg.MaxSnapshotRetentionMin,
	)
	var i TenantQuotum
	err := row.Scan(
		&i.TenantID,
		&i.MaxConcurrentSandbox,
		&i.MaxCpu,
		&i.MaxMemoryMb,
		&i.IdleTimeoutMin,
		&i.MaxLifetimeMin,
		&i.MaxKeepaliveMin,
		&i.MaxSnapshotRetentionMin,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTool = `-- name: UpsertTool :one
INSERT INTO tool (id, code, name, kind, eco_tags, resource_spec, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    kind = EXCLUDED.kind,
    eco_tags = EXCLUDED.eco_tags,
    resource_spec = EXCLUDED.resource_spec,
    status = EXCLUDED.status,
    updated_at = now()
RETURNING id, code, name, kind, eco_tags, resource_spec, status, created_at, updated_at
`

type UpsertToolParams struct {
	ID           int64  `json:"id"`
	Code         string `json:"code"`
	Name         string `json:"name"`
	Kind         int16  `json:"kind"`
	EcoTags      string `json:"eco_tags"`
	ResourceSpec []byte `json:"resource_spec"`
	Status       int16  `json:"status"`
}

func (q *Queries) UpsertTool(ctx context.Context, arg UpsertToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, upsertTool,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Kind,
		arg.EcoTags,
		arg.ResourceSpec,
		arg.Status,
	)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.EcoTags,
		&i.ResourceSpec,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
