// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	ClaimTransferTask(ctx context.Context, arg ClaimTransferTaskParams) (TransferTask, error)
	CompleteTransferTask(ctx context.Context, arg CompleteTransferTaskParams) (TransferTask, error)
	CountTransferTasks(ctx context.Context, arg CountTransferTasksParams) (int64, error)
	CreateTransferTask(ctx context.Context, arg CreateTransferTaskParams) (TransferTask, error)
	DeletePendingTransferTask(ctx context.Context, arg DeletePendingTransferTaskParams) error
	FailTransferTask(ctx context.Context, arg FailTransferTaskParams) (TransferTask, error)
	GetTransferTask(ctx context.Context, arg GetTransferTaskParams) (TransferTask, error)
	ListTransferTasks(ctx context.Context, arg ListTransferTasksParams) ([]TransferTask, error)
}

var _ Querier = (*Queries)(nil)
