// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimTransferTask = `-- name: ClaimTransferTask :one
WITH expire_exhausted AS (
    UPDATE transfer_task AS task
    SET status = 'failed',
        last_error = '执行租约已过期',
        updated_at = $1::timestamptz,
        completed_at = $1::timestamptz,
        next_attempt_after = NULL,
        lease_token = '',
        lease_until = NULL
    WHERE task.tenant_id = $4
      AND task.id = $5
      AND task.status = 'running'
      AND task.lease_until <= $1::timestamptz
      AND task.attempt_count >= task.max_attempts
)
UPDATE transfer_task AS task
SET status = 'running',
    attempt_count = attempt_count + 1,
    last_error = '',
    updated_at = $1::timestamptz,
    completed_at = NULL,
    next_attempt_after = NULL,
    lease_token = $2,
    lease_until = $3::timestamptz
WHERE task.tenant_id = $4
  AND task.id = $5
  AND task.attempt_count < task.max_attempts
  AND (
      (task.status IN ('pending', 'retrying') AND (task.next_attempt_after IS NULL OR task.next_attempt_after <= $1::timestamptz))
      OR (task.status = 'running' AND task.lease_until <= $1::timestamptz)
  )
RETURNING id, tenant_id, account_id, channel, subject, status, content_type, file_name,
          attempt_count, max_attempts, last_error, artifact_ref, artifact_size,
          artifact_content_type, artifact_file_name, created_at, updated_at,
          completed_at, next_attempt_after, lease_token, lease_until
`

type ClaimTransferTaskParams struct {
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	LeaseToken string             `json:"lease_token"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	TenantID   int64              `json:"tenant_id"`
	ID         int64              `json:"id"`
}

func (q *Queries) ClaimTransferTask(ctx context.Context, arg ClaimTransferTaskParams) (TransferTask, error) {
	row := q.db.QueryRow(ctx, claimTransferTask,
		arg.UpdatedAt,
		arg.LeaseToken,
		arg.LeaseUntil,
		arg.TenantID,
		arg.ID,
	)
	var i TransferTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Channel,
		&i.Subject,
		&i.Status,
		&i.ContentType,
		&i.FileName,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.ArtifactRef,
		&i.ArtifactSize,
		&i.ArtifactContentType,
		&i.ArtifactFileName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NextAttemptAfter,
		&i.LeaseToken,
		&i.LeaseUntil,
	)
	return i, err
}

const completeTransferTask = `-- name: CompleteTransferTask :one
UPDATE transfer_task
SET status = 'succeeded',
    last_error = '',
    artifact_ref = $1,
    artifact_size = $2,
    artifact_content_type = $3,
    artifact_file_name = $4,
    updated_at = $5::timestamptz,
    completed_at = $6::timestamptz,
    next_attempt_after = NULL,
    lease_token = '',
    lease_until = NULL
WHERE tenant_id = $7
  AND id = $8
  AND status = 'running'
  AND lease_token = $9
  AND lease_until > $5::timestamptz
RETURNING id, tenant_id, account_id, channel, subject, status, content_type, file_name,
          attempt_count, max_attempts, last_error, artifact_ref, artifact_size,
          artifact_content_type, artifact_file_name, created_at, updated_at,
          completed_at, next_attempt_after, lease_token, lease_until
`

type CompleteTransferTaskParams struct {
	ArtifactRef         string             `json:"artifact_ref"`
	ArtifactSize        int64              `json:"artifact_size"`
	ArtifactContentType string             `json:"artifact_content_type"`
	ArtifactFileName    string             `json:"artifact_file_name"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	TenantID            int64              `json:"tenant_id"`
	ID                  int64              `json:"id"`
	LeaseToken          string             `json:"lease_token"`
}

func (q *Queries) CompleteTransferTask(ctx context.Context, arg CompleteTransferTaskParams) (TransferTask, error) {
	row := q.db.QueryRow(ctx, completeTransferTask,
		arg.ArtifactRef,
		arg.ArtifactSize,
		arg.ArtifactContentType,
		arg.ArtifactFileName,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.TenantID,
		arg.ID,
		arg.LeaseToken,
	)
	var i TransferTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Channel,
		&i.Subject,
		&i.Status,
		&i.ContentType,
		&i.FileName,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.ArtifactRef,
		&i.ArtifactSize,
		&i.ArtifactContentType,
		&i.ArtifactFileName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NextAttemptAfter,
		&i.LeaseToken,
		&i.LeaseUntil,
	)
	return i, err
}

const countTransferTasks = `-- name: CountTransferTasks :one
SELECT count(*)::bigint
FROM transfer_task
WHERE tenant_id = $1
  AND account_id = $2
  AND ($3::varchar = '' OR channel = $3)
  AND ($4::varchar = '' OR status = $4)
`

type CountTransferTasksParams struct {
	TenantID  int64  `json:"tenant_id"`
	AccountID int64  `json:"account_id"`
	Column3   string `json:"column_3"`
	Column4   string `json:"column_4"`
}

func (q *Queries) CountTransferTasks(ctx context.Context, arg CountTransferTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransferTasks,
		arg.TenantID,
		arg.AccountID,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTransferTask = `-- name: CreateTransferTask :one
INSERT INTO transfer_task (
    id, tenant_id, account_id, channel, subject, status, content_type, file_name,
    attempt_count, max_attempts, last_error, artifact_ref, artifact_size,
    artifact_content_type, artifact_file_name, created_at, updated_at,
    completed_at, next_attempt_after, lease_token, lease_until
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20, $21
)
RETURNING id, tenant_id, account_id, channel, subject, status, content_type, file_name,
          attempt_count, max_attempts, last_error, artifact_ref, artifact_size,
          artifact_content_type, artifact_file_name, created_at, updated_at,
          completed_at, next_attempt_after, lease_token, lease_until
`

type CreateTransferTaskParams struct {
	ID                  int64              `json:"id"`
	TenantID            int64              `json:"tenant_id"`
	AccountID           int64              `json:"account_id"`
	Channel             string             `json:"channel"`
	Subject             string             `json:"subject"`
	Status              string             `json:"status"`
	ContentType         string             `json:"content_type"`
	FileName            string             `json:"file_name"`
	AttemptCount        int32              `json:"attempt_count"`
	MaxAttempts         int32              `json:"max_attempts"`
	LastError           string             `json:"last_error"`
	ArtifactRef         string             `json:"artifact_ref"`
	ArtifactSize        int64              `json:"artifact_size"`
	ArtifactContentType string             `json:"artifact_content_type"`
	ArtifactFileName    string             `json:"artifact_file_name"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	NextAttemptAfter    pgtype.Timestamptz `json:"next_attempt_after"`
	LeaseToken          string             `json:"lease_token"`
	LeaseUntil          pgtype.Timestamptz `json:"lease_until"`
}

func (q *Queries) CreateTransferTask(ctx context.Context, arg CreateTransferTaskParams) (TransferTask, error) {
	row := q.db.QueryRow(ctx, createTransferTask,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.Channel,
		arg.Subject,
		arg.Status,
		arg.ContentType,
		arg.FileName,
		arg.AttemptCount,
		arg.MaxAttempts,
		arg.LastError,
		arg.ArtifactRef,
		arg.ArtifactSize,
		arg.ArtifactContentType,
		arg.ArtifactFileName,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.NextAttemptAfter,
		arg.LeaseToken,
		arg.LeaseUntil,
	)
	var i TransferTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Channel,
		&i.Subject,
		&i.Status,
		&i.ContentType,
		&i.FileName,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.ArtifactRef,
		&i.ArtifactSize,
		&i.ArtifactContentType,
		&i.ArtifactFileName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NextAttemptAfter,
		&i.LeaseToken,
		&i.LeaseUntil,
	)
	return i, err
}

const deletePendingTransferTask = `-- name: DeletePendingTransferTask :exec
DELETE FROM transfer_task
WHERE tenant_id = $1 AND id = $2 AND status = 'pending' AND attempt_count = 0
`

type DeletePendingTransferTaskParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) DeletePendingTransferTask(ctx context.Context, arg DeletePendingTransferTaskParams) error {
	_, err := q.db.Exec(ctx, deletePendingTransferTask, arg.TenantID, arg.ID)
	return err
}

const failTransferTask = `-- name: FailTransferTask :one
UPDATE transfer_task
SET status = CASE WHEN attempt_count < max_attempts THEN 'retrying' ELSE 'failed' END,
    last_error = $1,
    updated_at = $2::timestamptz,
    completed_at = CASE WHEN attempt_count < max_attempts THEN NULL ELSE $3::timestamptz END,
    next_attempt_after = CASE WHEN attempt_count < max_attempts THEN $4::timestamptz ELSE NULL END,
    lease_token = '',
    lease_until = NULL
WHERE tenant_id = $5
  AND id = $6
  AND status = 'running'
  AND lease_token = $7
  AND lease_until > $2::timestamptz
RETURNING id, tenant_id, account_id, channel, subject, status, content_type, file_name,
          attempt_count, max_attempts, last_error, artifact_ref, artifact_size,
          artifact_content_type, artifact_file_name, created_at, updated_at,
          completed_at, next_attempt_after, lease_token, lease_until
`

type FailTransferTaskParams struct {
	LastError        string             `json:"last_error"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	NextAttemptAfter pgtype.Timestamptz `json:"next_attempt_after"`
	TenantID         int64              `json:"tenant_id"`
	ID               int64              `json:"id"`
	LeaseToken       string             `json:"lease_token"`
}

func (q *Queries) FailTransferTask(ctx context.Context, arg FailTransferTaskParams) (TransferTask, error) {
	row := q.db.QueryRow(ctx, failTransferTask,
		arg.LastError,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.NextAttemptAfter,
		arg.TenantID,
		arg.ID,
		arg.LeaseToken,
	)
	var i TransferTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Channel,
		&i.Subject,
		&i.Status,
		&i.ContentType,
		&i.FileName,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.ArtifactRef,
		&i.ArtifactSize,
		&i.ArtifactContentType,
		&i.ArtifactFileName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NextAttemptAfter,
		&i.LeaseToken,
		&i.LeaseUntil,
	)
	return i, err
}

const getTransferTask = `-- name: GetTransferTask :one
SELECT id, tenant_id, account_id, channel, subject, status, content_type, file_name,
       attempt_count, max_attempts, last_error, artifact_ref, artifact_size,
       artifact_content_type, artifact_file_name, created_at, updated_at,
       completed_at, next_attempt_after, lease_token, lease_until
FROM transfer_task
WHERE tenant_id = $1 AND id = $2
`

type GetTransferTaskParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetTransferTask(ctx context.Context, arg GetTransferTaskParams) (TransferTask, error) {
	row := q.db.QueryRow(ctx, getTransferTask, arg.TenantID, arg.ID)
	var i TransferTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Channel,
		&i.Subject,
		&i.Status,
		&i.ContentType,
		&i.FileName,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.ArtifactRef,
		&i.ArtifactSize,
		&i.ArtifactContentType,
		&i.ArtifactFileName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NextAttemptAfter,
		&i.LeaseToken,
		&i.LeaseUntil,
	)
	return i, err
}

const listTransferTasks = `-- name: ListTransferTasks :many
SELECT id, tenant_id, account_id, channel, subject, status, content_type, file_name,
       attempt_count, max_attempts, last_error, artifact_ref, artifact_size,
       artifact_content_type, artifact_file_name, created_at, updated_at,
       completed_at, next_attempt_after, lease_token, lease_until
FROM transfer_task
WHERE tenant_id = $1
  AND account_id = $2
  AND ($3::varchar = '' OR channel = $3)
  AND ($4::varchar = '' OR status = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListTransferTasksParams struct {
	TenantID  int64  `json:"tenant_id"`
	AccountID int64  `json:"account_id"`
	Column3   string `json:"column_3"`
	Column4   string `json:"column_4"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListTransferTasks(ctx context.Context, arg ListTransferTasksParams) ([]TransferTask, error) {
	rows, err := q.db.Query(ctx, listTransferTasks,
		arg.TenantID,
		arg.AccountID,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransferTask{}
	for rows.Next() {
		var i TransferTask
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.Channel,
			&i.Subject,
			&i.Status,
			&i.ContentType,
			&i.FileName,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.LastError,
			&i.ArtifactRef,
			&i.ArtifactSize,
			&i.ArtifactContentType,
			&i.ArtifactFileName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.NextAttemptAfter,
			&i.LeaseToken,
			&i.LeaseUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
