// M5 题库与模板中心错误码(51xxx 内容 / 52xxx 版本 / 53xxx 共享 / 54xxx 组卷)。
// 文案面向用户,内部技术原因通过 WithCause 进入日志。
package apperr

var (
	ErrContentNotFound              = New("51001", "内容不存在或已被移除")
	ErrContentInvalid               = New("51002", "内容信息不完整,请检查后重试")
	ErrContentForbidden             = New("51003", "你不能访问该内容")
	ErrContentImmutable             = New("51004", "已发布内容不能直接修改,请创建新版本")
	ErrContentDeleteBlocked         = New("51005", "该内容已被引用,不能删除")
	ErrContentUnavailable           = New("51006", "内容暂未发布或已弃用")
	ErrContentRequestInvalid        = New("51007", "内容请求格式不正确,请检查后重试")
	ErrContentIDInvalid             = New("51008", "内容编号不正确,请检查后重试")
	ErrContentCategoryInvalid       = New("51009", "分类信息不正确,请检查后重试")
	ErrContentQueryFailed           = New("51010", "内容列表暂时无法加载,请稍后重试")
	ErrContentCategoryQueryFailed   = New("51011", "分类列表暂时无法加载,请稍后重试")
	ErrContentIntegrity             = New("51012", "内容版本校验未通过,请联系管理员处理")
	ErrContentCodeConflict          = New("52001", "该内容版本已存在,请使用新的版本号")
	ErrContentVersionInvalid        = New("52002", "版本号不正确,请检查后重试")
	ErrContentVersionRequestInvalid = New("52003", "新版本请求格式不正确,请检查后重试")
	ErrContentVersionQueryFailed    = New("52004", "版本列表暂时无法加载,请稍后重试")
	ErrContentShareInvalid          = New("53001", "共享内容不存在或已撤回")
	ErrContentCloneInvalid          = New("53002", "暂时无法克隆该内容")
	ErrContentCloneRequestInvalid   = New("53003", "克隆请求格式不正确,请检查后重试")
	ErrPaperInvalid                 = New("54001", "组卷信息不完整,请检查后重试")
	ErrPaperNotFound                = New("54002", "试卷不存在或已被移除")
	ErrPaperRandomNotEnough         = New("54003", "符合条件的题目数量不足,请调整组卷条件")
	ErrPaperRequestInvalid          = New("54004", "试卷请求格式不正确,请检查后重试")
	ErrPaperIDInvalid               = New("54005", "试卷编号不正确,请检查后重试")
	ErrPaperQueryFailed             = New("54006", "试卷暂时无法加载,请稍后重试")
)
