// M1 身份与租户错误码(12xxx 账号认证 / 13xxx 租户组织 / 14xxx 导入)。
// 依据 docs/总-API接口总览.md §5。文案面向用户(CLAUDE.md §8)。
package apperr

// ---- 12xxx 账号与认证 ----
var (
	ErrAccountNotFound                = New("12001", "账号不存在")
	ErrWrongCredentials               = New("12002", "手机号或密码不正确")
	ErrAccountLocked                  = New("12003", "账号已锁定,请稍后再试或联系管理员")
	ErrAccountInactive                = New("12004", "账号尚未激活,请先完成激活")
	ErrAccountDisabled                = New("12005", "账号已停用,请联系管理员")
	ErrAccountArchived                = New("12006", "账号已归档,无法登录")
	ErrAccountCancelled               = New("12007", "账号已注销")
	ErrSmsCodeInvalid                 = New("12009", "验证码错误或已过期")
	ErrSmsRateLimited                 = New("12010", "验证码发送过于频繁,请稍后再试")
	ErrRefreshInvalid                 = New("12011", "登录已失效,请重新登录")
	ErrRefreshReused                  = New("12012", "检测到异常登录,请重新登录")
	ErrWeakPassword                   = New("12013", "密码强度不足,至少8位且含字母和数字")
	ErrPhoneAlreadyExists             = New("12014", "该手机号在本校已注册")
	ErrSsoNotInRoster                 = New("12015", "账号未在名单中,请联系管理员")
	ErrOldPasswordWrong               = New("12016", "原密码不正确")
	ErrSsoUnavailable                 = New("12017", "学校统一认证暂不可用,请联系管理员")
	ErrSsoLoginFailed                 = New("12018", "统一认证失败,请检查账号后重试")
	ErrActivationCodeInvalid          = New("12019", "激活码无效或已过期")
	ErrAccountInvalid                 = New("12020", "账号信息不完整,请检查后重试")
	ErrPhoneInvalid                   = New("12021", "手机号格式不正确,请检查后重试")
	ErrAccountQueryInvalid            = New("12022", "账号筛选条件不正确,请检查后重试")
	ErrLoginPhoneInvalid              = New("12023", "登录信息不完整,请检查手机号和密码")
	ErrLoginNoInvalid                 = New("12024", "登录信息不完整,请检查账号和密码")
	ErrLoginSmsInvalid                = New("12025", "短信登录信息不完整,请检查手机号和验证码")
	ErrSsoLoginInvalid                = New("12026", "统一认证登录参数不完整,请重新发起登录")
	ErrSsoCallbackInvalid             = New("12027", "统一认证回调信息不完整,请重新登录")
	ErrLDAPLoginInvalid               = New("12028", "统一认证账号信息不完整,请检查后重试")
	ErrSmsRequestInvalid              = New("12029", "验证码请求信息不完整,请检查手机号")
	ErrRefreshRequestInvalid          = New("12030", "刷新登录状态的信息不完整,请重新登录")
	ErrResetPasswordInvalid           = New("12031", "找回密码信息不完整,请检查后重试")
	ErrActivationInvalid              = New("12032", "账号激活信息不完整,请检查后重试")
	ErrAccountCreateInvalid           = New("12033", "新建账号信息不完整,请检查后重试")
	ErrAccountUpdateInvalid           = New("12034", "账号更新信息不完整,请检查后重试")
	ErrAccountStatusInvalid           = New("12035", "账号状态变更信息不完整,请检查后重试")
	ErrPasswordChangeInvalid          = New("12036", "改密信息不完整,请检查后重试")
	ErrPhoneChangeInvalid             = New("12037", "换绑手机信息不完整,请检查后重试")
	ErrAccountNoAlreadyExists         = New("12038", "学号或工号已存在,请检查后重试")
	ErrAccountStatusTransitionInvalid = New("12039", "账号当前状态不支持该操作")
	ErrResetPasswordTenantAmbiguous   = New("12040", "该手机号关联多个学校,请先选择学校后重试")
	ErrAccountIdentityInvalid         = New("12041", "账号身份类型不正确,请检查后重试")
	ErrAccountOrgIDInvalid            = New("12042", "账号所属组织不正确,请检查后重试")
	ErrBatchAccountIDsInvalid         = New("12043", "请选择需要操作的账号")
	ErrSmsTenantRequired              = New("12044", "该手机号关联多个学校,请先选择学校后再获取验证码")
	ErrSmsTenantInvalid               = New("12045", "验证码所属学校不正确,请重新选择学校")
	ErrBatchAccountArchiveInvalid     = New("12046", "账号归档信息不完整,请检查学年后重试")
	ErrPlatformLoginInvalid           = New("12047", "平台管理员登录信息不完整,请检查账号和密码")
	ErrSmsCodeAttemptsExceeded        = New("12048", "验证码错误次数过多,请重新获取验证码")
	ErrResetPasswordTenantInvalid     = New("12049", "找回密码所属学校不正确,请重新选择学校")
	ErrAccountCredentialFailed        = New("12050", "账号凭据处理失败,请稍后重试")
	ErrAuthTokenIssueFailed           = New("12051", "登录状态签发失败,请稍后重试")
	ErrAuthSessionStoreFailed         = New("12052", "登录状态保存失败,请稍后重试")
	ErrAuthLookupUnavailable          = New("12053", "登录服务暂不可用,请稍后重试")
	ErrAuthReplayRevokeFailed         = New("12054", "登录状态处理失败,请重新登录")
	ErrSmsRateLimitStoreFailed        = New("12055", "验证码服务暂不可用,请稍后重试")
	ErrSmsCodeGenerateFailed          = New("12056", "验证码生成失败,请稍后重试")
	ErrSmsCodeStoreFailed             = New("12057", "验证码保存失败,请稍后重试")
	ErrSmsSendFailed                  = New("12058", "验证码发送失败,请稍后重试")
	ErrSmsVerifyStoreFailed           = New("12059", "验证码校验失败,请稍后重试")
	ErrActivationCodeIssueFailed      = New("12060", "激活码生成失败,请稍后重试")
	ErrActivationLookupUnavailable    = New("12061", "激活服务暂不可用,请稍后重试")
	ErrPlatformAuthSessionFailed      = New("12062", "平台登录状态保存失败,请稍后重试")
	ErrAccountMutationFailed          = New("12063", "账号信息保存失败,请稍后重试")
	ErrAccountQueryFailed             = New("12064", "账号信息读取失败,请稍后重试")
	ErrAuthSessionQueryFailed         = New("12065", "登录状态读取失败,请稍后重试")
)

// ---- 13xxx 租户与组织 ----
var (
	ErrTenantNotFound               = New("13001", "学校不存在")
	ErrTenantCodeExists             = New("13002", "学校短码已被占用")
	ErrTenantDisabled               = New("13003", "学校账号已停用或到期")
	ErrApplicationNotFound          = New("13004", "申请不存在")
	ErrApplicationHandled           = New("13005", "该申请已处理")
	ErrDepartmentNotFound           = New("13006", "院系不存在")
	ErrMajorNotFound                = New("13007", "专业不存在")
	ErrClassNotFound                = New("13008", "班级不存在")
	ErrOrgNameExists                = New("13009", "名称已存在")
	ErrGrantAdminNonTeacher         = New("13010", "仅教师账号可被授予管理员权限")
	ErrTenantInvalid                = New("13011", "学校信息不完整,请检查后重试")
	ErrSsoConfigInvalid             = New("13012", "统一认证配置不完整,请检查后重试")
	ErrOrgInvalid                   = New("13013", "组织信息不完整,请检查后重试")
	ErrApplicationInvalid           = New("13014", "入驻申请信息不完整,请检查后重试")
	ErrTenantUpdateInvalid          = New("13015", "学校更新信息不完整,请检查后重试")
	ErrTenantConfigInvalid          = New("13016", "学校配置不完整,请检查后重试")
	ErrTenantStatusInvalid          = New("13017", "学校状态不正确,请检查后重试")
	ErrTenantAuthModeInvalid        = New("13018", "认证方式不正确,请检查后重试")
	ErrSchoolTypeInvalid            = New("13019", "学校类型不正确,请检查后重试")
	ErrApplicationStatusInvalid     = New("13020", "申请状态筛选条件不正确,请检查后重试")
	ErrTenantFeatureFlagsInvalid    = New("13021", "学校功能配置格式不正确,请检查后重试")
	ErrApplicationApproveInvalid    = New("13022", "审核通过信息不完整,请检查后重试")
	ErrTenantExpireAtInvalid        = New("13023", "学校到期时间格式不正确,请检查后重试")
	ErrSsoTypeInvalid               = New("13024", "统一认证类型不正确,请检查后重试")
	ErrSsoMatchFieldInvalid         = New("13025", "统一认证匹配字段不正确,请检查后重试")
	ErrSsoCASURLInvalid             = New("13026", "CAS 服务地址不正确,请检查后重试")
	ErrSsoLDAPConfigInvalid         = New("13027", "LDAP 配置不完整或不安全,请检查后重试")
	ErrSsoConfigFormatInvalid       = New("13028", "统一认证配置格式不正确,请检查后重试")
	ErrOrgParentIDInvalid           = New("13029", "上级组织不正确,请检查后重试")
	ErrClassEnrollmentYearInvalid   = New("13030", "班级入学年份不正确,请检查后重试")
	ErrBatchClassIDsInvalid         = New("13031", "请选择需要操作的班级")
	ErrBatchClassPromoteInvalid     = New("13032", "班级升级信息不完整,请检查后重试")
	ErrDepartmentCreateInvalid      = New("13033", "院系创建信息不完整,请检查后重试")
	ErrDepartmentUpdateInvalid      = New("13034", "院系更新信息不完整,请检查后重试")
	ErrMajorCreateInvalid           = New("13035", "专业创建信息不完整,请检查后重试")
	ErrMajorUpdateInvalid           = New("13036", "专业更新信息不完整,请检查后重试")
	ErrClassCreateInvalid           = New("13037", "班级创建信息不完整,请检查后重试")
	ErrClassUpdateInvalid           = New("13038", "班级更新信息不完整,请检查后重试")
	ErrClassPromoteInvalid          = New("13039", "班级升级信息不完整,请检查后重试")
	ErrOrgImportRequestInvalid      = New("13040", "组织导入信息不完整,请检查后重试")
	ErrSsoConfigRequestInvalid      = New("13041", "统一认证保存信息不完整,请检查后重试")
	ErrBootstrapConfigInvalid       = New("13042", "初始化配置不完整,请检查后重试")
	ErrBootstrapConflict            = New("13043", "初始化目标已存在但信息不一致,请检查配置")
	ErrIdentityAuditQueryInvalid    = New("13044", "审计查询条件不正确,请检查后重试")
	ErrIdentityAuditWriteFailed     = New("13045", "审计记录写入失败,请稍后重试")
	ErrIdentityStatsQueryFailed     = New("13046", "统计数据读取失败,请稍后重试")
	ErrIdentityAuditQueryFailed     = New("13047", "审计记录读取失败,请稍后重试")
	ErrTenantApplicationStoreFailed = New("13048", "入驻申请保存失败,请稍后重试")
	ErrTenantQueryFailed            = New("13049", "学校信息读取失败,请稍后重试")
	ErrTenantMutationFailed         = New("13050", "学校信息保存失败,请稍后重试")
	ErrSsoConfigProtectFailed       = New("13051", "统一认证配置保存失败,请稍后重试")
	ErrSsoConfigReadFailed          = New("13052", "统一认证配置读取失败,请稍后重试")
	ErrBootstrapStoreFailed         = New("13053", "初始化信息保存失败,请稍后重试")
	ErrIdentityDataQueryFailed      = New("13054", "身份数据读取失败,请稍后重试")
	ErrIdentityPrivilegedRequired   = New("13055", "身份服务配置不完整,请联系管理员")
	ErrOrgMutationFailed            = New("13056", "组织信息保存失败,请稍后重试")
)

// ---- 14xxx 导入 ----
var (
	ErrImportFormat              = New("14001", "文件格式不正确,请使用提供的模板")
	ErrImportEmpty               = New("14002", "文件中没有有效数据")
	ErrImportTooLarge            = New("14003", "导入数据量超出单次上限")
	ErrImportInvalid             = New("14004", "导入参数不完整,请检查后重试")
	ErrImportTargetInvalid       = New("14005", "导入类型不正确,请检查后重试")
	ErrImportUploadMissing       = New("14006", "请上传需要导入的文件")
	ErrImportCommitInvalid       = New("14007", "导入提交信息不完整,请检查后重试")
	ErrImportPreviewNotFound     = New("14008", "导入预览不存在或已失效,请重新上传")
	ErrImportRowsInvalid         = New("14009", "导入数据格式不正确,请重新上传")
	ErrOrgImportRowsInvalid      = New("14010", "组织导入数据格式不正确,请重新上传")
	ErrOrgImportInvalid          = New("14011", "组织导入信息不完整,请检查后重试")
	ErrImportTemplateBuildFailed = New("14012", "导入模板生成失败,请稍后重试")
	ErrImportPreviewStoreFailed  = New("14013", "导入预览保存失败,请稍后重试")
	ErrImportPreviewReadFailed   = New("14014", "导入预览读取失败,请重新上传")
	ErrImportBatchQueryFailed    = New("14015", "导入记录读取失败,请稍后重试")
)
