// M2 沙箱引擎错误码(21xxx 运行时 / 22xxx 沙箱 / 23xxx 工具 / 24xxx 配额)。
// 文案面向用户,内部技术原因通过 WithCause 进入日志。
package apperr

var (
	ErrRuntimeNotFound              = New("21001", "运行环境不存在")
	ErrRuntimeUnavailable           = New("21002", "运行环境暂不可用")
	ErrRuntimeInvalid               = New("21003", "运行环境配置不正确")
	ErrRuntimeImageNotFound         = New("21004", "运行环境镜像不存在")
	ErrRuntimeSelftestFailed        = New("21005", "运行环境自检未通过")
	ErrRuntimePrepullFailed         = New("21006", "运行环境镜像准备失败,请稍后重试")
	ErrRuntimeCapabilityUnavailable = New("21007", "运行环境能力暂不可用")
	ErrRuntimePersistenceFail       = New("21008", "运行环境配置保存失败,请稍后重试")
	ErrRuntimeSelftestConfigInvalid = New("21009", "运行环境自检配置不正确")

	ErrSandboxNotFound               = New("22001", "实验环境不存在或已释放")
	ErrSandboxCreateFail             = New("22002", "实验环境创建失败,请稍后重试")
	ErrSandboxRecycleFail            = New("22003", "实验环境释放失败,请稍后重试")
	ErrSandboxInvalidState           = New("22004", "实验环境当前状态不支持该操作")
	ErrSandboxTimeout                = New("22005", "实验环境响应超时,请稍后重试")
	ErrSandboxFileInvalid            = New("22006", "文件路径或内容不正确")
	ErrSandboxFileNotFound           = New("22007", "文件不存在或暂时无法读取")
	ErrSandboxFileSaveFail           = New("22008", "文件保存失败,请稍后重试")
	ErrSandboxInitFail               = New("22009", "实验环境初始化失败,请稍后重试")
	ErrSandboxChainOperationFail     = New("22010", "链上操作失败,请稍后重试")
	ErrSandboxCommandFail            = New("22011", "实验环境执行失败,请稍后重试")
	ErrSandboxRequestInvalid         = New("22012", "实验环境请求信息不完整,请检查后重试")
	ErrRuntimeCreateInvalid          = New("22013", "运行环境注册信息不完整,请检查后重试")
	ErrRuntimeUpdateInvalid          = New("22014", "运行环境更新信息不完整,请检查后重试")
	ErrRuntimeImageCreateInvalid     = New("22015", "运行环境镜像信息不完整,请检查后重试")
	ErrRuntimeImagePrepullInvalid    = New("22016", "运行环境镜像预拉取参数不正确,请检查后重试")
	ErrSandboxCreateRequestInvalid   = New("22017", "实验环境创建信息不完整,请检查后重试")
	ErrSandboxOwnerInvalid           = New("22018", "实验环境使用者信息不正确,请检查后重试")
	ErrSandboxRecycleRequestInvalid  = New("22019", "实验环境回收信息不完整,请检查后重试")
	ErrSandboxChainDeployInvalid     = New("22020", "合约部署请求信息不完整,请检查后重试")
	ErrSandboxChainTxInvalid         = New("22021", "链上交易请求信息不完整,请检查后重试")
	ErrSandboxFileWriteInvalid       = New("22022", "文件写入信息不完整,请检查后重试")
	ErrSandboxAccessDenied           = New("22023", "无法访问该实验环境")
	ErrSandboxPersistenceFail        = New("22024", "实验环境状态保存失败,请稍后重试")
	ErrSandboxAuditFail              = New("22025", "操作记录保存失败,请稍后重试")
	ErrSandboxSnapshotUnavailable    = New("22026", "实验环境快照能力暂不可用")
	ErrSandboxSchedulerConfigInvalid = New("22027", "实验环境回收配置不正确")
	ErrSandboxRecycleScanFail        = New("22028", "实验环境回收任务扫描失败,请稍后重试")
	ErrSandboxRecycleFinalizeFail    = New("22029", "实验环境回收任务处理失败,请稍后重试")
	ErrSandboxSnapshotCleanupFail    = New("22030", "实验环境快照清理失败,请稍后重试")

	ErrToolNotFound        = New("23001", "工具不存在或已停用")
	ErrToolNotFitRuntime   = New("23002", "所选工具不适用于该运行环境")
	ErrToolProxyFail       = New("23003", "工具暂时无法打开,请稍后重试")
	ErrToolCreateInvalid   = New("23004", "工具注册信息不完整,请检查后重试")
	ErrToolPersistenceFail = New("23005", "工具配置保存失败,请稍后重试")

	ErrQuotaExceeded        = New("24001", "当前学校实验环境数量已达上限,请稍后再试")
	ErrQuotaInvalid         = New("24002", "资源配额配置不正确")
	ErrQuotaResourceBusy    = New("24003", "实验环境资源繁忙,请稍后再试")
	ErrQuotaUpdateInvalid   = New("24004", "资源配额调整信息不完整,请检查后重试")
	ErrQuotaPersistenceFail = New("24005", "资源配额保存失败,请稍后重试")
)
