// M6 教学模块错误码(61xxx 课程 / 62xxx 作业 / 63xxx 进度互动 / 64xxx 成绩)。
// 文案面向用户,内部技术原因通过 WithCause 进入日志。
package apperr

var (
	ErrCourseNotFound      = New("61001", "课程不存在或已被移除")
	ErrCourseInvalid       = New("61002", "课程信息不完整,请检查后重试")
	ErrCourseForbidden     = New("61003", "你不能管理或访问该课程")
	ErrCourseInvalidState  = New("61004", "课程当前状态不支持该操作")
	ErrCourseJoinInvalid   = New("61005", "邀请码无效或课程暂不可加入")
	ErrCourseMemberInvalid = New("61006", "课程成员信息不正确")
	ErrCourseQueryFailed   = New("61007", "课程数据暂时无法读取,请稍后重试")
	ErrCourseIDInvalid     = New("61008", "课程内容编号不正确,请检查后重试")
	ErrCourseInviteFailed  = New("61009", "课程邀请码暂时无法生成,请稍后重试")

	ErrAssignmentNotFound             = New("62001", "作业不存在或已被移除")
	ErrAssignmentInvalid              = New("62002", "作业信息不完整,请检查后重试")
	ErrAssignmentInvalidState         = New("62003", "作业当前状态不支持该操作")
	ErrSubmissionNotFound             = New("62004", "提交记录不存在")
	ErrSubmissionInvalid              = New("62005", "提交内容不完整,请检查后重试")
	ErrSubmissionTooMany              = New("62006", "提交次数已达上限")
	ErrSubmissionLateRejected         = New("62007", "作业已截止,不再接受提交")
	ErrSubmissionForbidden            = New("62008", "只有已加入课程的学生可以提交作业")
	ErrAssignmentUsageFailed          = New("62009", "作业题目引用暂时无法确认,请稍后重试")
	ErrAssignmentQueryFailed          = New("62010", "作业数据暂时无法读取,请稍后重试")
	ErrSubmissionQueryFailed          = New("62011", "提交数据暂时无法读取,请稍后重试")
	ErrSubmissionEventInvalid         = New("62012", "判题结果暂时无法处理,请稍后重试")
	ErrSubmissionJudgeLink            = New("62013", "判题任务暂时无法绑定,请稍后重试")
	ErrSubmissionEventUnmatched       = New("62014", "判题结果暂时无法匹配提交记录,请稍后重试")
	ErrSubmissionEventSubscribeFailed = New("62015", "判题结果订阅暂时不可用,请稍后重试")

	ErrProgressInvalid               = New("63001", "学习进度信息不正确")
	ErrDiscussionInvalid             = New("63002", "讨论内容不完整,请检查后重试")
	ErrAnnouncementInvalid           = New("63003", "公告内容不完整,请检查后重试")
	ErrReviewInvalid                 = New("63004", "课程评价不正确")
	ErrTeachingStatsQueryInvalid     = New("63005", "教学统计查询条件不正确,请检查后重试")
	ErrDiscussionModerationInvalid   = New("63006", "讨论管理操作不可用,请检查权限或内容状态")
	ErrAnnouncementModerationInvalid = New("63007", "公告管理操作不可用,请检查权限或内容状态")
	ErrDiscussionLikeInvalid         = New("63008", "暂时无法点赞该讨论,请检查后重试")
	ErrReviewForbidden               = New("63009", "只有已加入课程的学生可以评价")
	ErrProgressForbidden             = New("63010", "只有已加入课程的学生可以更新或查看本人进度")
	ErrProgressQueryFailed           = New("63011", "学习进度暂时无法读取,请稍后重试")
	ErrDiscussionQueryFailed         = New("63012", "讨论内容暂时无法读取,请稍后重试")
	ErrAnnouncementQueryFailed       = New("63013", "公告暂时无法读取,请稍后重试")

	ErrGradeWeightInvalid = New("64001", "成绩权重必须合计为 100%")
	ErrGradeNotFound      = New("64002", "成绩记录不存在")
	ErrGradeInvalid       = New("64003", "成绩信息不正确")
	ErrGradeExportFailed  = New("64004", "成绩导出失败,请稍后重试")
	ErrGradeEventFailed   = New("64005", "成绩变更暂时无法同步,请稍后重试")
	ErrGradeQueryFailed   = New("64006", "成绩数据暂时无法读取,请稍后重试")

	ErrTeachingAuditFailed = New("65001", "操作记录暂时无法写入,请稍后重试")
)
