// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countContentItems = `-- name: CountContentItems :one
SELECT COUNT(*)::bigint
FROM content_item
WHERE deleted_at IS NULL
  AND (tenant_id = $1 OR visibility = 3)
  AND ($2::smallint = 0 OR type = $2)
  AND ($3::bigint = 0 OR category_id = $3)
  AND ($4::smallint = 0 OR difficulty = $4)
  AND ($5::text = '' OR tags @> ARRAY[$5]::text[])
  AND ($6::text = '' OR knowledge_points @> ARRAY[$6]::text[])
  AND ($7::text = '' OR title ILIKE '%' || $7 || '%' OR code ILIKE '%' || $7 || '%')
  AND ($8::smallint = 0 OR visibility = $8)
  AND ($9::smallint = 0 OR status = $9)
  AND ($10::bigint = 0 OR author_id = $10)
`

type CountContentItemsParams struct {
	TenantID int64  `json:"tenant_id"`
	Column2  int16  `json:"column_2"`
	Column3  int64  `json:"column_3"`
	Column4  int16  `json:"column_4"`
	Column5  string `json:"column_5"`
	Column6  string `json:"column_6"`
	Column7  string `json:"column_7"`
	Column8  int16  `json:"column_8"`
	Column9  int16  `json:"column_9"`
	Column10 int64  `json:"column_10"`
}

func (q *Queries) CountContentItems(ctx context.Context, arg CountContentItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContentItems,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPapers = `-- name: CountPapers :one
SELECT COUNT(*)::bigint FROM paper WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountPapers(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPapers, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createContentBody = `-- name: CreateContentBody :one
INSERT INTO content_body (item_id, tenant_id, body, sensitive_fields, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING item_id, tenant_id, body, sensitive_fields, created_at, updated_at
`

type CreateContentBodyParams struct {
	ItemID          int64    `json:"item_id"`
	TenantID        int64    `json:"tenant_id"`
	Body            []byte   `json:"body"`
	SensitiveFields []string `json:"sensitive_fields"`
}

func (q *Queries) CreateContentBody(ctx context.Context, arg CreateContentBodyParams) (ContentBody, error) {
	row := q.db.QueryRow(ctx, createContentBody,
		arg.ItemID,
		arg.TenantID,
		arg.Body,
		arg.SensitiveFields,
	)
	var i ContentBody
	err := row.Scan(
		&i.ItemID,
		&i.TenantID,
		&i.Body,
		&i.SensitiveFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContentCategory = `-- name: CreateContentCategory :one
INSERT INTO content_category (id, tenant_id, parent_id, name, sort, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, now(), now(), NULL)
RETURNING id, tenant_id, parent_id, name, sort, created_at, updated_at, deleted_at
`

type CreateContentCategoryParams struct {
	ID       int64       `json:"id"`
	TenantID int64       `json:"tenant_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
	Name     string      `json:"name"`
	Sort     int32       `json:"sort"`
}

func (q *Queries) CreateContentCategory(ctx context.Context, arg CreateContentCategoryParams) (ContentCategory, error) {
	row := q.db.QueryRow(ctx, createContentCategory,
		arg.ID,
		arg.TenantID,
		arg.ParentID,
		arg.Name,
		arg.Sort,
	)
	var i ContentCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Sort,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createContentItem = `-- name: CreateContentItem :one
INSERT INTO content_item (id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, 0, $15, now(), now(), NULL)
RETURNING id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
`

type CreateContentItemParams struct {
	ID              int64       `json:"id"`
	TenantID        int64       `json:"tenant_id"`
	Code            string      `json:"code"`
	Version         string      `json:"version"`
	Type            int16       `json:"type"`
	Title           string      `json:"title"`
	CategoryID      pgtype.Int8 `json:"category_id"`
	Difficulty      int16       `json:"difficulty"`
	Tags            []string    `json:"tags"`
	KnowledgePoints []string    `json:"knowledge_points"`
	AuthorID        int64       `json:"author_id"`
	AuthorType      int16       `json:"author_type"`
	Visibility      int16       `json:"visibility"`
	Status          int16       `json:"status"`
	VersionHash     string      `json:"version_hash"`
}

func (q *Queries) CreateContentItem(ctx context.Context, arg CreateContentItemParams) (ContentItem, error) {
	row := q.db.QueryRow(ctx, createContentItem,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Version,
		arg.Type,
		arg.Title,
		arg.CategoryID,
		arg.Difficulty,
		arg.Tags,
		arg.KnowledgePoints,
		arg.AuthorID,
		arg.AuthorType,
		arg.Visibility,
		arg.Status,
		arg.VersionHash,
	)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Version,
		&i.Type,
		&i.Title,
		&i.CategoryID,
		&i.Difficulty,
		&i.Tags,
		&i.KnowledgePoints,
		&i.AuthorID,
		&i.AuthorType,
		&i.Visibility,
		&i.Status,
		&i.UsageCount,
		&i.VersionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPaper = `-- name: CreatePaper :one
INSERT INTO paper (id, tenant_id, name, author_id, gen_mode, gen_criteria, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now(), NULL)
RETURNING id, tenant_id, name, author_id, gen_mode, gen_criteria, created_at, updated_at, deleted_at
`

type CreatePaperParams struct {
	ID          int64  `json:"id"`
	TenantID    int64  `json:"tenant_id"`
	Name        string `json:"name"`
	AuthorID    int64  `json:"author_id"`
	GenMode     int16  `json:"gen_mode"`
	GenCriteria []byte `json:"gen_criteria"`
}

func (q *Queries) CreatePaper(ctx context.Context, arg CreatePaperParams) (Paper, error) {
	row := q.db.QueryRow(ctx, createPaper,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.AuthorID,
		arg.GenMode,
		arg.GenCriteria,
	)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.AuthorID,
		&i.GenMode,
		&i.GenCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPaperItem = `-- name: CreatePaperItem :one
INSERT INTO paper_item (id, tenant_id, paper_id, item_code, item_version, score, seq, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
RETURNING id, tenant_id, paper_id, item_code, item_version, score, seq, created_at
`

type CreatePaperItemParams struct {
	ID          int64  `json:"id"`
	TenantID    int64  `json:"tenant_id"`
	PaperID     int64  `json:"paper_id"`
	ItemCode    string `json:"item_code"`
	ItemVersion string `json:"item_version"`
	Score       int32  `json:"score"`
	Seq         int32  `json:"seq"`
}

func (q *Queries) CreatePaperItem(ctx context.Context, arg CreatePaperItemParams) (PaperItem, error) {
	row := q.db.QueryRow(ctx, createPaperItem,
		arg.ID,
		arg.TenantID,
		arg.PaperID,
		arg.ItemCode,
		arg.ItemVersion,
		arg.Score,
		arg.Seq,
	)
	var i PaperItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PaperID,
		&i.ItemCode,
		&i.ItemVersion,
		&i.Score,
		&i.Seq,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContentCategory = `-- name: DeleteContentCategory :one
UPDATE content_category
SET deleted_at = now(), updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, parent_id, name, sort, created_at, updated_at, deleted_at
`

type DeleteContentCategoryParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) DeleteContentCategory(ctx context.Context, arg DeleteContentCategoryParams) (ContentCategory, error) {
	row := q.db.QueryRow(ctx, deleteContentCategory, arg.TenantID, arg.ID)
	var i ContentCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Sort,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePaperItems = `-- name: DeletePaperItems :exec
DELETE FROM paper_item WHERE tenant_id = $1 AND paper_id = $2
`

type DeletePaperItemsParams struct {
	TenantID int64 `json:"tenant_id"`
	PaperID  int64 `json:"paper_id"`
}

func (q *Queries) DeletePaperItems(ctx context.Context, arg DeletePaperItemsParams) error {
	_, err := q.db.Exec(ctx, deletePaperItems, arg.TenantID, arg.PaperID)
	return err
}

const deprecateContentItem = `-- name: DeprecateContentItem :one
UPDATE content_item
SET status = 3, updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND status = 2 AND deleted_at IS NULL
RETURNING id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
`

type DeprecateContentItemParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) DeprecateContentItem(ctx context.Context, arg DeprecateContentItemParams) (ContentItem, error) {
	row := q.db.QueryRow(ctx, deprecateContentItem, arg.TenantID, arg.ID)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Version,
		&i.Type,
		&i.Title,
		&i.CategoryID,
		&i.Difficulty,
		&i.Tags,
		&i.KnowledgePoints,
		&i.AuthorID,
		&i.AuthorType,
		&i.Visibility,
		&i.Status,
		&i.UsageCount,
		&i.VersionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContentItemByID = `-- name: GetContentItemByID :one
SELECT id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
FROM content_item
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetContentItemByIDParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetContentItemByID(ctx context.Context, arg GetContentItemByIDParams) (ContentItem, error) {
	row := q.db.QueryRow(ctx, getContentItemByID, arg.TenantID, arg.ID)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Version,
		&i.Type,
		&i.Title,
		&i.CategoryID,
		&i.Difficulty,
		&i.Tags,
		&i.KnowledgePoints,
		&i.AuthorID,
		&i.AuthorType,
		&i.Visibility,
		&i.Status,
		&i.UsageCount,
		&i.VersionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContentItemByRef = `-- name: GetContentItemByRef :one
SELECT id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
FROM content_item
WHERE code = $1 AND version = $2 AND deleted_at IS NULL AND (tenant_id = $3 OR visibility = 3)
ORDER BY CASE WHEN tenant_id = $3 THEN 0 ELSE 1 END
LIMIT 1
`

type GetContentItemByRefParams struct {
	Code     string `json:"code"`
	Version  string `json:"version"`
	TenantID int64  `json:"tenant_id"`
}

func (q *Queries) GetContentItemByRef(ctx context.Context, arg GetContentItemByRefParams) (ContentItem, error) {
	row := q.db.QueryRow(ctx, getContentItemByRef, arg.Code, arg.Version, arg.TenantID)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Version,
		&i.Type,
		&i.Title,
		&i.CategoryID,
		&i.Difficulty,
		&i.Tags,
		&i.KnowledgePoints,
		&i.AuthorID,
		&i.AuthorType,
		&i.Visibility,
		&i.Status,
		&i.UsageCount,
		&i.VersionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContentItemWithBodyByID = `-- name: GetContentItemWithBodyByID :one
SELECT i.id, i.tenant_id, i.code, i.version, i.type, i.title, i.category_id, i.difficulty, i.tags, i.knowledge_points, i.author_id, i.author_type, i.visibility, i.status, i.usage_count, i.version_hash, i.created_at, i.updated_at, i.deleted_at,
       b.body, b.sensitive_fields
FROM content_item i
JOIN content_body b ON b.tenant_id = i.tenant_id AND b.item_id = i.id
WHERE i.tenant_id = $1 AND i.id = $2 AND i.deleted_at IS NULL
`

type GetContentItemWithBodyByIDParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

type GetContentItemWithBodyByIDRow struct {
	ID              int64              `json:"id"`
	TenantID        int64              `json:"tenant_id"`
	Code            string             `json:"code"`
	Version         string             `json:"version"`
	Type            int16              `json:"type"`
	Title           string             `json:"title"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Difficulty      int16              `json:"difficulty"`
	Tags            []string           `json:"tags"`
	KnowledgePoints []string           `json:"knowledge_points"`
	AuthorID        int64              `json:"author_id"`
	AuthorType      int16              `json:"author_type"`
	Visibility      int16              `json:"visibility"`
	Status          int16              `json:"status"`
	UsageCount      int32              `json:"usage_count"`
	VersionHash     string             `json:"version_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	Body            []byte             `json:"body"`
	SensitiveFields []string           `json:"sensitive_fields"`
}

func (q *Queries) GetContentItemWithBodyByID(ctx context.Context, arg GetContentItemWithBodyByIDParams) (GetContentItemWithBodyByIDRow, error) {
	row := q.db.QueryRow(ctx, getContentItemWithBodyByID, arg.TenantID, arg.ID)
	var i GetContentItemWithBodyByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Version,
		&i.Type,
		&i.Title,
		&i.CategoryID,
		&i.Difficulty,
		&i.Tags,
		&i.KnowledgePoints,
		&i.AuthorID,
		&i.AuthorType,
		&i.Visibility,
		&i.Status,
		&i.UsageCount,
		&i.VersionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Body,
		&i.SensitiveFields,
	)
	return i, err
}

const getContentItemWithBodyByRef = `-- name: GetContentItemWithBodyByRef :one
SELECT i.id, i.tenant_id, i.code, i.version, i.type, i.title, i.category_id, i.difficulty, i.tags, i.knowledge_points, i.author_id, i.author_type, i.visibility, i.status, i.usage_count, i.version_hash, i.created_at, i.updated_at, i.deleted_at,
       b.body, b.sensitive_fields
FROM content_item i
JOIN content_body b ON b.tenant_id = i.tenant_id AND b.item_id = i.id
WHERE i.code = $1 AND i.version = $2 AND i.deleted_at IS NULL AND (i.tenant_id = $3 OR i.visibility = 3)
ORDER BY CASE WHEN i.tenant_id = $3 THEN 0 ELSE 1 END
LIMIT 1
`

type GetContentItemWithBodyByRefParams struct {
	Code     string `json:"code"`
	Version  string `json:"version"`
	TenantID int64  `json:"tenant_id"`
}

type GetContentItemWithBodyByRefRow struct {
	ID              int64              `json:"id"`
	TenantID        int64              `json:"tenant_id"`
	Code            string             `json:"code"`
	Version         string             `json:"version"`
	Type            int16              `json:"type"`
	Title           string             `json:"title"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Difficulty      int16              `json:"difficulty"`
	Tags            []string           `json:"tags"`
	KnowledgePoints []string           `json:"knowledge_points"`
	AuthorID        int64              `json:"author_id"`
	AuthorType      int16              `json:"author_type"`
	Visibility      int16              `json:"visibility"`
	Status          int16              `json:"status"`
	UsageCount      int32              `json:"usage_count"`
	VersionHash     string             `json:"version_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	Body            []byte             `json:"body"`
	SensitiveFields []string           `json:"sensitive_fields"`
}

func (q *Queries) GetContentItemWithBodyByRef(ctx context.Context, arg GetContentItemWithBodyByRefParams) (GetContentItemWithBodyByRefRow, error) {
	row := q.db.QueryRow(ctx, getContentItemWithBodyByRef, arg.Code, arg.Version, arg.TenantID)
	var i GetContentItemWithBodyByRefRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Version,
		&i.Type,
		&i.Title,
		&i.CategoryID,
		&i.Difficulty,
		&i.Tags,
		&i.KnowledgePoints,
		&i.AuthorID,
		&i.AuthorType,
		&i.Visibility,
		&i.Status,
		&i.UsageCount,
		&i.VersionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Body,
		&i.SensitiveFields,
	)
	return i, err
}

const getPaper = `-- name: GetPaper :one
SELECT id, tenant_id, name, author_id, gen_mode, gen_criteria, created_at, updated_at, deleted_at
FROM paper
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetPaperParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetPaper(ctx context.Context, arg GetPaperParams) (Paper, error) {
	row := q.db.QueryRow(ctx, getPaper, arg.TenantID, arg.ID)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.AuthorID,
		&i.GenMode,
		&i.GenCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementContentUsage = `-- name: IncrementContentUsage :one
UPDATE content_item
SET usage_count = usage_count + 1, updated_at = now()
WHERE code = $1 AND version = $2 AND tenant_id = $3 AND status = 2 AND deleted_at IS NULL
RETURNING id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
`

type IncrementContentUsageParams struct {
	Code     string `json:"code"`
	Version  string `json:"version"`
	TenantID int64  `json:"tenant_id"`
}

func (q *Queries) IncrementContentUsage(ctx context.Context, arg IncrementContentUsageParams) (ContentItem, error) {
	row := q.db.QueryRow(ctx, incrementContentUsage, arg.Code, arg.Version, arg.TenantID)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Version,
		&i.Type,
		&i.Title,
		&i.CategoryID,
		&i.Difficulty,
		&i.Tags,
		&i.KnowledgePoints,
		&i.AuthorID,
		&i.AuthorType,
		&i.Visibility,
		&i.Status,
		&i.UsageCount,
		&i.VersionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listContentCategories = `-- name: ListContentCategories :many
SELECT id, tenant_id, parent_id, name, sort, created_at, updated_at, deleted_at
FROM content_category
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY parent_id NULLS FIRST, sort ASC, id ASC
`

func (q *Queries) ListContentCategories(ctx context.Context, tenantID int64) ([]ContentCategory, error) {
	rows, err := q.db.Query(ctx, listContentCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentCategory{}
	for rows.Next() {
		var i ContentCategory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Sort,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentItems = `-- name: ListContentItems :many
SELECT id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
FROM content_item
WHERE deleted_at IS NULL
  AND (tenant_id = $1 OR visibility = 3)
  AND ($2::smallint = 0 OR type = $2)
  AND ($3::bigint = 0 OR category_id = $3)
  AND ($4::smallint = 0 OR difficulty = $4)
  AND ($5::text = '' OR tags @> ARRAY[$5]::text[])
  AND ($6::text = '' OR knowledge_points @> ARRAY[$6]::text[])
  AND ($7::text = '' OR title ILIKE '%' || $7 || '%' OR code ILIKE '%' || $7 || '%')
  AND ($8::smallint = 0 OR visibility = $8)
  AND ($9::smallint = 0 OR status = $9)
  AND ($10::bigint = 0 OR author_id = $10)
ORDER BY updated_at DESC, id DESC
LIMIT $11 OFFSET $12
`

type ListContentItemsParams struct {
	TenantID int64  `json:"tenant_id"`
	Column2  int16  `json:"column_2"`
	Column3  int64  `json:"column_3"`
	Column4  int16  `json:"column_4"`
	Column5  string `json:"column_5"`
	Column6  string `json:"column_6"`
	Column7  string `json:"column_7"`
	Column8  int16  `json:"column_8"`
	Column9  int16  `json:"column_9"`
	Column10 int64  `json:"column_10"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListContentItems(ctx context.Context, arg ListContentItemsParams) ([]ContentItem, error) {
	rows, err := q.db.Query(ctx, listContentItems,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentItem{}
	for rows.Next() {
		var i ContentItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Version,
			&i.Type,
			&i.Title,
			&i.CategoryID,
			&i.Difficulty,
			&i.Tags,
			&i.KnowledgePoints,
			&i.AuthorID,
			&i.AuthorType,
			&i.Visibility,
			&i.Status,
			&i.UsageCount,
			&i.VersionHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentVersions = `-- name: ListContentVersions :many
SELECT id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
FROM content_item
WHERE code = $1 AND deleted_at IS NULL AND (tenant_id = $2 OR visibility = 3)
ORDER BY created_at DESC, id DESC
`

type ListContentVersionsParams struct {
	Code     string `json:"code"`
	TenantID int64  `json:"tenant_id"`
}

func (q *Queries) ListContentVersions(ctx context.Context, arg ListContentVersionsParams) ([]ContentItem, error) {
	rows, err := q.db.Query(ctx, listContentVersions, arg.Code, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentItem{}
	for rows.Next() {
		var i ContentItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Version,
			&i.Type,
			&i.Title,
			&i.CategoryID,
			&i.Difficulty,
			&i.Tags,
			&i.KnowledgePoints,
			&i.AuthorID,
			&i.AuthorType,
			&i.Visibility,
			&i.Status,
			&i.UsageCount,
			&i.VersionHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaperItems = `-- name: ListPaperItems :many
SELECT id, tenant_id, paper_id, item_code, item_version, score, seq, created_at
FROM paper_item
WHERE tenant_id = $1 AND paper_id = $2
ORDER BY seq ASC
`

type ListPaperItemsParams struct {
	TenantID int64 `json:"tenant_id"`
	PaperID  int64 `json:"paper_id"`
}

func (q *Queries) ListPaperItems(ctx context.Context, arg ListPaperItemsParams) ([]PaperItem, error) {
	rows, err := q.db.Query(ctx, listPaperItems, arg.TenantID, arg.PaperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaperItem{}
	for rows.Next() {
		var i PaperItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PaperID,
			&i.ItemCode,
			&i.ItemVersion,
			&i.Score,
			&i.Seq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPapers = `-- name: ListPapers :many
SELECT id, tenant_id, name, author_id, gen_mode, gen_criteria, created_at, updated_at, deleted_at
FROM paper
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListPapersParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListPapers(ctx context.Context, arg ListPapersParams) ([]Paper, error) {
	rows, err := q.db.Query(ctx, listPapers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Paper{}
	for rows.Next() {
		var i Paper
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.AuthorID,
			&i.GenMode,
			&i.GenCriteria,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishContentItem = `-- name: PublishContentItem :one
UPDATE content_item
SET status = 2, updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND status = 1 AND deleted_at IS NULL
RETURNING id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
`

type PublishContentItemParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) PublishContentItem(ctx context.Context, arg PublishContentItemParams) (ContentItem, error) {
	row := q.db.QueryRow(ctx, publishContentItem, arg.TenantID, arg.ID)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Version,
		&i.Type,
		&i.Title,
		&i.CategoryID,
		&i.Difficulty,
		&i.Tags,
		&i.KnowledgePoints,
		&i.AuthorID,
		&i.AuthorType,
		&i.Visibility,
		&i.Status,
		&i.UsageCount,
		&i.VersionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const randomPickContentItems = `-- name: RandomPickContentItems :many
SELECT id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
FROM content_item
WHERE tenant_id = $1 AND deleted_at IS NULL AND status = 2
  AND ($2::smallint = 0 OR type = $2)
  AND (cardinality($3::smallint[]) = 0 OR difficulty = ANY($3::smallint[]))
  AND (cardinality($4::text[]) = 0 OR knowledge_points && $4::text[])
ORDER BY random()
LIMIT $5
`

type RandomPickContentItemsParams struct {
	TenantID int64    `json:"tenant_id"`
	Column2  int16    `json:"column_2"`
	Column3  []int16  `json:"column_3"`
	Column4  []string `json:"column_4"`
	Limit    int32    `json:"limit"`
}

func (q *Queries) RandomPickContentItems(ctx context.Context, arg RandomPickContentItemsParams) ([]ContentItem, error) {
	rows, err := q.db.Query(ctx, randomPickContentItems,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentItem{}
	for rows.Next() {
		var i ContentItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Version,
			&i.Type,
			&i.Title,
			&i.CategoryID,
			&i.Difficulty,
			&i.Tags,
			&i.KnowledgePoints,
			&i.AuthorID,
			&i.AuthorType,
			&i.Visibility,
			&i.Status,
			&i.UsageCount,
			&i.VersionHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setContentVisibility = `-- name: SetContentVisibility :one
UPDATE content_item
SET visibility = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND status = 2 AND deleted_at IS NULL
RETURNING id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
`

type SetContentVisibilityParams struct {
	TenantID   int64 `json:"tenant_id"`
	ID         int64 `json:"id"`
	Visibility int16 `json:"visibility"`
}

func (q *Queries) SetContentVisibility(ctx context.Context, arg SetContentVisibilityParams) (ContentItem, error) {
	row := q.db.QueryRow(ctx, setContentVisibility, arg.TenantID, arg.ID, arg.Visibility)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Version,
		&i.Type,
		&i.Title,
		&i.CategoryID,
		&i.Difficulty,
		&i.Tags,
		&i.KnowledgePoints,
		&i.AuthorID,
		&i.AuthorType,
		&i.Visibility,
		&i.Status,
		&i.UsageCount,
		&i.VersionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteDraftContentItem = `-- name: SoftDeleteDraftContentItem :one
UPDATE content_item
SET deleted_at = now(), updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND status = 1 AND usage_count = 0 AND deleted_at IS NULL
RETURNING id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
`

type SoftDeleteDraftContentItemParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) SoftDeleteDraftContentItem(ctx context.Context, arg SoftDeleteDraftContentItemParams) (ContentItem, error) {
	row := q.db.QueryRow(ctx, softDeleteDraftContentItem, arg.TenantID, arg.ID)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Version,
		&i.Type,
		&i.Title,
		&i.CategoryID,
		&i.Difficulty,
		&i.Tags,
		&i.KnowledgePoints,
		&i.AuthorID,
		&i.AuthorType,
		&i.Visibility,
		&i.Status,
		&i.UsageCount,
		&i.VersionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateContentBody = `-- name: UpdateContentBody :one
UPDATE content_body
SET body = $3,
    sensitive_fields = $4,
    updated_at = now()
WHERE tenant_id = $1 AND item_id = $2
RETURNING item_id, tenant_id, body, sensitive_fields, created_at, updated_at
`

type UpdateContentBodyParams struct {
	TenantID        int64    `json:"tenant_id"`
	ItemID          int64    `json:"item_id"`
	Body            []byte   `json:"body"`
	SensitiveFields []string `json:"sensitive_fields"`
}

func (q *Queries) UpdateContentBody(ctx context.Context, arg UpdateContentBodyParams) (ContentBody, error) {
	row := q.db.QueryRow(ctx, updateContentBody,
		arg.TenantID,
		arg.ItemID,
		arg.Body,
		arg.SensitiveFields,
	)
	var i ContentBody
	err := row.Scan(
		&i.ItemID,
		&i.TenantID,
		&i.Body,
		&i.SensitiveFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContentCategory = `-- name: UpdateContentCategory :one
UPDATE content_category
SET parent_id = $3, name = $4, sort = $5, updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, parent_id, name, sort, created_at, updated_at, deleted_at
`

type UpdateContentCategoryParams struct {
	TenantID int64       `json:"tenant_id"`
	ID       int64       `json:"id"`
	ParentID pgtype.Int8 `json:"parent_id"`
	Name     string      `json:"name"`
	Sort     int32       `json:"sort"`
}

func (q *Queries) UpdateContentCategory(ctx context.Context, arg UpdateContentCategoryParams) (ContentCategory, error) {
	row := q.db.QueryRow(ctx, updateContentCategory,
		arg.TenantID,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Sort,
	)
	var i ContentCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Sort,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDraftContentItem = `-- name: UpdateDraftContentItem :one
UPDATE content_item
SET title = $3,
    category_id = $4,
    difficulty = $5,
    tags = $6,
    knowledge_points = $7,
    visibility = $8,
    version_hash = $9,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND status = 1 AND deleted_at IS NULL
RETURNING id, tenant_id, code, version, type, title, category_id, difficulty, tags, knowledge_points, author_id, author_type, visibility, status, usage_count, version_hash, created_at, updated_at, deleted_at
`

type UpdateDraftContentItemParams struct {
	TenantID        int64       `json:"tenant_id"`
	ID              int64       `json:"id"`
	Title           string      `json:"title"`
	CategoryID      pgtype.Int8 `json:"category_id"`
	Difficulty      int16       `json:"difficulty"`
	Tags            []string    `json:"tags"`
	KnowledgePoints []string    `json:"knowledge_points"`
	Visibility      int16       `json:"visibility"`
	VersionHash     string      `json:"version_hash"`
}

func (q *Queries) UpdateDraftContentItem(ctx context.Context, arg UpdateDraftContentItemParams) (ContentItem, error) {
	row := q.db.QueryRow(ctx, updateDraftContentItem,
		arg.TenantID,
		arg.ID,
		arg.Title,
		arg.CategoryID,
		arg.Difficulty,
		arg.Tags,
		arg.KnowledgePoints,
		arg.Visibility,
		arg.VersionHash,
	)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Version,
		&i.Type,
		&i.Title,
		&i.CategoryID,
		&i.Difficulty,
		&i.Tags,
		&i.KnowledgePoints,
		&i.AuthorID,
		&i.AuthorType,
		&i.Visibility,
		&i.Status,
		&i.UsageCount,
		&i.VersionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
