// config_test 校验平台基础设施配置的安全边界与独立密钥约束。
package config

import (
	"os"
	"strings"
	"testing"
)

// TestLoadUsesDedicatedTranscriptSigningKey 确认成绩单签名密钥不再复用内部服务 HMAC 密钥。
func TestLoadUsesDedicatedTranscriptSigningKey(t *testing.T) {
	for key, value := range map[string]string{
		"DEPLOY_MODE":                              "saas",
		"PLATFORM_LAYER_ENABLED":                   "true",
		"HTTP_ADDR":                                "0.0.0.0",
		"HTTP_PORT":                                "8080",
		"WS_PATH":                                  "/ws",
		"LOG_LEVEL":                                "info",
		"LOG_FORMAT":                               "json",
		"APP_ENV":                                  "test",
		"HEALTH_CHECK_TIMEOUT_SECONDS":             "3",
		"HTTP_SHUTDOWN_TIMEOUT_SECONDS":            "10",
		"PG_HOST":                                  "localhost",
		"PG_PORT":                                  "5432",
		"PG_DATABASE":                              "chaimir",
		"PG_USER":                                  "app",
		"PG_PASSWORD":                              "password",
		"PG_SSLMODE":                               "disable",
		"PG_MAX_CONNS":                             "20",
		"PG_MIN_CONNS":                             "2",
		"REDIS_HOST":                               "localhost",
		"REDIS_PORT":                               "6379",
		"REDIS_DB":                                 "0",
		"REDIS_PING_TIMEOUT_SECONDS":               "5",
		"NATS_URL":                                 "nats://localhost:4222",
		"NATS_RECONNECT_WAIT_SECONDS":              "2",
		"NATS_CONSUMER_RETRY_MAX":                  "3",
		"NATS_CONSUMER_RETRY_DELAY_MS":             "100",
		"NATS_DEAD_LETTER_PREFIX":                  "dead",
		"MINIO_ENDPOINT":                           "localhost:9000",
		"MINIO_USE_SSL":                            "false",
		"MINIO_REGION":                             "cn-local",
		"MINIO_ACCESS_KEY":                         "access-key",
		"MINIO_SECRET_KEY":                         "secret-key",
		"MINIO_BUCKET_CODE":                        "chaimir-code",
		"MINIO_BUCKET_ATTACHMENT":                  "chaimir-attachment",
		"MINIO_BUCKET_REPORT":                      "chaimir-report",
		"MINIO_BUCKET_BACKUP":                      "chaimir-backup",
		"MINIO_PING_TIMEOUT_SECONDS":               "5",
		"STORAGE_DOWNLOAD_GRANT_TTL_SECONDS":       "300",
		"JWT_SIGNING_KEY":                          strings.Repeat("j", 32),
		"JWT_ACCESS_TTL_MIN":                       "15",
		"JWT_REFRESH_TTL_DAY":                      "7",
		"JWT_ISSUER":                               "chaimir",
		"APP_ENCRYPTION_KEY":                       strings.Repeat("e", 32),
		"APP_HMAC_KEY":                             strings.Repeat("h", 32),
		"SERVICE_AUTH_MAX_SKEW_SECONDS":            "300",
		"SMS_PROVIDER":                             "log",
		"SMS_TIMEOUT_SECONDS":                      "5",
		"UPLOAD_IMPORT_MAX_BYTES":                  "1048576",
		"UPLOAD_SIM_BUNDLE_MAX_BYTES":              "1048576",
		"UPLOAD_SIM_BUNDLE_MAX_FILES":              "10",
		"UPLOAD_SIM_BUNDLE_MAX_UNPACKED_BYTES":     "1048576",
		"UPLOAD_VIRUS_SCAN_REQUIRED":               "true",
		"UPLOAD_VIRUS_SCAN_NETWORK":                "tcp",
		"UPLOAD_VIRUS_SCAN_ADDRESS":                "clamav:3310",
		"UPLOAD_VIRUS_SCAN_TIMEOUT_SECONDS":        "10",
		"UPLOAD_VIRUS_SCAN_MAX_BYTES":              "1048576",
		"TRANSFER_TASK_MAX_ATTEMPTS":               "3",
		"TRANSFER_TASK_RETRY_DELAY_MS":             "1000",
		"TRANSFER_TASK_DOWNLOAD_TTL_SECONDS":       "900",
		"CONTEST_VULN_SOURCE_MAX_RESPONSE_BYTES":   "1048576",
		"CONTEST_VULN_SOURCE_TIMEOUT_SECONDS":      "10",
		"NOTIFY_EVENT_RETRY_MAX":                   "3",
		"NOTIFY_EVENT_RETRY_DELAY_MS":              "100",
		"NOTIFY_UNREAD_TTL_HOURS":                  "24",
		"NOTIFY_SEND_RATE_WINDOW_SECONDS":          "60",
		"NOTIFY_SEND_RATE_MAX":                     "10",
		"TEACHING_COURSE_GRADES_MAX_ROWS":          "100",
		"TEACHING_JUDGE_OUTBOX_BATCH_SIZE":         "10",
		"TEACHING_JUDGE_OUTBOX_POLL_INTERVAL_MS":   "1000",
		"TEACHING_GRADE_EXPORT_BATCH_SIZE":         "100",
		"GRADE_APPEAL_WINDOW_DAYS":                 "30",
		"GRADE_TRANSCRIPT_SIGNING_KEY":             strings.Repeat("t", 32),
		"SANDBOX_NS_PREFIX_STUDENT":                "sbx",
		"SANDBOX_NS_PREFIX_JUDGE":                  "judge",
		"SANDBOX_NS_PREFIX_BATTLE":                 "battle",
		"SANDBOX_PREPULL_NAMESPACE":                "prepull",
		"IMAGE_REGISTRY":                           "harbor.local",
		"SANDBOX_IMAGE_ATTESTATIONS_JSON":          `[{"image_url":"harbor.local/runtime@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","digest":"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","cosign_verified":true,"trivy_status":"passed"}]`,
		"SANDBOX_DEFAULT_CPU":                      "500m",
		"SANDBOX_DEFAULT_MEMORY":                   "512Mi",
		"SANDBOX_DEFAULT_REQUEST_CPU":              "250m",
		"SANDBOX_DEFAULT_REQUEST_MEMORY":           "256Mi",
		"SANDBOX_MAX_CPU":                          "2",
		"SANDBOX_MAX_MEMORY":                       "2Gi",
		"SANDBOX_MAX_PODS":                         "10",
		"SANDBOX_WORKSPACE_STORAGE":                "10Gi",
		"SANDBOX_PREPULL_TIMEOUT_SECONDS":          "10",
		"SANDBOX_READY_TIMEOUT_SECONDS":            "10",
		"SANDBOX_PREPULL_POLL_INTERVAL_SECONDS":    "2",
		"SANDBOX_READY_POLL_INTERVAL_SECONDS":      "2",
		"SANDBOX_PREPULL_REQUEST_CPU":              "250m",
		"SANDBOX_PREPULL_REQUEST_MEMORY":           "256Mi",
		"SANDBOX_PREPULL_LIMIT_CPU":                "1",
		"SANDBOX_PREPULL_LIMIT_MEMORY":             "512Mi",
		"SANDBOX_CHAIN_RPC_TIMEOUT_SECONDS":        "10",
		"SANDBOX_INIT_ARCHIVE_MAX_FILES":           "10",
		"SANDBOX_INIT_ARCHIVE_MAX_UNPACKED_BYTES":  "1048576",
		"SANDBOX_PROBE_DEFAULT_PERIOD_SECONDS":     "2",
		"SANDBOX_PROBE_DEFAULT_FAILURE_THRESHOLD":  "3",
		"SANDBOX_RECYCLE_POLL_INTERVAL_SECONDS":    "10",
		"SANDBOX_RECYCLE_BATCH_SIZE":               "10",
		"SANDBOX_READY_IDLE_TIMEOUT_SECONDS":       "60",
		"SANDBOX_SELFTEST_RECYCLE_TIMEOUT_SECONDS": "60",
		"SANDBOX_CONTROL_NAMESPACE":                "chaimir-system",
		"SANDBOX_CONTROL_POD_LABEL_KEY":            "app",
		"SANDBOX_CONTROL_POD_LABEL_VALUE":          "backend",
		"JUDGE_QUEUE_POLL_INTERVAL_MS":             "1000",
		"JUDGE_WORKER_BATCH_SIZE":                  "10",
		"JUDGE_SUBMIT_RATE_LIMIT_SECONDS":          "1",
		"JUDGE_DEFAULT_MAX_RETRIES":                "3",
		"JUDGE_SANDBOX_READY_POLL_INTERVAL_MS":     "1000",
		"JUDGE_RESULT_DETAILS_MAX_BYTES":           "1048576",
		"JUDGE_INPUT_INJECT_TIMEOUT_SECONDS":       "10",
		"JUDGE_INPUT_ARCHIVE_MAX_FILES":            "10",
		"JUDGE_INPUT_ARCHIVE_MAX_UNPACKED_BYTES":   "1048576",
		"JUDGE_SIMILARITY_DEFAULT_THRESHOLD":       "0.8",
		"MONITORING_PANELS_JSON":                   "[]",
		"SNOWFLAKE_NODE_ID":                        "1",
		"IDENTITY_ACTIVATION_CODE_TTL_HOURS":       "24",
		"IDENTITY_SSO_NETWORK_TIMEOUT_SECONDS":     "10",
		"IDENTITY_SSO_ALLOWED_SERVICE_ORIGINS":     "https://chaimir.example.edu",
		"IDENTITY_PASSWORD_MAX_FAILED_COUNT":       "5",
		"IDENTITY_PASSWORD_LOCK_MINUTES":           "15",
		"IDENTITY_SMS_RESEND_SECONDS":              "60",
		"IDENTITY_SMS_DAILY_LIMIT":                 "5",
		"IDENTITY_SMS_CODE_TTL_MINUTES":            "5",
		"IDENTITY_SMS_VERIFY_MAX_ATTEMPTS":         "5",
		"IDENTITY_IMPORT_MAX_ROWS":                 "100",
		"IDENTITY_IMPORT_PREVIEW_TTL_HOURS":        "24",
	} {
		t.Setenv(key, value)
	}

	cfg, err := Load()
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	if cfg.Grade.TranscriptSigningKey != strings.Repeat("t", 32) {
		t.Fatalf("unexpected transcript signing key")
	}
	if cfg.Grade.TranscriptSigningKey == cfg.Auth.HMACKey {
		t.Fatalf("transcript signing key should not reuse auth hmac key")
	}
}

// TestLoadRequiresDedicatedTranscriptSigningKey 确认缺少独立成绩单签名密钥会在启动期失败。
func TestLoadRequiresDedicatedTranscriptSigningKey(t *testing.T) {
	os.Clearenv()
	t.Setenv("DEPLOY_MODE", "saas")
	t.Setenv("PLATFORM_LAYER_ENABLED", "true")

	_, err := Load()
	if err == nil || !strings.Contains(err.Error(), "GRADE_TRANSCRIPT_SIGNING_KEY") {
		t.Fatalf("expected dedicated transcript signing key error, got %v", err)
	}
}

// TestLoadRequiresVirusScanAddressWhenRequired 确认启用强制病毒扫描时必须提供扫描器地址。
func TestLoadRequiresVirusScanAddressWhenRequired(t *testing.T) {
	for key, value := range map[string]string{
		"DEPLOY_MODE":                              "saas",
		"PLATFORM_LAYER_ENABLED":                   "true",
		"HTTP_ADDR":                                "0.0.0.0",
		"HTTP_PORT":                                "8080",
		"WS_PATH":                                  "/ws",
		"LOG_LEVEL":                                "info",
		"LOG_FORMAT":                               "json",
		"APP_ENV":                                  "test",
		"HEALTH_CHECK_TIMEOUT_SECONDS":             "3",
		"HTTP_SHUTDOWN_TIMEOUT_SECONDS":            "10",
		"PG_HOST":                                  "localhost",
		"PG_PORT":                                  "5432",
		"PG_DATABASE":                              "chaimir",
		"PG_USER":                                  "app",
		"PG_PASSWORD":                              "password",
		"PG_SSLMODE":                               "disable",
		"PG_MAX_CONNS":                             "20",
		"PG_MIN_CONNS":                             "2",
		"REDIS_HOST":                               "localhost",
		"REDIS_PORT":                               "6379",
		"REDIS_DB":                                 "0",
		"REDIS_PING_TIMEOUT_SECONDS":               "5",
		"NATS_URL":                                 "nats://localhost:4222",
		"NATS_RECONNECT_WAIT_SECONDS":              "2",
		"NATS_CONSUMER_RETRY_MAX":                  "3",
		"NATS_CONSUMER_RETRY_DELAY_MS":             "100",
		"NATS_DEAD_LETTER_PREFIX":                  "dead",
		"MINIO_ENDPOINT":                           "localhost:9000",
		"MINIO_USE_SSL":                            "false",
		"MINIO_REGION":                             "cn-local",
		"MINIO_ACCESS_KEY":                         "access-key",
		"MINIO_SECRET_KEY":                         "secret-key",
		"MINIO_BUCKET_CODE":                        "chaimir-code",
		"MINIO_BUCKET_ATTACHMENT":                  "chaimir-attachment",
		"MINIO_BUCKET_REPORT":                      "chaimir-report",
		"MINIO_BUCKET_BACKUP":                      "chaimir-backup",
		"MINIO_PING_TIMEOUT_SECONDS":               "5",
		"STORAGE_DOWNLOAD_GRANT_TTL_SECONDS":       "300",
		"JWT_SIGNING_KEY":                          strings.Repeat("j", 32),
		"JWT_ACCESS_TTL_MIN":                       "15",
		"JWT_REFRESH_TTL_DAY":                      "7",
		"JWT_ISSUER":                               "chaimir",
		"APP_ENCRYPTION_KEY":                       strings.Repeat("e", 32),
		"APP_HMAC_KEY":                             strings.Repeat("h", 32),
		"SERVICE_AUTH_MAX_SKEW_SECONDS":            "300",
		"SMS_PROVIDER":                             "log",
		"SMS_TIMEOUT_SECONDS":                      "5",
		"UPLOAD_IMPORT_MAX_BYTES":                  "1048576",
		"UPLOAD_SIM_BUNDLE_MAX_BYTES":              "1048576",
		"UPLOAD_SIM_BUNDLE_MAX_FILES":              "10",
		"UPLOAD_SIM_BUNDLE_MAX_UNPACKED_BYTES":     "1048576",
		"UPLOAD_VIRUS_SCAN_REQUIRED":               "true",
		"UPLOAD_VIRUS_SCAN_TIMEOUT_SECONDS":        "10",
		"UPLOAD_VIRUS_SCAN_MAX_BYTES":              "1048576",
		"TRANSFER_TASK_MAX_ATTEMPTS":               "3",
		"TRANSFER_TASK_RETRY_DELAY_MS":             "1000",
		"TRANSFER_TASK_DOWNLOAD_TTL_SECONDS":       "900",
		"CONTEST_VULN_SOURCE_MAX_RESPONSE_BYTES":   "1048576",
		"CONTEST_VULN_SOURCE_TIMEOUT_SECONDS":      "10",
		"NOTIFY_EVENT_RETRY_MAX":                   "3",
		"NOTIFY_EVENT_RETRY_DELAY_MS":              "100",
		"NOTIFY_UNREAD_TTL_HOURS":                  "24",
		"NOTIFY_SEND_RATE_WINDOW_SECONDS":          "60",
		"NOTIFY_SEND_RATE_MAX":                     "10",
		"TEACHING_COURSE_GRADES_MAX_ROWS":          "100",
		"TEACHING_JUDGE_OUTBOX_BATCH_SIZE":         "10",
		"TEACHING_JUDGE_OUTBOX_POLL_INTERVAL_MS":   "1000",
		"TEACHING_GRADE_EXPORT_BATCH_SIZE":         "100",
		"GRADE_APPEAL_WINDOW_DAYS":                 "30",
		"GRADE_TRANSCRIPT_SIGNING_KEY":             strings.Repeat("t", 32),
		"SANDBOX_NS_PREFIX_STUDENT":                "sbx",
		"SANDBOX_NS_PREFIX_JUDGE":                  "judge",
		"SANDBOX_NS_PREFIX_BATTLE":                 "battle",
		"SANDBOX_PREPULL_NAMESPACE":                "prepull",
		"IMAGE_REGISTRY":                           "harbor.local",
		"SANDBOX_IMAGE_ATTESTATIONS_JSON":          `[{"image_url":"harbor.local/runtime@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","digest":"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","cosign_verified":true,"trivy_status":"passed"}]`,
		"SANDBOX_DEFAULT_CPU":                      "500m",
		"SANDBOX_DEFAULT_MEMORY":                   "512Mi",
		"SANDBOX_DEFAULT_REQUEST_CPU":              "250m",
		"SANDBOX_DEFAULT_REQUEST_MEMORY":           "256Mi",
		"SANDBOX_MAX_CPU":                          "2",
		"SANDBOX_MAX_MEMORY":                       "2Gi",
		"SANDBOX_MAX_PODS":                         "10",
		"SANDBOX_WORKSPACE_STORAGE":                "10Gi",
		"SANDBOX_PREPULL_TIMEOUT_SECONDS":          "10",
		"SANDBOX_READY_TIMEOUT_SECONDS":            "10",
		"SANDBOX_PREPULL_POLL_INTERVAL_SECONDS":    "2",
		"SANDBOX_READY_POLL_INTERVAL_SECONDS":      "2",
		"SANDBOX_PREPULL_REQUEST_CPU":              "250m",
		"SANDBOX_PREPULL_REQUEST_MEMORY":           "256Mi",
		"SANDBOX_PREPULL_LIMIT_CPU":                "1",
		"SANDBOX_PREPULL_LIMIT_MEMORY":             "512Mi",
		"SANDBOX_CHAIN_RPC_TIMEOUT_SECONDS":        "10",
		"SANDBOX_INIT_ARCHIVE_MAX_FILES":           "10",
		"SANDBOX_INIT_ARCHIVE_MAX_UNPACKED_BYTES":  "1048576",
		"SANDBOX_PROBE_DEFAULT_PERIOD_SECONDS":     "2",
		"SANDBOX_PROBE_DEFAULT_FAILURE_THRESHOLD":  "3",
		"SANDBOX_RECYCLE_POLL_INTERVAL_SECONDS":    "10",
		"SANDBOX_RECYCLE_BATCH_SIZE":               "10",
		"SANDBOX_READY_IDLE_TIMEOUT_SECONDS":       "60",
		"SANDBOX_SELFTEST_RECYCLE_TIMEOUT_SECONDS": "60",
		"SANDBOX_CONTROL_NAMESPACE":                "chaimir-system",
		"SANDBOX_CONTROL_POD_LABEL_KEY":            "app",
		"SANDBOX_CONTROL_POD_LABEL_VALUE":          "backend",
		"JUDGE_QUEUE_POLL_INTERVAL_MS":             "1000",
		"JUDGE_WORKER_BATCH_SIZE":                  "10",
		"JUDGE_SUBMIT_RATE_LIMIT_SECONDS":          "1",
		"JUDGE_DEFAULT_MAX_RETRIES":                "3",
		"JUDGE_SANDBOX_READY_POLL_INTERVAL_MS":     "1000",
		"JUDGE_RESULT_DETAILS_MAX_BYTES":           "1048576",
		"JUDGE_INPUT_INJECT_TIMEOUT_SECONDS":       "10",
		"JUDGE_INPUT_ARCHIVE_MAX_FILES":            "10",
		"JUDGE_INPUT_ARCHIVE_MAX_UNPACKED_BYTES":   "1048576",
		"JUDGE_SIMILARITY_DEFAULT_THRESHOLD":       "0.8",
		"MONITORING_PANELS_JSON":                   "[]",
		"SNOWFLAKE_NODE_ID":                        "1",
		"IDENTITY_ACTIVATION_CODE_TTL_HOURS":       "24",
		"IDENTITY_SSO_NETWORK_TIMEOUT_SECONDS":     "10",
		"IDENTITY_SSO_ALLOWED_SERVICE_ORIGINS":     "https://chaimir.example.edu",
		"IDENTITY_PASSWORD_MAX_FAILED_COUNT":       "5",
		"IDENTITY_PASSWORD_LOCK_MINUTES":           "15",
		"IDENTITY_SMS_RESEND_SECONDS":              "60",
		"IDENTITY_SMS_DAILY_LIMIT":                 "5",
		"IDENTITY_SMS_CODE_TTL_MINUTES":            "5",
		"IDENTITY_SMS_VERIFY_MAX_ATTEMPTS":         "5",
		"IDENTITY_IMPORT_MAX_ROWS":                 "100",
		"IDENTITY_IMPORT_PREVIEW_TTL_HOURS":        "24",
	} {
		t.Setenv(key, value)
	}

	_, err := Load()
	if err == nil || !strings.Contains(err.Error(), "UPLOAD_VIRUS_SCAN_ADDRESS") {
		t.Fatalf("expected virus scan address error, got %v", err)
	}
}

// TestLoadRequiresStorageAndTransferTTLs 确认统一文件服务和导入导出中心的运行边界必须显式配置。
func TestLoadRequiresStorageAndTransferTTLs(t *testing.T) {
	for key, value := range map[string]string{
		"DEPLOY_MODE":                              "saas",
		"PLATFORM_LAYER_ENABLED":                   "true",
		"HTTP_ADDR":                                "0.0.0.0",
		"HTTP_PORT":                                "8080",
		"WS_PATH":                                  "/ws",
		"WS_ALLOWED_ORIGINS":                       "https://chaimir.example.edu",
		"LOG_LEVEL":                                "info",
		"LOG_FORMAT":                               "json",
		"APP_ENV":                                  "test",
		"HEALTH_CHECK_TIMEOUT_SECONDS":             "5",
		"HTTP_SHUTDOWN_TIMEOUT_SECONDS":            "10",
		"PG_HOST":                                  "localhost",
		"PG_PORT":                                  "5432",
		"PG_DATABASE":                              "chaimir",
		"PG_USER":                                  "chaimir",
		"PG_PASSWORD":                              "secret",
		"PG_SSLMODE":                               "disable",
		"PG_MAX_CONNS":                             "10",
		"PG_MIN_CONNS":                             "1",
		"REDIS_HOST":                               "localhost",
		"REDIS_PORT":                               "6379",
		"REDIS_DB":                                 "0",
		"REDIS_PING_TIMEOUT_SECONDS":               "3",
		"NATS_URL":                                 "nats://localhost:4222",
		"NATS_RECONNECT_WAIT_SECONDS":              "2",
		"NATS_CONSUMER_RETRY_MAX":                  "3",
		"NATS_CONSUMER_RETRY_DELAY_MS":             "100",
		"NATS_DEAD_LETTER_PREFIX":                  "dead",
		"MINIO_ENDPOINT":                           "localhost:9000",
		"MINIO_USE_SSL":                            "false",
		"MINIO_REGION":                             "cn-local",
		"MINIO_ACCESS_KEY":                         "key",
		"MINIO_SECRET_KEY":                         "secret",
		"MINIO_BUCKET_CODE":                        "chaimir-code",
		"MINIO_BUCKET_ATTACHMENT":                  "chaimir-attachment",
		"MINIO_BUCKET_REPORT":                      "chaimir-report",
		"MINIO_BUCKET_BACKUP":                      "chaimir-backup",
		"MINIO_PING_TIMEOUT_SECONDS":               "5",
		"STORAGE_DOWNLOAD_GRANT_TTL_SECONDS":       "0",
		"JWT_SIGNING_KEY":                          "12345678901234567890123456789012",
		"JWT_ACCESS_TTL_MIN":                       "15",
		"JWT_REFRESH_TTL_DAY":                      "7",
		"JWT_ISSUER":                               "chaimir",
		"APP_ENCRYPTION_KEY":                       "12345678901234567890123456789012",
		"APP_HMAC_KEY":                             "12345678901234567890123456789012",
		"SERVICE_AUTH_MAX_SKEW_SECONDS":            "30",
		"IDENTITY_ACTIVATION_CODE_TTL_HOURS":       "24",
		"IDENTITY_SSO_NETWORK_TIMEOUT_SECONDS":     "10",
		"IDENTITY_SSO_ALLOWED_SERVICE_ORIGINS":     "https://chaimir.example.edu",
		"IDENTITY_PASSWORD_MAX_FAILED_COUNT":       "5",
		"IDENTITY_PASSWORD_LOCK_MINUTES":           "15",
		"IDENTITY_SMS_RESEND_SECONDS":              "60",
		"IDENTITY_SMS_DAILY_LIMIT":                 "10",
		"IDENTITY_SMS_CODE_TTL_MINUTES":            "5",
		"IDENTITY_SMS_VERIFY_MAX_ATTEMPTS":         "5",
		"IDENTITY_IMPORT_MAX_ROWS":                 "5000",
		"IDENTITY_IMPORT_PREVIEW_TTL_HOURS":        "24",
		"SMS_PROVIDER":                             "log",
		"SMS_TIMEOUT_SECONDS":                      "5",
		"UPLOAD_IMPORT_MAX_BYTES":                  "10485760",
		"UPLOAD_SIM_BUNDLE_MAX_BYTES":              "20971520",
		"UPLOAD_SIM_BUNDLE_MAX_FILES":              "200",
		"UPLOAD_SIM_BUNDLE_MAX_UNPACKED_BYTES":     "52428800",
		"UPLOAD_VIRUS_SCAN_REQUIRED":               "false",
		"UPLOAD_VIRUS_SCAN_TIMEOUT_SECONDS":        "10",
		"UPLOAD_VIRUS_SCAN_MAX_BYTES":              "52428800",
		"TRANSFER_TASK_MAX_ATTEMPTS":               "0",
		"TRANSFER_TASK_RETRY_DELAY_MS":             "0",
		"TRANSFER_TASK_DOWNLOAD_TTL_SECONDS":       "0",
		"CONTEST_VULN_SOURCE_MAX_RESPONSE_BYTES":   "10485760",
		"CONTEST_VULN_SOURCE_TIMEOUT_SECONDS":      "10",
		"NOTIFY_EVENT_RETRY_MAX":                   "3",
		"NOTIFY_EVENT_RETRY_DELAY_MS":              "100",
		"NOTIFY_UNREAD_TTL_HOURS":                  "24",
		"NOTIFY_SEND_RATE_WINDOW_SECONDS":          "60",
		"NOTIFY_SEND_RATE_MAX":                     "10",
		"TEACHING_COURSE_GRADES_MAX_ROWS":          "10000",
		"TEACHING_JUDGE_OUTBOX_BATCH_SIZE":         "10",
		"TEACHING_JUDGE_OUTBOX_POLL_INTERVAL_MS":   "1000",
		"TEACHING_GRADE_EXPORT_BATCH_SIZE":         "200",
		"GRADE_APPEAL_WINDOW_DAYS":                 "30",
		"GRADE_TRANSCRIPT_SIGNING_KEY":             "grade-signing-key-123456789012345",
		"SANDBOX_NS_PREFIX_STUDENT":                "student",
		"SANDBOX_NS_PREFIX_JUDGE":                  "judge",
		"SANDBOX_NS_PREFIX_BATTLE":                 "battle",
		"SANDBOX_PREPULL_NAMESPACE":                "prepull",
		"IMAGE_REGISTRY":                           "harbor.example.edu/chaimir",
		"SANDBOX_IMAGE_ATTESTATIONS_JSON":          `[{"image_url":"harbor.example.edu/chaimir/runtime:1","digest":"sha256:abc","cosign_verified":true,"trivy_status":"clean"}]`,
		"CHAIMIR_COLLECTOR_ALLOWED_PREFIXES":       "https://collector.example.edu",
		"SANDBOX_DEFAULT_CPU":                      "500m",
		"SANDBOX_DEFAULT_MEMORY":                   "512Mi",
		"SANDBOX_DEFAULT_REQUEST_CPU":              "250m",
		"SANDBOX_DEFAULT_REQUEST_MEMORY":           "256Mi",
		"SANDBOX_MAX_CPU":                          "2",
		"SANDBOX_MAX_MEMORY":                       "2Gi",
		"SANDBOX_MAX_PODS":                         "20",
		"SANDBOX_WORKSPACE_STORAGE":                "10Gi",
		"SANDBOX_PREPULL_TIMEOUT_SECONDS":          "30",
		"SANDBOX_READY_TIMEOUT_SECONDS":            "60",
		"SANDBOX_PREPULL_POLL_INTERVAL_SECONDS":    "5",
		"SANDBOX_READY_POLL_INTERVAL_SECONDS":      "5",
		"SANDBOX_PREPULL_REQUEST_CPU":              "100m",
		"SANDBOX_PREPULL_REQUEST_MEMORY":           "128Mi",
		"SANDBOX_PREPULL_LIMIT_CPU":                "500m",
		"SANDBOX_PREPULL_LIMIT_MEMORY":             "512Mi",
		"SANDBOX_CHAIN_RPC_TIMEOUT_SECONDS":        "10",
		"SANDBOX_INIT_ARCHIVE_MAX_FILES":           "100",
		"SANDBOX_INIT_ARCHIVE_MAX_UNPACKED_BYTES":  "10485760",
		"SANDBOX_PROBE_DEFAULT_PERIOD_SECONDS":     "5",
		"SANDBOX_PROBE_DEFAULT_FAILURE_THRESHOLD":  "3",
		"SANDBOX_RECYCLE_POLL_INTERVAL_SECONDS":    "30",
		"SANDBOX_RECYCLE_BATCH_SIZE":               "10",
		"SANDBOX_READY_IDLE_TIMEOUT_SECONDS":       "600",
		"SANDBOX_SELFTEST_RECYCLE_TIMEOUT_SECONDS": "120",
		"SANDBOX_CONTROL_NAMESPACE":                "chaimir-system",
		"SANDBOX_CONTROL_POD_LABEL_KEY":            "app",
		"SANDBOX_CONTROL_POD_LABEL_VALUE":          "sandbox-control",
		"JUDGE_QUEUE_POLL_INTERVAL_MS":             "1000",
		"JUDGE_WORKER_BATCH_SIZE":                  "5",
		"JUDGE_SUBMIT_RATE_LIMIT_SECONDS":          "5",
		"JUDGE_DEFAULT_MAX_RETRIES":                "1",
		"JUDGE_SANDBOX_READY_POLL_INTERVAL_MS":     "1000",
		"JUDGE_RESULT_DETAILS_MAX_BYTES":           "1048576",
		"JUDGE_INPUT_INJECT_TIMEOUT_SECONDS":       "10",
		"JUDGE_INPUT_ARCHIVE_MAX_FILES":            "100",
		"JUDGE_INPUT_ARCHIVE_MAX_UNPACKED_BYTES":   "10485760",
		"JUDGE_SIMILARITY_DEFAULT_THRESHOLD":       "0.8",
		"MONITORING_PANELS_JSON":                   "{}",
		"SNOWFLAKE_NODE_ID":                        "1",
	} {
		t.Setenv(key, value)
	}

	_, err := Load()
	if err == nil {
		t.Fatalf("expected storage/transfer ttl validation to fail")
	}
	if !strings.Contains(err.Error(), "STORAGE_DOWNLOAD_GRANT_TTL_SECONDS") {
		t.Fatalf("expected storage ttl error, got %v", err)
	}
	if !strings.Contains(err.Error(), "TRANSFER_TASK_MAX_ATTEMPTS") {
		t.Fatalf("expected transfer max attempts error, got %v", err)
	}
	if !strings.Contains(err.Error(), "TRANSFER_TASK_RETRY_DELAY_MS") {
		t.Fatalf("expected transfer retry delay error, got %v", err)
	}
	if !strings.Contains(err.Error(), "TRANSFER_TASK_DOWNLOAD_TTL_SECONDS") {
		t.Fatalf("expected transfer download ttl error, got %v", err)
	}
}
